### ISSUE TITLE
AI unnecessarily switching out Pokemon on the first turn

### ISSUE THREAD

**Issue by Pyredrid** [rh-hideout/pokeemerald-expansion#1208]
Some NPC trainers are switching out their pokemon right on the first turn.  This seems like an AI bug and also probably doesn't happen in the base vanilla game.  Some NPCs that have been tested to have this are: FISHERMAN IVAN, HIKER DEVAN, and LEADER ROXANNE

**Comment by ultima-soul** [comment]
Resolved by #1346.
