### ISSUE TITLE
[BE+IE] #ifndef ITEM_EXPANSION is useless

### ISSUE THREAD

**Issue by MandL27** [rh-hideout/pokeemerald-expansion#1210]
https://github.com/rh-hideout/pokeemerald-expansion/blob/8e30647ca17b0247c0f4c599834211fb0fde9d57/include/constants/battle_config.h#L31

The above line evaluates to false even if `ITEM_EXPANSION` is defined in item_config.h (but works as expected if it's (re)defined in battle_config.h). Replacing it with `#ifdef` always evaluates to false, and more robust conditional logic with `#if` syntax-highlights in VS Code with the boolean not of itself, but compiles as if false.

**Comment by MandL27** [comment]
As discussed on Discord, a fix is to move the `#define XYZ_EXPANSION` lines into global.h. I'll PR this tomorrow if no one else does by then.

**Comment by ExpoSeed** [comment]
#1212, #1213, #1214
