### ISSUE TITLE
Setting B_ABILITY_POP_UP to FALSE causes a strange pause upon Intimidate's activation

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#1217]
Lunos, but written in JapaneseToday at 1:15 PM
Without the ability popups there seems to be a weird pause
Lunos, but written in JapaneseToday at 1:29 PM
It's worth to note that the weird pause actually happens in the battle_engine without changes.

To replicate, simply set `B_ABILITY_POP_UP` in `include/constants/battle_config.h` to `FALSE`, and throw into battle a Pokémon with Intimidate as its ability.
There'll be a weird pause after the "*Go! [POKéMON]!*" text string, and before the text string used by Intimidate itself.

**Comment by DizzyEggg** [comment]
#1537
