### ISSUE TITLE
[pokemon_expansion] Weird green line in Landorus' icon sprite

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#1222]
Title.
![Untitled1042](https://user-images.githubusercontent.com/4485172/99007866-d2768d80-2523-11eb-9574-f35ab55328f3.gif)

**Comment by Blackforest92** [comment]
It is not caused by Hoopa. but [Landorus](https://github.com/rh-hideout/pokeemerald-expansion/blob/pokemon_expansion/graphics/pokemon/landorus/icon.png).
Here small fix :
![icon](https://user-images.githubusercontent.com/64682409/99032595-8ae81400-25ac-11eb-837e-759488d8563d.png)

**Comment by AsparagusEduardo** [comment]
https://github.com/rh-hideout/pokeemerald-expansion/commit/bb2be3cf98e303bcb14c27eb0421ec05832ce6fc
