### ISSUE TITLE
Guts Not Boosting Physical Attack Boost

### ISSUE THREAD

**Issue by ultima-soul** [rh-hideout/pokeemerald-expansion#1225]
From kageru on Discord:
> someone reported guts not properly boosting stats in the EE discord, and it seems like that’s an issue with rhh expansion as well. you don’t half the physical attack if the user has guts (which is correct), but you don’t apply the 1.5x boost afterwards.
from what I can see, CalcAttackStat in battle_util.c should have a case for guts like
```c
case ABILITY_GUTS:
    if (gBattleMons[battlerAtk].status1 & STATUS1_ANY && IS_MOVE_PHYSICAL(move))
        MulModifier(&modifier, UQ_4_12(1.5));
    break;
```

**Comment by AsparagusEduardo** [comment]
https://github.com/rh-hideout/pokeemerald-expansion/commit/06e3097d44ad5f4d417cdcd9ad104b02c5088a26
