### ISSUE TITLE
Discharge softlocks when used in battle.

### ISSUE THREAD

**Issue by Ryuhouji** [rh-hideout/pokeemerald-expansion#1229]
https://i.imgur.com/ygDNkjT.gif
to recreate: use discharge.

**Comment by LOuroboros** [comment]
Can't confirm.
![Untitled1147](https://user-images.githubusercontent.com/4485172/99309522-59837880-2838-11eb-9804-1acce5e10fb5.gif)

**Comment by AsparagusEduardo** [comment]
![image](https://user-images.githubusercontent.com/2904965/99398161-cc393600-28c2-11eb-8121-0912ce89bc57.png)
