### ISSUE TITLE
Certain Arceus Forms use the wrong palette

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#1230]
Title.
Namely, `SPECIES_ARCEUS_FLYING` and `SPECIES_ARCEUS_FIGHTING`, but double checking wouldn't hurt.
![Untitled1124](https://user-images.githubusercontent.com/4485172/99283278-8e310900-2813-11eb-8d8d-e34a909ed59c.png)![Untitled1125](https://user-images.githubusercontent.com/4485172/99283279-8ec99f80-2813-11eb-9c83-f77dac881042.png)

**Comment by AsparagusEduardo** [comment]
https://github.com/rh-hideout/pokeemerald-expansion/commit/be10a005d61072f6c77203c4076bc5830bd16ba5
