### ISSUE TITLE
Multiple mon icons have errors

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#1231]
Combee
![image](https://user-images.githubusercontent.com/2904965/99307372-27bce280-2835-11eb-8796-b0ae7b10a759.png)
Sawk
![image](https://user-images.githubusercontent.com/2904965/99307515-5f2b8f00-2835-11eb-8ded-9b6eb7d006af.png)
Solosis
![image](https://user-images.githubusercontent.com/2904965/99307607-7e2a2100-2835-11eb-856f-47e378f1b67b.png)
Tynamo
![image](https://user-images.githubusercontent.com/2904965/99306641-33f47000-2834-11eb-923a-fade9c0cb645.png)
Landorus
![image](https://user-images.githubusercontent.com/2904965/99306798-6d2ce000-2834-11eb-9c4c-c873dfda418e.png)

**Comment by LOuroboros** [comment]
There's a fixed icon for Landorus in #1222, someone just needs to test it out and submit a PR.

I might get to it and the rest of the species if no one else does it in the next couple of hours.

**Comment by AsparagusEduardo** [comment]
https://github.com/rh-hideout/pokeemerald-expansion/commit/bb2be3cf98e303bcb14c27eb0421ec05832ce6fc
