### ISSUE TITLE
[battle_engine] A party of MissingNo. is being generated after the first battle at Route 101

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#1233]
Title.
To reproduce, clone the battle_engine, build a ROM and start a savefile.
Keep playing until Birch gives you your starter Pokémon, and check your party afterward.
https://streamable.com/t085kz
https://streamable.com/p4j29a

**Comment by LOuroboros** [comment]
Clarification: This actually happens right after a battle, any battle, not just the first one.

**Comment by AsparagusEduardo** [comment]
Fixed in https://github.com/rh-hideout/pokeemerald-expansion/commit/985b0874c9e3ced2d0559d5d828e8aae0debf951
