### ISSUE TITLE
Terrain moves causes graphical glitch 

### ISSUE THREAD

**Issue by veterandrake** [rh-hideout/pokeemerald-expansion#1263]
![terrain](https://user-images.githubusercontent.com/75160712/101151292-721ccc80-3647-11eb-911b-38624e45f74a.gif)

terrain moves always causes graphical glitch in next consecutive battle if terrain was still active when first battle ends.

**Comment by veterandrake** [comment]
terrain abilities still don't refresh background untill a new screen is loaded.
![terrain](https://user-images.githubusercontent.com/75160712/101984143-7c714300-3ca5-11eb-84f1-db0d37664a51.gif)

**Comment by ExpoSeed** [comment]
#1295
