### ISSUE TITLE
Item define warnings when merging Item expansion with Battle Engine

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#1264]
When merging with Item expansion, a lot of these warning appear:
![image](https://user-images.githubusercontent.com/2904965/100529678-b08a3580-31c8-11eb-8698-21206114b0f6.png)

**Comment by ExpoSeed** [comment]
for whatever reason, i can't reproduce this.

nonetheless, including `global.h` in `battle_config.h` may be a potential solution

**Comment by ExpoSeed** [comment]
#1552, #1553, and #1554
