### ISSUE TITLE
Techno Blast's animation resets the game

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1266]
![Techno freeze](https://user-images.githubusercontent.com/28769716/101238204-8219d680-3743-11eb-967f-219143c78546.gif)

Tested on a ROM with only the three expansion branches.

**Comment by LOuroboros** [comment]
Can't confirm on an up-to-date copy of the BE. Also, the move animation of Techno Blast doesn't seem to be using the particles you're showing on your .gif there either.
![Untitled1739](https://user-images.githubusercontent.com/4485172/101259632-bcb24d80-3708-11eb-98c6-f7536a089a72.gif)

**Comment by Pyredrid** [comment]
Try with all three branches, I suspect this might be another "triple branch" issue or a missing ifdef

**Comment by ExpoSeed** [comment]
I'm just wondering where the animation came from, I don't think I've seen an animation like that before for techno blast

**Comment by LOuroboros** [comment]
Could you please give us some more information about this problem, @BuffelSaft?

Did you make any changes to Techno Blast's animation on your end? Did you tweak the particle settings in `include/constants/battle_config.h`?

Any extra details would be appreciated.

**Comment by BuffelSaft** [comment]
@ExpoSeed I assumed that was the fire type version of Techno Blast; could be something else entirely though, I haven't tested the Drives with a Genesect.

@LOuroboros Only thing I changed in this ROM was the starter, everything else was left default.

After some further testing it seems the issue is that Empoleon is holding Leftovers in that gif; for some reason that's making Techno Blast use that animation. Removing the Leftovers makes it use the default animation. Some other items also cause the reset (I tried TM09), but some don't (e.g. the Burn Drive).

**Comment by LOuroboros** [comment]
> 
> 
> @ExpoSeed I assumed that was the fire type version of Techno Blast; could be something else entirely though, I haven't tested the Drives with a Genesect.
> 
> @LOuroboros Only thing I changed in this ROM was the starter, everything else was left default.
> 
> After some further testing it seems the issue is that Empoleon is holding Leftovers in that gif; for some reason that's making Techno Blast use that animation. Removing the Leftovers makes it use the default animation. Some other items also cause the reset (I tried TM09), but some don't (e.g. the Burn Drive).

Alright, can confirm that when you give a Pokémon the Leftovers to hold and use Techno Blast, its animation changes to Fire type, and said animation does make the game freeze in a branch with the BE and the IE.

![Untitled1752](https://user-images.githubusercontent.com/4485172/101267285-cbfbc000-3735-11eb-9d98-a1142da07473.gif)

**Comment by ExpoSeed** [comment]
I understand what's going on now. When I refactored Techno Blast, I forgot to change the battle scripts. This caused another issue, and I didn't know the animations were implemented so I didn't consider them. So the script needs to be looked at.

**Comment by ExpoSeed** [comment]
Good news! We figured out part of the issue! The reason why it activated on leftovers was that it was checking the `holdEffectParam`, and leftover's `holdEffectParam` happened to be 10, which is the same as `TYPE_FIRE`. This was fixed by adding a check for drives and for taking the `secondaryId` instead. Now, the right items get the right animations!

Bad news: the animations still freeze the game 🙃. We're still trying to figure this out.

unrelated: would you be willing to join [rhh discord](https://discord.gg/cmUtxRsqvG)? You've been an absolute pro at finding bugs

**Comment by BuffelSaft** [comment]
Oh nice, that makes sense. Might be worth going through all the animations at some point as it seems quite a few of them have issues.

Also yep I'd love to join the discord, would be nice to contribute to the expansions as well as report bugs.
