### ISSUE TITLE
Jump Kick should hurt the user when used on a target that is immune

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1268]
Current behavior:
![Jump Kick](https://user-images.githubusercontent.com/28769716/101267405-2724c580-37bd-11eb-9678-ccf85f7dad40.gif)

As of generation IV, Jump Kick and Hi Jump Kick make the user crash if used on something that is immune to the move. Usually that'd only be Ghost types, but it could also happen if Wonder Guard is swapped onto something that isn't weak to Fighting.

**Comment by ultima-soul** [comment]
Resolved in #1272.
