### ISSUE TITLE
Grass types are immune to their own Rage Powder

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1269]
Noticed this on an Amoonguss in doubles while playing through my hack, just tested it to confirm:
![Rage Powder](https://user-images.githubusercontent.com/28769716/101267586-22f9a780-37bf-11eb-8245-998dce9ab6ef.gif)
The move doesn't do anything in singles of course, but it can still be used. Presumably this is a side effect of Grass types being immune to powder moves. They should be immune to the move redirection effect of Rage Powder, but should still be able to use it.

**Comment by LOuroboros** [comment]
> but it can still be used

That's arguable. I tested the move's behavior with my Decidueye in Ultra Sun, and he never gets to actually use the move.
The message "Pokémon used move!" never gets printed and its animation never comes up either.
The only thing there is, is a "But it failed!" text string.
![Untitled1772](https://user-images.githubusercontent.com/4485172/101268500-63ffa680-3742-11eb-9991-0fd4141da677.gif)

**Comment by BuffelSaft** [comment]
Yeah, should be seeing "but it failed!" instead of "it doesn't affect..."
Here's a less lazy test in a multi battle anyway, same behavior:
![Rage Powder](https://user-images.githubusercontent.com/28769716/101268674-e2079000-37ca-11eb-90b4-d0361b4af131.gif)

**Comment by BuffelSaft** [comment]
#1418
