### ISSUE TITLE
Mandibuzz

### ISSUE THREAD

**Issue by chrisasma103** [rh-hideout/pokeemerald-expansion#1282]
The Party Icon for Mandibuzz is actually a picture of Mienfoo.

**Comment by AsparagusEduardo** [comment]
Confirmed.
![image](https://user-images.githubusercontent.com/2904965/101996539-2656cc80-3cb2-11eb-8618-762d19d9c2ec.png)

**Comment by ultima-soul** [comment]
Resolved in #1297.
