### ISSUE TITLE
Final Gambit effect is not correct

### ISSUE THREAD

**Issue by veterandrake** [rh-hideout/pokeemerald-expansion#1287]
![final gambit](https://user-images.githubusercontent.com/75160712/101984076-fb19b080-3ca4-11eb-82f1-a640ad5dd1fc.gif)
final gambit effect is not correct.

**Comment by LOuroboros** [comment]
Can't confirm it breaking the game on a clean copy of the battle_engine.
![Untitled1983](https://user-images.githubusercontent.com/4485172/101987004-38178000-3c70-11eb-81fd-ec77748f82af.gif)

Granted, the effect is incorrect regardless. Final Gambit is not a clone of Dragon Tail.

**Comment by ultima-soul** [comment]
Resolved by #1289.
