### ISSUE TITLE
Digging activates Mummy on first turn

### ISSUE THREAD

**Issue by ghoulslash** [rh-hideout/pokeemerald-expansion#1296]
Using dig (and most likely other contact, two-turn moves) causes Mummy to trigger on the disappearing turn:

![dig_mummy_bug](https://user-images.githubusercontent.com/41651341/102119818-f36e1f00-3dfe-11eb-938d-7430fa15039f.gif)

Should likely just involve a `STATUS3_SEMI_INVULNERABLE` check, or `TARGET_TURN_DAMAGED` in the mummy activation

**Comment by ultima-soul** [comment]
Resolved in #1298.
