### ISSUE TITLE
Ghost types are still trapped by Mean Look/binding moves

### ISSUE THREAD

**Issue by SubzeroEclipse** [rh-hideout/pokeemerald-expansion#1303]
By setting the config to Gen 6 or beyond Ghost types can switch from abilities such as Shadow Tag, but not from moves (Mean Look, Infestation, etc.).
![ghost test1](https://user-images.githubusercontent.com/64367060/102602781-4529e880-4122-11eb-8713-3baa64cbbcf9.gif)
![ghost test2](https://user-images.githubusercontent.com/64367060/102602782-46f3ac00-4122-11eb-8143-860137bc9f10.gif)

**Comment by ultima-soul** [comment]
Can confirm.

**Comment by AsparagusEduardo** [comment]
#1397
