### ISSUE TITLE
Night Slash Does Not Make Healthbox Disappear When Config is Enabled

### ISSUE THREAD

**Issue by ultima-soul** [rh-hideout/pokeemerald-expansion#1310]
As title says.

**Comment by LOuroboros** [comment]
Can confirm.
![Untitled2287](https://user-images.githubusercontent.com/4485172/102824305-55a8c000-43bb-11eb-92d3-947975f8b415.gif)

**Comment by DizzyEggg** [comment]
Was fixed with #1392
