### ISSUE TITLE
Focus Blast's effect goes above or way beyond the UI.

### ISSUE THREAD

**Issue by Syreldar** [rh-hideout/pokeemerald-expansion#1351]
![mGBA_bXD2ogg18a](https://user-images.githubusercontent.com/42327659/104685350-1ee47200-56fb-11eb-8593-e423add8b754.png)
![mGBA_hW0ig43jZn](https://user-images.githubusercontent.com/42327659/104685353-20159f00-56fb-11eb-8e72-620636814734.png)

**Comment by LOuroboros** [comment]
I can confirm that Focus Blast's animation does overlap the textbox in a clean copy of the BE.
![Untitled2957](https://user-images.githubusercontent.com/4485172/104799051-a3da9480-57aa-11eb-8086-09699ab36f5d.gif)
