### ISSUE TITLE
AI doesn't check for ELEC type immunity to Stun Spore?

### ISSUE THREAD

**Issue by Syreldar** [rh-hideout/pokeemerald-expansion#1352]
Enemy Shroomish tried to use stun spore on my electrike over and over, despite it having no effect obviously. The enemy trainer had pretty smart flags.

**Comment by ghoulslash** [comment]
This is handled via #1308 and AI_CheckBadMove:
![voyager-0](https://user-images.githubusercontent.com/41651341/104752095-7989c800-5713-11eb-8e83-1824bc014a31.png)
