### ISSUE TITLE
Two-turn moves fail when attacker faints itself

### ISSUE THREAD

**Issue by ghoulslash** [rh-hideout/pokeemerald-expansion#1363]
For example (in gif), opponent uses memento and I use dig afterwards but it fails. Since it hasn't yet targeted the memento'd battler, there's no reason it should fail
![memento_dig_fail](https://user-images.githubusercontent.com/41651341/105129295-f87b5980-5aa1-11eb-8a11-86dc842b63d4.gif)

**Comment by ultima-soul** [comment]
Resolved in #1364.
