### ISSUE TITLE
The ability popup struggles to show the 12th character of an ability's name

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#1368]
Title.
![Untitled3145](https://user-images.githubusercontent.com/4485172/105679617-7a69e900-5ecd-11eb-95bd-630b5f62914d.png)

**Comment by BuffelSaft** [comment]
Same thing happens with longer Pokémon names - the "'s" gets cut off as it doesn't fit in the box.

**Comment by AsparagusEduardo** [comment]
#1957
