### ISSUE TITLE
Riolu should evolve only during the day

### ISSUE THREAD

**Issue by BLourenco** [rh-hideout/pokeemerald-expansion#1372]
https://github.com/rh-hideout/pokeemerald-expansion/blob/2e0b02e491fafcc4d44699609a4ca0969c13ca18/src/data/pokemon/evolution.h#L295

https://bulbapedia.bulbagarden.net/wiki/Riolu_(Pok%C3%A9mon)#Evolution

**Comment by LOuroboros** [comment]
Solved by #1373
