### ISSUE TITLE
Kyurem-Black & Kyurem-White's signature moves are mixed up.

### ISSUE THREAD

**Issue by BLourenco** [rh-hideout/pokeemerald-expansion#1374]
https://github.com/rh-hideout/pokeemerald-expansion/blob/0f142048bf988672ecbc511ebf0c4a8374b74c3a/src/data/pokemon/level_up_learnsets.h#L18964-L19000

https://bulbapedia.bulbagarden.net/wiki/Kyurem_(Pok%C3%A9mon)/Generation_VII_learnset#By_leveling_up

**Comment by ultima-soul** [comment]
Resolved in #1380.
