### ISSUE TITLE
Charging Moves Text Change as of Gen 5

### ISSUE THREAD

**Issue by ultima-soul** [rh-hideout/pokeemerald-expansion#1398]
It seems charging moves say you use the move before the animation for charging starting as of Gen 5 as you can see in this video:
https://www.youtube.com/watch?v=JFN6FUH2tZQ

This should be double-checked with all moves like this and then fixed for the ones that do have this change.

**Comment by LOuroboros** [comment]
I'll give it a shot.

**Comment by ultima-soul** [comment]
Resolved in #1399.
