### ISSUE TITLE
X Sp. Def raises Special Attack

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#14]
Title
![92670455-6e98d400-f2ea-11ea-810b-2bcbabc584fb](https://user-images.githubusercontent.com/2904965/96061391-79a2cf00-0e69-11eb-8795-2fd4343bdd51.gif)

**Comment by LOuroboros** [comment]
I gave this a quick shot, but I think there's changes that I'm missing and that I cannot fully grasp due to my lack of knowledge about C.
These are the changes I did so far in case anyone wants to take a look and expand on them or give me some feedback.
https://github.com/LOuroboros/pokeemerald/commit/0e96ee73ce783332d3939e124a7bfdfa493b68d9

**Comment by ketsuban** [comment]
@LOuroboros Item effects are byte arrays, so that does at best nothing since `0x100` exceeds the size of a byte.

The item effect system is pretty intricate - you can create items with any combination of effects programmed into the game. Game Freak seem to have left the door open for items which boost stats by more than one level - rather than just using a single bit for each X item, they use four, and then the value of those four bytes is added to the stat stage directly before being capped at the maximum.

This would be hard to fix and maintain that flexibility since there's not much room, but in `include/constants/item_effects.h` you can remove `ITEM0_X_ATTACK`, `ITEM2_X_SPATK` and `ITEM2_X_ACCURACY`, and use one byte as a bitfield for X item effects like so.

```c
// field 1 masks
#define ITEM1_X_ATTACK          0x01
#define ITEM1_X_DEFEND          0x02
#define ITEM1_X_SPEED           0x04
#define ITEM1_X_SPATK           0x08
#define ITEM1_X_SPDEF           0x10
#define ITEM1_X_ACCURACY        0x20
```

Then you'd need to alter all the X items like this.

```c
const u8 gItemEffect_XAttack[8] = {
    [1] = ITEM1_X_ATTACK,
    [5] = ITEM5_FRIENDSHIP_LOW | ITEM5_FRIENDSHIP_MID,
    [6] = 1,
    [7] = 1,
};
```

And change `PokemonUseItemEffects` to reflect the new data arrangement.

```c
        // in-battle stat boosting effects
        case 1:
            if ((itemEffect[cmdIndex] & ITEM0_X_ATTACK)
             && gBattleMons[gActiveBattler].statStages[STAT_ATK] < MAX_STAT_STAGE)
            {
                gBattleMons[gActiveBattler].statStages[STAT_ATK] += 1; // or 2 for the Gen 7+ effect
                if (gBattleMons[gActiveBattler].statStages[STAT_ATK] > MAX_STAT_STAGE)
                    gBattleMons[gActiveBattler].statStages[STAT_ATK] = MAX_STAT_STAGE;
                retVal = FALSE;
            }
            if ((itemEffect[cmdIndex] & ITEM1_X_DEFEND)
             && gBattleMons[gActiveBattler].statStages[STAT_DEF] < MAX_STAT_STAGE)
            {
                gBattleMons[gActiveBattler].statStages[STAT_DEF] += 1; // or 2 for the Gen 7+ effect
                if (gBattleMons[gActiveBattler].statStages[STAT_DEF] > MAX_STAT_STAGE)
                    gBattleMons[gActiveBattler].statStages[STAT_DEF] = MAX_STAT_STAGE;
                retVal = FALSE;
            }
            if ((itemEffect[cmdIndex] & ITEM1_X_SPEED)
             && gBattleMons[gActiveBattler].statStages[STAT_SPEED] < MAX_STAT_STAGE)
            {
                gBattleMons[gActiveBattler].statStages[STAT_SPEED] += 1; // or 2 for the Gen 7+ effect
                if (gBattleMons[gActiveBattler].statStages[STAT_SPEED] > MAX_STAT_STAGE)
                    gBattleMons[gActiveBattler].statStages[STAT_SPEED] = MAX_STAT_STAGE;
                retVal = FALSE;
            }
            if ((itemEffect[cmdIndex] & ITEM2_X_SPATK)
             && gBattleMons[gActiveBattler].statStages[STAT_SPATK] < MAX_STAT_STAGE)
            {
                gBattleMons[gActiveBattler].statStages[STAT_SPATK] += 1; // or 2 for the Gen 7+ effect
                if (gBattleMons[gActiveBattler].statStages[STAT_SPATK] > MAX_STAT_STAGE)
                    gBattleMons[gActiveBattler].statStages[STAT_SPATK] = MAX_STAT_STAGE;
                retVal = FALSE;
            }
            if ((itemEffect[cmdIndex] & ITEM2_X_SPDEF)
             && gBattleMons[gActiveBattler].statStages[STAT_SPDEF] < MAX_STAT_STAGE)
            {
                gBattleMons[gActiveBattler].statStages[STAT_SPDEF] += 1; // or 2 for the Gen 7+ effect
                if (gBattleMons[gActiveBattler].statStages[STAT_SPDEF] > MAX_STAT_STAGE)
                    gBattleMons[gActiveBattler].statStages[STAT_SPDEF] = MAX_STAT_STAGE;
                retVal = FALSE;
            }
            if ((itemEffect[cmdIndex] & ITEM2_X_ACCURACY)
             && gBattleMons[gActiveBattler].statStages[STAT_ACC] < MAX_STAT_STAGE)
            {
                gBattleMons[gActiveBattler].statStages[STAT_ACC] += 1; // or 2 for the Gen 7+ effect
                if (gBattleMons[gActiveBattler].statStages[STAT_ACC] > MAX_STAT_STAGE)
                    gBattleMons[gActiveBattler].statStages[STAT_ACC] = MAX_STAT_STAGE;
                retVal = FALSE;
            }
            break;
```

**Comment by ShinyDragonHunter** [comment]
If you’re using the one, then `ITEM1` seems pointless? I understand if it clashes with the actual item define but the `1` would imply there’s more than one.

**Comment by ketsuban** [comment]
There's multiple bytes in item effect structures, and the constants associated with them have the naming scheme of starting with ITEM*n* for the constants applied to byte *n*.

**Comment by ShinyDragonHunter** [comment]
I guess? It just seems silly to have the `1` prefix when there’s only one.

**Comment by ketsuban** [comment]
I don't know how to respond to that. The 1 doesn't mean "1 of X", it means "this constant applies to byte 1 of the item effect array".

**Comment by LOuroboros** [comment]
> 
> 
> @LOuroboros Item effects are byte arrays, so that does at best nothing since `0x100` exceeds the size of a byte.
> 
> The item effect system is pretty intricate - you can create items with any combination of effects programmed into the game. Game Freak seem to have left the door open for items which boost stats by more than one level - rather than just using a single bit for each X item, they use four, and then the value of those four bytes is added to the stat stage directly before being capped at the maximum.
> 
> This would be hard to fix and maintain that flexibility since there's not much room, but in `include/constants/item_effects.h` you can remove `ITEM0_X_ATTACK`, `ITEM2_X_SPATK` and `ITEM2_X_ACCURACY`, and use one byte as a bitfield for X item effects like so.
> 
> ```c
> // field 1 masks
> #define ITEM1_X_ATTACK          0x01
> #define ITEM1_X_DEFEND          0x02
> #define ITEM1_X_SPEED           0x04
> #define ITEM1_X_SPATK           0x08
> #define ITEM1_X_SPDEF           0x10
> #define ITEM1_X_ACCURACY        0x20
> ```
> 
> Then you'd need to alter all the X items like this.
> 
> ```c
> const u8 gItemEffect_XAttack[8] = {
>     [1] = ITEM1_X_ATTACK,
>     [5] = ITEM5_FRIENDSHIP_LOW | ITEM5_FRIENDSHIP_MID,
>     [6] = 1,
>     [7] = 1,
> };
> ```
> 
> And change `PokemonUseItemEffects` to reflect the new data arrangement.
> 
> ```c
>         // in-battle stat boosting effects
>         case 1:
>             if ((itemEffect[cmdIndex] & ITEM1_X_ATTACK)
>              && gBattleMons[gActiveBattler].statStages[STAT_ATK] < MAX_STAT_STAGE)
>             {
>                 gBattleMons[gActiveBattler].statStages[STAT_ATK] += 1; // or 2 for the Gen 7+ effect
>                 if (gBattleMons[gActiveBattler].statStages[STAT_ATK] > MAX_STAT_STAGE)
>                     gBattleMons[gActiveBattler].statStages[STAT_ATK] = MAX_STAT_STAGE;
>                 retVal = FALSE;
>             }
>             if ((itemEffect[cmdIndex] & ITEM1_X_DEFEND)
>              && gBattleMons[gActiveBattler].statStages[STAT_DEF] < MAX_STAT_STAGE)
>             {
>                 gBattleMons[gActiveBattler].statStages[STAT_DEF] += 1; // or 2 for the Gen 7+ effect
>                 if (gBattleMons[gActiveBattler].statStages[STAT_DEF] > MAX_STAT_STAGE)
>                     gBattleMons[gActiveBattler].statStages[STAT_DEF] = MAX_STAT_STAGE;
>                 retVal = FALSE;
>             }
>             if ((itemEffect[cmdIndex] & ITEM1_X_SPEED)
>              && gBattleMons[gActiveBattler].statStages[STAT_SPEED] < MAX_STAT_STAGE)
>             {
>                 gBattleMons[gActiveBattler].statStages[STAT_SPEED] += 1; // or 2 for the Gen 7+ effect
>                 if (gBattleMons[gActiveBattler].statStages[STAT_SPEED] > MAX_STAT_STAGE)
>                     gBattleMons[gActiveBattler].statStages[STAT_SPEED] = MAX_STAT_STAGE;
>                 retVal = FALSE;
>             }
>             if ((itemEffect[cmdIndex] & ITEM1_X_SPATK)
>              && gBattleMons[gActiveBattler].statStages[STAT_SPATK] < MAX_STAT_STAGE)
>             {
>                 gBattleMons[gActiveBattler].statStages[STAT_SPATK] += 1; // or 2 for the Gen 7+ effect
>                 if (gBattleMons[gActiveBattler].statStages[STAT_SPATK] > MAX_STAT_STAGE)
>                     gBattleMons[gActiveBattler].statStages[STAT_SPATK] = MAX_STAT_STAGE;
>                 retVal = FALSE;
>             }
>             if ((itemEffect[cmdIndex] & ITEM1_X_SPDEF)
>              && gBattleMons[gActiveBattler].statStages[STAT_SPDEF] < MAX_STAT_STAGE)
>             {
>                 gBattleMons[gActiveBattler].statStages[STAT_SPDEF] += 1; // or 2 for the Gen 7+ effect
>                 if (gBattleMons[gActiveBattler].statStages[STAT_SPDEF] > MAX_STAT_STAGE)
>                     gBattleMons[gActiveBattler].statStages[STAT_SPDEF] = MAX_STAT_STAGE;
>                 retVal = FALSE;
>             }
>             if ((itemEffect[cmdIndex] & ITEM1_X_ACCURACY)
>              && gBattleMons[gActiveBattler].statStages[STAT_ACC] < MAX_STAT_STAGE)
>             {
>                 gBattleMons[gActiveBattler].statStages[STAT_ACC] += 1; // or 2 for the Gen 7+ effect
>                 if (gBattleMons[gActiveBattler].statStages[STAT_ACC] > MAX_STAT_STAGE)
>                     gBattleMons[gActiveBattler].statStages[STAT_ACC] = MAX_STAT_STAGE;
>                 retVal = FALSE;
>             }
>             break;
> ```

I'm giving your idea a try, but I must be making a mistake somewhere because things aren't just quite working on my end.
I'm looking at the changes myself, but after correcting every single mistake I could spot, things are just not working on my end.
The X Attack, the Dire Hit and the Guard Spec all seem to work, but the other X Items simply don't.
Trying to use them in battle returns a "It won't have any effect." message.

If it's not too much to ask, could you please give it a quick check? Maybe you can see whatever I'm not seeing :eyes:
https://github.com/LOuroboros/pokeemerald/commit/d78d08cda2860996c06a6bb5cf90095b37ee4406

**Comment by ketsuban** [comment]
You have some extraneous `break` statements in your `case 1:` - they might be preventing processing of anything after X Attack. Try removing those and see if it works.

**Comment by LOuroboros** [comment]
> 
> 
> You have some extraneous `break` statements in your `case 1:` - they might be preventing processing of anything after X Attack. Try removing those and see if it works.

Each `break;` is written in the file just as it was originally, meaning after every item effect.
Now that you do mention it, I can notice that I somehow missed one right after the effect of the X Defense though.

In any case, I'll try to remove them all minus the last one and swap the checks with `else if`s. I'll cross my fingers as hard as I can!

**Comment by ketsuban** [comment]
```
#define ITEM1_X_ATTACK          0x1
#define ITEM1_X_SPEED           0x2
#define ITEM1_X_DEFEND          0x4
#define ITEM1_X_SPATK           0x8
#define ITEM1_X_ACCURACY        0x10
#define ITEM1_X_SPDEF           0x20
```
This strikes me as kind of a wacky order. I put them in Gamefreak's standard order - Attack, Defense, Speed, Special Attack, Special Defense. Perhaps something expects them in this order.

**Comment by LOuroboros** [comment]
> 
> 
> ```
> #define ITEM1_X_ATTACK          0x1
> #define ITEM1_X_SPEED           0x2
> #define ITEM1_X_DEFEND          0x4
> #define ITEM1_X_SPATK           0x8
> #define ITEM1_X_ACCURACY        0x10
> #define ITEM1_X_SPDEF           0x20
> ```
> 
> This strikes me as kind of a wacky order. I put them in Gamefreak's standard order - Attack, Defense, Speed, Special Attack, Special Defense. Perhaps something expects them in this order.

The current order is Game Freak's own order in the Gen. 3 Games *(minus the fact that X Sp. Def. didn't exist in them hence why I added it right after the X Accuracy's effect)*, and in Gen. 4 they seem to order them as Attack, Defense, Speed, Accuracy, Sp. Atk. and Sp. Def. though.

I think I already tried to swap around the orders a bit but I couldn't get a different result. Some items were still swapping in battle.
I guess I'll try again following your order. I hope it works.
If I'm actually not missing anything, then I don't know what could be going wrong here. Perhaps this is caused by a change Egg made...?

**Comment by ExpoSeed** [comment]
#1276 and #1277
