### ISSUE TITLE
Gravity move animation bugged

### ISSUE THREAD

**Issue by Thelostrune** [rh-hideout/pokeemerald-expansion#1400]
Currently the Gravity move animation uses AnimTask_ShakeAndSinkMon, which is copied directly from Strength's script, and pasted one time for each target type. This task does neither shake the mon nor do it for any other targets than the attacker. I've replaced the task with AnimTask_SlackOffSquish, which no matter how and where I put it, can not target any other mon to do the animation other than the attacker. MAX_BATTLERS_COUNT does not seem to work at all here and on a lot of other animation tasks as well.

**Comment by DizzyEggg** [comment]
#1536
