### ISSUE TITLE
Intimidate tries to lower attack of fainted Pokemon in double battle

### ISSUE THREAD

**Issue by surskitty** [rh-hideout/pokeemerald-expansion#1405]
Both I and the opponent had had one pokemon faint, and when I sent in a pokemon with Intimidate as replacement, both their alive and fainted pokemon had their attack lowered.  Then they sent in their own new pokemon. The KO'd pokemon should not have its attack go down.

**Comment by DizzyEggg** [comment]
Cannot reproduce. Please attach a video

**Comment by LOuroboros** [comment]
I couldn't reproduce the specific issue Surskitty talked about, but I did notice that if the Pokémon you defeat on the opposing side is the one on the left, you lose your Pokémon on the right and then you send out a 'mon with Intimidate, the ability won't activate properly.

https://user-images.githubusercontent.com/4485172/121321831-d2d1de00-c8e4-11eb-809e-5d4825aac3a9.mp4

That Lotad has Swift Swim as its ability, so it shouldn't be interfering with Intimidate's effect.

The deceased Seedot had Cholorophyll, Torchic has Blaze and Treecko had Overgrow.

**Comment by DizzyEggg** [comment]
That  video was very helpful and allowed me to repro the issue

**Comment by AsparagusEduardo** [comment]
#1987
