### ISSUE TITLE
A few bugs with Mimikyu / Disguise ability

### ISSUE THREAD

**Issue by kevinmc37** [rh-hideout/pokeemerald-expansion#1407]
When Mimikyu is hit with a move in Disguised form, it correctly transforms into Busted Mimikyu, but if Mimikyu is switched out and switched in again, it should stay in Busted form, and only turn into Disguised form outside battle or reviving it. Currently when you do that switch out-in, Mimikyu is disguised again.

https://bulbapedia.bulbagarden.net/wiki/Disguise_(Ability)

**Comment by kevinmc37** [comment]
Got another problem with Mimikyu/Disguise. When Mimikyu is Disguised, if he uses a recoil move, something weird happens: Disguise tries to activate on the target instead of Mimikyu. Mimikyu loses its disguise but doesn't transform into Busted Mimikyu. I recorded a gif for better understanding

![gif1](https://user-images.githubusercontent.com/32335569/107863552-9ec63f00-6e55-11eb-9b7f-15dd5ee87057.gif)

**Comment by Pyredrid** [comment]
These should likely be made as two separate issues for the repo.

**Comment by DizzyEggg** [comment]
#1565 #1630
