### ISSUE TITLE
Defog's effect and usage string are on the opponent's mon

### ISSUE THREAD

**Issue by Syreldar** [rh-hideout/pokeemerald-expansion#1408]
I have a Glaceon. Opponent has a Breloom that already has set up Leech Seed on my Glaceon.

I use Defog.
opponent uses Close Combat.
The battle proceeds as follows:

Foe Breloom used Defog!
>Effect plays on him.
>Removes my Leech Seed.

Foe Breloom used Close Combat!
Hits my Glaceon.

End of the turn.

**Comment by BuffelSaft** [comment]
I haven't been able to find any problems with Defog; as it doesn't normally remove Leech Seed this might not be an issue with the battle engine.
