### ISSUE TITLE
Infiltrator Not Fully Implemented

### ISSUE THREAD

**Issue by jirachiwish** [rh-hideout/pokeemerald-expansion#1414]
The ability of Infiltrator doesn't bypass the move of Safeguard. A Whimsicott with Infiltrator used the moves of Poison Powder and Stun Spore, but do not affect the target with Safeguard protected.

The following commits in the battle scripts are just used for skipping the battle strings of Safeguard Protected.
https://github.com/DizzyEggg/pokeemerald/commit/738d92e39d13e1af167be3d242c14d4e8ecb3d4d

**Comment by LOuroboros** [comment]
> The ability of Infiltrator doesn't bypass the move of Safeguard. A Whimsicott with Infiltrator used the moves of Poison Powder and Stun Spore, but do not affect the target with Safeguard protected.

Can't confirm. I tried to use Poison Powder using a Torchic with Infiltrator against a Wurmple protected by Safeguard, and they were poisoned normally.

![Untitled3667](https://user-images.githubusercontent.com/4485172/109525051-e670db80-7a8f-11eb-913a-1e5663be4a25.gif)
