### ISSUE TITLE
Rage Powder not updated to gen 6+

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1417]
**Issue:**
From Bulbapedia:
"Generation VI onward
Grass-type Pokémon, Pokémon with Overcoat, Stalwart, Propeller Tail, and Pokémon holding the Safety Goggles are now immune to Rage Powder, such that their attacks are not diverted by it."

Stalwart and Propeller Tail's effects are implemented, but Pokemon with powder immunity are still affected by Rage Powder.

**Example:**
After fixing the other Rage Powder bug (can't be used by grass types as it targets the user, and they're immune to powder moves), this is how it behaves in the battle engine:
![Rage Powder fix 1](https://user-images.githubusercontent.com/28769716/110221512-8e275700-7f31-11eb-8977-ad41b73c7184.gif)
What should happen:
- Snivy and Wingull target Poochyena
- Foongus uses Rage Powder
- Snivy hits Poochyena, Wingull hits Foongus

What actually happens:
- Snivy and Wingull target Poochyena
- Foongus uses Rage Powder
- Snivy and Wingull hit Foongus

**Comment by DizzyEggg** [comment]
The fix was merged a while ago
