### ISSUE TITLE
Thousand Arrows effect is not implemented

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1429]
![1000 arrows](https://user-images.githubusercontent.com/28769716/112827409-cb26d980-90ea-11eb-8eb3-36214a5dcd08.gif)
Thousand Arrows should bypass immunity to ground type moves, but doesn't.

**Comment by ExpoSeed** [comment]
#1453

**Comment by ExpoSeed** [comment]
The knockdown doesn't happen either

**Comment by BuffelSaft** [comment]
Addressed by #1432
