### ISSUE TITLE
Missing config for healing item nerfs

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1444]
Hyper Potions, Fresh Water, Energy Root etc. heal less HP from gen 7 onwards. This was a significant change (e.g. Hyper Potions went from healing 200 HP to 120 HP), so shouldn't there be a config option somewhere for this?

**Comment by LOuroboros** [comment]
> 
> 
> Hyper Potions, Fresh Water, Energy Root etc. heal less HP from gen 7 onwards. This was a significant change (e.g. Hyper Potions went from healing 200 HP to 120 HP), so shouldn't there be a config option somewhere for this?

Yes, there should be one imo. I'll get to it right away.

**Comment by LOuroboros** [comment]
#1445
