### ISSUE TITLE
Exp points glitches while gaining large exp

### ISSUE THREAD

**Issue by veterandrake** [rh-hideout/pokeemerald-expansion#1455]
If B_SCALED_EXP is set to gen 5 or gen 7+ and large exp is earned then exp points glitches for that pokemon
tested on battle_engine and master branch.
Usually happens when exp is greater than 30000.
![exp1](https://user-images.githubusercontent.com/75160712/113562050-1aa56200-9623-11eb-9368-f063e475a177.gif)
![exp2](https://user-images.githubusercontent.com/75160712/113562059-1d07bc00-9623-11eb-9d00-faf81664f82c.png)

**Comment by ultima-soul** [comment]
Resolved in #1521.
