### ISSUE TITLE
Overdrive's animation makes the game crash

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#1473]
> Revo Today at 7:22 PM
> Apparently Toxtricity's signature move crashes pokemon expansion ROM
> the animation specifically

![Untitled4890](https://user-images.githubusercontent.com/4485172/116830597-c9d14c80-ab81-11eb-8831-4381b0c43956.gif)

**Comment by ProjectRevoTPP** [comment]
This issue can be fixed by changing:

https://github.com/rh-hideout/pokeemerald-expansion/blob/02c20c0737b8fabb6bbbbe234233e4be9c3d1060/data/battle_anim_scripts.s#L13364

Change SOUND_PAN_ATTACKER to 0x0.

**Comment by LOuroboros** [comment]
> 
> 
> This issue can be fixed by changing:
> 
> https://github.com/rh-hideout/pokeemerald-expansion/blob/02c20c0737b8fabb6bbbbe234233e4be9c3d1060/data/battle_anim_scripts.s#L13364
> 
> Change SOUND_PAN_ATTACKER to 0x0.

As you can see above, there's a PR available fixing the problem.

**Comment by Meister-anon** [comment]
another way to fix it is, to just put a comma behind every value after "launchtemplate" up to the last value in the row.

That's the way it was done on eerie impulse, I've already tested and it works.

**Comment by DizzyEggg** [comment]
#1474
