### ISSUE TITLE
Poison Heal doesn't work correctly in OW

### ISSUE THREAD

**Issue by Meister-anon** [rh-hideout/pokeemerald-expansion#1476]
It works fine in battle, but if the pokemon is healing from poison, they shouldn't be taking damage in the overworld from it either.

Should be a simple fix, adding an exclusion for pokemon with poisonheal ability should do it.

**Comment by AmbientDinosaur** [comment]
> 
> 
> It works fine in battle, but if the pokemon is healing from poison, they shouldn't be taking damage in the overworld from it either.
> 
> Should be a simple fix, adding an exclusion for pokemon with poisonheal ability should do it.

Strangely enough, this is the correct behavior for Poison Heal. Before the outside of battle effect of poison was removed altogether Gen V, it did affect Pokémon with Poison Heal as well.

**Comment by Meister-anon** [comment]
huh that is weird, its proving difficult to remove as well.  Its not as simple as I thought it would be.
Or at least I just can't figure it out.

**Comment by LOuroboros** [comment]
> It works fine in battle, but if the pokemon is healing from poison, they shouldn't be taking damage in the overworld from it either.

They should. Poison Heal does not heal poisoning in the overworld, and we try to implement such effects as accurately as possible.

I'm closing this.

**Comment by Meister-anon** [comment]
ok so I've been looking at it, and I've about figured out _how_ to block the overworld poison effect, but I can't figure out where to put it.

I've realized I need to put this code somewhere.
u8 i;
for (i = 0; i < PARTY_SIZE; i++)
    {
        if (GetMonAbility(&gPlayerParty[i]) == ABILITY_POISON_HEAL)
            
    }

with this in the includes at the top


#include "constants/abilities.h"

if ya'll want to try and change it , that's my input on how.

I've almost got it, so far I was able to stop the effect from playing but the pokemon is still taking poison damage.
