### ISSUE TITLE
Pokemon's Shadow doesn't dissapear when caught & learn new move

### ISSUE THREAD

**Issue by Meister-anon** [rh-hideout/pokeemerald-expansion#1477]
This is only really noticeable when you level up and learn a new move.

 But the dark circle placeholder for the pokemon's shadow is still there.
Along with the enemy health box.

**Comment by Meister-anon** [comment]
can't remember exactly, but it may only happen on level up from capture exp

**Comment by Blackforest92** [comment]
There seems to be no anomaly in my repo.
I cannot produce the bug.
https://user-images.githubusercontent.com/64682409/116887181-361c8080-ac54-11eb-928f-49fa576cd541.mp4

**Comment by Meister-anon** [comment]
I had to delete a move. and if it matters I was on grass.

I only noticed it  after it came back from changing the move, (I think) so that may be it.

**Comment by Blackforest92** [comment]
Bug is produced,
(1) Pokemon has 4 moves.
(2) Catch the enemy, EXP gained.
(3) Pokemon leveled up and learn new moves,
(4) If your Pokemon already has 4 moves, and you decided that you want to learn new moves. You will be taken to the summary screen.
(5) The shadow will pop up after fading back into the battlefield.

Note : From what i know, The shadow is one (share the same palette) with Battle Interface.

Video : 
https://user-images.githubusercontent.com/64682409/116910108-50178c80-ac6f-11eb-984e-337205e02344.mp4

**Comment by LOuroboros** [comment]
#1539
