### ISSUE TITLE
Flame Burst Issue and Fix

### ISSUE THREAD

**Issue by ShardofComet** [rh-hideout/pokeemerald-expansion#1478]
Flame Burst has an issue in double battles when attacking the pokemon on the right. This code fixes the move so it performs properly no matter which pokemon its used on. (This is my first time submitting an issue and fix so if I did something wrong please let me know so I don't do it again in the future.)

BattleScript_MoveEffectFlameBurst::
	printstring STRINGID_BURSTINGFLAMESHIT
	waitmessage 0x40
	savetarget
	copybyte gBattlerTarget, sBATTLER
	healthbarupdate BS_TARGET
	datahpupdate BS_TARGET
	restoretarget
	tryfaintmon BS_TARGET, FALSE, NULL
	goto BattleScript_MoveEnd

**Comment by LOuroboros** [comment]
Can confirm.
![Untitled4929](https://user-images.githubusercontent.com/4485172/116930096-b2539b80-ac35-11eb-92a8-915523f22236.gif)

**Comment by ShardofComet** [comment]
Sorry. I forgot to test if it would faint the ally pokemon. I fixed that though with this.
BattleScript_MoveEffectFlameBurst::
	printstring STRINGID_BURSTINGFLAMESHIT
	waitmessage 0x40
	savetarget
	copybyte gBattlerTarget, sBATTLER
	healthbarupdate BS_TARGET
	datahpupdate BS_TARGET
	restoretarget
	tryfaintmon BS_TARGET, FALSE, NULL
	setallytonexttarget BattleScript_AllyFaintCheck
	goto BattleScript_MoveEnd
BattleScript_AllyFaintCheck::
	tryfaintmon BS_TARGET, FALSE, NULL
	goto BattleScript_MoveEnd

**Comment by ultima-soul** [comment]
Resolved in #1519.
