### ISSUE TITLE
King's Rock doesn't affect all non-flinching moves past Gen 5?

### ISSUE THREAD

**Issue by kevinmc37** [rh-hideout/pokeemerald-expansion#1483]
This is more of a doubt than an issue, but I was checking the recent Stench battle effect pull request and saw it uses the new list sMovesNotAffectedByStench which contains all flinching moves that are not affected by it. The item King's Rock, prior Gen 5, used a moves' list to decide which moves where affected by it. After Gen 5, all moves that don't cause flinching are afected by it. Check the following link:

https://bulbapedia.bulbagarden.net/wiki/King%27s_Rock#Effect

For example, the move Dragon Rage was affected by King's Rock on Gen 3, but not anymore on Gen 4. On Gen 5+ though, it should be afected by King's Rock again as it doesn't normally cause flinching. Same with for example the moves Fire Punch or Confusion, they were not affected by it prior Gen 5, but they should for next generations.

They're not using the FLAG_KINGS_ROCK_AFFECTED, so I was guessing maybe there was a check on src/battle_util.c. But checking myself on the lines 'case ITEMEFFECT_KINGSROCK_SHELLBELL', it only looks for FLAG_KINGS_ROCK_AFFECTED. It doesn't check which generation the project is set to to decide if it should look for the flag or the new sMovesNotAffectedByStench list.

My guess is a constant should be added on file include/constants/battle_config.h, as different moves are affected on Gen 3 and Gen 4. Add FLAG_KINGS_ROCK_AFFECTED with if statements depending on that constant to those moves, and using sMovesNotAffectedByStench on src/battle_util.c if that constant is Gen 5 or more.

Hopefully someone can tell if I missed some code that manages all of that, but at first glance I think that's something that should be looked at.

**Comment by AmbientDinosaur** [comment]
`ITEMEFFECT_KINGSROCK_SHELLBELL` was not updated when the battle effect for Stench was added. Like you said, adding a new constant to `battle_config.h` is probably the best course of action.

**Comment by kevinmc37** [comment]
Okay, so yesterday I worked on it, but because of my outdated fork I'm unable to do a pull request right now. While I try to fix this, I uploaded the changes here:
[https://github.com/kevinmc37/pokeemerald_updates/commit/431c38bb62882739ff0eb237dddb5139252e5d06](url)

The work consists on what I mentioned in this issue, plus removing the FLAG_KINGS_ROCK_AFFECTED from flinching moves (as they presumibly don't need it because of the King's Rock effect not stacking) and adding the Serene Grace Boost in Gen5+. Didn't add the Water/Fire Pledge boost because those are still not coded. I'll be glad if someone can check the commit and tell me if something is wrong or needs changes

**Comment by LOuroboros** [comment]
> 
> 
> Okay, so yesterday I worked on it, but because of my outdated fork I'm unable to do a pull request right now. While I try to fix this, I uploaded the changes here:
> [https://github.com/kevinmc37/pokeemerald_updates/commit/431c38bb62882739ff0eb237dddb5139252e5d06](url)
> 
> The work consists on what I mentioned in this issue, plus removing the FLAG_KINGS_ROCK_AFFECTED from flinching moves (as they presumibly don't need it because of the King's Rock effect not stacking) and adding the Serene Grace Boost in Gen5+. Didn't add the Water/Fire Pledge boost because those are still not coded. I'll be glad if someone can check the commit and tell me if something is wrong or needs changes

For some reason, the link just redirects to a search for the word "url" in the Issues tab of this repository.

Here's the actual commit: https://github.com/kevinmc37/pokeemerald_updates/commit/431c38bb62882739ff0eb237dddb5139252e5d06

A few quick observations:

1) Serene Grace is already handled in `src/battle_script_commands.c`.

2) If the list of moves in `sMovesNotAffectedByStench` matches the list of moves affected by King's Rock, it would probably be a good idea to rename the list entirely and find a more neutral definition for it.

**Comment by kevinmc37** [comment]
Thanks for fixing the link. So, Serene Grace doubles the effect of King's Rock, and that's not handled right now, it only checks for secondary effects of moves. Should I put that part in src/battle_script_commands.c instead?

Also, Stench and King's Rock work basically the same way, yes.

**Comment by LOuroboros** [comment]
> So, Serene Grace doubles the effect of King's Rock

Does it? [This Japanese Pokémon Wiki explicitly mentions that Serene Grace does not boost the flinch chance of King's rock](https://wikiwiki.jp/boudai/%E3%83%9D%E3%82%B1%E3%83%A2%E3%83%B3%E3%81%AE%E7%89%B9%E6%80%A7%E4%B8%80%E8%A6%A7/%E3%81%A6%E3%82%93%E3%81%AE%E3%82%81%E3%81%90%E3%81%BF).

> 「おうじゃのしるし」などによる怯みの確率は変動しない。

> The probability of frightening due to "Ouja no Shirushi" does not change.

**Comment by ultima-soul** [comment]
#1396 is handling setting King's Rock Affected flags to all affected moves.

**Comment by ultima-soul** [comment]
Resolved in #1396.
