### ISSUE TITLE
Some sprites need to be corrected

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#1488]
Title.

-Minior's Meteor Form looks black in its icon sprite, when it shouldn't.
![](https://media.discordapp.net/attachments/774393519569502268/841120083359039488/Untitled5119.png)

-Popplio's front sprite's normal palette looks like a mix between its regular and its shiny palettes.
![](https://media.discordapp.net/attachments/774393519569502268/841129668798578708/Untitled5125.png)

**Comment by DizzyEggg** [comment]
#1513
