### ISSUE TITLE
Pokemon with hidden abilities have no ability when mega evolved

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1490]
![pokeemerald-0](https://user-images.githubusercontent.com/28769716/118412883-8d106400-b6f0-11eb-93b7-320a26d078de.png)
Noticed this while playing my hack, which uses all three expansion branches. Pic is an Alakazam that has Magic Guard in its base form.

The problem is that megas only have two ability slots assigned in base_stats.h, so if the base mon has its third ability it will get ABILITY_NONE when it mega evolves.

**Comment by ExpoSeed** [comment]
#1491
