### ISSUE TITLE
Melmetal's sprite has a red spot

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#1497]
Forgot to open an issue for this.
Basically title. There's a spot in the sprite that should be green just like the rest of the background.
![Untitled5444](https://user-images.githubusercontent.com/4485172/119063094-a2b2b180-b9ae-11eb-89dd-3b455cf45727.png)

**Comment by Jaizu** [comment]
Sir that's his tail 
![image](https://user-images.githubusercontent.com/18596778/119109973-f4485400-ba21-11eb-8c27-21333f1d4193.png)
