### ISSUE TITLE
New species are missing back animations

### ISSUE THREAD

**Issue by Jaizu** [rh-hideout/pokeemerald-expansion#1522]
This issue makes that Pokémon that doesn't have a back animation defined read garbage data, which can lead into crashes or random back animations.

The table of back anims can be found here:
https://github.com/rh-hideout/pokeemerald-expansion/blob/pokemon_expansion/src/pokemon_animation.c#L215

Note that Spherical Ice provided a temp solution (looking at you people who release games) to disable animations for Pokémon taht don't have one defined: https://discord.com/channels/419213663107416084/774393519569502268/850695295952093214

**Comment by ExpoSeed** [comment]
#1528
