### ISSUE TITLE
Imposter Softlock

### ISSUE THREAD

**Issue by ProjectRevoTPP** [rh-hideout/pokeemerald-expansion#1529]
If you send out an imposter Mon as the second Mon, the game tries to imposter the first pokemon that doesn't have the ability, and it's stuck in a loop forever.

**Comment by ProjectRevoTPP** [comment]
I have more info: this apparently occured against Tate and liza. "2nd pokemon died, sent in imposter, my first pokemon attempted to imposter even though it didn't have that ability and it was stuck trying to imposter"

**Comment by ProjectRevoTPP** [comment]
https://www.twitch.tv/jaaaren/clip/HeadstrongCourteousDaikonKappaClaus-DzZ3aVfqJDJ1L_Sv

A randomizer is involved, but this bug generally seems on the code side rather than something corrupt data wise. I could be wrong though.

**Comment by LOuroboros** [comment]
#1541
