### ISSUE TITLE
As One text glitch

### ISSUE THREAD

**Issue by ProjectRevoTPP** [rh-hideout/pokeemerald-expansion#1530]
When "As One" abilities get announced, the ability text window glitches/blackens.

**Comment by LOuroboros** [comment]
> 
> 
> When "As One" abilities get announced, the ability text window glitches/blackens.

I quickly tested them out, and at a glance, both seem to be working normally.
![AsOneIceRiderEntrance](https://user-images.githubusercontent.com/4485172/121109735-82725780-c7e2-11eb-8bb8-bc598c203ec6.gif)![AsOneShadowRiderEntrance](https://user-images.githubusercontent.com/4485172/121109741-83a38480-c7e2-11eb-8318-ad635186d231.gif)

**Comment by ProjectRevoTPP** [comment]
Maybe its broken on the z_move or mega branch? Im not sure then.
