### ISSUE TITLE
Bug: Doubles AI can't choose strongest move consistently

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1535]
**Scenario:**
This is an inverse double battle with the following AI flags set:
- AI_FLAG_CHECK_BAD_MOVE
- AI_FLAG_TRY_TO_FAINT
- AI_FLAG_CHECK_VIABILITY
- AI_FLAG_PREFER_STRONGEST_MOVE

The AI has a Slowbro and Claydol. I've slightly increased the AI score for using Trick Room, so that being the chosen move is expected here.

**Issue:**
The AI's second choice, which it will use next turn (as that'll be the best option once Trick Room is set), seems to be randomised. It'll often decide to use Signal Beam on Alakazam, which is pretty stupid as it's not very effective and both of its other attacks do more damage. These screenshots are all taken on the first turn after resetting the game, so they're the same scenario:
![pokeemerald-0](https://user-images.githubusercontent.com/28769716/121135191-5e695180-c888-11eb-88c5-8818e3957117.png)
![pokeemerald-1](https://user-images.githubusercontent.com/28769716/121135198-5f9a7e80-c888-11eb-947e-2c919f794ccf.png)
![pokeemerald-2](https://user-images.githubusercontent.com/28769716/121135200-5f9a7e80-c888-11eb-8903-e85e3b2008f8.png)
So the AI is either not determining/storing its strongest move correctly, or there's a score increase somewhere that happens randomly that should be removed. Randomness is great if all three attacks are equally effective, but in this case it should probably go for super-effective STAB Psychic every time, as that's by far its best option.

Also worth mentioning the old AI handled inverse battles correctly, so that's probably not the problem here.

**Comment by BuffelSaft** [comment]
Seems this only happens in doubles, in singles the AI score is always as expected:
![pokeemerald-0](https://user-images.githubusercontent.com/28769716/121472286-175c9700-ca15-11eb-95ef-039d4e670a28.png)

**Comment by Fontbane** [comment]
> Also worth mentioning the old AI handled inverse battles correctly, so that's probably not the problem here. 

Does this happen in a normal double battle too? It could be a problem with inverse battles in the new AI.

**Comment by BuffelSaft** [comment]
Yeah, similar results in a normal double battle. I think part of the problem is that `IncreaseConfusionScore` gives Signal Beam +2 score just because it has a 10% chance to confuse, which gives it the same score as the AI's most damaging move.

**Comment by BuffelSaft** [comment]
99% sure this was a bug on my end and not an issue with the BE, so this can be closed.
