### ISSUE TITLE
Unown (A) is broken

### ISSUE THREAD

**Issue by Jaizu** [rh-hideout/pokeemerald-expansion#1544]
The first Unown species has a broken icon, front sprite and back sprite in-game.
The icon seems to load fine in porymap wild Pokémon tab.
![QlYTjghNXC](https://user-images.githubusercontent.com/18596778/121588155-e04aad80-ca35-11eb-99d4-b8b40e73cb80.gif)
![mGBA_LjjlgiQecK](https://user-images.githubusercontent.com/18596778/121588167-e3459e00-ca35-11eb-873d-632d5646007d.png)

**Comment by AsparagusEduardo** [comment]
#1650
