### ISSUE TITLE
White Smoke prevents stat drops from Shell Smash

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1555]
See gif:
![shell smash](https://user-images.githubusercontent.com/28769716/124370563-1eea2580-dccd-11eb-88a2-a20c32ff0a3d.gif)

White Smoke and similar abilities (Clear Body, Hyper Cutter, Big Pecks etc.) shouldn't prevent self-inflicted stat drops.

**Comment by DizzyEggg** [comment]
Merged a while ago #1560
