### ISSUE TITLE
Disguise doesn't handle the user's recoil moves

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1566]
This is the comment in #1407 created as a separate issue. Can confirm it still happens in the latest version of the battle engine.

![disgusie bug](https://user-images.githubusercontent.com/28769716/125181045-22ddf080-e255-11eb-89d0-ddae9aa5c242.gif)

It seems recoil damage breaks the disguise, but tries to play the form change animation on the target instead. As a result Mimikyu was changed to busted form, but didn't change its sprite.

Not sure what's supposed to happen here, should recoil break the disguise?

**Comment by Syreldar** [comment]
Recoil shouldn't trigger Disguise.

**Comment by DizzyEggg** [comment]
#1630
