### ISSUE TITLE
Cotton Down is affecting a fainted Pokémon in battle

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#1568]
Repost from: https://github.com/ProjectRevoTPP/pokeemerald-ex-speedchoice/issues/4

> 
> 
> **Describe the bug**
> When in a double battle, and an ability activates such as Cotton Down or Frisk, fainted opponents will also be affected. I have only noticed the issue regarding the two listed abilities.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Obtain a pokemon with Cotton Down (Debug menu possible, or reading randomiser log)
> 
>     2. Enter a double battle (earliest would be just before Roxanne)
> 
>     3. Knock out one of the opponents on their side
> 
>     4. Knock out or be attacked on the pokemon with Cotton Down
> 
>     5. Cotton Down will activate, including on the fainted mon
> 
> 
> **Expected behavior**
> Only pokemon that have have not fainted should be affected by abilities.
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/6518223/125319881-14660680-e333-11eb-96a8-342814a8b196.png)
> 
> **Version of EX**
> Originally found on 0.2.4. Replicated on 0.2.6.
> 
> **If applicable, what was version of EX was it known to work on?:**
> N/A
> 
> **Additional context**
> Add any other context about the problem here.

I checked it out on a copy of the latest battle_engine with the only change done being Torchic's ability which was set to Cotton Down, and effectively, it's happening there too.

https://user-images.githubusercontent.com/4485172/125460312-0cb833f6-6160-43e7-9595-c5f0ec7f119e.mp4

**Comment by ProjectRevoTPP** [comment]
Waiting on Frisk to be checked too since it's in the issue description.

**Comment by LOuroboros** [comment]
> 
> 
> Waiting on Frisk to be checked too since it's in the issue description.

I just did. Frisk seems to be working normally on my end. If I made a mistake, please let me know.
Compared to Cotton Down, it doesn't trigger when the user is hit though. It triggers when they enter the battle.

https://user-images.githubusercontent.com/4485172/125811341-d4bc7b82-c017-4833-b2d0-a910de9f9945.mp4

**Comment by LOuroboros** [comment]
#1569
