### ISSUE TITLE
Flickering sprites for Cap, Cosplay Pikachus and Spiky-eared Pichu

### ISSUE THREAD

**Issue by StubbornOne** [rh-hideout/pokeemerald-expansion#1571]
Spiky-eared Pichu:
<img src="https://i.imgur.com/nJmjpxY.gif" />
[https://i.imgur.com/nJmjpxY.gif](url)

Cap Pikachu:
<img src="https://i.imgur.com/cKfDwHo.gif" />
[https://i.imgur.com/cKfDwHo.gif](url)

Cosplay Pikachu (including SPECIES_PIKACHU_COSPLAY):
<img src="https://i.imgur.com/OqG6nUC.gif" />
[https://i.imgur.com/OqG6nUC.gif](url)

When some Pokemon are viewed before moving to the Pikachus, the previous Pokemon appears in the missing moments. I noticed it with Kirlia and Gardevoir; Mudbray didn't have this(?)
<img src="https://i.imgur.com/iNkUDwH.gif" />
[https://i.imgur.com/iNkUDwH.gif](url)

Am a newbie so have no idea how to fix these, apologies

**Comment by ultima-soul** [comment]
Resolved in #1572.
