### ISSUE TITLE
Pikachu Partner Cap backsprite colors are wrong

### ISSUE THREAD

**Issue by kevinmc37** [rh-hideout/pokeemerald-expansion#1576]
As you can see below, the backsprite colors of Pikachu Partner Cap are totally messed up. I guess the frontsprite in its shiny form is also wrong
![pokeemerald_01](https://user-images.githubusercontent.com/32335569/126865230-cfd59ed2-f7fc-46f1-8d22-3a48e62b4991.png)

**Comment by LOuroboros** [comment]
#1978
