### ISSUE TITLE
Thousand Arrows Bad Animation Particle

### ISSUE THREAD

**Issue by ghoulslash** [rh-hideout/pokeemerald-expansion#1585]
![voyager-0](https://user-images.githubusercontent.com/41651341/128546506-67060cd8-5905-4b44-8dc9-b404ba9b0b2e.png)

**Comment by LOuroboros** [comment]
> 
> 
> ![voyager-0](https://user-images.githubusercontent.com/41651341/128546506-67060cd8-5905-4b44-8dc9-b404ba9b0b2e.png)

Can't confirm. The animation is working fine on my end, using a clean and up-to-date copy of the battle_engine.
![%pn_304](https://user-images.githubusercontent.com/4485172/128547828-0a6e0686-d427-45e5-84db-d4255181f734.gif)
