### ISSUE TITLE
Ability pop up activates for the wrong Pokemon if player targets their own mon

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1586]
See gif:
![shields down](https://user-images.githubusercontent.com/28769716/128593548-55837630-92e0-4a4f-9543-0729b5ed1549.gif)
Shields Down blocks the Thunder Wave, but Tyranitar's Sand Stream pops up on the foe's side. Should be Minior's Shields Down on the player's side.

**Comment by DizzyEggg** [comment]
Does this still occur?
