### ISSUE TITLE
PokeNav - Gym Leader Rematches don't trigger

### ISSUE THREAD

**Issue by Jordanar21** [rh-hideout/pokeemerald-expansion#1599]
Haven't gotten a rematch notice.  Would be useful for CEA

**Comment by LOuroboros** [comment]
> 
> 
> Haven't gotten a rematch notice. Would be useful for CEA

And you're 100% sure this is caused by any of the 3 feature branches? Because they don't change the behavior of the Pokénav or Gym Leader rematches, as far as I know.

**Comment by Jordanar21** [comment]
What are the branches? I know of New Mauville and beating E4.

**Comment by LOuroboros** [comment]
> 
> 
> What are the branches? I know of New Mauville and beating E4.

I'm talking about the feature branches hosted in this repository, in other words, the `battle_engine`, the `item_expansion` and the `pokemon_expansion`, and I'm asking you if you're actually sure that any of the 3 branches is causing an issue with Gym Leader rematches.
Otherwise I don't know why did you create this issue post.

**Comment by ExpoSeed** [comment]
If you're here by playing a hack, what hack did you encounter this bug in

**Comment by Jordanar21** [comment]
I don't know if a branch is causing an issue.  I'm playing Emerald EX.

**Comment by LOuroboros** [comment]
> 
> 
> I don't know if a branch is causing an issue. I'm playing Emerald EX.

What is Emerald EX? Are you sure that it uses the feature branches hosted in this repository?

**Comment by Jordanar21** [comment]
![Capture1](https://user-images.githubusercontent.com/63768951/130383207-0975ce4e-b5a6-4527-916d-243be0b75e6a.PNG)

**Comment by LOuroboros** [comment]
> 
> 
> ![Capture1](https://user-images.githubusercontent.com/63768951/130383207-0975ce4e-b5a6-4527-916d-243be0b75e6a.PNG)

That's a picture of the branches in this repository, which doesn't really answer my question at all.

**Comment by Jordanar21** [comment]
This isn't the Emerald EX repository?

**Comment by ExpoSeed** [comment]
this is the repository for pokeemerald expansion, which is a resource for devs to use for their hacks. this repo isn't a complete romhack in and of itself. we don't know of any hack named emerald ex or whether it uses the branches here
