### ISSUE TITLE
If a user defeats a mega evolved Pokémon using Knock Off, its "item stolen" text string gets printed

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#1602]
Title.

https://user-images.githubusercontent.com/4485172/130678722-2fb13c72-b4d4-42f5-8eba-f3cded6b6222.mp4

**Comment by AsparagusEduardo** [comment]
Can't reproduce currently.
![knockoffmega](https://user-images.githubusercontent.com/2904965/135701038-8d8a2bdf-2f01-4b1e-9bc7-ead154c159a1.gif)

**Comment by LOuroboros** [comment]
Most likely fixed back in #1221. Closing.
