### ISSUE TITLE
Tag battles could be improved

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#1604]
Title.

Done:
> When battling alongside Steven in Emerald, his Pokémon are shown to gain experience after the defeat of an opponent Pokémon. This does not happen to a partner's Pokémon in the Multi Battles of Generation IV.

To do:
> Having the player's party be defeated in the Multi Battle with Steven will cause the player to white out. This was also changed in Generation IV, where a white out will not occur until both the player's and the partner's Pokémon are all knocked out.

**Comment by AsparagusEduardo** [comment]
#1980

**Comment by LOuroboros** [comment]
#1980
