### ISSUE TITLE
Pinch berries confuse the wrong Pokemon

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1608]
Pinch berries (Figy Berry, Wiki Berry etc.) confuse the attacking mon:
![pinch berry](https://user-images.githubusercontent.com/28769716/130904015-84ce21a3-17c3-4f8e-8298-052aa46fd855.gif)

They should confuse the mon holding them instead.

Tested on the latest version of the BE.

**Comment by LOuroboros** [comment]
That's also happening in doubles.

https://user-images.githubusercontent.com/4485172/132416853-9af42d24-d430-415c-87e4-723c2dd81f57.mp4

I forgot to mention it this morning, but I also found another situation where they're malfunctioning.
The effect can get triggered right after the user uses a move if they have 50% HP or less, and when that happens, it gets casted twice for some reason.

https://user-images.githubusercontent.com/4485172/132416571-0246585b-ff2d-4624-9dde-8564956c070d.mp4

Strangely enough, both in singles and doubles, this instance of the effect does confuse the right battler.
