### ISSUE TITLE
King's Shield lowers attack if foe uses Dig or Sucker Punch

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1609]
![sucker](https://user-images.githubusercontent.com/28769716/130919700-7c0513c0-cf7a-40e5-b117-4d9233afe8c6.gif)
![kingsshield](https://user-images.githubusercontent.com/28769716/130919707-f013da30-cdd8-4353-bb26-d1923180ee16.gif)
Two related bugs:
- King's Shield lowers attack on the first turn of Dig; this should only happen on the second turn.
- It also lowers attack when the foe uses Sucker Punch; I'm pretty sure Sucker Punch should fail and attack shouldn't be lowered.

**Comment by BuffelSaft** [comment]
I've been told this also happens if the attacker is asleep and selects a contact move. Wouldn't be surprised it also happened if the attacker is fully paralyzed, but haven't tested either to confirm yet.

**Comment by DizzyEggg** [comment]
#1618
