### ISSUE TITLE
Many strings/items/abilities/form changes have a hard time choosing the correct target

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1611]
This seems to be a recurring bug with a lot of features in the battle engine. IMO some of these things should probably be refactored as the current system seems to be quite fragile, so I'm raising it as a general issue.

A few examples because it's probably not clear what I'm on about:
- [ ] Power Herb prints the target's held item when it activates ("Foe ____ became fully charged due its Leftovers!")
- [ ] Schooling will _sometimes_ activate for the wrong Pokémon, especially in doubles, making Wishiwashi useless
- [ ] Pinch berries confuse the attacker
- [ ] Download says it boosts the target's stats
- [x] Multiple abilities activating in the same turn is often buggy (see #1586)

**Comment by StubbornOne** [comment]
Hi, attaching gif showing Schooling problem:
![schooling](https://user-images.githubusercontent.com/81517503/132693842-4ab6fd66-4265-442c-9923-37b816a2cfc8.gif)

**Comment by AsparagusEduardo** [comment]
Edited issue description to have a list of elements.
