### ISSUE TITLE
EFFECT_HIT_ESCAPE is buggy when used with Choice items

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1613]
Bug: If a move with EFFECT_HIT_ESCAPE (U-turn etc.) is used and fails to switch out the user while it's holding a Choice item, the user is not locked into the move and can choose a different one next turn.

Some examples to test and replicate the bug:
- Attacker with Choice Specs uses Volt Switch against a Ground Type
- Attacker with Choice Band uses U-turn while there are no other Pokemon to switch to
- Attacker with Choice Scarf uses Flip Turn against a Pokemon with Storm Drain

**Comment by LOuroboros** [comment]
#1615
