### ISSUE TITLE
Galvanize Explosion + Lightningrod is buggy

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1614]
If a mon with Galvanize uses Explosion against a target with Lightningrod, the fainting animation doesn't play for the exploding mon and its sprite isn't removed from the screen. 

If this happens in a trainer battle the next mon will be sent out as usual, but the exploded mon's sprite will overlap it.

**Comment by DizzyEggg** [comment]
#1635
