### ISSUE TITLE
Milotic's shiny palette is incorrect

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#1629]
Title.
Looks like this:
![](https://media.discordapp.net/attachments/774393519569502268/884256906603024414/mGBA_827.png)

Should look like this:
![](https://images-ext-1.discordapp.net/external/v-vlxVPWR2o-aq95Vliv6PNOt_I6o0ze8sQ9BbbkMLc/https/i.imgur.com/DH6fpBe.png)

**Comment by AsparagusEduardo** [comment]
#1631
