### ISSUE TITLE
Dragon Tail + Stealth Rock activates Weak Armor

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1636]
Scenario:
- Foe uses Dragon Tail, switches out player's mon
- A player mon with Weak Armor is dragged out and takes damage from Stealth Rock
- Weak Armor activates (it shouldn't)

Normally Stealth Rock doesn't activate Weak Armor (so that's good!) but in this case it does, presumably because the previous mon was damaged by Dragon Tail.

Related case that needs testing:
- Does Weak Armor still activate if Dragon Tail is used when there's no Stealth Rock?

**Comment by DizzyEggg** [comment]
Does Weak Armor still activate if Dragon Tail is used when there's no Stealth Rock?

Yes, Weak Armor activates after Dragon Tail is used, the stat changes are applied and the mon is then dragged out.
