### ISSUE TITLE
Dive user stays semi-invulnerable if target has Storm Drain

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1637]
Gif to explain:
![storm drain](https://user-images.githubusercontent.com/28769716/132618793-011a85a8-0ec4-46ce-8e1b-ce74c502c59e.gif)

**Comment by BuffelSaft** [comment]
Doesn't affect Dry Skin or Water Absorb:
![dry skin](https://user-images.githubusercontent.com/28769716/132637811-0de51a23-eda8-4ca6-8f5a-3c962a379186.gif)
![water absorb](https://user-images.githubusercontent.com/28769716/132637782-3f44f20e-e6c8-415d-8fbf-90c8fb9be677.gif)

**Comment by ghoulslash** [comment]
#1764
