### ISSUE TITLE
Held Item name sometimes prints "????????"

### ISSUE THREAD

**Issue by Syreldar** [rh-hideout/pokeemerald-expansion#1638]
https://user-images.githubusercontent.com/42327659/132645389-52c9fcd3-da97-48af-b0cd-dc713d538e57.mp4

![Discord_OPlwuGsCXF](https://user-images.githubusercontent.com/42327659/132644442-c0438c70-785d-4966-aee3-beac0c3f926e.png)
![Discord_zQEXV26LQO](https://user-images.githubusercontent.com/42327659/132644445-1e7129b6-484b-4f6e-9993-5056cf1b83ed.png)

This bug only happens sometimes, can't reproduce consistently/can't locate the issue.

**Comment by DizzyEggg** [comment]
#1641
