### ISSUE TITLE
Round doesn't cause ally to move + ally's Round loses power if faint

### ISSUE THREAD

**Issue by StubbornOne** [rh-hideout/pokeemerald-expansion#1639]
[https://i.imgur.com/ll9utX6.gif](url)
Apologies for large GIF
1. Round currently doesn't let the ally move immediately
2. If I understand correctly, currently Round's power boost is based on the partner being present:
`if (gChosenMove... == MOVE_ROUND && !(gAbsentBattlerFlags & gBitTable[BATTLE_PARTNER...])) basePower *= 2;`
In the screenshot I believe the Sylveon was hitting with a 60-power round (no hard proof though). Don't know that is the correct behaviour, but if not, even if 1 is fixed, the current method may be disrupted by Destiny Bond/Life Orb etc

**Comment by DizzyEggg** [comment]
Fixed by #2602
