### ISSUE TITLE
Echoed Voice power not increasing on next turn

### ISSUE THREAD

**Issue by StubbornOne** [rh-hideout/pokeemerald-expansion#1640]
![echoVoiceCounter](https://user-images.githubusercontent.com/81517503/132697269-d64b4d27-cfcf-4e6f-816f-29e8e93bf544.jpg)
echoVoiceCounter doesn't seem to be incremented or reset
Failed to record battle, apologies. Will try to get one again

**Comment by DizzyEggg** [comment]
@StubbornOne  Could you confirm the fix is working for you?

**Comment by StubbornOne** [comment]
Hi, I believe it's lagging by a turn (2nd turn of use is (basePower * 1)), but otherwise it's working. Thanks!

**Comment by DizzyEggg** [comment]
@StubbornOne all good now? 😄

**Comment by StubbornOne** [comment]
@DizzyEggg Yep! :)
