### ISSUE TITLE
Alolan Sandshrew and Sandslash have no entries in gSpeciesToNationalPokedexNum

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1644]
This is very dangerous, as the game will still write the dex seen/caught flags somewhere outside the bounds of the dex flags. In my case this was two slots in the PC, so receiving an Alolan Sandshrew corrupted the Pokemon in those two slots.

**Comment by ultima-soul** [comment]
Resolved in #1645.
