### ISSUE TITLE
Static shouldn't paralyze electric types

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1653]
![static](https://user-images.githubusercontent.com/28769716/133169347-2ed25811-3484-4a0e-b0fe-b52b40efd82d.png)
If B_PARALYZE_ELECTRIC >= GEN_6, static shouldn't affect electric types.

The issue is that `CanParalyzeType(u8 battlerAttacker, u8 battlerTarget)` checks if the target can be paralyzed, but not the attacker.

**Comment by ghoulslash** [comment]
I believe #1358 `CanBeParalyzed` will fix this

**Comment by ultima-soul** [comment]
Resolved in #1358.
