### ISSUE TITLE
Clanging Scales should hit both foes

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1654]
Normally I'd just PR a fix for this, but I think this change will need testing - what happens if a move that lowers the user's stats hits two targets? Does it lower stats twice (it should only be once)?

**Comment by ghoulslash** [comment]
The defense is indeed lowered twice. I assume it should only lower once as well but this may need confirmation from original games.

![clangingscales](https://user-images.githubusercontent.com/41651341/140648314-520d859f-231b-4dd3-9b8d-408ecbbddd25.gif)

**Comment by kleeenexfeu** [comment]
It looks like a side effect of the moveend command looping the battlescript for spread moves.
