### ISSUE TITLE
Rototiller Target Selection

### ISSUE THREAD

**Issue by ghoulslash** [rh-hideout/pokeemerald-expansion#1656]
As shown in the GIF, after selecting rototiller, sableye continues to blink as a target indefinitely. Rototiller should also be highlighting every battler instead of just the user's side. Flower shield has the same issue. 

This is caused by `MOVE_TARGET_FOES_AND_ALLY | MOVE_TARGET_USER`. Ideally, a new target flag, e.g. `MOVE_TARGET_ALL` should be created.

![rototiller_selection](https://user-images.githubusercontent.com/41651341/133613758-c78925ec-89a7-4d65-9ed7-23b81f18e986.gif)

**Comment by AsparagusEduardo** [comment]
#1657
