### ISSUE TITLE
Update Brick Break to its modern effect/add config?

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1669]
In Gen 4+, Brick Break can also break screens on the ally's side of the field. Not sure _why_ anyone would want to do that, or if it's worth making it a config option.

In Gen 5+, Brick Break doesn't remove screens if the target is immune to Brick Break.

More importantly, it should also break Aurora Veil.

**Comment by AsparagusEduardo** [comment]
#1889
