### ISSUE TITLE
Mon icon overlaps textbox when changing form

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#1683]
When using a form-changing item with the last mon in the party, the icon overlaps the textbox.
![image](https://user-images.githubusercontent.com/2904965/134787770-b4422be4-5993-4f9c-9afb-91db3f9fbf4a.png)

**Comment by LOuroboros** [comment]
Should I fix this right now, or wait until #1375 is merged?

**Comment by AsparagusEduardo** [comment]
> Should I fix this right now, or wait until #1375 is merged?

It's already merged

**Comment by AsparagusEduardo** [comment]
#1685
