### ISSUE TITLE
The Safari Zone is broken

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1700]
Tested using the battle engine branch on its own with a downloaded save file:
![safari zone broken](https://user-images.githubusercontent.com/28769716/135587070-0e317665-d587-432d-98e6-10245010e46c.gif)
This is due to some recent change - I suspect it was #1538, as that made changes to `battle_controller_opponent.c`.

Someone found the bug in the latest version of my hack, but it's not  present the previous one, and between those versions this was the only change made to `battle_controller_opponent.c`, which is why I suspect this PR is the cause. Will test to confirm.

**Comment by LOuroboros** [comment]
Can confirm.
![%pn_1184](https://user-images.githubusercontent.com/4485172/135588823-37975752-11df-463f-a6cd-3bc3391bf7bb.gif)

**Comment by AsparagusEduardo** [comment]
#1701
