### ISSUE TITLE
Sleep Talk doesn't call other moves.

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#1707]
Discovered by dekzeh#4128 on Discord
https://clips.twitch.tv/ImportantGleamingPorpoiseTooSpicy-uu8g1TcQ5LPYhtoB

Confirmed:
![sleeptalk](https://user-images.githubusercontent.com/2904965/135704462-f46c10c8-45ff-4a1d-a091-d75ed8778465.gif)

**Comment by Jaizu** [comment]
Should be closed.

**Comment by LOuroboros** [comment]
#1708
