### ISSUE TITLE
Issues with interaction between Soundproof and Perish Song

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#1713]
When Perish Song is used by a mon with Soundproof, it cancels the entire move instead of applying it to the rest of the battlers.
![perishsong](https://user-images.githubusercontent.com/2904965/135729258-f71f3203-a90b-4572-b32b-da71a9f54712.gif)

**Comment by ghoulslash** [comment]
#1732
