### ISSUE TITLE
Electric, Misty and Psychic Terrains aren't disappearing after 5 turns.

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#1751]
Electric
![electric terrain](https://user-images.githubusercontent.com/2904965/137049667-f3431647-f537-4e1f-91ca-68463f535a21.gif)
Misty
![gif](https://user-images.githubusercontent.com/2904965/137050061-249bf2f2-4a6d-48f4-8ad9-fa4affbb5b5b.gif)
Psychic
![gif](https://user-images.githubusercontent.com/2904965/137050297-fb1676c4-9b6a-465c-93f1-eecdefce538f.gif)
Grassy Terrain is disappearing correctly.
![gif](https://user-images.githubusercontent.com/2904965/137049954-afe53173-5461-4622-b04a-e7e8b2318b01.gif)

**Comment by ghoulslash** [comment]
#1754
