### ISSUE TITLE
Config for catching mon in semi-vulnerable state

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#1761]
From Gen 4 onwards, Pokémon shouldn't be able to be caught in a semi-invulnerable state.
![theyflynow](https://user-images.githubusercontent.com/2904965/137234647-095057d4-7110-4162-85f3-480aba2f77df.gif)
Source: https://bulbapedia.bulbagarden.net/wiki/Semi-invulnerable_turn

**Comment by AsparagusEduardo** [comment]
Tested from Gen 5, it doesn't allow to use the ball, similar to how it doesn't allow the use against multiple wild mon.
![digdug](https://user-images.githubusercontent.com/2904965/137404870-9e8390e3-08fd-4465-bdf1-6b24359cc3bc.gif)

**Comment by LOuroboros** [comment]
#1768
