### ISSUE TITLE
Multi target moves are broken 

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1767]
Some time between the last master branch update and now this line was added to `case MOVEEND_NEXT_TARGET` in `Cmd_moveend`: `gBattleStruct->atkCancellerTracker = 0; // Run all cancellers on next target`

This causes things like PP, paralysis, confusion, etc. to be checked when hitting each target of a multi-target move, instead of once when the move is used. Examples: 
- Paralyzed mon uses Lava Plume, can move, and hits its ally. It's then fully paralyzed when trying to hit the next target.
- Mon uses Earthquake with 1 PP left. It hits the first target, then has no PP left and can't hit the other targets as a result.

**Comment by BuffelSaft** [comment]
> This was introduced for prankster because the battler `B_POSITION_OPPONENT_RIGHT` was not blocking a prankster'ed move due to CANCELLER_PRANKSTER not getting called again. So prankster will have to be reworked when this bug is fixed.

Could this be fixed by only calling `CANCELLER_PRANKSTER `? We could change the canceller enums into proper defines, make `CANCELLER_PRANKSTER ` the last one and skip all the previous cancellers.

So something like: `gBattleStruct->atkCancellerTracker = CANCELLER_PRANKSTER;`

**Comment by AsparagusEduardo** [comment]
#1771
