### ISSUE TITLE
Magic bounce bug in double battles

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#1774]
Found this while testing #1773 .

Magic Bounce works differently with moves like growl in double battles depending on the position of the mon with the ability.

In this first GIF, Wurmple has Magic Bounce and the wild Taillow is affected by the growl like it should. The bounced-back attack affects only Torchic.
![bounceleft](https://user-images.githubusercontent.com/2904965/137595401-d36c4a03-affa-40df-a1be-ffef54aeb67d.gif)
In this second GIF, the wild Taillow has Magic Bounce but it blocks it for both Wurmple and itself. The bounced-back attack affects both Torchic and my Taillow
![bounceright](https://user-images.githubusercontent.com/2904965/137595403-0314c09a-7608-43e2-8bbb-befcabcae11a.gif)

Bulbapedia doesn't specify if the bounced-back attack would affect both, so I don't know how that aspect should be handled.

**Comment by DizzyEggg** [comment]
I checked how it works on Showdown and the behaviour is always the same regardless of position of the mons. That is:
- Growl is bounced back and affects both pokemon
- Growl still affects the partner of the pokemon with Magic Coat / Magic Bounce
