### ISSUE TITLE
Trainer item theft not updated to gen 5+

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1778]
Ghoulslash's recent PR allows trainers to steal items from the player and restores them afterwards, but there's another aspect of trainer item theft that isn't handled. In gen 5+, items that the player steals from a trainer aren't kept after battle. This also applies to items that the AI gives you when it uses Trick/Switcheroo.

**Comment by Bassoonian** [comment]
Fixed by #4605
