### ISSUE TITLE
Contrary animation bug

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#1783]
When a mon with Contrary uses a move that would raise one of its stats, it still plays the Stat Up animation despite lowering the stat
Power-up Punch
![powerpunch2](https://user-images.githubusercontent.com/2904965/137645147-ef01b9e8-1d2e-4d26-aff7-848ebc71faba.gif)
Diamond Storm
![diamondstorm](https://user-images.githubusercontent.com/2904965/137645151-8a3e2f2f-b353-4e6f-89af-4955ea986eba.gif)

**Comment by LOuroboros** [comment]
After reading the code, I think I can provide some insight. Hopefully I didn't misunderstand.

Currently, there's at least 2 different ways to display the stat de/buff animation.
Diamond Storm uses the `EFFECT_DEFENSE_UP2_HIT`. Its BattleScript, `BattleScript_EffectDefenseUp2Hit`, sets the move's effect to `MOVE_EFFECT_DEF_PLUS_2`.
`MOVE_EFFECT_DEF_PLUS_2` eventually ends jumping to `BattleScript_StatUp`.
Now here's the thing, `BattleScript_StatUp` doesn't call `playstatchangeanimation`, it calls `playanimation` instead, and `playanimation` does not handle Contrary.

If we go deeper into this rabbit hole of code, `playanimation` calls the animation script for de/buffing stat when needed, that is, `General_StatsChange`, which in turn calls the `AnimTask_StatsChange`.
This is probably a good place to throw in a check for Contrary.

**Comment by ghoulslash** [comment]
#1888
