### ISSUE TITLE
Ensure all non-standard damaging moves can be seen by AI

### ISSUE THREAD

**Issue by Xavion3** [rh-hideout/pokeemerald-expansion#1794]
After some reports and testing indicated several moves that can't be seen correctly, making this more as a place to track them all. I'll be going through and testing every move to try and narrow this list, out of the eight moves checked so far only one works correctly though so not looking great yet. Some moves may be in multiple lists, this was just made quickly.

Fully Variable Power:
- [ ] Beat Up
- [x] Crush Grip
- [ ] Dragon Energy
- [ ] Electro Ball
- [ ] Eruption
- [x] Flail
- [ ] Fling
- [ ] Frustration
- [x] Grass Knot
- [x] Gyro Ball
- [ ] Heat Crash
- [ ] Heavy Slam
- [ ] Hidden Power
- [x] Low Kick
- [ ] Magnitude
- [ ] Natural Gift
- [ ] Pika Papow
- [ ] Power Trip
- [ ] Present
- [ ] Punishment
- [ ] Return
- [ ] Reversal
- [ ] Spit Up
- [ ] Stored Power
- [ ] Trump Card
- [ ] Veevee Volley
- [ ] Water Spout
- [ ] Wring Out

Situationally Boosted Power/Damage:
- [ ] Acrobatics
- [ ] Assurance
- [ ] Avalanche
- [ ] Behemoth Bash
- [ ] Behemoth Blade
- [ ] Bolt Beak
- [ ] Brine
- [ ] Dynamax Cannon
- [ ] Earthquake
- [ ] Echoed Voice
- [ ] Facade
- [ ] Fire Pledge
- [ ] Fishious Rend
- [ ] Fury Cutter
- [ ] Fusion Bolt
- [ ] Fusion Flare
- [ ] Grass Pledge
- [ ] Grav Apple
- [ ] Gust
- [ ] Hex
- [ ] Ice Ball
- [ ] Knock Off
- [ ] Lash Out
- [ ] Payback
- [ ] Pursuit
- [x] Retaliate
- [ ] Revenge
- [ ] Rising Voltage
- [ ] Rollout
- [ ] Round
- [ ] Smelling Salts
- [ ] Stomp
- [ ] Stomping Tantrum
- [ ] Surf
- [ ] Triple Kick
- [ ] Twister
- [ ] Venoshock
- [ ] Wake-Up Slap
- [ ] Water Pledge
- [ ] Weather Ball
- [ ] Whirlpool

Minimize Boost:
- [ ] Astonish - Gen 3
- [ ] Body Slam - Gen 6+
- [ ] Double Iron Bash - Gen 7
- [ ] Dragon Rush - Gen 6+
- [ ] Extrasensory - Gen 3
- [ ] Flying Press - Gen 6+
- [ ] Heat Crash - Gen 6+
- [ ] Heavy Slam - Gen 7+
- [ ] Needle Arm - Gen 3
- [ ] Phantom Force - Gen 6
- [ ] Shadow Force - Gen 6
- [ ] Steamroller - Gen 5-7 (Move not in gen 8 to confirm)
- [ ] Stomp - Gen 2+

Multi-Hit Moves:
- [ ] Arm Thrust
- [ ] Barrage
- [ ] Beat Up
- [ ] Bone Rush
- [ ] Bonemerang
- [ ] Bullet Seed
- [ ] Comet Punch
- [ ] Double Hit
- [ ] Double Iron Bash
- [ ] Double Kick
- [ ] Double Slap
- [ ] Dragon Darts
- [ ] Dual Chop
- [ ] Dual Wingbeat
- [ ] Fury Attack
- [ ] Fury Swipes
- [ ] Gear Grind
- [ ] Icicle Spear
- [ ] Pin Missile
- [ ] Rock Blast
- [ ] Scale Shot
- [ ] Spike Cannon
- [ ] Surging Strikes
- [ ] Tail Slap
- [ ] Triple Axel
- [ ] Triple Kick
- [ ] Twineedle
- [ ] Water Shuriken

Set Damage:
- [ ] Dragon Rage
- [ ] Endeavor
- [ ] Final Gambit
- [ ] Nature's Madness
- [x] Nightshade
- [ ] Psywave
- [ ] Seismic Toss
- [ ] Sonic Boom
- [ ] Super Fang

**Comment by AlexOn1ine** [comment]
According to my sophisticated research (I checked function `CalcMoveBasePower`) everything should be implemented. For `Minimize Boost` there is a flag `minimizeDoubleDamage` for effected moves.

**Comment by AlexOn1ine** [comment]
Closing this. Everything should be handled in `AI_CalcDamage`. If something was missed a new issue can be opened.
