### ISSUE TITLE
Hurricane's animation is broken

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1827]
![hurricane](https://user-images.githubusercontent.com/28769716/139518411-43597321-4675-48e0-b27f-6678e55b38b2.gif)

This was tested on a clean copy of the BE.

**Comment by Blackforest92** [comment]
I think it has something to do with this [PR](https://github.com/rh-hideout/pokeemerald-expansion/commit/cb9f4fbb429712080541f5611a024f0c3ab5f6c9). I tested grassy terrain and psychic terrain, they're both produce the same effect.

**Comment by BuffelSaft** [comment]
> I think it has something to do with this [PR](https://github.com/rh-hideout/pokeemerald-expansion/commit/cb9f4fbb429712080541f5611a024f0c3ab5f6c9). I tested grassy terrain and psychic terrain, they're both produce the same effect.
Can confirm, just reverted it and tested, that fixed the problem.

**Comment by LOuroboros** [comment]
There wasn't a need to revert the PR, the only thing missing is the `.lz` extension for the tilemaps that were modified.

**Comment by BuffelSaft** [comment]
> There wasn't a need to revert the PR, the only thing missing was the `.lz` extension in `src/graphics.c` for the tilemaps that were modified.

Ah ok, didn't realise it would be that simple to fix.
