### ISSUE TITLE
Corrosion doesn't work

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1830]
![corrosion](https://user-images.githubusercontent.com/28769716/139523796-975cbe1e-efc9-4d3c-8878-6a4568b5d543.gif)
Pokemon with Corrosion can't poison Poison or Steel types. The move animation will play, but the target won't be inflicted with the poison/toxic status.

**Comment by ghoulslash** [comment]
#1849
