### ISSUE TITLE
Add Contest data for Gen VIII moves

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#1841]
Leaving this as a reminder to update with Gen 8 moves. However, the source of Gen 4-7 moves (https://pokemonurpg.com/info/contests/rse-move-list/) hasn't updated with Gen 8 data, so this issue might be open for a while.

**Comment by LOuroboros** [comment]
> However, the source of Gen 4-7 moves (pokemonurpg.com/info/contests/rse-move-list) hasn't updated with Gen 8 data

The spreadsheet is updated though. There's a notice in that same page.

> WARNING: Generation 8 Moves have been added to URPG. Currently, they are only listed on the below Spreadsheet. Please CTRL+F there to find those moves.

![firefox_1724](https://user-images.githubusercontent.com/4485172/139754421-d6bf4756-1b1d-4ff7-ad03-0189ffd138c6.png)

**Comment by AsparagusEduardo** [comment]
oh! thank you!, just needs to add the data then :)
