### ISSUE TITLE
please merge zmove

### ISSUE THREAD

**Issue by sayseong** [rh-hideout/pokeemerald-expansion#1844]
I am very expect zmove and see this wift pull requests please merge this。

**Comment by ghoulslash** [comment]
this is completely innapropriate.

**Comment by LOuroboros** [comment]
To further explain, pull requests, specially big ones like the Z-Moves PR, need to be checked and tested carefully by the reviewers before being merged.
The reviewers, however, are human beings with their own lives and hobbies. They can't dedicate all of their time to this community made project.

The Z-Move PR will be merged when it's been properly tested and deemed ready to be merged.

**Comment by sayseong** [comment]
Thank you for your explanation, I thought you forgot this thing
