### ISSUE TITLE
EFFECT_SPEED_UP_HIT raises speed when KO'ing the last mon in a party

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1857]
In gen 8, this move effect doesn't activate if the move KOs the last mon in a party. Similar move effects (EFFECT_ATTACK_UP_HIT, EFFECT_DEFENSE_UP_HIT, EFFECT_FELL_STINGER) need to be tested to see if they behave the same way, and if so, they should all be fixed too.

**Comment by ghoulslash** [comment]
#1862
