### ISSUE TITLE
Primal Reversion doesn't correctly work in doubles

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#1860]
Sometimes it activates, sometimes it doesn't.
![](https://media.discordapp.net/attachments/774393519569502268/905806763209678890/pn_1767.gif)

**Comment by LOuroboros** [comment]
I *think* I successfully solved this problem?
It seems to be a matter of rewriting [this nested check](https://github.com/rh-hideout/pokeemerald-expansion/blob/battle_engine/src/battle_util.c#L8887-L8892) to:
```c
    if (gBattleTypeFlags & BATTLE_TYPE_DOUBLE
     && IsPartnerMonFromSameTrainer(battlerId)
     && (mega->alreadyEvolved[partnerPosition] || (mega->toEvolve & gBitTable[BATTLE_PARTNER(battlerId)])))
        return FALSE;
```

**Comment by AsparagusEduardo** [comment]
#1861
