### ISSUE TITLE
Shell Side Arm not implemented correctly

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1868]
Sorry, I might be a bit late to this, but I happened to be going through some of these pull requests and noticed there are a few problems here.

1. The way Shell Side Arm was implemented is inconsistent with how it actually works in the official games. It's supposed to choose the damage category at the beginning of the turn, and not mid-turn. See [here](https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8508168).
2. It doesn't take into account Reflect or Light Screen. See link in 1.
3. It doesn't take into account Wonder Room. See [here](https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8707046). Similar things like Body Press and Download may be implemented incorrectly in other places in your battle engine, but I haven't checked.
4. The AI would have no idea how to use it properly due to this implementation. If you hooked it directly into the damage calculator, it would work much better for the AI, and you wouldn't have to worry about a global variable being set incorrectly.
5. In Link Battles the animation wouldn't play correctly because ``gSwapDamageCategory`` isn't being sent over.

This is also just a general note based on things I've seen in a few places, but is there a specific reason global variables are being used to handle things like this? Why not just add a field in ``gBattleStruct`` instead? It's automatically cleared at the beginning of each battle, and it takes up no extra static memory.

_Originally posted by @Skeli789 in https://github.com/rh-hideout/pokeemerald-expansion/issues/1817#issuecomment-962477674_

**Comment by LOuroboros** [comment]
Relevant information about how the move's effect works at a code level in SwSh, courtesy of Anubis *(a trustworthy dataminer)* and Marty from the Smogon Forums.

https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-9595743

**Comment by AlexOn1ine** [comment]
> The way Shell Side Arm was implemented is inconsistent with how it actually works in the official games. It's supposed to choose the damage category at the beginning of the turn, and not mid-turn. See [here](https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8508168).

Is this correct or did Showdown never bother to fix it? I did some tests and according do Showdown it does recalc mid-turn

```
Turn 1

The opposing Dragapult used Agility!
The opposing Dragapult's Speed rose sharply!

Slowbro used Shell Side Arm!
It's not very effective...
(The opposing Dragapult lost 19% of its health!)
(Physical Shell Side Arm)

Turn 2

The opposing Dragapult used Reflect!
Reflect made the opposing team stronger against physical moves!

Slowbro used Shell Side Arm!
It's not very effective...
(The opposing Dragapult lost 10% of its health!)
(Physical Shell Side Arm)
```

**Comment by AlexOn1ine** [comment]
So I watched the linked vod and it looks like nobody checked the damage calcs. 
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/d405a325-6f1e-4e17-a2a0-dd238c28a299)

Slowbro does almost 100% to a Gardevoir without reflect. In the vod Shell Side Arm did 50% so it has to recalc mid-turn. The only reason people thought it doesn't is doesn't is because of the animation.

**Comment by BuffelSaft** [comment]
> Slowbro does almost 100% to a Gardevoir without reflect. In the vod Shell Side Arm did 50% so it has to recalc mid-turn. The only reason people thought it doesn't is doesn't is because of the animation.
The damage it deals still works like every other move, but it chooses whether it's physical or special at the start of the turn and can't change category mid turn to respond to e.g. Iron Defense being used before it hits. That video does make it look like It's affected by Reflect though - it switched to the special version the turn after Reflect was used.

**Comment by AlexOn1ine** [comment]
> > Slowbro does almost 100% to a Gardevoir without reflect. In the vod Shell Side Arm did 50% so it has to recalc mid-turn. The only reason people thought it doesn't is doesn't is because of the animation.
> 
> The damage it deals still works like every other move, but it chooses whether it's physical or special at the start of the turn and can't change category mid turn to respond to e.g. Iron Defense being used before it hits. That video does make it look like It's affected by Reflect though - it switched to the special version the turn after Reflect was used.

I think this one will need extensive testing in-game since it looks like that competitive play doesn't seem to care much for it. I don't have a any newer Pokemon games so would be great if someone is open to do some testing. 

It's a pretty old issue so would be nice to finally take care of it.
