### ISSUE TITLE
AI: CanAttackerFaintTarget doesn't do what the name implies

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1874]
`CanAttackerFaintTarget` checks if the _current move_ can faint the target. To know if the attacker can faint the target, all of the attacker's damaging moves should be checked. This is a problem as `CanAttackerFaintTarget` is used in the logic for many status move checks (e.g. `ShouldLowerEvasion`), but instead of checking if the AI can KO its target, it's checking if the status move it's calculating a score for can KO the target. Naturally, no status move will KO the target, so this check does nothing and is causing the AI to behave very stupidly in some situations.

**Comment by ghoulslash** [comment]
#1875
