### ISSUE TITLE
EFFECT_RAMPAGE not updated to modern standards

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1893]
This is Thrash, Outrage etc. 
From Gen 5 onwards:
"It is disrupted if it is not successful due to missing, sleeping, paralysis, freeze, flinching, a Protecting target, Ghost-type, or Wonder Guard immunity. If a disruption occurs on what would have been the final, confusion-inducing turn of Thrash, the user will still become confused."

In gen 3, Thrash can keep going even if a ghost type switches into it on the second turn, so if it lasts three turns it gives the opponent a free turn.

**Comment by AsparagusEduardo** [comment]
#1925
