### ISSUE TITLE
Small battle_engine changes needed after the item_expansion revamp

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#1896]
It feels like the BE needs some changes.
`ITEM_MEGA_BRACELET` and `ITEM_Z_RING` should be replaced with their new alternatives, and `Cmd_handleballthrow` should be corrected so it won't try to use `gBattleResults.usedMasterBall` which was removed from the IE.

**Comment by AsparagusEduardo** [comment]
When IE is merged into BE, all instances of  `gBattleResults.usedMasterBall` are deleted, so I don't think there's an issue there. PR coming soon

**Comment by AsparagusEduardo** [comment]
#1898
