### ISSUE TITLE
Wish is broken

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1915]
Just had a report of wish restoring 1 HP when used by an Alomomola, and looking at the code I don't follow where it's getting the HP value to restore - shouldn't it be stored somewhere on use and then read when it heals? The whole point of the gen 5 mechanic is that the user can switch out and then the target will receive half of the user's max HP. Currently it's reading from a field that only includes mons that are in battle, so it's definitely not doing that.

**Comment by ghoulslash** [comment]
#1924
