### ISSUE TITLE
Some Poké Ball effects may or may not be wrong

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#1921]
I'm dropping this here as a reminder to be checked someday.
First things first, I think the Net Ball's multiplier is wrong.
Currently it's set to 50, which is x5 *(if I'm not misreading)* `if B_NET_BALL_MODIFIER >= GEN_7`, when it should be set to 35, which is x3.5.

Secondly, the effect of the Nest Ball *may* be incorrect, I'll proceed to copy-paste my message on Discord:
> In USUM's source code, GF has a file containing functions to handle the catch rate boost of the Heavy, Moon and Level Balls specifically, and only those. Weird.
> Found the Nesuto Booru :PogChamp:
> Okay, so basically:
> ```c
> if (gBattleMons[gBattlerTarget].level < 30)
> {
>     ballMultiplier = 41 - gBattleMons[gBattlerTarget].level;
>     if (ballMultiplier > 40)
>         ballMultiplier = 40;
>     // and here, they have a return that passes `ballMultiplier / 10` through a macro called FX32_CONST that does a bit of bitshifting and shit
> }
> ```
> I'm not sure if that last bit with the `return` matters, but if not, then the BE should be mostly correct, ignoring that there's no division by 10 and that the value of `ballMultiplier` isn't being set to 40 if it's bigger than 40 in the BE, which I'm assuming it's done in USUM's source code as a safety measure.
> In case anyone wants to give it a check straight from the source code: https://www.toptal.com/developers/hastebin/ravakayoso.php

Link: https://www.toptal.com/developers/hastebin/repixufuco.php

**Comment by AsparagusEduardo** [comment]
For the first point, #2259 .

Regarding the 2nd one, I looked at the USUM source code and it seems that it's a failsafe in case you get a Lvl 0 mon in battle. Don't see much point in adding that failsafe, as it's not something that would occur in regular gameplay afaik.

**Comment by LOuroboros** [comment]
Did you check the other balls too, @AsparagusEduardo? :eyes:

**Comment by AsparagusEduardo** [comment]
> Did you check the other balls too, @AsparagusEduardo? eyes

Yes, they're fine.
