### ISSUE TITLE
Sticky Web's speed drop doesn't activate Defiant

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1941]
I've also had reports of Intimidate failing to activate Defiant in double battles, so I assume there's an issue with the way Defiant/Competitive are activated (possibly something to do with setting the target battler?).

**Comment by BuffelSaft** [comment]
Found the problem, it's this line: 'gSpecialStatuses[gBattlerTarget].changedStatsBattlerId != gBattlerTarget)'. Removing it fixes the problem, but I'm not sure why it's there, so removing might break something else.

**Comment by kleeenexfeu** [comment]
> Found the problem, it's this line: `gSpecialStatuses[gBattlerTarget].changedStatsBattlerId != gBattlerTarget)`. Removing it fixes the problem, but I'm not sure why it's there, so removing might break something else.

It might want to do gSpecialStatuses[gBattlerTarget].changedStatsBattlerId != gBattlerAttacker instead ? Or gActiveBattler ? To not activate defiant if you lower your own stats

**Comment by ghoulslash** [comment]
#1932
