### ISSUE TITLE
Finish move animations

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1945]
Some moves have placeholder animations, or no animations at all. Some of the placeholders may be fine as is, but I've listed most of them anyway:

LGPE:
- [ ]  Move_ZIPPY_ZAP
- [ ]  Move_SPLISHY_SPLASH
- [ ]  Move_FLOATY_FALL
- [ ]  Move_PIKA_PAPOW
- [ ]  Move_BOUNCY_BUBBLE
- [ ]  Move_BUZZY_BUZZ
- [ ]  Move_SIZZLY_SLIDE
- [ ]  Move_GLITZY_GLOW
- [ ]  Move_BADDY_BAD
- [ ]  Move_SAPPY_SEED
- [ ]  Move_FREEZY_FROST
- [ ]  Move_SPARKLY_SWIRL
- [ ]  Move_VEEVEE_VOLLEY

SwSh:
- [ ] Move_DYNAMAX_CANNON (Move_HYPER_BEAM)
- [x] Move_TEATIME (Move_MILK_DRINK)
- [ ] Move_COURT_CHANGE (Move_TRICK_ROOM)
- [ ] Move_DECORATE (Move_FLOWER_SHIELD)
- [ ] Move_SNAP_TRAP (Move_BITE)
- [ ] Move_BEHEMOTH_BLADE (Move_SACRED_SWORD)
- [ ] Move_BEHEMOTH_BASH (Move_SUNSTEEL_STRIKE)
- [x] Move_SPIRIT_BREAK (Move_PSYCHIC)
- [x] Move_FALSE_SURRENDER (Move_FEINT)
- [ ] Move_ETERNA_BEAM (Move_HYPER_BEAM)
- [x] Move_EXPANDING_FORCE
- [x] Move_STEEL_ROLLER (Move_GYRO_BALL)
- [x] Move_SCALE_SHOT
- [x] Move_METEOR_BEAM
- [x] Move_MISTY_EXPLOSION
- [x] Move_GRASSY_GLIDE
- [x] Move_RISING_VOLTAGE
- [x] Move_SKITTER_SMACK
- [x] Move_BURNING_JEALOUSY (Move_OVERHEAT)
- [x] Move_LASH_OUT
- [x] Move_POLTERGEIST
- [x] Move_CORROSIVE_GAS
- [x] Move_FLIP_TURN
- [x] Move_TRIPLE_AXEL
- [x] Move_DUAL_WINGBEAT
- [x] Move_SCORCHING_SANDS
- [x] Move_JUNGLE_HEALING (Move_AROMATHERAPY)
- [x] Move_WICKED_BLOW
- [x] Move_SURGING_STRIKES
- [x] Move_THUNDER_CAGE
- [x] Move_DRAGON_ENERGY
- [x] Move_FREEZING_GLARE
- [x] Move_FIERY_WRATH
- [x] Move_THUNDEROUS_KICK
- [x] Move_GLACIAL_LANCE
- [x] Move_ASTRAL_BARRAGE
- [x] Move_EERIE_SPELL

PLA:
- [x] Move_DIRE_CLAW
- [x] Move_PSYSHIELD_BASH
- [x] Move_POWER_SHIFT
- [x] Move_STONE_AXE
- [x] Move_SPRINGTIDE_STORM
- [x] Move_MYSTICAL_POWER
- [x] Move_RAGING_FURY
- [x] Move_WAVE_CRASH
- [x] Move_CHLOROBLAST
- [x] Move_MOUNTAIN_GALE
- [x] Move_VICTORY_DANCE
- [x] Move_HEADLONG_RUSH
- [x] Move_BARB_BARRAGE
- [x] Move_ESPER_WING
- [x] Move_BITTER_MALICE
- [x] Move_SHELTER
- [x] Move_TRIPLE_ARROWS
- [x] Move_INFERNAL_PARADE
- [x] Move_CEASELESS_EDGE
- [x] Move_BLEAKWIND_STORM
- [x] Move_WILDBOLT_STORM
- [x] Move_SANDSEAR_STORM
- [x] Move_LUNAR_BLESSING
- [x] Move_TAKE_HEART

SV:
- [ ] Move_TERA_BLAST
- [x] Move_SILK_TRAP
- [ ] Move_AXE_KICK
- [ ] Move_LAST_RESPECTS
- [ ] Move_LUMINA_CRASH
- [ ] Move_ORDER_UP
- [ ] Move_JET_PUNCH
- [ ] Move_SPICY_EXTRACT
- [ ] Move_SPIN_OUT
- [ ] Move_POPULATION_BOMB
- [x] Move_ICE_SPINNER
- [ ] Move_GLAIVE_RUSH
- [ ] Move_REVIVAL_BLESSING
- [ ] Move_SALT_CURE
- [ ] Move_TRIPLE_DIVE
- [ ] Move_MORTAL_SPIN
- [ ] Move_DOODLE
- [ ] Move_FILLET_AWAY
- [ ] Move_KOWTOW_CLEAVE
- [ ] Move_FLOWER_TRICK
- [ ] Move_TORCH_SONG
- [ ] Move_AQUA_STEP
- [ ] Move_RAGING_BULL
- [ ] Move_MAKE_IT_RAIN
- [ ] Move_RUINATION
- [ ] Move_COLLISION_COURSE
- [ ] Move_ELECTRO_DRIFT
- [ ] Move_SHED_TAIL
- [ ] Move_CHILLY_RECEPTION
- [ ] Move_TIDY_UP
- [x] Move_SNOWSCAPE
- [ ] Move_POUNCE
- [ ] Move_TRAILBLAZE
- [ ] Move_CHILLING_WATER
- [ ] Move_HYPER_DRILL
- [ ] Move_TWIN_BEAM
- [ ] Move_RAGE_FIST
- [ ] Move_ARMOR_CANNON
- [x] Move_BITTER_BLADE
- [x] Move_DOUBLE_SHOCK
- [ ] Move_GIGATON_HAMMER
- [ ] Move_COMEUPPANCE
- [x ] Move_AQUA_CUTTER
- [ ] Move_BLAZING_TORQUE
- [ ] Move_WICKED_TORQUE
- [ ] Move_NOXIOUS_TORQUE
- [ ] Move_COMBAT_TORQUE
- [ ] Move_MAGICAL_TORQUE

**Comment by LOuroboros** [comment]
Needs an update, @BuffelSaft. `Move_POLTERGEIST` recently got an animation in #2154 :eyes:

**Comment by AsparagusEduardo** [comment]
Added moves missing from the list:
- Move_ME_FIRST
- Move_HEART_SWAP
- Move_ALLY_SWITCH
- Move_TRICK_OR_TREAT
- Move_ION_DELUGE
- Move_METEOR_BEAM
- Move_BURNING_JEALOUSY 
- Move_JUNGLE_HEALING

**Comment by AsparagusEduardo** [comment]
Added PLA and SV missing move animations

**Comment by AlexOn1ine** [comment]
#5192
