### ISSUE TITLE
Possible issues with #1696

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1953]
After merging #1696 into Inclement Emerald, I had many reports of AI freezes, the AI attacking itself, the AI switching into mons that were already on the field, and things like #1950. After some brief testing, it seems that reverting this PR solves these problems, so I think something is wrong with it, though I can't tell what - it may be best to revert it for now.

Could also be a mistake I made during merging of course.

Example test cases:
- Battle with wild Ditto freezes when Ditto runs out of PP
- Battle with wild mon freezes when you disable a move and its only other move has no effect

**Comment by AsparagusEduardo** [comment]
#1954
