### ISSUE TITLE
[battle_engine]Volt absorb stops explosion from damaging other pokémon

### ISSUE THREAD

**Issue by kleeenexfeu** [rh-hideout/pokeemerald-expansion#1961]
EDIT : [this PR](https://github.com/rh-hideout/pokeemerald-expansion/pull/1975) addresses all the problems mentionned, this issue can be closed once the PR is merged!

To be accurate, if you use explosion with the galvanize ability, in a double battle, and one of the mon has motor drive or volt absorb.
When voltabsorb/motor drive is activated, all the subsequent targets will not get damaged (and they should, did the test in showdown, plus it makes sense).
I thought I could fix it when working on https://github.com/rh-hideout/pokeemerald-expansion/pull/1958 but I can't seem to.
I think that explosion's battlescript should be updated, because it seems to use the same old version that earthquake was using; makes me think it might be the reason why surf doesn't have the same issue with water absorb/storm drain in double, or earthquake with levitate.
I tried to mess a little with the battlescripts but this process is inherently flawed, because if it luckily works at some point and I don't know why, I wouldn't know if I've broken something else.
If someone with a strong understanding of these battlescripts and the moveend command could look into this, and perhaps give me some pointers, it'd be very helpful.

**Comment by AsparagusEduardo** [comment]
We need to test how it's handled in USUM. Showdown may have its own inaccuracies, so shouldn't be taken as standard.

**Comment by kleeenexfeu** [comment]
Yep testing is always better, I don't have anything to do so though. But volt absorb and friends aren't supposed to stop spread damage. Leads me to believe that what's happening rn in the battle engine needs a fix

**Comment by AsparagusEduardo** [comment]
My bad, in my head I was think that the absorb abilities were the same as Lightning Rod and Storm Drain. It is certainly weird that it's stopping them.

**Comment by kleeenexfeu** [comment]
Thinking about it, I wonder if explosion shouldn't have a normal battlescript, like tackle.
This way the target will be correctly hit (I assume, because it works for surf).
Then, in moveend, add a "recoil" effect, except that it is a 100% recoil, especially made for explosion-like moves.
For the damp preventing explosion, it should be directly added in the attackcanceler I would say; it's weird to have it in a battlescript when fizzled moves and everything else is handled there (plus it would free 2 battlescript commands)

**Comment by kleeenexfeu** [comment]
Done, [this PR](https://github.com/rh-hideout/pokeemerald-expansion/pull/1967) addresses all the problems mentionned, this issue can be closed once the PR is merged!
