### ISSUE TITLE
[battle_engine] bolt beak doesn't deal double damage on a switched in target.

### ISSUE THREAD

**Issue by kleeenexfeu** [rh-hideout/pokeemerald-expansion#1968]
Bolt beak won't deal double damage for a target that has chosen to switch out. According to bulbapedia, it should. Currently the pokemon coming in will only take normal damages.
In addition to https://github.com/rh-hideout/pokeemerald-expansion/blob/battle_engine/src/battle_util.c#L7949, we have to check if the mon was switched in during this turn. You cannot simply check gActionsByTurnOrder because the switching mon will always go first, by the time we want to check its action, the index will always be B_ACTION_FINISHED (0xC) and not B_ACTION_SWITCH ( 0x2). If there's an existing field that call tell us about an switched in mon we can use it. Otherwise, when a pokemon switches out at the start of a turn, a bit should be set, 1 bit per battler is enough. Then, at the end of the turn it should be cleared, like the protect/kings shield etc. flags.

**Comment by BuffelSaft** [comment]
I wonder if that behaviour is a bug in the official games? Payback used to behave the same way but that was fixed in gen 5. Could add a config for that when this is fixed too I guess.

**Comment by kleeenexfeu** [comment]
Bulbapedia doesn't mention any bug about it. The explanation I gave fixes it, but I didn't want to create a field if there's already an existing one that we could use :p

**Comment by BuffelSaft** [comment]
sSWITCH_CASE gets set on switch out, if that was cleared at the end of each turn (assuming it's safe to do so) it could be recycled to handle this too. Would have to add 1 to all the switch types though, as they start at 0:
// switch cases
```
#define B_SWITCH_NORMAL     0
#define B_SWITCH_HIT        1   // dragon tail, circle throw
#define B_SWITCH_RED_CARD   2
```

**Comment by kleeenexfeu** [comment]
I don't think it'd work anyway, you need 4 bits (or bytes if you want to make the code shorter but take more space), because this one seems to get used for all four mons

**Comment by ghoulslash** [comment]
#2116
