### ISSUE TITLE
The palette of the back sprite of Pikachu's Partner Cap form is glitchy

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#1977]
As evidenced by our shiny new debug menu for the PE.
![mGBA_2560](https://user-images.githubusercontent.com/4485172/144721711-c446ebf4-a2fe-4cd6-ab9b-d91e1d56a564.png)![mGBA_2561](https://user-images.githubusercontent.com/4485172/144721712-ae6f586d-16fb-42fb-9fba-7ad81daa5ce0.png)

**Comment by AsparagusEduardo** [comment]
Duplicate of #1576
