### ISSUE TITLE
Inconsistency with white herb activation.

### ISSUE THREAD

**Issue by kleeenexfeu** [rh-hideout/pokeemerald-expansion#1985]
In the battle script command [Cmd_moveend](https://github.com/rh-hideout/pokeemerald-expansion/blob/battle_engine/src/battle_script_commands.c#L4900), the [MOVEEND_ITEM_EFFECTS_ALL](https://github.com/rh-hideout/pokeemerald-expansion/blob/battle_engine/src/battle_script_commands.c#L5080) case calls for several items effect, with the parameter ITEMEFFECT_MOVE_END, which is then used in the [ItemBattleEffects](https://github.com/rh-hideout/pokeemerald-expansion/blob/battle_engine/src/battle_util.c#L6178). It will trigger the white herb a [little bit too early](https://github.com/rh-hideout/pokeemerald-expansion/blob/battle_engine/include/constants/battle_script_commands.h#L263). [According to bulbapedia](https://bulbapedia.bulbagarden.net/wiki/White_Herb), it should be after the multi hit strike of a move.
All of this is tested with the [parental bond PR](https://github.com/rh-hideout/pokeemerald-expansion/pull/1676). The PR itself doesn't have any issue, it's just the white herb effect that should be moved to its own MOVEEND case.
I may address this problem in a future PR if someone hasn't done it by then, I just wanted the information to not be lost (and secretly hoped someone would fix it before me).

Edit: Reorganizing the moveend cases would also solve the inconsistency with knock off/items removed; many items shouldn't activate the turn they are knocked off, but because of the current order of the events, they do.

**Comment by AlexOn1ine** [comment]
Can you give an example were White Herb will be triggered to early?

And I believe the Knock Off issue was fixed by Egg.

**Comment by kleeenexfeu** [comment]
Been too long, I'm closing it and we'll see in the future if it comes back
