### ISSUE TITLE
Teleport's LGPE+ behavior is missing

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#1988]
Since Pokémon LGPE, the only situation in which Teleport can cause a wild battle to end, is when it's used by an opponent.

When one of the Player's Pokémon uses Teleport, it either fails *(1 Pokémon alive in the party)*, or makes said Pokémon switch out with another party member.

I've no idea how it works in wild double battles.

Meanwhile, in the battle_engine, Teleport has its old behavior in which a wild battle ends if the Player's Pokémon uses Teleport.

https://user-images.githubusercontent.com/4485172/145463909-f464d081-bea6-4a02-9123-e16c2d774bc7.mp4

**Comment by DizzyEggg** [comment]
Does it also apply to Trainer Battles? Wow, this makes the move actually viable in battles now.

**Comment by pkmnsnfrn** [comment]
> 

It absolutely applies in Trainer battles, it has made Slowpoke-family _very_ powerful in competitive battling.

**Comment by LOuroboros** [comment]
> > 
> 
> It absolutely applies in Trainer battles, it has made Slowpoke-family _very_ powerful in competitive battling.
> 
> [bulbapedia.bulbagarden.net/wiki/Teleport_(move)#Generation_VII](https://bulbapedia.bulbagarden.net/wiki/Teleport_(move)#Generation_VII)

What about local battles against the AI? :eyes:

Can a trainer controlled by the AI use Teleport in a double battle for example, or does it fail?

**Comment by pkmnsnfrn** [comment]
I cant test it right now, but I would be surprised if it didn't work that
same way as U-Turn and Volt Switch, just -6 priority.

**Comment by AsparagusEduardo** [comment]
#2121
