### ISSUE TITLE
Role Play needs an update

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#2006]
In Pokémon BDSP, though the change may have been introduced earlier, switch-in abilities that are copied through Role Play activate as a part of the move's effect, like for example, Intimidate.

https://user-images.githubusercontent.com/4485172/147194449-c1ee40c1-0f11-4bba-8fdb-bc55bb267546.mp4

However, in the battle_engine this doesn't happen.

https://user-images.githubusercontent.com/4485172/147193487-2e1724db-db4e-4b0f-945b-6c0ccc6bfcf1

**Comment by AsparagusEduardo** [comment]
#2007
