### ISSUE TITLE
Bug Bite/Pluck removes the user's old item permanently if the berry they consume helps them

### ISSUE THREAD

**Issue by eatthepear** [rh-hideout/pokeemerald-expansion#2027]
I was testing out Bug Bite in my game and found that it doesn't work correctly. If the user of Bug Bite is at full HP, it works correctly. However, if the user is healed by the opponent's berry in some way (for example, eating the opponent's Oran Berry when the user is not at full health), the user's original item is lost.

In PR #1581, I saw Ghoulslash's gif that showed the correct usage of Bug Bite. However in that GIF the Ariados isn't actually healing any HP from the Poochyena's Oran Berry. I tried this out a couple times using the battle debug, and confirmed my theory that if the user of Bug Bite heals from the opponent's berry, the user's original item is lost. Not sure if this is true for status conditions.

This is my first time submitting an issue, so apologies if I'm missing anything necessary

**Comment by AsparagusEduardo** [comment]
#2433
