### ISSUE TITLE
Relic Song form change happens at the wrong time

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#2040]
When reviewing #1734 , I noticed that the edge case of Meloetta with Magician didn't work properly because Meloetta's transformation is happening before any other event, including fainting and triggering of abilities like Magician.

https://user-images.githubusercontent.com/2904965/150601299-d287f043-cd82-4e6d-a077-772873ba89c0.mp4

![](https://cdn.discordapp.com/attachments/774393519569502268/932458620988297286/mGBA_dkKXnnKVPo.gif)

**Comment by BLourenco** [comment]
![relic-song-bug](https://user-images.githubusercontent.com/4230137/235767302-635f5e31-185b-4d71-93cd-2e7f7e15e492.gif)
The transformation doesn't just happen before every event, but it also triggers after each foe that's hit.

**Comment by AlexOn1ine** [comment]
Should the Magician interaction be tested? Meloetta doesn't have the ability

**Comment by AlexOn1ine** [comment]
@AsparagusEduardo Do you want to test this? It should be fixed in #3476

**Comment by AsparagusEduardo** [comment]
> @AsparagusEduardo Do you want to test this? It should be fixed in #3476

Sure, give me a sec.

**Comment by AsparagusEduardo** [comment]
Issue fixed :D
![mGBA_92T9Ll69aJ](https://github.com/rh-hideout/pokeemerald-expansion/assets/2904965/1c16f906-d0b6-4904-8102-99cbac794122)

Can you make a test for this edge case? ^^;

**Comment by AlexOn1ine** [comment]
> Issue fixed :D ![mGBA_92T9Ll69aJ](https://user-images.githubusercontent.com/2904965/284009346-1c16f906-d0b6-4904-8102-99cbac794122.gif) [ ![mGBA_92T9Ll69aJ](https://user-images.githubusercontent.com/2904965/284009346-1c16f906-d0b6-4904-8102-99cbac794122.gif) ](https://user-images.githubusercontent.com/2904965/284009346-1c16f906-d0b6-4904-8102-99cbac794122.gif) [ ](https://user-images.githubusercontent.com/2904965/284009346-1c16f906-d0b6-4904-8102-99cbac794122.gif)
> 
> Can you make a test for this edge case? ^^;

I would but I'm not sure how we feel about illegal abilities.

**Comment by AsparagusEduardo** [comment]
> I would but I'm not sure how we feel about illegal abilities.

Skill Swap maybe? It's the only legimitate way this edge case would manifest anyway 👀

**Comment by AlexOn1ine** [comment]
> > I would but I'm not sure how we feel about illegal abilities.
> 
> Skill Swap maybe? It's the only legimitate way this edge case would manifest anyway 👀

Right. I always forget Skill Swap exists lol

**Comment by Bassoonian** [comment]
Fixed by #3583
