### ISSUE TITLE
Inconsistency in `AI_WhoStrikesFirst`

### ISSUE THREAD

**Issue by aarant** [rh-hideout/pokeemerald-expansion#2048]
Function does not return the correct result when move priorities for battlers are equal; this is because `TRUE != AI_IS_FASTER`:

https://github.com/rh-hideout/pokeemerald-expansion/blob/0046283c04b990e9426ce6ccc3cf6f151db8ddce/src/battle_ai_util.c#L1023-L1027

It should probably instead read:

```c 
if (GetWhoStrikesFirst(battlerAI, battler2, TRUE) == 0)
    return AI_IS_FASTER;
else
    return AI_IS_SLOWER;
```

**Comment by ghoulslash** [comment]
#2052
