### ISSUE TITLE
Dragon Tail/Circle Throw animations repeat after use

### ISSUE THREAD

**Issue by kevinmc37** [rh-hideout/pokeemerald-expansion#2051]
https://user-images.githubusercontent.com/32335569/153171624-2cc542c6-781f-4482-ba82-4c2ff0fc63aa.mp4

As you can see in the video, after using Dragon Tail on a Wild Pokémon, it repeats the same animation in order to flee from the battle. I don't know if that's intended, but I think it should work more like Whirlwind or Roar, where the Pokémon, instead of disappearing, moves to the right outside the frame. At least, I looked into Sun/Moon animations and the move animation doesn't seem to repeat 2 times. Let me know what you think

**Comment by LOuroboros** [comment]
Yeah, the move's animation should definitely not play twice, that much is obvious.

**Comment by ghoulslash** [comment]
Since Lunos can not reproduce this on a fresh checkout of the battle engine, I'm going to clsoe this
