### ISSUE TITLE
Everstone is not preventing both Karrablast and Shelmet from evolving

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#2057]
> If either Karrablast or Shelmet holds an Everstone when traded for the other, neither can evolve.

![wsl_31DQFsKxN1](https://user-images.githubusercontent.com/2904965/153773470-ad35f0ac-7dbe-4f9e-b6de-50da1603dc58.gif)

**Comment by ghoulslash** [comment]
#2072
