### ISSUE TITLE
List of Pokémon: Legends Arceus Content

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#2058]
I am bored.
We'll likely have to discuss what to implement from PLA at one point or another, so I made this sensible list of the things we could add.
The Items list is probably the one that will need most discussion.
Anyway, this is probably something that should be taken care of in the far future, so this is just a huge reminder for the most part.

### Moves:
- [x] Barb Barrage
- [x] Bitter Malice
- [x] Bleakwind Storm
- [x] Ceaseless Edge
- [x] Chloroblast
- [x] Dire Claw
- [x] Esper Wing
- [x] Headlong Rush
- [x] Infernal Parade
- [x] Lunar Blessing
- [x] Mountain Gale
- [x] Mystical Power
- [x] Power Shift
- [x] Psyshield Bash
- [x] Raging Fury
- [x] Sandsear Storm
- [x] Shelter
- [x] Springtide Storm
- [x] Stone Axe
- [x] Take Heart
- [x] Triple Arrows
- [x] Victory Dance
- [x] Wave Crash
- [x] Windbolt Storm

### Items:
- [ ] Origin Ball
- [x] Black Augurite
- [x] Linking Cord
- [x] Peat Block
- [x] Jubilife Muffin
- [x] Remedy
- [x] Fine Remedy
- [x] Superb Remedy
- [x] Aux Evasion
- [x] Aux Guard
- [x] Aux Power
- [x] Aux Powerguard
- [x] Choice Dumpling
- [x] Swap Snack
- [x] Twice-Spiced Radish
- [x] Pokéshi Doll
- [ ] Hopo Berry
- [x] Adamant Crystal
- [ ] Legend Plate
- [x] Lustrous Globe

### Species:
- [x] #2248 
- [x] #2249 
- [x] #2250 
- [x] #2251 
- [x] #2252 
- [x] #2253 
- [x] #2254 

### Regional Forms *(Hisuian Forms)*:
- [x] Growlithe
- [x] Arcanine
- [x] Voltorb
- [x] Electrode
- [x] Typhlosion
- [x] Qwilfish
- [x] Sneasel
- [x] Samurott
- [x] Lilligant
- [x] Zorua
- [x] Zoroark
- [x] Braviary
- [x] Goomy
- [x] Sliggoo
- [x] Goodra
- [x] Avalugg
- [x] Decidueye

### Other Forms
- [x] Dialga Origin Forme
- [x] Palkia Origin Forme

### Notes and Thoughts:
* Basculegion has gender differences.
* I only added the items that have a reasonable usage case outside the boundaries of the game, like the Linking Cord.
* I skipped LA's own Heavy Ball and its upgrades because they don't have a purpose in a game without sneaking mechanics such as Pokémon Emerald.
* ~~On that note, the Feather, Wing and Jet Balls, which make lightweight and Flying type Pokémon easier to catch, could be implemented just fine.~~
***EDIT**: Nevermind, they don't actually have an increased catch rate, so they're not really fit. As such, I removed them from the list.*
* The Stealth Spray could be added as a variant of one of the Repelents. Dunno.
* I ignored crafting recipes and materials including the Brown Apricorn.
  * I wanted to add it for consistency, but without any of the other items used to craft Poké Balls it wouldn't have a purpose.
* ~~**[Cherrim's Sunshine Form got a BST buff](https://bulbapedia.bulbagarden.net/wiki/Cherrim_(Pok%C3%A9mon)#Sunshine_Form)**. It could be added behind a `#if P_UPDATED_STATS >= GEN_8` maybe.~~
***EDIT**: Nevermind. As it was pointed out by @bitter6290, the buff is likely meant to act as a replacement to Flower Gift in a game with no usable abilities like LA is.*
  * Alternatively, we could make sub-versions, so instead of `GEN_8` we could add a `GEN_8_LA` or something like that.
* Each new species and form introduced has abilities set in the code of Legends Arceus, as it can be seen in **[Kaphotics' PLA base stats dump](https://gist.githubusercontent.com/kwsch/24b527c4aa63f42c9132e7b7c76ce08d/raw/6d5de345ff884af1c26d69b78f6d1171abbbc85f/gistfile1.txt)**.

**Comment by bitter6290** [comment]
This is a small nitpick, but isn't it reasonable to assume that the Cherrim Sunshine Form buff is meant to replace the Flower Gift buff, making it unnecessary in a game that still has abilities?

**Comment by LOuroboros** [comment]
> This is a small nitpick, but isn't it reasonable to assume that the Cherrim Sunshine Form buff is meant to replace the Flower Gift buff, making it unnecessary in a game that still has abilities?

You're probably right. The stats that were raised are the same ones affected by Flower Gift after all.

I think we could perfectly add the buff regardless in case there's people who'd want to let Cherrim get both boosts, but well, that's more of a subjective thing, so I'll scratch that item off the list.

**Comment by alaxandir** [comment]
Ability to toggle the Frostbite Mechanic on/off instead of Freeze would be really neat!

**Comment by AsparagusEduardo** [comment]
> Alternatively, we could make sub-versions, so instead of GEN_8 we could add a GEN_8_LA or something like that.
No point in doing this, as we don't currently support disabling abilities.

**Comment by LOuroboros** [comment]
> > Alternatively, we could make sub-versions, so instead of GEN_8 we could add a GEN_8_LA or something like that.
> 
> No point in doing this, as we don't currently support disabling abilities.

?

The suggestion was not related to "disabling abilities" at all.

The idea was that the buff in base stats could be applied behind a version constant, and since we already have `GEN_8`, we could use a `GEN_8_LA` label for it.

**Comment by AsparagusEduardo** [comment]
> The suggestion was not related to "disabling abilities" at all.

The idea was that the buff in base stats could be applied behind a version constant, and since we already have GEN_8, we could use a GEN_8_LA label for it.

Then the stat change makes even less sense if we were to always have abilities on.
Also, I remember that there was a consensus that mid-gen configs would make things too comboluted.

**Comment by LOuroboros** [comment]
> Then the stat change makes even less sense if we were to always have abilities on.

Sure, whatever. As long as the original intention is understood I don't care what we end up doing.

The idea was to add the stat buff Cherrim for in LA behind a preproc.

We have base stats changes determined by the value of the `P_UPDATED_STATS` preproc config.

Thus, it'd be the cleanest to have a subversion constant *(`GEN_8_LA`)* for a case like this.

I think Bitter's conjecture is reasonable and that the stat buff was probably to make up for the lack of Flower Gift fwiw, but I do think that a user may want to retain or apply those stat buffs regardless of Flower Gift's availability. I don't know enough about balancing in fanmade projects to determine that, but I also don't care enough to push for it myself.

I hope other people come around and write up their thoughts.

>  Also, I remember that there was a consensus that mid-gen configs would make things too comboluted.

I do remember you submitted a list with a good number of them, but for isolated cases I think it may end up being necessary to take specific versions into account down the road.

In this case and only speaking hypothetically, Cherrim would have its base stats set by a `#if P_UPDATED_STATS == GEN_8_LA` and `#else`, which sounds nice, clean and consistent with the way we do things right now.

Certainly, we could instead have a regular preproc config like `P_CHERRIM_BASE_STATS` like we already do for Kadabra, Shedinja and such.

I don't care either way myself.

**Comment by AsparagusEduardo** [comment]
Not all items were added. Reopening.
