### ISSUE TITLE
Very minor edge case regarding shinies with gender differences and pokédex entry upon catch

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#2063]
Just realized that #2056's aproach doesn't correctly handle an edge case regarding Shiny Pokémon:
Normaly, when a mon is shown on the Pokédex after being caught, it shows the regular colors and then once it moves to the nickname phase, it changes its palette if its shiny. With this implementation, Pokémon with gender differences will show the shiny colors on the Pokédex.
It's really minor, but decided to add this issue as a reminder to eventually fix this.

**Comment by AsparagusEduardo** [comment]
> In gens 5+, both the "new entry" screen and viewing the entry later will use the shiny sprite by default if the first catch of that species is shiny. I say apply this palette behavior to all mon tbh.

I will only be able to apply the first behavior, as saving the palette for each entry would be out of scope.

**Comment by MandL27** [comment]
> saving the palette for each entry would be out of scope

Yeah, I meant showing shininess on the "new entry" screen only in my previous comment. Bad wording on my part.

**Comment by ghoulslash** [comment]
#2064
