### ISSUE TITLE
Shed Shell doesn't allow you to switch out of Shadow Tag (and presumably other trapping abilities)

### ISSUE THREAD

**Issue by dekzeh** [rh-hideout/pokeemerald-expansion#2081]
Title is self-explanatory, images following show a Shed Shell Aggron being trapped by a Shadow Tag Chandelure

![shadowshed1](https://user-images.githubusercontent.com/6068615/159369402-a9e284da-5086-4d3e-a5f8-0784660c0df2.png)
![shadowshed2](https://user-images.githubusercontent.com/6068615/159369400-53615900-5961-424d-a228-0ce6a79dadd4.png)

**Comment by ghoulslash** [comment]
#2114
