### ISSUE TITLE
Heal block doesn't stop healing held items such as leftovers or sitrus berry

### ISSUE THREAD

**Issue by Sneed69** [rh-hideout/pokeemerald-expansion#2097]
Grassy terrain also ignores it.

**Comment by Sneed69** [comment]
Fixed (I think) for my project, if anyone wants to port it over:
https://github.com/Sneed69/pokeemerald/commit/7b9f3e91f26a370ffa010df808517a1af37d98da

**Comment by Sneed69** [comment]
Also Strength Sap isn't blocked, but these two moves don't coexist in the games at any point.

**Comment by AsparagusEduardo** [comment]
#2105
