### ISSUE TITLE
Extra code for Leek crits is unnecessary - should remove it

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#2118]
The config for `B_LEEK_ALWAYS_CRIT` is not needed. In gen 6 onwards,  Farfetch'd will always crit with a Leek and one other crit stage boost (e.g from a high crit move or Focus Energy) because crit chances were changed in that gen - it's not a specific change to Farfetch'd, and is not limited to moves with a high crit chance. Farfetch'd under the effects of Super Luck or Focus Energy will also have a 100% crit rate, but with any move.

This is because anything with +3 crit stages will always crit in gen 6 onwards. Leek gives Farfetch'd +2, and high crit moves give +1. You can also get the same result on any other Pokémon by using Focus Energy while holding a Scope Lens.

**Comment by ghoulslash** [comment]
#2055
