### ISSUE TITLE
Berry graphics in the Berry Blender are broken

### ISSUE THREAD

**Issue by SubzeroEclipse** [rh-hideout/pokeemerald-expansion#2119]
Tested on item_expansion. When the Berries are thrown inside the Blender, the game loads the graphics of the Berry 6 slots before the selected one (in the first gif I put Roseli and loads Tanga instead; while in the second one I put a Cheri and it loads a glitched image) and the Berries thrown by the NPCs are just shadowy copies of the one loaded.
![roseli](https://user-images.githubusercontent.com/64367060/167248343-e177f514-147d-4b94-91e4-fcd490064718.gif)
![cheri](https://user-images.githubusercontent.com/64367060/167248349-044b6967-f3b2-4c2b-8cac-20bc4ad51301.gif)

**Comment by Sneed69** [comment]
Fixed by https://github.com/pret/pokeemerald/pull/1655

**Comment by LOuroboros** [comment]
> Fixed by [pret#1655](https://github.com/pret/pokeemerald/pull/1655)

Can't confirm. In fact, it's even more broken now than it is on Subzero's videos, lmao.

https://user-images.githubusercontent.com/4485172/170898070-c099bcec-9e6e-404f-b0c6-861cee7c5c97.mp4

Tested on a clean copy of the item_expansion.

**Comment by DizzyEggg** [comment]
Closing as per comment above.
