### ISSUE TITLE
If you Fling a berry towards a partner in double battle, it erases their item

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#2137]
> Duke Today at 11:47 AM
> yeah flinging a berry on your double battle partner deletes its item

**Comment by AsparagusEduardo** [comment]
Needs to be tested after #2138 is merged, as the related issue #2027 is fixed by it.

**Comment by AsparagusEduardo** [comment]
Confirmed solved after #2433.
