### ISSUE TITLE
build.sh gives me tons of errors

### ISSUE THREAD

**Issue by ACIDULATED** [rh-hideout/pokeemerald-expansion#2158]
build.sh gives me TONS of errors. Like, too many to put here, as it exceeds the character limit.

**Comment by LOuroboros** [comment]
The Pokeemerald-expansion doesn't have any `build.sh` scripts, so I assume you're talking about Agbcc.

Questions about the installation or usage of Agbcc are naturally unrelated to this project.

You may ask your questions or report your errors in Pret's or RHH's Discord server, or in Agbcc's Github repository.
