### ISSUE TITLE
Inverse battles still enforce some regular immunities

### ISSUE THREAD

**Issue by ghoulslash** [rh-hideout/pokeemerald-expansion#2168]
`MulByTypeEffectiveness` calls `GetTypeModifier`, which will handle inverse battles, but then exceptions are handled afterwards, such ungrounded pokemon being immune to ground [here](https://github.com/rh-hideout/pokeemerald-expansion/blob/15fe85902f2f4f3e6e2202113aa224ef4b1eb3f3/src/battle_util.c#L9175). So, while in an inverse battle ground should do 2x to flying, it will still be resisted.

**Comment by AsparagusEduardo** [comment]
#2169
