### ISSUE TITLE
Broken ui in 1vs2 single battles

### ISSUE THREAD

**Issue by Jaizu** [rh-hideout/pokeemerald-expansion#2172]
Bug 1: since I only have one pokémon, single battle ui should load in battle (bigger battle box and centered gengar)
Bug 2: since I only have one pokémon, single battle ui should load in the party menu

![image](https://user-images.githubusercontent.com/18596778/174828823-1b7e5fca-c8d7-4686-b656-7083ede72b86.png)

**Comment by Jaizu** [comment]
This is what I used to test it
`Debug_Script_1::
	givemon SPECIES_GENGAR, 100, ITEM_NONE
	trainerbattle_single TRAINER_GABBY_AND_TY_1, GabbyAndTy_Text_GabbyPreFirstBattle, GabbyAndTy_Text_GabbyDefeatFirstTime, GabbyAndTy_EventScript_FirstInterview
	msgbox GabbyAndTy_Text_KeepingAnEyeOutForYou, MSGBOX_DEFAULT
	end`

**Comment by laserXdolphin** [comment]
Shouldn't this be fixable by checking if the player has only one Pokemon at the start of a double battle and if that's the case drawing the single battle boxes and Pokemon positions on the player side.
If someone could point me to where I find those I'll try to fix it.
The two functions I found that should have something to do with it are CreateBattlerHealthboxSprites and DoBattleIntro

**Comment by Jaizu** [comment]
You also have to make sure you are not in a partner battle and make sure battle anims work as intended. The theory is easy yeah
