### ISSUE TITLE
Mega Icon doesn't leave with the defeated Pokemon

### ISSUE THREAD

**Issue by Kraballa** [rh-hideout/pokeemerald-expansion#2175]
### What
I gave Flannery a Cameruptite. When I beat her mega Camerupt I noticed its mega icon did not disappear and stayed for the next Pokemon. [Video](https://www.youtube.com/watch?v=7SOQa1fb44k). If you look closely it seems as if the mega icon got cloned for my Pokemon. At the start of the clip the icon does not wiggle during move selection. After the accuracy drop it does. I don't know if it has to be an accuracy drop.

![image](https://user-images.githubusercontent.com/27429196/175375293-6af7895c-6728-4427-bca1-bdc03ae5bc0b.png)
Here's an image of the leftover icon.

### Steps I did to get this behavior
1. gave Flannery a camerupt mega stone
2. gave mega camerupt an accuracy drop using mud bomb. It did not seem to occur if the stat drop doesn't happen, camerupt used overheat and dropped its own stats or if my own pokemon got a stat raise (in this case ancient power).
3. the icon started waggling during move selection and didn't disappear until the end of the fight.

**Comment by LOuroboros** [comment]
I moved Camerupt to the first slot of her party so she would Mega Evolve early, and made sure to reduce its Accuracy via Sand Attack in battle as well and I just can't replicate in a copy of the Master branch. Maybe I'm doing it wrong though.

https://user-images.githubusercontent.com/4485172/175435899-0ab80902-762b-4b9a-a9d1-c10b7fe2a406.mp4

Battle Scene didn't make a difference, even with the move animations enabled I couldn't replicate it.

Say, when was the last time you `git pull`ed either the Master branch or the feature branches? :eyes:

**Comment by Kraballa** [comment]
I'm up to date. Seems like one of the changes I implemented messed it up. Unfortunately I don't have the knowledge on how to fix it but it doesn't seem to occur in the main branch, I double checked it. So we can close this?

**Comment by LOuroboros** [comment]
> it doesn't seem to occur in the main branch, I double checked it. So we can close this?

Yup.

**Comment by LOuroboros** [comment]
I'm re-opening this for now. I'd like to get some extra tests to corroborate if this is actually an issue in the branches or not before dismissing it.

**Comment by DizzyEggg** [comment]
Couldn't reproduce on Master using the same instructions. As Lunos said, it most likely wasn't an issue with the branches.
