### ISSUE TITLE
Last move not animated

### ISSUE THREAD

**Issue by mrgriffin** [rh-hideout/pokeemerald-expansion#2188]
https://github.com/rh-hideout/pokeemerald-expansion/blob/master/src/battle_gfx_sfx_util.c#L536
```c
bool8 IsMoveWithoutAnimation(u16 moveId, u8 animationTurn)
{
    if (moveId >= (MOVES_COUNT - 1))
        return TRUE;
    else
        return FALSE;
}
```

This causes the last move not to be animated, which causes somebody to come into the pret Discord every couple of months wondering why their animation doesn't play.
I would expect to see `moveId >= MOVES_COUNT`.

(For the curious, it has been broken essentially forever: https://github.com/rh-hideout/pokeemerald-expansion/commit/2293d1ddbcff5466c7865772bfae1b733e8fe9d9#diff-1e33c3dd8be8f19905a1f76a329e2347042673054e6201d12971bf06fab862a0R505)

**Comment by LOuroboros** [comment]
@Sneed69 removed that function from the BE actually, so that commit will make it into the next Master merge.

https://github.com/rh-hideout/pokeemerald-expansion/commit/c60de5055d70a21328babc47f3cf1510fa46ac84

**Comment by AsparagusEduardo** [comment]
#2162
