### ISSUE TITLE
Heal Ball sometimes doesn't heal the caught mon

### ISSUE THREAD

**Issue by eatthepear** [rh-hideout/pokeemerald-expansion#2189]
In cmd_handleballthrow, there's two potential cases where you catch a pokemon. One is where odds > 254, and the other is the shake calculator. The heal ball only heals the pokemon in the shake calculator, and doesn't heal in the odds one. The fix would simply be copy pasting the heal ball if statement into the odds > 254 case.

**Comment by ghoulslash** [comment]
#2212
