### ISSUE TITLE
CanSpeciesLearnTMHM likely needs fix

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#2207]
A proper test may be needed, but chances are this report is correct.

So, back when TMs 51-100 were reincorporated into the item_expansion and some spooky ternary magic was applied to a couple of files in order to handle those TMs being unusable or something in #1561, the function `CanSpeciesLearnTMHM` used by the Apprentice system of the Battle Frontier was not updated. As a result, there's a chance this could cause a softlock to Players that engage with said system.

> GriffinR 01/09/2022
> I also suspect that this can softlock on Apprentices because the usage of CanSpeciesLearnTMHM in GetRandomAlternateMove isn't updated. It still gives it TM item values, when it should be giving it TM item value - first TM item value
> If that's relevant to you at all

https://github.com/rh-hideout/pokeemerald-expansion/blob/item_expansion/src/apprentice.c#L375-L381

https://github.com/rh-hideout/pokeemerald-expansion/blob/item_expansion/src/pokemon.c#L6228-L6244

**Comment by StephenLynx** [comment]
I noticed a commit that subtracts 50 when calling CanMonLearnTMHM, but not CanMonLearnTMHM itself. So all other instances calling that function are still broken, so I'd suggest making CanMonLearnTMHM being the place that performs the subtraction. I'd also recommend the removal of CanSpeciesLearnTMHM, it's only called once and the function that calls it seems to have access to the mon and not just the species: src/aprentice.c line 332, function GetRandomAlternateMove.

**Comment by StephenLynx** [comment]
I made a commit on a repo I made: https://github.com/StephenLynx/pokeemerald/commit/9367c85b1a8bca2c01a1807a8557ba14a876603e

I also removed the duplicate code of CanSpeciesLearnTMHM

**Comment by AsparagusEduardo** [comment]
#2233
