### ISSUE TITLE
Bad AI related merge

### ISSUE THREAD

**Issue by ghoulslash** [rh-hideout/pokeemerald-expansion#2216]
default:
                {
                    u16 chosenMove = moveInfo->moves[chosenMoveId];

                    if (GetBattlerMoveTargetType(gActiveBattler, chosenMove) & (MOVE_TARGET_USER_OR_SELECTED | MOVE_TARGET_USER))
                        gBattlerTarget = gActiveBattler;
                    if (GetBattlerMoveTargetType(gActiveBattler, chosenMove) & MOVE_TARGET_BOTH)
                    {
                        gBattlerTarget = GetBattlerAtPosition(B_POSITION_PLAYER_LEFT);
                        if (gAbsentBattlerFlags & gBitTable[gBattlerTarget])
                            gBattlerTarget = GetBattlerAtPosition(B_POSITION_PLAYER_RIGHT);
                    }                    
                    if (ShouldUseZMove(gActiveBattler, gBattlerTarget, chosenMove))
                        QueueZMove(gActiveBattler, chosenMove);                    
                    if (CanMegaEvolve(gActiveBattler)) // If opponent can mega evolve, do it.
                        BtlController_EmitTwoReturnValues(BUFFER_B, 10, (chosenMoveId) | (RET_MEGA_EVOLUTION) | (gBattlerTarget << 8));
                    else
                        BtlController_EmitTwoReturnValues(BUFFER_B, 10, (chosenMoveId) | (gBattlerTarget << 8));
                }
                break;

**Comment by AsparagusEduardo** [comment]
#2217
