### ISSUE TITLE
Healing Wish and Lunar Dance have outdated mechanics

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#2222]
Per Bulbapedia (should perhaps be confirmed independently), Healing Wish and Lunar Dance only send out (and heal) the user's replacement at the end of the turn from Generation V onwards. This contrasts with the replacement being sent out immediately after the move is used, which occurs in Generation IV alone and is the current behaviour of these two moves in BE.

**Comment by Bassoonian** [comment]
Apparently this issue is already addressed in https://github.com/rh-hideout/pokeemerald-expansion/pull/2126, my bad!

**Comment by AsparagusEduardo** [comment]
Issue should be kept open until the corresponding PR is merged.
