### ISSUE TITLE
Missing form changes

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#2266]
* [x] Deoxys *(Overworld form change ) (2 different methods; Gen. 4 and Gen. 5+)*
* [x] Rotom *(Overworld form change, Rotom Catalog)*
* [x] Shaymin *(Should revert from Sky to Land Forme when frozen)*
* [ ] Furfrou *(Overworld form change)* *(reverts to base form after 5 days have passed, [and also reverts under other conditions](https://bulbapedia.bulbagarden.net/wiki/Furfrou_(Pok%C3%A9mon)#Forms))*
* [ ] Hoopa Unbound *(reverts to base form after 3 days have passed.)* *([TODO: Test if it happens after 48hs60mins or 72 full hours](https://discord.com/channels/419213663107416084/774393519569502268/932015410214223952))*
* [x] Xerneas *(turn into `SPECIES_XERNEAS_ACTIVE` when sent out.)*
* [x] Zygarde *(Gen. 8 Zygarde Cube)*
* [x] Eiscue *(change form when hit by a physical attack and revert once per hailstorm)*
* [x] Zacian/Zamazenta *(turn into `SPECIES_ZACIAN_CROWNED_SWORD`/`SPECIES_ZAMAZENTA_CROWNED_SHIELD` when sent out while holding a specific item.)*

### Notes:

- Certain species have been ignored because they're heavily tied to factors such as a seasons system or savefile struct edits.

- I added overworld-reliant form changes because #2113 kinda gave plausible cause to incorporate those in the project or at least support for them, in my opinion. Mantainers can remove them from the ticket if they're deemed out of scope.

  - Those forms can be easily handled with a quick function that passes `MON_DATA_SPECIES` through a `SetMonData` call in some cheap function called with a macro at `asm/macros/event.inc`.

**Comment by ExpoSeed** [comment]
on this note, i believe we can also start adding in battle form changes to the form change tables now that we don't gotta worry about juggling multiple branches

**Comment by ExpoSeed** [comment]
on hoopa unbound we also need to look into how it handles the reversion of multiple hoopa unbound in one savefile

**Comment by AsparagusEduardo** [comment]
Furfrou also reverts after 5 days of being groomed.

**Comment by LOuroboros** [comment]
> Furfrou also reverts after 5 days of being groomed.

I actually didn't know that, but I made explicit mention of Hoopa's revert because that's the only part that is missing. [Hoopa->Hoopa Unbound is already implemented](https://github.com/rh-hideout/pokeemerald-expansion/blob/master/src/data/pokemon/form_change_tables.h#L147), although it's commented out currently :eyes:

**Comment by AsparagusEduardo** [comment]
Just so it's recorded here, Hoopa's and Furfrou's form reversion happens at midnight, like how Pokérus works.

**Comment by Bassoonian** [comment]
Fixed by #4778
