### ISSUE TITLE
Missing/Relocated Anims?

### ISSUE THREAD

**Issue by bnthomason** [rh-hideout/pokeemerald-expansion#2267]
DizzyEgg's anims_front still exists, but it is not in the same place or at all in Rocket Hideout's code.

id_script.txt should have it listed here:

Lines 9 and 10

`__anim_mon_load_address = 0x8b00000;
__gfx_load_address = 0x8c00000;`

and here:

Lines 1299 - 1303
`    anim_mon_front_pic_data __anim_mon_load_address :
    ALIGN(4)
    {
        src/anim_mon_front_pics.o(.rodata);
    } =0`

**Comment by LOuroboros** [comment]
I'm not really sure what are you talking about. Could you clarify?

If you Ctrl+F `__anim_mon_load_address` or `anim_mon_front_pics` inside ld_script.txt you'll see no mention of either.

https://github.com/rh-hideout/pokeemerald-expansion/blob/master/ld_script.txt

If you're using the branches present inside Egg's repository; don't. They're well out of date. The development for those branches is happening in *this* repository, more specifically, in the Master branch.

**Comment by LOuroboros** [comment]
This doesn't look like a valid Issue ticket and the lack of information doesn't help, so I'm closing it for the time being.
