### ISSUE TITLE
Split P_NEW_POKEMON into gens

### ISSUE THREAD

**Issue by Jaizu** [rh-hideout/pokeemerald-expansion#2272]
I think this is a cool suggestion

**Comment by AsparagusEduardo** [comment]
I can see it working if we have it with a `GEN_X` constant, enabling all mon up to that generation. Would that suffice?

**Comment by LOuroboros** [comment]
> I can see it working if we have it with a `GEN_X` constant, enabling all mon up to that generation. Would that suffice?

Assuming it's not the same `GEN_X` constants that are used to modify the battle mechanics, I'd say so.

Labels like `P_GEN_4_SPECIES` or something like that acting within the realm of `P_NEW_POKEMON` which would retain its functionality as a master switch would be nice, imo.

**Comment by AsparagusEduardo** [comment]
#2283
