### ISSUE TITLE
Extend compatibility in teachable_learnsets.h

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#2274]
With the restructuring of how move compatibility is stored and moves no longer being linked to specific TMs, it is now possible to extend these teachable learnsets to include moves that are tutorable either by move tutor or by TM/TR in Generations IV-VIII (and potentially also Generations I-II, as well as FRLG). This eliminates the need for external tools such as PoryMoves (which for instance don't natively run on OSX) and allows people to add new move tutors and TMs without having to (manually) add compatibility for over 1,000 species. The only possible side effect is increased ROM space, which I personally believe is a fair sacrifice in function of ease of use.

**Comment by AlexOn1ine** [comment]
#3856
