### ISSUE TITLE
Add let's go eevee and let's go pikachu species

### ISSUE THREAD

**Issue by Jaizu** [rh-hideout/pokeemerald-expansion#2291]
I think they fit and should be added to the pokémon expansion.
They should differ from regular ones on:
Species ID
Not being able to breed
Different movesets/learnset
Base stats
Shiny locked (not sure if this is out of scope)
Unable to evolve

Additionally, this could be an excuse to make something like not being able to deposit a certain species ID in a storage box, but I feel like that should be handled in a different github issue.

**Comment by AsparagusEduardo** [comment]
- Something you missed was that they always perfect IVs.

- Shiny lock could be a separate feature as a separate table, but with no species by default, as its not a very liked thing ^^;


> something like not being able to deposit a certain species ID in a storage box
- In LGPE you could take Pikachu and Eevee out from your party, it's just that you can still interact with them in the overworld and other stuff.

**Comment by Jaizu** [comment]
Oh, then ignore the pc box stuff.
For shiny and perfects ivs they should should into separate tables/features then? And add the new species to those tables.

**Comment by AsparagusEduardo** [comment]
> Oh, then ignore the pc box stuff. For shiny and perfects ivs they should should into separate tables/features then? And add the new species to those tables.

Yes, but now that I think about it, instead of using tables, we could add new species flags. We only have one left anyway, so might as well expand them to u16.

**Comment by Jaizu** [comment]
Both options seem fine to me o/

**Comment by AlexOn1ine** [comment]
#4281
