### ISSUE TITLE
Bug Bite isn't actually making the user eat the stolen berry 

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#23]
Reposting this from @DizzyEggg's repository.
Bug Bite is a move that does damage. If the opponent is holding a berry, the user steals the berry and eats it on the spot effectively benefitting from said berry's effect.

In the battle_engine however, while there's a text string saying that the user stole and ate the berry, the user is not actually eating the berry.
![Untitled239](https://user-images.githubusercontent.com/4485172/96102916-716c8300-0ead-11eb-9a64-73f158cdc99f.gif)

Test case:
-Made Torchic learn Bug Bite at Lv1
-Changed all the encounters in Route 102 with Lv2 Golem
-Changed Golem's held items to `ITEM_ORAN_BERRY` in `src/data/pokemon/base_stats.h`
-Built a ROM and tested the move

I used a clean copy of the RHH's battle_engine branch with no major modifications to test this out.

**Comment by AsparagusEduardo** [comment]
Confirmed while doing test to verify #8

**Comment by BuffelSaft** [comment]
Addressed by #1581
