### ISSUE TITLE
Dauntless Shield & Intrepid Sword do not behave correctly when switching-in position B_POSITION_PLAYER_RIGHT after a mon fainted

### ISSUE THREAD

**Issue by Baptiste-Lecoutre** [rh-hideout/pokeemerald-expansion#2311]
These abilities work correctly at the beginning of battle, and when manually switching-in during a turn action.

However, switching-in after a mon fainted does weird stuff. 
-> The ability popup shows the name + ability of the mon in B_POSITION_PLAYER_LEFT. (I haven't tested with the opponent, but I feel it's going to show the ability popup for mon in position 0).
-> The text in B_WIN_MSG after the ability popup is correct.
-> The stat raise does not happen at all (that's what the debug menu tells).

**Comment by AsparagusEduardo** [comment]
![DShield](https://user-images.githubusercontent.com/2904965/189543861-64d14c6e-096b-4a10-b820-2e625dabfa44.gif)
Confirmed, and it seems it raises B_POSITION_PLAYER_LEFT's stat.

**Comment by Baptiste-Lecoutre** [comment]
Indeed, it does raise B_POSITION_PLAYER_LEFT's stat. I didn't see I've been growled the first time, my bad.
