### ISSUE TITLE
Z-Move not cleared if Pokemon faints

### ISSUE THREAD

**Issue by StubbornOne** [rh-hideout/pokeemerald-expansion#2317]
The next Pokemon is thus able to use a Z-Move:
![zmove](https://user-images.githubusercontent.com/81517503/189881091-ef53e19b-3595-41c7-9852-3db7309d90d1.gif)
Another sample, built from master branch:
![zmove2](https://user-images.githubusercontent.com/81517503/190179122-6a96308f-b3e6-4061-9430-a4ec82df832c.gif)

**Comment by AsparagusEduardo** [comment]
#2389
