### ISSUE TITLE
Update gFrontierBannedSpecies

### ISSUE THREAD

**Issue by Jaizu** [rh-hideout/pokeemerald-expansion#2322]

**Comment by AsparagusEduardo** [comment]
I think it would make more sense to add a new flag for [Special Pokémon](https://bulbapedia.bulbagarden.net/wiki/Special_Pok%C3%A9mon) and ban those and Mythicals instead of expanding the table itself.
Thinking this could be added in #2293 .

**Comment by Jaizu** [comment]
Whatever works for me as long as is faithful to later gen games (gen iv facilities)

**Comment by AsparagusEduardo** [comment]
#3465
