### ISSUE TITLE
Multi-fixed-battle pokemon placement and party menu, when only 1 Pokemon

### ISSUE THREAD

**Issue by StubbornOne** [rh-hideout/pokeemerald-expansion#2328]
Hi, noticed this in multis when the player has only one Pokemon in the party:
![mult_fixed_2v1](https://user-images.githubusercontent.com/81517503/190687948-059948c5-e2ba-4119-ab84-4bb5e10663fb.gif)
Sprite placement is centered and party menu is not in the multi format

If I'm not wrong it's related to #2238

**Comment by ghoulslash** [comment]
#2335
