### ISSUE TITLE
Multi-fixed-wild partner not calculating damage

### ISSUE THREAD

**Issue by StubbornOne** [rh-hideout/pokeemerald-expansion#2341]
Hi, in `GetAILogicData` in battle_ai_main.c, there's a check
`if (!(gBattleTypeFlags & (BATTLE_TYPE_TRAINER | BATTLE_TYPE_FIRST_BATTLE | BATTLE_TYPE_SAFARI | BATTLE_TYPE_ROAMER))
      && !IsWildMonSmart())
        return;`
This lacks `BATTLE_TYPE_INGAME_PARTNER`, so the battle partner does not calculate damage in a `multi_fixed_wild` battle.
![multi_fixed_wild](https://user-images.githubusercontent.com/81517503/191520237-668e517e-58af-4edd-92dc-2651216cdca0.gif)
Based on [2c287b7](https://github.com/rh-hideout/pokeemerald-expansion/commit/2c287b779f8a5a2c945298bb89193c3de206e06d)

If I'm not wrong, the four can be replaced with `BATTLE_TYPE_HAS_AI`, which includes `BATTLE_TYPE_INGAME_PARTNER` and is used in a check guarding `ComputeBattleAiScores` in battle_main.c

**Comment by AsparagusEduardo** [comment]
> If I'm not wrong, the four can be replaced with `BATTLE_TYPE_HAS_AI`, which includes `BATTLE_TYPE_INGAME_PARTNER` and is used in a check guarding `ComputeBattleAiScores` in battle_main.c

Yes, indeed it should. Feel free to make a PR if you are able to, so I can review it.

**Comment by AsparagusEduardo** [comment]
#2343
