### ISSUE TITLE
Jump to invalid address during Light That Burns the Sky

### ISSUE THREAD

**Issue by StubbornOne** [rh-hideout/pokeemerald-expansion#2348]
Hi, Light That Burns the Sky seems to jump to an invalid address.
![lightthatburnsthesky](https://user-images.githubusercontent.com/81517503/192087688-0e872033-8b34-45ac-a3a0-6def7c06cdcb.gif)
Couldn't get the crash popup on video (Windows Game Recorder), here is a screenshot:
![gamecrash](https://user-images.githubusercontent.com/81517503/192087706-0ac97c47-cb79-4fce-be04-371b97f35402.jpg)
I put Ultra-Necrozma directly into the party, not sure if it matters. Also tested with an arbitrary Pokemon and Light That Burns the Sky as its move (without needing Z-Crystal).

Tested on dev [29c3f57](https://github.com/rh-hideout/pokeemerald-expansion/commit/29c3f57772e5d34e9ea9968c7407046f616df16e), both mGBA (crash) and VBA-M (hangs).

**Comment by AsparagusEduardo** [comment]
Yeah, putting Ultra Necrozma in the party directly shouldn't matter. From what I'm seeing in the recording, it looks to be an issue with the animation script.

**Comment by AsparagusEduardo** [comment]
#2350
