### ISSUE TITLE
Switch-in abilities activate against fainted mons

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#2371]
Example: 
Current behaviour:
1. Player's mon KO's an AI mon with Volt Switch and switches out
2. Player sends out a mon with Intimidate
3. Intimidate activates against the fainted mon
4. AI sends out its next mon

Expected behaviour:
1. Player's mon KO's an AI mon with Volt Switch and switches out
2. Player sends out a mon with Intimidate
3. AI sends out its next mon
4. Intimidate activates against the new opponent

Presumably this also affects Trace, Frisk, Download, Anticipation, Forewarn and whatever other switch in abilities interact with the opponents.

**Comment by AsparagusEduardo** [comment]
There's #2148 that would fix it for Download, but I didn't approve it because it would skip triggering at all in this situation. I'm thinking switch-in abilities should be rethought to fix this for all of them.

**Comment by BuffelSaft** [comment]
Yeah, at the the very least they need some extra logic to wait for both sides to finish any switch-ins before they activate.
