### ISSUE TITLE
Sever fork

### ISSUE THREAD

**Issue by gruxor** [rh-hideout/pokeemerald-expansion#2375]
Title, basically. 

The project has diverged massively, both from Egg's repo and pret, I think it'd be a good idea to cut the cord.

### **Pros**
- We can create our own personal forks for this repo while also having forks for pret/pokeemerald, allowing for easier/cleaner PRs and less confusion about compatibility
- Less confusing for new users/contributors (it won't link to Egg's repo, which is now inactive/used for other things)

### **Cons**
- None that I can see. Egg is already credited in the readme (could update it to a link to his github or his repo, same thing) so the fork isn't really facilitating anything other than causing the issues that the above "pros" section fixes.

I guess this might be unfixable until @ultima-soul is back, or whoever has access to this sort of thing, but still figured I'd throw it out there.

**Comment by AsparagusEduardo** [comment]
> * We can create our own personal forks for this repo while also having forks for pret/pokeemerald, allowing for easier/cleaner PRs and less confusion about compatibility

It doesn't really matter if a user forks from this repo or from pret's, they can set up remotes in their local repos to either.
A way to have separate environments for working with pokeemerald's and expansion's repos separetly is cloning twice, each with their own remotes and PRs if needed.

> * Less confusing for new users/contributors (it won't link to Egg's repo, which is now inactive/used for other things)

The only thing we're linked to Egg's repo is hierarchy-wise in the fork tree, but besides that there's nothing really binding us to it. The Pokécommunity thread now points here, so users know to look in here for the latest updates.
 
Honestly, I don't see the point at all of doing this. The transition will be more confusing to users and discoverability would suffer due to it no longer being part of the forking tree.

**Comment by gruxor** [comment]
> It doesn't really matter if a user forks from this repo or from pret's, they can set up remotes in their local repos to either. A way to have separate environments for working with pokeemerald's and expansion's repos separetly is cloning twice, each with their own remotes and PRs if needed.

Entirely unnecessary workaround for an easily fixable problem. 

> The only thing we're linked to Egg's repo is hierarchy-wise in the fork tree, but besides that there's nothing really binding us to it. The Pokécommunity thread now points here, so users know to look in here for the latest updates.

Yes, that's precisely the reason it shouldn't be in the fork tree. There's nothing binding us to it. The split branches are gone, Egg's repo serves no function for this repo, and pret commits are merged in with careful consideration for the changes that have been made here.

> Honestly, I don't see the point at all of doing this. The transition will be more confusing to users and discoverability would suffer due to it no longer being part of the forking tree.

There's several points addressed above, but there's also one you didn't address - the "compatibility" aspect that I talked about. Unless someone marks their published branches with prefixes or something similar, there's no telling if a given feature branch is dependent on pret or this repo. If split, it becomes extremely clear which projects are for which repo. 

It's a hundred times more confusing for new users otherwise (at least those familiar with typical github practices), because it implies that code designed for one is compatible with the other and vice versa - but that's almost never the case, and this project makes a multitude of breaking, incompatible changes (and the canyon of difference will only increase in the future).

Discoverability won't suffer for the reason you already listed yourself - it's linked on the PokéCommunity page. 

On top of that, pokeemerald has [over a thousand forks.](https://github.com/pret/pokeemerald/network/members) Even if you're looking at the most popular/active forks via a tool such as [this one,](https://techgaun.github.io/active-forks/index.html#pret/pokeemerald) you'll see Egg's repo first. You'd have to then run _that_ fork through the same tool to find the top list, of which this repo is _second_ behind BuffelSaft's. No one is discovering this through the fork tree, I promise.

There's zero point in keeping it as a fork, not the other way around.

**Comment by ExpoSeed** [comment]
The reason why it was a fork initially was to credit egg and to migrate prs from egg to us

>>> If split, it becomes extremely clear which projects are for which repo.

This is not true because each project can have branches with different remotes, and it's the norm for feature branches to be on someone's fork of pret

Additionally I think it's valuable enough to stay in the fork network because when making a pr, github will show you branches from the fork network, and I still want that to include forks of vanilla (both because it's easier and because that's the standard for prs now)

**Comment by gruxor** [comment]
> The reason why it was a fork initially was to credit egg and to migrate prs from egg to us

Not arguing it never should have been a fork, just that it's now outgrown it - and continue to grow as the scope expands and things are modified.

> This is not true because each project can have branches with different remotes, and it's the norm for feature branches to be on someone's fork of pret

It's the norm because it's currently the only option. Because this is a fork.

Having fundamentally divergent code on the same repo is a bad setup, so ideally you'd split those. Yes, locally you can do whatever you want with remotes, but when you go to publish it things become messy quickly - again, you'd need branch prefixes to separate which branches are for pret and which are for RHH. Doesn't make any sense if you care at all about usability and clarity. It's a complete... clusterfork. (no, I'm not sorry)

**Comment by ExpoSeed** [comment]
The problem is that the cost of removing rhh from the fork network of pret is losing the ability for pret-descended repos to be able to pr to us. I do not think that is worth the cost

**Comment by ExpoSeed** [comment]
I don't think it's a non issue because currently all of the PRs are on pret's fork network, which means there will be some overhead in migrating everything to the new fork network, which I don't think is worth. In addition, I don't think the costs of being a fork are so high in the first place (I have never seen confusion about compatibility between rhh and pret PRs), and I don't think making a new fork network will address the problems of feature branches you bring up (feature branches for RHH by users will stay on the same repo as feature branches for pret, because feature branches are not constrained by fork network).

**Comment by gruxor** [comment]
> I don't think it's a non issue because currently all of the PRs are on pret's fork network, which means there will be some overhead in migrating everything to the new fork network, which I don't think is worth.

It's only done this way because it's currently done wrong, detaching it would remove this issue with any future branches/forks/PRs that exist (as well as any that update, and they should).

> In addition, I don't think the costs of being a fork are so high in the first place (I have never seen confusion about compatibility between rhh and pret PRs)

There's little confusion currently because it's the only way it's ever been done. That doesn't make it the correct way, or the best way (and it isn't, unless you're creating compatible/adjacent code, which RHH hasn't for a while now). 

It doesn't cause any confusion about PRs because PRs exist on the respective repo. The confusion stems from the fact that in order to PR into both pret and RHH, you currently have to either store RHH-cloned branches in pret-forked repos, or you have to store pret-cloned branches in RHH-forked repos. You can't PR without a fork, and you can't fork if you already have an upstream/downstream/somewhere-else-in-network fork on your account. This is why people detach, and why I'm suggesting it.

> feature branches for RHH by users will stay on the same repo as feature branches for pret

Not if they update them, as they should. If they don't that's on them, but they also won't have comparison compatibility with the proper upstream, and personally I'm not going to pull from a repo that isn't designed to be compatible with the version I'm using (RHH in this case) unless it merges clean.

> because feature branches are not constrained by fork network

This isn't true at all if you care about the repo your code resides on matching the target repo/fork it was intended for. If you don't care then that's fine - but for a public repo that other people are going to use, it should at least try to be somewhat organized and reduce as many headaches as possible. It also helps promote people to contribute and build upon the repo if their contribution doesn't depend on them bastardizing their existing pret fork.

> I also haven't really seen an issue of contributors being confused by the link to egg's repo

I was, when I first got involved (along with a lot of confusion surrounding the three-separate-branches issue which was one of the first things I discussed when I joined). I remember thinking, "Why is this fork derived from another that's seemingly inactive? If Egg isn't with the project anymore, why fork it? Is he still working on it separately? Why fork it in the first place, if it was planned to be a separate expansion with no goal of compatibility? Why not parent it upstream, at least? Or better yet, detach it altogether, since it seems to cause compatibility issues via the massive overhauls/features it implements, which break other feature branches that are designed for upstream?" and so here we are. I just never brought it up until now, because I was mostly focused on the expansion and learning in the context of improving it, rather than submitting a PR to pret. But I got the idea for one that'd fit better in pret today, only to realize I couldn't due to the fork network.

Hopefully that clears up the intent here a bit, and clarifies why it's necessary if the repo is one that's meant to be for public use.

**Comment by ExpoSeed** [comment]
> This isn't true at all if you care about the repo your code resides on matching the target repo/fork it was intended for. If you don't care then that's fine - but for a public repo that other people are going to use, it should at least try to be somewhat organized and reduce as many headaches as possible. It also helps promote people to contribute and build upon the repo if their contribution doesn't depend on them bastardizing their existing pret fork.

I agree that repos should do this, my point was that deforking wouldn't force them so they won't change anything. When I said they weren't constrained, I mean in terms of git

Aside from that nitpick, FIQ in discord outlined how managing remotes can be more error prone (even if I don't really think it's very burdensome) so I'm more inclined to support this

**Comment by gruxor** [comment]
> my point was that deforking wouldn't force them so they won't change anything.

I don't know what'd convince you of that. Right now the alternative isn't even possible without detaching the repo, so it seems fairly defeatist and pessimistic to say "we shouldn't do this because everyone will keep doing it the wrong way anyways."

> When I said they weren't constrained, I mean in terms of git

Just to clarify then, git isn't part of this discussion - this is specifically in reference to forks and pull requests on GitHub. It doesn't affect local repositories, but we aren't a solely local repository - RHH and pret are on GitHub. So they _are_ constrained, again, if you care about your code matching the repo that it resides on (and everyone should - that's one of the reasons we use GitHub instead of zipping up our projects and sending them to each other to compare/pull changes locally).

But yeah, FIQ did do a good job of adding to the explanation as well.

**Comment by ExpoSeed** [comment]
> I don't know what'd convince you of that.

I'd be convinced if deforking was a breaking change. This is true for PR branches, but it's not for feature branches. I'm not saying we shouldn't do this, just that one of the specific benefits you cited is incorrect

> Git is not part of this discussion

Git and GitHub go hand in hand. Forks and pull requests involve discussions of branches and repos, which use git

**Comment by gruxor** [comment]
> I'd be convinced if deforking was a breaking change. This is true for PR branches, but it's not for feature branches. I'm not saying we shouldn't do this, just that one of the specific benefits you cited is incorrect

It isn't incorrect if people have been prevented from setting their repos up correctly because of the fork, and I know I'm not the only one. Either way, you're talking about a problem that already exists and has to exist with the current system. I'm suggesting we stop forcing people to use an objectively worse, less organized method of repo management. Not to force them to do it a certain way that I think is right. Never said that, wouldn't want that, and it doesn't refute the issue in question in the slightest - it's still a problem no matter what. 

> Git and GitHub go hand in hand. Forks and pull requests involve discussions of branches and repos, which use git

Not in the context of this issue.

**Comment by ExpoSeed** [comment]
> it doesn't refute the issue in question in the slightest - it's still a problem no matter what.

Glad we've come to an agreement 

> Not in the context of the issue.

It was in the context of feature branches. You cannot discuss feature branches without discussing git. However that discussion is now concluded

**Comment by Bassoonian** [comment]
No.
