### ISSUE TITLE
Moves that use the MOVE_TARGET_FOES_AND_ALLY target type are buggy in doubles

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#2393]
Reposting from #1771, may need further testing.

> [bnthomason](https://github.com/bnthomason) commented [on Aug 10](https://github.com/rh-hideout/pokeemerald-expansion/pull/1771#issuecomment-1210963400) •

> Has this been fully fixed yet? Surf and Petal Blizzard, among other moves that target 3 pokemon (player and opponent), don't seem to function properly. I notice that the right side player pokemon uses these moves, and the left side player pokemon isn't affected. Similar thing happens with the left side opposing pokemon for the right side player pokemon.

> [LOuroboros](https://github.com/LOuroboros) commented [on Aug 10](https://github.com/rh-hideout/pokeemerald-expansion/pull/1771#issuecomment-1211003066) •

> I can replicate the issue, but I don't think it's related to the changes in this PR itself.

![wsl_20220810_140241661](https://user-images.githubusercontent.com/4485172/183973680-cbc236aa-302a-40cc-86f2-575d202c0b2b.gif)

***Note**: `HITMARKER_ALLOW_NO_PP` is the new name of `HITMARKER_x800000`.*

**Comment by AsparagusEduardo** [comment]
It seems #1676 will fix this.
![foesAndAlly2](https://user-images.githubusercontent.com/2904965/197354281-f1346549-e872-4188-824f-f5a46ae5bbb9.gif)

**Comment by AsparagusEduardo** [comment]
#1676
