### ISSUE TITLE
[battle_engine] Indefinite stall starting a 2v1 multi-battle

### ISSUE THREAD

**Issue by Pyredrid** [rh-hideout/pokeemerald-expansion#24]
Originally submitted by LOuroboros on DizzyEggg's bev2 branch as Issue 492.  Being resubmitted just before submitting my pull request for future clarification.

> As brought up by @Ryuhouji on Discord, multi battles on an up-to-date copy of the battle_engine_v2 are freezing right after your partner and you send out their Pokémon.
https://streamable.com/xr2nae

> However, I noticed that it all works normally if I go back to the commit a42bd3f, @DizzyEggg.
https://streamable.com/5hep7y

> I suppose the problem may have been caused by one of the following commits: 9a7963e, f70a9ce or 97d0643, since they're the only commits you submitted after commit a42bd3f.

> For reference, the tests were done using this script: https://pastebin.com/raw/mGQdvCv9

**Comment by ExpoSeed** [comment]
c4d83f0640b3cdae7698bdf14800f61b80a8ef34
