### ISSUE TITLE
Ash-Greninja's Water Shuriken doesn't always hits 3 times

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#2400]
![shuriwhat](https://user-images.githubusercontent.com/2904965/197062690-c537cfee-bea2-4713-bf46-9c1dc8b97fcb.gif)

**Comment by LOuroboros** [comment]
It may be worth re-testing this in a branch with #1676 merged? There's a chance that PR could solve the problem after all :eyes:

**Comment by BuffelSaft** [comment]
Yeah that should be fixed in the multihit PR. If anyone's ready for a re-review I can merge in the latest changes tomorrow.

**Comment by BuffelSaft** [comment]
Resolved by #1676
