### ISSUE TITLE
Reminder: Add changelog to the repository

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#2406]

**Comment by DizzyEggg** [comment]
Can this be closed since we have a changelog every release now?

**Comment by LOuroboros** [comment]
I think this could be repurpose into a reminder to have a more general CHANGELOG.md for the project :eyes:

**Comment by AsparagusEduardo** [comment]
I think this was specifically about adding the changelog to the repo itsel---ninja'd

**Comment by AlexOn1ine** [comment]
wasn't one added recently?

**Comment by LOuroboros** [comment]
> wasn't one added recently?

Neither the Master branch nor the Upcoming branch have one right now, and there's no PRs including the word "changelog" in their title, I'm guessing that there wasn't :eyes:

**Comment by AlexOn1ine** [comment]
> > wasn't one added recently?
> 
> Neither the Master branch nor the Upcoming branch have one right now, and there's no PRs including the word "changelog" in their title, so I'm guessing that there wasn't 👀

I thought Edu made one. Could have been something else though.

**Comment by AsparagusEduardo** [comment]
> I thought Edu made one. Could have been something else though.

All changelogs I made were for the Releases page. We could move those to the repo 👀
