### ISSUE TITLE
Battle Arena/Fallarbor tent issue

### ISSUE THREAD

**Issue by Doct0rLekter** [rh-hideout/pokeemerald-expansion#2421]
Damaging moves don’t display type until you hover a status move, at which point they will display the type of the status move you hover. If the players first Pokémon faints for any reason, or loses in any other way, the player will crash to title screen. There are also several other instances where it crashes, but none as easily reproducible as having player’s first Pokémon faint. (Apologies for not posting this with the original battle palace issue #2396 since they are clearly linked.)

![image](https://user-images.githubusercontent.com/115762567/198855425-e769e331-7c99-4755-b800-9ff8e5d349d1.png)

![image](https://user-images.githubusercontent.com/115762567/198855487-d1ceff2f-a57f-4a9c-8eae-8cb1ac7cefe6.png)

![image](https://user-images.githubusercontent.com/115762567/198855494-4d7e8eff-6236-4ebf-a205-7d64f77d3523.png)

![image](https://user-images.githubusercontent.com/115762567/198855506-ffce1f93-71a0-420c-9fa6-30f8456a7d3c.png)

**Comment by DizzyEggg** [comment]
Couldn't reproduce in the upcoming branch. Does it still occur / are there additional steps needed?

**Comment by Doct0rLekter** [comment]
Hmmm, I am not having the issue on a clean branch with the fix applied. It seems that, while there was a problem prior to the fix for Verdanturf, that issue is now resolved. In other words, the crash to desktop issue is on my end, and the other noted issues were succesfully solved.

**Comment by Doct0rLekter** [comment]
#2416
