### ISSUE TITLE
Battle Bond doesn't transform when fainting ally

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#2431]
Found by akimoto#5337 on RHH's discord

![player](https://user-images.githubusercontent.com/2904965/199972456-ed89fd05-10d6-48de-9e9a-caa37cc01d65.gif)

**Comment by LOuroboros** [comment]
Can't confirm. It's working just fine in a clean copy of the upcoming branch.
![mGBA_20221104_095207163](https://user-images.githubusercontent.com/4485172/199976988-d7195b39-6db2-41d9-b864-a16e95d6567a.gif)

**Comment by DizzyEggg** [comment]
Cannot reproduce the check on upcoming. Could anyone else try this?

Also, I don't think it's necessary to change CalculateEnemyPartyCount, it does what it needs to do imo

**Comment by AlexOn1ine** [comment]
Tried to reproduce but everything seemed fine.

**Comment by LOuroboros** [comment]
> Also, I don't think it's necessary to change CalculateEnemyPartyCount, it does what it needs to do imo

Does it?

I mean, I provided a logical example with the AI, but what if it's the enemy's BB Greninja that performs the fainting? Wouldn't the ability's code *still* use `CalculateEnemyPartyCount` which reads `gEnemyParty`, when it should be using `CalculatePlayerPartyCount` instead?
