### ISSUE TITLE
To-do: check that all gen 1-3 moves and abilities have been updated to modern standards

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#2436]
There are still a few obscure mechanical changes to old moves that haven't been included in the expansion. E.g. in gen 4+, Sketch can copy  Metronome, Mimic, and Transform, but could not copy those moves in gen 3. Chances are there are more changes like this, so at some point we'll have to slog through Bulbapedia's [list of moves](https://bulbapedia.bulbagarden.net/wiki/List_of_moves) and check for changes to anything with non-generic effects.

**Comment by AsparagusEduardo** [comment]
We do have this: https://github.com/rh-hideout/pokeemerald-expansion/issues/1401

**Comment by BuffelSaft** [comment]
Oh nice, that's most of them. I assume we're just missing really weird stuff like move exclusions that get changed every other gen.

**Comment by AsparagusEduardo** [comment]
You can update the list if you feel something's missing :)
Because of that, I'll close this issue.
