### ISSUE TITLE
Berries don't work anymore (but they do work fine with Bug Bite!)

### ISSUE THREAD

**Issue by eatthepear** [rh-hideout/pokeemerald-expansion#2448]
I believe with the new fix to Bug Bite, berries in general are broken. I tried a battle with an enemy mon holding a Sitrus Berry, got it to less than half health. The message said "Foe Qwilfish's ???????? restored health!" then didn't restore any health. If someone else can confirm on a clean copy of the battle engine, that'd be great!

**Comment by BuffelSaft** [comment]
Unable to replicate this in a clean copy of upcoming:
![sitrus](https://user-images.githubusercontent.com/28769716/201074843-4a9485a6-c4a5-4652-9dcc-8456abb4ecfd.gif)
![sitrus2](https://user-images.githubusercontent.com/28769716/201075123-6938ed23-70d0-4704-8812-54c156daaef8.gif)

**Comment by AsparagusEduardo** [comment]
@eatthepear please describe the full situation in case you've encountered an edge case.

**Comment by eatthepear** [comment]
I'm taking a look right now. So far it seems to be working sometimes and not others (it seems the item ID is copied from a different pokemon's itemID). It might be an issue on my end (like a faulty merge conflict or smthn) but will keep y'all updated.

**Comment by eatthepear** [comment]
It might be a double battle / multi battle issue. In a standard double battle, I had both opponent's mons copying my left mon's item ID (it held a muscle band so the msg printed muscle band).

**Comment by eatthepear** [comment]
seems to be an issue on my end (just tested in single battle, works incorrectly). I'll close this issue and open a new one if I'm unable to find a difference between rhh and my code.

**Comment by eatthepear** [comment]
I tested on a clean copy of upcoming. Set lass Tiana to Roxanne's first gym party and gave her first Geodude a Sitrus Berry. My party was the CHEAT START party (lv 20 treecko leading with no item). When the Geodude fell below half HP, it said "Foe Geodude's ?????? restored health" and then didn't restore any health. The use item animation played. Very similar thing happened for her Nosepass holding an Oran Berry in the back.

**Comment by eatthepear** [comment]
![cleancopy](https://user-images.githubusercontent.com/65027979/201208420-92a2b6f9-b9bf-491e-86f4-3a1648560725.gif)

**Comment by eatthepear** [comment]
![playeritem](https://user-images.githubusercontent.com/65027979/201209333-2f75eac1-c165-48ce-8b18-e8d9b7f6ae3e.gif)
Player berries seem to work fine (need to still test for double battles).

**Comment by eatthepear** [comment]
FOUND THE ISSUE
Ghoulslash most likely accidentally deleted a line while copy pasting functions. In ItemBattleEffects, in the ITEMEFFECT_MOVE_END case, there should be a `gLastUsedItem = gBattleMons[battlerId].item;` line that's missing! It shoudl just go right below the for loop, as so:
![Capture](https://user-images.githubusercontent.com/65027979/201263487-02f84cc6-5a33-4967-a76e-a88e3c1a4cd2.PNG)

**Comment by eatthepear** [comment]
If someone can test to make sure this works (i.e. both regular berry activations and bug bite activations work), that'd be great! (This would explain why the message is both playing the wrong thing, as well as the wrong item is set.)

**Comment by BuffelSaft** [comment]
Turns out the reason I couldn't replicate this was because I forgot to build the ROM after pulling upstream. Can confirm the bug.

**Comment by AsparagusEduardo** [comment]
#2451
