### ISSUE TITLE
Eggs sometimes appear glitched

### ISSUE THREAD

**Issue by SubzeroEclipse** [rh-hideout/pokeemerald-expansion#2454]
I found out by testing some daycare stuff that once in a while, the game generates eggs that appear without both mini icon and sprite (for the latter, it pulls out a glitched sprite of the last mon that was shown).
![gif 1](https://user-images.githubusercontent.com/115349505/203298784-366813be-d63d-4d25-977b-58dcf3f87f9e.gif)
This happens with all mons enabled. I also noticed that this still happens with Gen 4+ guys disabled, but instead of an invisible mini icon it shows this weird square.
![3](https://user-images.githubusercontent.com/115349505/203299545-d626eec4-50c0-4d1a-be8f-28f631fc9acf.png)
That said, those eggs hatch just fine with the intended mon.

**Comment by SubzeroEclipse** [comment]
> what happens if you switch party positions?

Still keeps the invisible mini icon/square, but no other weirdness happens.
![switch2](https://user-images.githubusercontent.com/115349505/203334995-f1fc4396-42c5-4f14-a7d1-1a01ebaec831.gif)
![switch1](https://user-images.githubusercontent.com/115349505/203335021-962186c2-1e55-43bc-a211-02694268c569.gif)
Same deal for putting them in the PC.
![pc1](https://user-images.githubusercontent.com/115349505/203335884-dfac15d8-61f5-4189-a578-99b87f30e820.gif)
![pc2](https://user-images.githubusercontent.com/115349505/203336460-8d62121b-65b3-4ef8-9e93-4f95cf7a373b.gif)

**Comment by Land0fChocolate** [comment]
I would like to add, that this can happen when being given an egg from the old lady in Lavaridge, not just the daycare.
![eggspritebug_sum1](https://user-images.githubusercontent.com/52083703/209552072-5f78889e-d8d2-47eb-b43e-fc6096569852.png)
