### ISSUE TITLE
Add preproc config for (no longer) consumable items.

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#2458]
SV have been officially out for a while, so I figure we should start to keep some notes about certain features and mechanics that should/could be implemented in the expansion soon enough.

Held items that used to be fully consumed when activated are no longer consumed on activation. They're returned to the Pokémon holding them at the end of a battle.

https://twitter.com/Flametix/status/1596229960179814400

https://gamefaqs.gamespot.com/boards/370034-pokemon-scarlet/80245996

**Comment by AsparagusEduardo** [comment]
#2932
