### ISSUE TITLE
Mimicry may be broken

### ISSUE THREAD

**Issue by eatthepear** [rh-hideout/pokeemerald-expansion#2472]
Just had a battle in which the opposing Pokemon set up Electric Terrain, then when the Galarian Stunfisk came in, it said "Stunfisk changed into the Electric type" and froze, music still running.

**Comment by AsparagusEduardo** [comment]
Can you check if it happens with the other 3 terrains? If it only happens with Psychic Terrain too, you might want to apply the changes in #2469 if you're not using the `upcoming` branch.

If that fixes it, please let me know.

**Comment by eatthepear** [comment]
Pulled the changes in the upcoming branch, no dice unfortunately.
![mimicrybroken](https://user-images.githubusercontent.com/65027979/206539792-502407f2-a6ee-4e83-88ed-5b65dba4e3a7.gif)
![mimicrybroken2](https://user-images.githubusercontent.com/65027979/206539796-a02c7d63-9ce6-4ab5-8119-b0e3734cbec6.gif)

**Comment by AsparagusEduardo** [comment]
From the tests I've made, it only happens when switching in, as using while the Pokémon is already in battle will work correctly.
