### ISSUE TITLE
B_DOUBLE_WILD_CHANCE is not infallible

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#2521]
Title.

Sometimes, even if you set `B_DOUBLE_WILD_CHANCE` to 100 you can still get a single wild battle.

I imagine this shouldn't really happen, so I'm opening an Issue ticket for it.

**Comment by AsparagusEduardo** [comment]
yeah, that was my bad.
I think changing it to
```diff
- else if ((Random() % 100) + 1 < B_DOUBLE_WILD_CHANCE)
+ else if ((Random() % 100) + 1 <= B_DOUBLE_WILD_CHANCE)
```
should suffice.

**Comment by AsparagusEduardo** [comment]
#2526
