### ISSUE TITLE
Right move tutor in Battle Frontier is bugged

### ISSUE THREAD

**Issue by SubzeroEclipse** [rh-hideout/pokeemerald-expansion#2523]
Tested on 1.3.0. Talking to the old lady on the right loads up a glitched window that lets the player select only the first teachable move, and if exited by pressing B, the game gets frozen.
![1](https://user-images.githubusercontent.com/115349505/208297475-e067297c-c530-4d1f-a530-0204b207dc31.gif)
On the other hand, if the player talks to the tutor on the left first and then talks to the one on the right, it loads the left's selection (but the moves that are actually teached are the right's).
![2](https://user-images.githubusercontent.com/115349505/208297573-961f125b-ec6e-422c-b97c-d3d6ba8e2379.gif)
Anyway, looking at the scripts.inc file, I noticed that Crater's PR deleted the line that sets the variable loading the right tutor's scrollable menu, but not the left's. I tried adding those back and it solves the issue. So I'm wondering - was there a reason why those were removed in the first place?

**Comment by LOuroboros** [comment]
> So I'm wondering - was there a reason why those were removed in the first place?

If I had to guess judging by what you said in this ticket, I'd say it was an accident that was overlooked in the reviewing phase.
