### ISSUE TITLE
Display nature benefits

### ISSUE THREAD

**Issue by ciriousjoker** [rh-hideout/pokeemerald-expansion#2535]
In many hacks, the list of stats indicates which stat has been increased and decreased based on nature. This doesn't seem to be the case here.

Is this planned? Do I need to enable some config before building?

**Comment by LOuroboros** [comment]
> Is this planned? Do I need to enable some config before building?

No, and no.

Considering how "the scope" of the project is barely there, I wouldn't be surprised if it got merged in eventually though.

@AsparagusEduardo has the last word.

**Comment by AsparagusEduardo** [comment]
> @AsparagusEduardo has the last word.

Wait, I do? xD

I mainly voice my opinion on how stuff should be done and start developing based on that, but anyone is open to tell me if something should be done differently.

I think it would make sense to add this as a config option, as I feel the current scope of the expansion is "support for official features that can realistically be implemented".

**Comment by AlexOn1ine** [comment]
#3582
