### ISSUE TITLE
Shield Dust's interaction with Intimidate softlock the game

### ISSUE THREAD

**Issue by sphericalice** [rh-hideout/pokeemerald-expansion#2536]
On the `upcoming` branch, it looks like Shield Dust and Intimidate's interaction causes a soft lock:
![intimidate_softlock](https://user-images.githubusercontent.com/5409219/209480313-62a3881e-e79a-486d-886f-d2a652e0dc28.gif)

**Comment by AsparagusEduardo** [comment]
#2538
