### ISSUE TITLE
Intimidate is reading the wrong abilities names

### ISSUE THREAD

**Issue by eatthepear** [rh-hideout/pokeemerald-expansion#2537]
![bug](https://user-images.githubusercontent.com/65027979/209483083-780160c7-6a36-43db-8a4f-52f6d62397d1.gif)
If someone could verify this works on a clean copy of upcoming, that'd be great! (I am up to date)

**Comment by ShinyDragonHunter** [comment]
Looks like the string buffer is getting the name and ability of the Intimidate target instead of the Intimidate user

**Comment by AsparagusEduardo** [comment]
#2538
