### ISSUE TITLE
Houndour/Houndoom graphical softlock

### ISSUE THREAD

**Issue by sphericalice** [rh-hideout/pokeemerald-expansion#2540]
Very mysterious bug when the enemy party has a Houndoom or Houndour on its team (but only if the party is 2 or larger?):
![houndoom](https://user-images.githubusercontent.com/5409219/209583590-c084faf0-228c-427d-9b4c-bfcddf77c6ac.gif)
Recreated on the latest upcoming branch as of this issue's creation, the only changes being giving Route 103 May's team a lv32 Houndour and lv33 Houndoom.

**Comment by sphericalice** [comment]
Just documenting this on GitHub as well: this issue is actually caused by Beat Up's damage calc being called by the AI before gBattleCommunication[0] has been set by Beat Up's battle script, leading to an out-of-bounds arrray access that corrupts the party data.

<img width="541" alt="image" src="https://user-images.githubusercontent.com/5409219/209657288-91a2c8ab-79f5-4d8a-992a-5ce515d4f110.png">

**Comment by AsparagusEduardo** [comment]
#2541
