### ISSUE TITLE
Pokemon with Clear Body don't get self inflicted stat reduction from Hammer Arm

### ISSUE THREAD

**Issue by Land0fChocolate** [rh-hideout/pokeemerald-expansion#2546]
Scenario: Pokemon with Clear Body ability (e.g. Regice) uses Hammer Arm. Not getting the speed drop.

Curiously, Overheat doesn't have this problem.

**Comment by LOuroboros** [comment]
Can confirm.

![mGBA_20221231_150725239](https://user-images.githubusercontent.com/4485172/210152205-b057e06a-794c-4d50-b132-af48231a6a79.gif)

**Comment by AsparagusEduardo** [comment]
#2548
