### ISSUE TITLE
MOVE_BREAKNECK_BLITZ is broken

### ISSUE THREAD

**Issue by AaghatIsLive** [rh-hideout/pokeemerald-expansion#2558]
https://user-images.githubusercontent.com/109757010/210400806-5095c4b9-cf92-4f10-91ad-cd54b6a9d3cd.mp4

It always uses the 4th move instead of the selected one.

**Comment by AlexOn1ine** [comment]
It is not just an issue with `MOVE_BREAKNECK_BLITZ`. It is related to z moves. 
![z_move](https://user-images.githubusercontent.com/93446519/219974041-25c590cd-f9ab-474b-88c2-31f741e219b5.gif)
Basically anytime there is a status move of the same type in one of the 3 next slots it deletes the z move effect of the previous damaging dealing move in function `IsViableZMove`
```
            if (IS_MOVE_STATUS(move))
                gBattleStruct->zmove.chosenZMove = move;
            else
                gBattleStruct->zmove.chosenZMove = GetTypeBasedZMove(move, battlerId);
```
Changing it to just this line solves the bug
```
gBattleStruct->zmove.chosenZMove = GetTypeBasedZMove(move, battlerId);
```
![z_move2](https://user-images.githubusercontent.com/93446519/219974400-c9125457-1647-4c2a-b36e-9d67b7f8763a.gif)
Though I'm not sure if this creates a different problem but it shouldn't since it is just setting the type of the move z move, right?

**Comment by AaghatIsLive** [comment]
> ```
>             if (IS_MOVE_STATUS(move))
>                 gBattleStruct->zmove.chosenZMove = move;
>             else
>                 gBattleStruct->zmove.chosenZMove = GetTypeBasedZMove(move, battlerId);
> ```
> 
> Changing it to just this line solves the bug
> 
> ```
> gBattleStruct->zmove.chosenZMove = GetTypeBasedZMove(move, battlerId);
> ```
> I'm not sure if this creates a different problem but it shouldn't since it is just setting the type of the move z move, right?

@AlexOn1ine  Tested it out and this happened, 

![zm (1)](https://user-images.githubusercontent.com/109757010/221360237-63e5ae95-01eb-43e7-8984-1d3769356f4d.gif)

It forced me to use my zmove on a move of another type

**Comment by AlexOn1ine** [comment]
Yeah, was able to reproduce. I think I know what is happening but good that I didn't PR this. Thanks for testing it out.

**Comment by AlexOn1ine** [comment]
Something similar is also happening with the current implementation.
![z_move_status](https://user-images.githubusercontent.com/93446519/221552326-9b35b947-b1d4-479f-b7a5-4b474e4e5b7d.gif)

**Comment by AaghatIsLive** [comment]
> ```
>             if (IS_MOVE_STATUS(move))
>                 gBattleStruct->zmove.chosenZMove = move;
>             else
>                 gBattleStruct->zmove.chosenZMove = GetTypeBasedZMove(move, battlerId);
> ```
> 
> Changing it to just this line solves the bug
> 
> ```
> gBattleStruct->zmove.chosenZMove = GetTypeBasedZMove(move, battlerId);
> ```
> I'm not sure if this creates a different problem but it shouldn't since it is just setting the type of the move z move, right?

@AlexOn1ine I think your suggestion fixes it. The taunt one was a separate issue, and I haven't had any issues with Z-moves since then. 

except for this one where the move crashed the game in a double battle, but it could be a different issue.
![IMG_8244](https://user-images.githubusercontent.com/109757010/232472514-78b23a36-4c11-4cb0-9a84-cf83ed7179d4.jpg)

**Comment by AlexOn1ine** [comment]
> except for this one where the move crashed the game in a double battle, but it could be a different issue.

Does the issue happen without the change? If it does then I PR my change and maybe something comes up in the review.

**Comment by AaghatIsLive** [comment]
> Does the issue happen without the change? If it does then I PR my change and maybe something comes up in the review.

@AlexOn1ine Yeah, it does. You should go ahead and PR this.
