### ISSUE TITLE
Certain Pokémon do not evolve correctly when fed a Rare Candy at Lv100

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#2563]
Originally reported by Land0fChocolate#5435 at Pret's Discord. Since they didn't make an Issue ticket, here's one.

Basically, certain Pokémon such as Sneasel do not evolve when fed a Rare Candy at Lv100 even if the conditions are met.

For example, such is the case with Sneasel. Even if you feed a Rare Candy to a Lv100 Sneasel during the night while they're holding a Razor Claw, they do not evolve. They just lose the Razor Claw, and you just lose 1 Rare Candy.

![ApplicationFrameHost_20230108_033729337](https://user-images.githubusercontent.com/4485172/211189444-801c0d02-f24d-43e8-97e2-5f08826ce245.gif)

**Comment by Jaizu** [comment]
I'm party sure that affects Pokémon with held items
Issue appears to be here:
```
static void PartyMenuTryEvolution(u8 taskId)
{
    struct Pokemon *mon = &gPlayerParty[gPartyMenu.slotId];
    u16 targetSpecies = GetEvolutionTargetSpecies(mon, EVO_MODE_NORMAL, ITEM_NONE, NULL);
```
Since is not checking for `EVO_MODE_ITEM_CHECK`, which checks for EVO_ITEM, EVO_ITEM_FEMALE, EVO_ITEM_MALE and EVO_ITEM_NIGHT

**Comment by LOuroboros** [comment]
The cause is the way in which the evolution method removed the item from the Pokémon btw.
Commenting out the `` and `` within the `case EVO_ITEM_HOLD_NIGHT:` of the `switch` at `GetEvolutionTargetSpecies` "solves the issue", in the sense that it makes the Lv100 Rare Candy work normally.

*But then it naturally creates another issue as the held item is never consumed.*

**Comment by LOuroboros** [comment]
> I'm party sure that affects Pokémon with held items Issue appears to be here:
> 
> ```
> static void PartyMenuTryEvolution(u8 taskId)
> {
>     struct Pokemon *mon = &gPlayerParty[gPartyMenu.slotId];
>     u16 targetSpecies = GetEvolutionTargetSpecies(mon, EVO_MODE_NORMAL, ITEM_NONE, NULL);
> ```
> 
> Since is not checking for `EVO_MODE_ITEM_CHECK`, which checks for EVO_ITEM, EVO_ITEM_FEMALE, EVO_ITEM_MALE and EVO_ITEM_NIGHT

There's no need to check for `EVO_MODE_ITEM_CHECK` because the methods therein are not affected by this feature in the official games, and anyone can see, the method talked about in the example case is one of the methods inside the `EVO_MODE_NORMAL` which is the evolution mode that the feature should be working for.

The issue is definitely related to held items and how we clear them at the time of performing an evolution though.
