### ISSUE TITLE
Illusion does not fool the AI

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#2582]
Unless I've missed something, the issue seems to be that `SetBattlerData` only sets the illusion mon's species, but not its types or stats, so the AI acts as if it does nothing.

To test in a trainer battle:
- Disguise player side Zoroark as a Gengar
- Give enemy AI Psychic and Aura Sphere, no other moves
- Set aiFlags = AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_TRY_TO_FAINT | AI_FLAG_CHECK_VIABILITY | AI_FLAG_PREFER_STRONGEST_MOVE
- AI will go for aura sphere every time

In this scenario it should use Psychic as it thinks it's attacking a Gengar, then try aura sphere the next turn (if we want it to be smart), or keep using psychic (if we want game freak level AI).

**Comment by Jaizu** [comment]
I can confirm that I was having the same issue and this was noted on RHHs Discord
![image](https://user-images.githubusercontent.com/18596778/214054445-175c1d2b-f92b-496c-9075-517bdd0a84c7.png)

**Comment by Jaizu** [comment]
As a temporary fix you could make the AI treat illusion as an ability like water absorb. So if a move doesnt affect you, it will try another one.
![image](https://user-images.githubusercontent.com/18596778/214063627-99e43296-269c-4c2b-b51c-1532dc616374.png)

This is just a temp fix and is not being pushed -at least currently- to the rhh engine, a topic is being discussed about possible solutions in the RHH's Discord at the time I'm writing this.
