### ISSUE TITLE
Healing Wish/Lunar Dance missing gen 5 and 8 changes.

### ISSUE THREAD

**Issue by mrgriffin** [rh-hideout/pokeemerald-expansion#2596]
From [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Healing_Wish_(move)):
> The receiving Pokémon is now sent out at the end of the turn rather than immediately sending it out. 

> If the Pokémon sent out to replace the user already has full health and no status condition, Healing Wish's effect will not activate until a Pokémon is placed in that position (either by switching in or using Ally Switch). A pending Healing Wish will not activate if a Pokémon already in that position loses HP or gains a status condition; it will only activate when a new Pokémon is placed in that position. Each position can only have a single instance of Healing Wish pending (using it multiple times does not stack). Healing Wish can stack with Lunar Dance.

**Comment by LOuroboros** [comment]
#2222 and #2126.
