### ISSUE TITLE
Missing Mon Animations

### ISSUE THREAD

**Issue by ghoulslash** [rh-hideout/pokeemerald-expansion#26]
- [x] abomasnow
- [x] abomasnow (female)
- [ ] abomasnow_mega
- [x] abra
- [x] absol
- [ ] absol_mega
- [x] accelgor
- [x] aegislash
- [x] aegislash_blade
- [x] aerodactyl
- [ ] aerodactyl_mega
- [x] aggron
- [ ] aggron_mega
- [x] aipom
- [x] aipom (female)
- [x] alakazam
- [x] alakazam (female)
- [ ] alakazam_mega
- [ ] alcremie_caramel_swirl
- [ ] alcremie
- [ ] alcremie_lemon_cream
- [ ] alcremie_matcha_cream
- [ ] alcremie_mint_cream
- [ ] alcremie_rainbow_swirl
- [ ] alcremie_ruby_cream
- [ ] alcremie_ruby_swirl
- [ ] alcremie_salted_cream
- [x] alomomola
- [x] altaria
- [ ] altaria_mega
- [x] amaura
- [x] ambipom
- [x] ambipom (female)
- [x] amoonguss
- [x] ampharos
- [ ] ampharos_mega
- [x] anorith
- [x] appletun
- [x] applin
- [x] araquanid
- [x] arbok
- [x] arcanine
- [ ] arcanine_hisuian
- [x] arceus
- [x] archen
- [x] archeops
- [ ] arctovish
- [ ] arctozolt
- [x] ariados
- [x] armaldo
- [x] aromatisse
- [x] aron
- [ ] arrokuda
- [x] articuno
- [ ] articuno_galarian
- [x] audino
- [ ] audino_mega
- [x] aurorus
- [x] avalugg
- [ ] avalugg_hisuian
- [x] axew
- [x] azelf
- [x] azumarill
- [x] azurill
- [x] bagon
- [x] baltoy
- [x] banette
- [ ] banette_mega
- [x] barbaracle
- [x] barboach
- [ ] barraskewda
- [ ] basculegion_female
- [ ] basculegion
- [x] basculin
- [ ] basculin_blue_striped
- [ ] basculin_white_striped
- [x] bastiodon
- [x] bayleef
- [x] beartic
- [x] beautifly
- [x] beautifly (female)
- [x] beedrill
- [ ] beedrill_mega
- [x] beheeyem
- [x] beldum
- [x] bellossom
- [x] bellsprout
- [x] bergmite
- [x] bewear
- [x] bibarel
- [x] bibarel (female)
- [x] bidoof
- [x] bidoof (female)
- [x] binacle
- [x] bisharp
- [ ] blacephalon
- [x] blastoise
- [ ] blastoise_mega
- [x] blaziken
- [x] blaziken (female)
- [ ] blaziken_mega
- [ ] blipbug
- [x] blissey
- [x] blitzle
- [x] boldore
- [ ] boltund
- [x] bonsly
- [x] bouffalant
- [ ] bounsweet
- [x] braixen
- [x] braviary
- [ ] braviary_hisuian
- [x] breloom
- [ ] brionne
- [x] bronzong
- [x] bronzor
- [ ] bruxish
- [x] budew
- [x] buizel
- [x] bulbasaur
- [x] buneary
- [x] bunnelby
- [x] burmy
- [x] burmy_sandy_cloak
- [x] burmy_trash_cloak
- [x] butterfree
- [x] butterfree (female)
- [ ] buzzwole
- [x] cacnea
- [x] cacturne
- [x] cacturne (female)
- [ ] calyrex
- [ ] calyrex_ice_rider
- [ ] calyrex_shadow_rider
- [x] camerupt
- [x] camerupt (female)
- [ ] camerupt_mega
- [x] carbink
- [x] carkol
- [x] carnivine
- [x] carracosta
- [x] carvanha
- [x] cascoon
- [x] castform
- [x] castform_rainy
- [x] castform_snowy
- [x] castform_sunny
- [x] caterpie
- [x] celebi
- [ ] celesteela
- [x] centiskorch
- [x] chandelure
- [x] chansey
- [x] charizard
- [ ] charizard_mega_x
- [ ] charizard_mega_y
- [x] charjabug
- [x] charmander
- [x] charmeleon
- [x] chatot
- [x] cherrim_normal
- [x] cherrim_sunshine
- [x] cherubi
- [x] chesnaught
- [x] chespin
- [x] chewtle
- [x] chikorita
- [x] chimchar
- [x] chimecho
- [x] chinchou
- [x] chingling
- [x] cinccino
- [ ] cinderace
- [x] clamperl
- [x] clauncher
- [x] clawitzer
- [x] claydol
- [x] clefable
- [x] clefairy
- [x] cleffa
- [ ] clobbopus
- [x] cloyster
- [x] coalossal
- [x] cobalion
- [x] cofagrigus
- [x] combee
- [x] combusken
- [x] combusken (female)
- [ ] comfey
- [x] conkeldurr
- [ ] copperajah
- [x] corphish
- [x] corsola
- [ ] corsola_galarian
- [x] corviknight
- [x] corvisquire
- [ ] cosmoem
- [ ] cosmog
- [x] cottonee
- [ ] crabominable
- [ ] crabrawler
- [x] cradily
- [ ] cramorant
- [ ] cramorant_gorging
- [ ] cramorant_gulping
- [x] cranidos
- [x] crawdaunt
- [x] cresselia
- [x] croagunk
- [x] croagunk (female)
- [x] crobat
- [x] croconaw
- [x] crustle
- [x] cryogonal
- [x] cubchoo
- [x] cubone
- [ ] cufant
- [ ] cursola
- [ ] cutiefly
- [x] cyndaquil
- [x] darkrai
- [x] darmanitan
- [ ] darmanitan_galarian
- [x] darmanitan_zen_mode
- [ ] darmanitan_zen_mode_galarian
- [ ] dartrix
- [x] darumaka
- [ ] darumaka_galarian
- [ ] decidueye
- [ ] decidueye_hisuian
- [x] dedenne
- [x] deerling
- [x] deino
- [x] delcatty
- [x] delibird
- [x] delphox
- [x] deoxys
- [x] deoxys_attack
- [x] deoxys_defense
- [x] deoxys_speed
- [x] dewgong
- [x] dewott
- [x] dewpider
- [ ] dhelmise
- [x] dialga
- [ ] dialga_origin
- [x] diancie
- [ ] diancie_mega
- [x] diggersby
- [ ] diglett_alolan
- [x] diglett
- [x] ditto
- [x] dodrio
- [x] dodrio (female)
- [x] doduo
- [x] doduo (female)
- [x] donphan
- [x] donphan (female)
- [ ] dottler
- [x] doublade
- [ ] dracovish
- [ ] dracozolt
- [x] dragalge
- [ ] dragapult
- [x] dragonair
- [x] dragonite
- [ ] drakloak
- [ ] drampa
- [x] drapion
- [x] dratini
- [x] drednaw
- [ ] dreepy
- [x] drifblim
- [x] drifloon
- [x] drilbur
- [ ] drizzile
- [x] drowzee
- [x] druddigon
- [ ] dubwool
- [x] ducklett
- [ ] dugtrio_alolan
- [x] dugtrio
- [x] dunsparce
- [x] duosion
- [ ] duraludon
- [x] durant
- [x] dusclops
- [x] dusknoir
- [x] duskull
- [x] dustox
- [x] dustox (female)
- [x] dwebble
- [x] eelektrik
- [x] eelektross
- [x] eevee
- [x] eevee (female)
- [x] egg
- [ ] eiscue
- [ ] eiscue_noice_face
- [x] ekans
- [ ] eldegoss
- [x] electabuzz
- [x] electivire
- [x] electrike
- [x] electrode
- [ ] electrode_hisuian
- [x] elekid
- [x] elgyem
- [x] emboar
- [x] emolga
- [x] empoleon
- [ ] enamorus
- [ ] enamorus_therian
- [x] entei
- [x] escavalier
- [x] espeon
- [x] espurr
- [ ] eternatus_eternamax
- [ ] eternatus
- [x] excadrill
- [x] exeggcute
- [x] exeggutor_alolan
- [x] exeggutor
- [x] exploud
- [ ] falinks
- [x] farfetchd
- [ ] farfetchd_galarian
- [x] fearow
- [x] feebas
- [x] fennekin
- [x] feraligatr
- [x] ferroseed
- [x] ferrothorn
- [x] finneon
- [x] finneon (female)
- [x] flaaffy
- [x] flabebe
- [x] flapple
- [x] flareon
- [x] fletchinder
- [x] fletchling
- [x] floatzel
- [x] floette
- [ ] floette_eternal_flower
- [x] florges
- [x] flygon
- [ ] fomantis
- [x] foongus
- [x] forretress
- [x] fraxure
- [x] frillish
- [x] frillish (female)
- [x] froakie
- [x] frogadier
- [x] froslass
- [ ] frosmoth
- [x] furfrou
- [x] furfrou_dandy_trim
- [x] furfrou_debutante_trim
- [x] furfrou_diamond_trim
- [x] furfrou_heart_trim
- [x] furfrou_kabuki_trim
- [x] furfrou_la_reine_trim
- [x] furfrou_matron_trim
- [x] furfrou_pharaoh_trim
- [x] furfrou_star_trim
- [x] furret
- [x] gabite
- [x] gabite (female)
- [x] gallade
- [ ] gallade_mega
- [x] galvantula
- [x] garbodor
- [x] garchomp
- [x] garchomp (female)
- [ ] garchomp_mega
- [x] gardevoir
- [ ] gardevoir_mega
- [x] gastly
- [x] gastrodon
- [x] gastrodon_east_sea
- [x] genesect
- [x] gengar
- [ ] gengar_mega
- [ ] geodude_alolan
- [x] geodude
- [x] gible
- [x] gible (female)
- [x] gigalith
- [x] girafarig
- [x] girafarig (female)
- [x] giratina
- [x] giratina_origin
- [x] glaceon
- [x] glalie
- [ ] glalie_mega
- [x] glameow
- [ ] glastrier
- [x] gligar
- [x] gligar (female)
- [x] gliscor
- [x] gloom
- [x] gloom (female)
- [x] gogoat
- [x] golbat
- [x] golbat (female)
- [x] goldeen
- [x] goldeen (female)
- [x] golduck
- [ ] golem_alolan
- [x] golem
- [x] golett
- [x] golisopod
- [x] golurk
- [x] goodra
- [ ] goodra_hisuian
- [x] goomy
- [x] gorebyss
- [ ] gossifleur
- [x] gothita
- [x] gothitelle
- [x] gothorita
- [x] gourgeist
- [x] gourgeist_large
- [x] gourgeist_small
- [x] gourgeist_super
- [x] granbull
- [ ] grapploct
- [ ] graveler_alolan
- [x] graveler
- [ ] greedent
- [x] greninja
- [x] greninja_ash
- [ ] grimer_alolan
- [x] grimer
- [ ] grimmsnarl
- [ ] grookey
- [x] grotle
- [x] groudon
- [ ] groudon_primal
- [x] grovyle
- [x] growlithe
- [ ] growlithe_hisuian
- [x] grubbin
- [x] grumpig
- [x] gulpin
- [x] gulpin (female)
- [ ] gumshoos
- [x] gurdurr
- [ ] guzzlord
- [x] gyarados
- [x] gyarados (female)
- [ ] gyarados_mega
- [x] hakamo_o
- [x] happiny
- [x] hariyama
- [ ] hatenna
- [ ] hatterene
- [ ] hattrem
- [x] haunter
- [x] hawlucha
- [x] haxorus
- [x] heatmor
- [x] heatran
- [x] heliolisk
- [x] helioptile
- [x] heracross
- [x] heracross (female)
- [ ] heracross_mega
- [x] herdier
- [x] hippopotas
- [x] hippowdon
- [x] hitmonchan
- [x] hitmonlee
- [x] hitmontop
- [x] ho_oh
- [x] honchkrow
- [x] honedge
- [x] hoopa
- [x] hoopa_unbound
- [x] hoothoot
- [x] hoppip
- [x] horsea
- [x] houndoom
- [x] houndoom (female)
- [ ] houndoom_mega
- [x] houndour
- [x] huntail
- [x] hydreigon
- [x] hypno
- [x] hypno (female)
- [x] igglybuff
- [x] illumise
- [ ] impidimp
- [ ] incineroar
- [ ] indeedee_female
- [ ] indeedee
- [x] infernape
- [x] inkay
- [ ] inteleon
- [x] ivysaur
- [x] jangmo_o
- [x] jellicent
- [x] jellicent (female)
- [x] jigglypuff
- [x] jirachi
- [x] jolteon
- [x] joltik
- [x] jumpluff
- [x] jynx
- [x] kabuto
- [x] kabutops
- [x] kadabra
- [x] kadabra (female)
- [x] kakuna
- [x] kangaskhan
- [ ] kangaskhan_mega
- [x] karrablast
- [ ] kartana
- [x] kecleon
- [x] keldeo
- [ ] keldeo_resolute
- [x] kingdra
- [x] kingler
- [x] kirlia
- [x] klang
- [ ] kleavor
- [x] klefki
- [x] klink
- [x] klinklang
- [x] koffing
- [ ] komala
- [x] kommo_o
- [x] krabby
- [x] kricketot
- [x] kricketot (female)
- [x] kricketune
- [x] kricketune (female)
- [x] krokorok
- [x] krookodile
- [ ] kubfu
- [x] kyogre
- [ ] kyogre_primal
- [x] kyurem
- [x] kyurem_black
- [x] kyurem_white
- [x] lairon
- [x] lampent
- [x] landorus
- [x] landorus_therian
- [x] lanturn
- [x] lapras
- [x] larvesta
- [x] larvitar
- [x] latias
- [ ] latias_mega
- [x] latios
- [ ] latios_mega
- [x] leafeon
- [x] leavanny
- [x] ledian
- [x] ledian (female)
- [x] ledyba
- [x] ledyba (female)
- [x] lickilicky
- [x] lickitung
- [x] liepard
- [x] lileep
- [x] lilligant
- [ ] lilligant_hisuian
- [x] lillipup
- [x] linoone
- [ ] linoone_galarian
- [x] litleo
- [ ] litten
- [x] litwick
- [x] lombre
- [x] lopunny
- [ ] lopunny_mega
- [x] lotad
- [x] loudred
- [x] lucario
- [ ] lucario_mega
- [x] ludicolo
- [x] ludicolo (female)
- [x] lugia
- [x] lumineon
- [x] lumineon (female)
- [ ] lunala
- [x] lunatone
- [ ] lurantis
- [x] luvdisc
- [x] luxio
- [x] luxio (female)
- [x] luxray
- [x] luxray (female)
- [ ] lycanroc_dusk
- [ ] lycanroc
- [ ] lycanroc_midnight
- [x] machamp
- [x] machoke
- [x] machop
- [x] magby
- [x] magcargo
- [ ] magearna
- [ ] magearna_original_color
- [x] magikarp
- [x] magikarp (female)
- [x] magmar
- [x] magmortar
- [x] magnemite
- [x] magneton
- [x] magnezone
- [x] makuhita
- [x] malamar
- [x] mamoswine
- [x] mamoswine (female)
- [x] manaphy
- [x] mandibuzz
- [x] manectric
- [ ] manectric_mega
- [x] mankey
- [x] mantine
- [x] mantyke
- [x] maractus
- [ ] mareanie
- [x] mareep
- [x] marill
- [ ] marowak_alolan
- [x] marowak
- [x] marshadow
- [x] marshtomp
- [x] masquerain
- [x] mawile
- [ ] mawile_mega
- [x] medicham
- [x] medicham (female)
- [ ] medicham_mega
- [x] meditite
- [x] meditite (female)
- [x] meganium
- [x] meganium (female)
- [ ] melmetal
- [x] meloetta
- [ ] meloetta_pirouette
- [ ] meltan
- [x] meowstic
- [x] meowstic_female
- [ ] meowth_alolan
- [x] meowth
- [ ] meowth_galarian
- [x] mesprit
- [x] metagross
- [ ] metagross_mega
- [x] metang
- [x] metapod
- [x] mew
- [x] mewtwo
- [ ] mewtwo_mega_x
- [ ] mewtwo_mega_y
- [x] mienfoo
- [x] mienshao
- [x] mightyena
- [ ] milcery
- [x] milotic
- [x] milotic (female)
- [x] miltank
- [x] mime_jr
- [ ] mimikyu_busted
- [ ] mimikyu
- [x] minccino
- [ ] minior_core
- [ ] minior
- [x] minun
- [x] misdreavus
- [x] mismagius
- [x] moltres
- [ ] moltres_galarian
- [x] monferno
- [ ] morelull
- [ ] morgrem
- [ ] morpeko
- [ ] morpeko_hangry
- [x] mothim
- [x] mr_mime
- [ ] mr_mime_galarian
- [ ] mr_rime
- [ ] mudbray
- [x] mudkip
- [ ] mudsdale
- [ ] muk_alolan
- [x] muk
- [x] munchlax
- [x] munna
- [x] murkrow
- [x] murkrow (female)
- [x] musharna
- [ ] naganadel
- [x] natu
- [ ] necrozma_dawn_wings
- [ ] necrozma_dusk_mane
- [ ] necrozma
- [ ] necrozma_ultra
- [ ] nickit
- [x] nidoking
- [x] nidoqueen
- [x] nidoran_f
- [x] nidoran_m
- [x] nidorina
- [x] nidorino
- [ ] nihilego
- [x] nincada
- [ ] ninetales_alolan
- [x] ninetales
- [x] ninjask
- [x] noctowl
- [x] noibat
- [x] noivern
- [x] nosepass
- [x] numel
- [x] numel (female)
- [x] nuzleaf
- [x] nuzleaf (female)
- [ ] obstagoon
- [x] octillery
- [x] octillery (female)
- [x] oddish
- [x] omanyte
- [x] omastar
- [x] onix
- [ ] oranguru
- [ ] orbeetle
- [ ] oricorio
- [ ] oricorio_pau
- [ ] oricorio_pom_pom
- [ ] oricorio_sensu
- [x] oshawott
- [ ] overqwil
- [x] pachirisu
- [x] pachirisu (female)
- [x] palkia
- [ ] palkia_origin
- [ ] palossand
- [x] palpitoad
- [x] pancham
- [x] pangoro
- [x] panpour
- [x] pansage
- [x] pansear
- [x] paras
- [x] parasect
- [ ] passimian
- [x] patrat
- [x] pawniard
- [x] pelipper
- [ ] perrserker
- [ ] persian_alolan
- [x] persian
- [x] petilil
- [x] phanpy
- [x] phantump
- [ ] pheromosa
- [x] phione
- [x] pichu
- [ ] pichu_spiky_eared
- [x] pidgeot
- [ ] pidgeot_mega
- [x] pidgeotto
- [x] pidgey
- [x] pidove
- [x] pignite
- [ ] pikachu_alola_cap
- [x] pikachu
- [x] pikachu (female)
- [ ] pikachu_belle
- [ ] pikachu_cosplay
- [ ] pikachu_hoenn_cap
- [ ] pikachu_kalos_cap
- [ ] pikachu_libre
- [ ] pikachu_original_cap
- [ ] pikachu_partner_cap
- [ ] pikachu_ph_d
- [ ] pikachu_pop_star
- [ ] pikachu_rock_star
- [ ] pikachu_sinnoh_cap
- [ ] pikachu_unova_cap
- [ ] pikachu_world_cap
- [ ] pikipek
- [x] piloswine
- [x] piloswine (female)
- [x] pincurchin
- [x] pineco
- [x] pinsir
- [ ] pinsir_mega
- [x] piplup
- [x] plusle
- [ ] poipole
- [x] politoed
- [x] politoed (female)
- [x] poliwag
- [x] poliwhirl
- [x] poliwrath
- [ ] polteageist
- [x] ponyta
- [ ] ponyta_galarian
- [x] poochyena
- [ ] popplio
- [x] porygon_z
- [x] porygon
- [x] porygon2
- [ ] primarina
- [x] primeape
- [x] prinplup
- [x] probopass
- [x] psyduck
- [x] pumpkaboo
- [x] pumpkaboo_large
- [x] pumpkaboo_small
- [x] pumpkaboo_super
- [x] pupitar
- [x] purrloin
- [x] purugly
- [x] pyroar
- [x] pyroar (female)
- [x] pyukumuku
- [x] quagsire
- [x] quagsire (female)
- [x] question_mark_circled
- [x] question_mark_double
- [x] quilava
- [x] quilladin
- [x] qwilfish
- [ ] qwilfish_hisuian
- [ ] raboot
- [ ] raichu_alolan
- [x] raichu
- [x] raichu (female)
- [x] raikou
- [x] ralts
- [x] rampardos
- [x] rapidash
- [ ] rapidash_galarian
- [ ] raticate_alolan
- [x] raticate
- [x] raticate (female)
- [ ] rattata_alolan
- [x] rattata
- [x] rattata (female)
- [x] rayquaza
- [ ] rayquaza_mega
- [x] regice
- [ ] regidrago
- [ ] regieleki
- [x] regigigas
- [x] regirock
- [x] registeel
- [x] relicanth
- [x] relicanth (female)
- [x] remoraid
- [x] reshiram
- [x] reuniclus
- [x] rhydon
- [x] rhydon (female)
- [x] rhyhorn
- [x] rhyhorn (female)
- [x] rhyperior
- [x] rhyperior (female)
- [ ] ribombee
- [ ] rillaboom
- [x] riolu
- [ ] rockruff
- [x] roggenrola
- [x] rolycoly
- [x] rookidee
- [x] roselia
- [x] roselia (female)
- [x] roserade
- [x] roserade (female)
- [x] rotom
- [x] rotom_fan
- [x] rotom_frost
- [x] rotom_heat
- [x] rotom_mow
- [x] rotom_wash
- [ ] rowlet
- [x] rufflet
- [ ] runerigus
- [x] sableye
- [ ] sableye_mega
- [x] salamence
- [ ] salamence_mega
- [x] salandit
- [x] salazzle
- [x] samurott
- [ ] samurott_hisuian
- [ ] sandaconda
- [x] sandile
- [ ] sandshrew_alolan
- [x] sandshrew
- [ ] sandslash_alolan
- [x] sandslash
- [ ] sandygast
- [x] sawk
- [x] sawsbuck
- [ ] sawsbuck_autumn
- [ ] sawsbuck_summer
- [ ] sawsbuck_winter
- [x] scatterbug
- [x] sceptile
- [ ] sceptile_mega
- [x] scizor
- [x] scizor (female)
- [ ] scizor_mega
- [x] scolipede
- [ ] scorbunny
- [x] scrafty
- [x] scraggy
- [x] scyther
- [x] scyther (female)
- [x] seadra
- [x] seaking
- [x] seaking (female)
- [x] sealeo
- [x] seedot
- [x] seel
- [x] seismitoad
- [x] sentret
- [x] serperior
- [x] servine
- [x] seviper
- [x] sewaddle
- [x] sharpedo
- [ ] sharpedo_mega
- [x] shaymin
- [x] shaymin_sky
- [x] shedinja
- [x] shelgon
- [x] shellder
- [x] shellos
- [x] shellos_east_sea
- [x] shelmet
- [x] shieldon
- [x] shiftry
- [x] shiftry (female)
- [ ] shiinotic
- [x] shinx
- [x] shinx (female)
- [x] shroomish
- [x] shuckle
- [x] shuppet
- [x] sigilyph
- [x] silcoon
- [ ] silicobra
- [ ] silvally
- [x] simipour
- [x] simisage
- [x] simisear
- [ ] sinistea
- [ ] sirfetchd
- [x] sizzlipede
- [x] skarmory
- [x] skiddo
- [x] skiploom
- [x] skitty
- [x] skorupi
- [x] skrelp
- [x] skuntank
- [ ] skwovet
- [x] slaking
- [x] slakoth
- [x] sliggoo
- [ ] sliggoo_hisuian
- [x] slowbro
- [ ] slowbro_galarian
- [ ] slowbro_mega
- [x] slowking
- [ ] slowking_galarian
- [x] slowpoke
- [ ] slowpoke_galarian
- [x] slugma
- [x] slurpuff
- [x] smeargle
- [x] smoochum
- [x] sneasel
- [x] sneasel (female)
- [ ] sneasel_hisuian
- [ ] sneasel_hisuian (female)
- [ ] sneasler
- [x] snivy
- [ ] snom
- [x] snorlax
- [x] snorunt
- [x] snover
- [x] snover (female)
- [x] snubbull
- [ ] sobble
- [ ] solgaleo
- [x] solosis
- [x] solrock
- [x] spearow
- [ ] spectrier
- [x] spewpa
- [x] spheal
- [x] spinarak
- [x] spinda
- [x] spiritomb
- [x] spoink
- [x] spritzee
- [x] squirtle
- [ ] stakataka
- [x] stantler
- [x] staraptor
- [x] staraptor (female)
- [x] staravia
- [x] staravia (female)
- [x] starly
- [x] starly (female)
- [x] starmie
- [x] staryu
- [x] steelix
- [x] steelix (female)
- [ ] steelix_mega
- [ ] steenee
- [ ] stonjourner
- [x] stoutland
- [x] stufful
- [x] stunfisk
- [ ] stunfisk_galarian
- [x] stunky
- [x] sudowoodo
- [x] sudowoodo (female)
- [x] suicune
- [x] sunflora
- [x] sunkern
- [x] surskit
- [x] swablu
- [x] swadloon
- [x] swalot
- [x] swalot (female)
- [x] swampert
- [ ] swampert_mega
- [x] swanna
- [x] swellow
- [x] swinub
- [x] swirlix
- [x] swoobat
- [x] sylveon
- [x] taillow
- [x] talonflame
- [x] tangela
- [x] tangrowth
- [x] tangrowth (female)
- [x] tapu_bulu
- [x] tapu_fini
- [x] tapu_koko
- [x] tapu_lele
- [x] tauros
- [x] teddiursa
- [x] tentacool
- [x] tentacruel
- [x] tepig
- [x] terrakion
- [ ] thievul
- [x] throh
- [x] thundurus
- [x] thundurus_therian
- [ ] thwackey
- [x] timburr
- [x] tirtouga
- [ ] togedemaru
- [x] togekiss
- [x] togepi
- [x] togetic
- [x] torchic
- [x] torkoal
- [x] tornadus
- [x] tornadus_therian
- [ ] torracat
- [x] torterra
- [x] totodile
- [ ] toucannon
- [ ] toxapex
- [ ] toxel
- [x] toxicroak
- [x] toxicroak (female)
- [ ] toxtricity
- [ ] toxtricity_low_key
- [x] tranquill
- [x] trapinch
- [x] treecko
- [x] trevenant
- [x] tropius
- [x] trubbish
- [ ] trumbeak
- [ ] tsareena
- [x] turtonator
- [x] turtwig
- [x] tympole
- [x] tynamo
- [ ] type_null
- [x] typhlosion
- [ ] typhlosion_hisuian
- [x] tyranitar
- [ ] tyranitar_mega
- [x] tyrantrum
- [x] tyrogue
- [x] tyrunt
- [x] umbreon
- [x] unfezant
- [x] unfezant (female)
- [x] unown
- [x] unown_b
- [x] unown_c
- [x] unown_d
- [x] unown_e
- [x] unown_exclamation_mark
- [x] unown_f
- [x] unown_g
- [x] unown_h
- [x] unown_i
- [x] unown_j
- [x] unown_k
- [x] unown_l
- [x] unown_m
- [x] unown_n
- [x] unown_o
- [x] unown_p
- [x] unown_q
- [x] unown_question_mark
- [x] unown_r
- [x] unown_s
- [x] unown_t
- [x] unown_u
- [x] unown_v
- [x] unown_w
- [x] unown_x
- [x] unown_y
- [x] unown_z
- [ ] ursaluna
- [x] ursaring
- [x] ursaring (female)
- [ ] urshifu
- [ ] urshifu_rapid_strike_style
- [x] uxie
- [x] vanillish
- [x] vanillite
- [x] vanilluxe
- [x] vaporeon
- [x] venipede
- [x] venomoth
- [x] venonat
- [x] venusaur
- [x] venusaur (female)
- [ ] venusaur_mega
- [x] vespiquen
- [x] vibrava
- [x] victini
- [x] victreebel
- [x] vigoroth
- [x] vikavolt
- [x] vileplume
- [x] vileplume (female)
- [x] virizion
- [x] vivillon
- [x] vivillon_archipelago
- [x] vivillon_continental
- [x] vivillon_elegant
- [x] vivillon_fancy
- [x] vivillon_garden
- [x] vivillon_high_plains
- [x] vivillon_jungle
- [x] vivillon_marine
- [x] vivillon_meadow
- [x] vivillon_modern
- [x] vivillon_monsoon
- [x] vivillon_ocean
- [x] vivillon_poke_ball
- [x] vivillon_polar
- [x] vivillon_river
- [x] vivillon_sandstorm
- [x] vivillon_savanna
- [x] vivillon_sun
- [x] vivillon_tundra
- [x] volbeat
- [x] volcanion
- [x] volcarona
- [x] voltorb
- [ ] voltorb_hisuian
- [x] vullaby
- [ ] vulpix_alolan
- [x] vulpix
- [x] wailmer
- [x] wailord
- [x] walrein
- [x] wartortle
- [x] watchog
- [x] weavile
- [x] weavile (female)
- [x] weedle
- [x] weepinbell
- [x] weezing
- [ ] weezing_galarian
- [x] whimsicott
- [x] whirlipede
- [x] whiscash
- [x] whismur
- [x] wigglytuff
- [x] wimpod
- [x] wingull
- [ ] wishiwashi
- [ ] wishiwashi_school
- [x] wobbuffet
- [x] wobbuffet (female)
- [x] woobat
- [ ] wooloo
- [x] wooper
- [x] wooper (female)
- [x] wormadam
- [x] wormadam_sandy_cloak
- [x] wormadam_trash_cloak
- [x] wurmple
- [x] wynaut
- [ ] wyrdeer
- [x] xatu
- [x] xatu (female)
- [x] xerneas_active
- [ ] xerneas
- [ ] xurkitree
- [x] yamask
- [ ] yamask_galarian
- [ ] yamper
- [x] yanma
- [x] yanmega
- [ ] yungoos
- [x] yveltal
- [ ] zacian_crowned_sword
- [ ] zacian
- [ ] zamazenta_crowned_shield
- [ ] zamazenta
- [x] zangoose
- [x] zapdos
- [ ] zapdos_galarian
- [ ] zarude_dada
- [ ] zarude
- [x] zebstrika
- [x] zekrom
- [ ] zeraora
- [x] zigzagoon
- [ ] zigzagoon_galarian
- [x] zoroark
- [ ] zoroark_hisuian
- [x] zorua
- [ ] zorua_hisuian
- [x] zubat
- [x] zubat (female)
- [x] zweilous
- [x] zygarde_10_percent
- [x] zygarde
- [x] zygarde_complete

**Comment by LOuroboros** [comment]
Maybe the Arceus Forms and whichever other new form is missing a proper animation should be added to this list, and then close #1228 ?
This issue already seems to cover certain forms anyway.

**Comment by DizzyEggg** [comment]
This list gotta be surely out of date?

**Comment by LOuroboros** [comment]
> This list gotta be surely out of date?

Yup, it sure is.

As it stands, most of the Gen. 5 and 8 species lack a proper front animation, as well as many many forms such as the Alolan or Galarian Forms.
https://github.com/rh-hideout/pokeemerald-expansion/blob/master/src/pokemon.c#L2442
https://github.com/rh-hideout/pokeemerald-expansion/blob/master/src/pokemon.c#L2764
https://github.com/rh-hideout/pokeemerald-expansion/blob/master/src/pokemon.c#L2862

As for the back animations, every single species past Gen. 3 is lacking one.
https://github.com/rh-hideout/pokeemerald-expansion/blob/master/src/pokemon_animation.c#L602

**Comment by EchedeyLR** [comment]
Hi, just to ask.

I wanted to report a feature request related to Pokemon battle animations (Pokemon sprites themselves) and I found this.

Is this related to that? The report was related to some people (including me) wanting the Pokemon B/W sprite animations during battles showing the Pokemon more vivid.

**Comment by leo60228** [comment]
@EchedeyLR This issue is for the fact that some Pokémon have one animation frame instead of two. Using the BW sprites isn't possible as they're larger than GBA sprites, and drawing over 1000 fully animated sprites would be a very difficult task (not to mention the ROM space and coding required).

**Comment by SonikkuA-DatH** [comment]
As of October 2024...

**Missing Front 2nd Frame (Gen 7)**

Litten
Torracat
Incinereoar
Popplio
Brionne
Primarina
Yungoos
Gumshoos
Crabrawler
Crabdominable
Oricorio Red
Oricorio Yellow
Oricorio Pink
Oricoria Indigo
Wishiwashi
Wishiwashi Form
Mareanie
Toxapex
Mudbray
Mudsdale
Fomantis
Lurantis
Morellul
Shiinotic
Bounsweet(?)
Steenee
Tsareena
Sandygast
Palossand
Type:Null
Silvally
Komala
Mimikyu
Bruxish
Dhelmise
Cosmog
Cosmoem
Solgaleo
Lunala
Nihilego
Buzzwole
Phermosa
Xurkitree
Celesteela
Kartana
Guzzlord
Necrozma
Necrozma Dusk Mane
Necrozma Dawn Wing
Ultra Necrozma
Poipal
Naganadel
Stakataka
Blacephalon
Zeraora
Meltan
Melmetal
Melmetal Gmax

Note: Most missing the 2nd frame still have a unique affine anim set


**Missing Front 2nd Frame (Gen 8)**

Grookey
Thwackey
Rillaboom
Scorbunny
Raboot
Cinderace
Sobble
Drizzlie
Inteleon
Skwovet
Greedent
Blipbug
Dottler
Orbeetle
Orbeetle Gmax
Nickit
Thievul
Gossifleur
Eldegoss
Wooloo
Dubwool
Yamper
Boltund
Silicobra
Sandaconda
Cramorant
Cramorant fish
Cramorant rat
Arrocuda
Baraskewda
Toxel
Toxtricity Yellow
Toxtricity Blue
Centiscorch Gmax
Sinistea
Sinistea Antique
Polteageist
Polteageist
Hatena
Hatterem
Hatterene
Impidimp
Mogrem
Grimmsnarl
Obstagoon
Perrserker
Cursola
Sirfetch'd
Mr. Rime
Runerigus
Milcery
Alcremie and all BS forms
Alcremie Gmax
Falinks
Snom
Frosmoth
Stonjourner
Eiscue
Eiscue Thawed
Indeedee M
Indeedee F
Morpeko
Morpeko Hangry
Cufant
Copperajah
Dracozolt
Arctozolt
Dracovish
Arctovish
Duraludon
Duraludon Gmax
Dreepy
Drakloak
Dragapult
Zacian
Zacian Sword
Zamazenta
Zamazenta Shield
Eternatus
Eternatus Gmax
Kubfu
Urshifu Single Strike
Urshifu Gmax
Urshifu Rapid Strike
Urshifu Gmax
Zarude
Zarude Movie
Regileleki
RegiDrago
Glastrier
Spectrier
Calyrex
Calyrex Ice
Calyrex Ghost
Wyrdeer
Kleavor
Ursaluna
Uraluna BloodMoon
Basculegion
Basculegion White
Sneasler
Overqwil
Enamorus

**Hisuian Forms**

H. Growlithe
H. Arcanine
H. Voltorb
H. Electrode
H. Typhlosion
H. Qwilfish
H. Sneasel M
H. Sneasel F
H. Samurott
H. Lilligant
H. Zorua
H. Zoroark
H. Braviary
H. Sliggoo
H. Goodra
H. Avalugg
H. Decidueye


Incidentally, most mons for backsprite have H Vibrate for default

TODO: Look at Megas and Gen 7/8 alt forms for existing mons

**Comment by AsparagusEduardo** [comment]
Superseded by #5883
