### ISSUE TITLE
The move After you seems to be bugged 

### ISSUE THREAD

**Issue by AlexOn1ine** [rh-hideout/pokeemerald-expansion#2615]
Torkoal is supposed to move after Lilligant. Instead it just the normal turn order.

https://user-images.githubusercontent.com/93446519/215330259-c2fb7371-6a08-4a22-826f-648c51afcc96.mp4

**Comment by mrgriffin** [comment]
Added a failing test in #2564, seems to be `B_RECALC_TURN_AFTER_ACTIONS` overwriting the turn order after After You adjusts it.
