### ISSUE TITLE
Transform doesnt take players gender into account

### ISSUE THREAD

**Issue by Jaizu** [rh-hideout/pokeemerald-expansion#2617]
![image](https://user-images.githubusercontent.com/18596778/215722455-e8d6698b-7250-4790-b5da-b1e1079684d7.png)

The issue seems to be in `HandleSpeciesGfxDataChange`. I wonder if forms/megas are also broken, I think it's worth checking those too.

**Comment by AsparagusEduardo** [comment]
#2618
