### ISSUE TITLE
Some abilities are broken in certain battle types like battle factory

### ISSUE THREAD

**Issue by Jaizu** [rh-hideout/pokeemerald-expansion#2619]
Have an enemy mon
Ko it
Enemy trainer sends a mon with Intimidate
Popup gets enabled from player side and not from enemies, including wrong buffers on the text.

SBird made a test for this and it's confirmed to be broken.

**Comment by LOuroboros** [comment]
Can't confirm in a clean copy of the upcoming branch.

Uploading intimidated.mp4…

**Comment by Jaizu** [comment]
Confirming that is not just the ability popup, the enemy gets -1 attack
This also happens on more abilities. 

Example of Frisk being broken:
![mGBA_mJcVExN75k](https://user-images.githubusercontent.com/18596778/216425542-de33a070-b74f-44eb-ac1f-da39ade55095.gif)
