### ISSUE TITLE
Contrary : Battle message error

### ISSUE THREAD

**Issue by Arlequiin** [rh-hideout/pokeemerald-expansion#2632]
When battling a Pokémon with intimidate there is a default string "X's intimidate lowers X's attack", when having a Pokémon with Contrary, his stat is boosted as expected but the strings is saying "lowers".
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/78297845/216833406-6d1615b6-bebc-44fa-a371-028ee0e02ee5.png">

**Comment by LOuroboros** [comment]
Please refrain from reporting any problems with Intimidate until #2622 is merged.

Alternatively, if you're going to do tests with that ability, make sure to have the contents of that PR merged.

**Comment by Arlequiin** [comment]
PR merged
<img width="415" alt="image" src="https://user-images.githubusercontent.com/78297845/216833574-be607eb3-2f5f-4dde-9ee1-a28ac11dd5cf.png">
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/78297845/216833590-1e15368f-5c71-4929-b244-0cbf125ddd58.png">
same problem

**Comment by Arlequiin** [comment]
(réduit means lower)

**Comment by LOuroboros** [comment]
> PR merged <img alt="image" width="415" src="https://user-images.githubusercontent.com/78297845/216833574-be607eb3-2f5f-4dde-9ee1-a28ac11dd5cf.png"> <img alt="image" width="1399" src="https://user-images.githubusercontent.com/78297845/216833590-1e15368f-5c71-4929-b244-0cbf125ddd58.png"> same problem

Just so you know, the PR was not merged yet, so `git pull`ing from any of the expansion's branches wouldn't do anything.
