### ISSUE TITLE
Bibarel sprite is broken

### ISSUE THREAD

**Issue by Jaizu** [rh-hideout/pokeemerald-expansion#2634]
Future me will fix 
![image](https://user-images.githubusercontent.com/18596778/216949919-7a25bc3a-24d0-45f1-8d77-24239b2e56af.png)

Note to future Jaizu: Take is from 1db75d007e42c41df23714a8654350aabdafb10c in the unova_emerald repo

**Comment by AsparagusEduardo** [comment]
#3122
