### ISSUE TITLE
Feature suggestion: add scriptable 1v2 double battles

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#2651]
We currently have support for 2v1 battles (i.e. the player and an AI trainer vs one AI trainer) and 2v2 battles, but we do not have a version where the player is matched against two trainers. This partially exists in vanilla; when you catch the eyes of two trainers at once you start a double battle against both, but there are no scripted battles where this happens.

This is slightly different from setting a trainer as a double battle, as having two separate opponents allows each of them to mega evolve, use z-moves, etc.

**Comment by eatthepear** [comment]
I believe I figured out the skeleton of how to do this. 

In your script, you can do something like:
`trainerbattle(TRAINER_BATTLE_SET_TRAINER_A, TRAINER_NAME_1, 0, NULL, "ahhh")
trainerbattle(TRAINER_BATTLE_SET_TRAINER_B, TRAINER_NAME_2, 0, NULL, "bahhhh")`
Then just call `dotrainerbattle`

In src/battle_setup.c, you can set `gNoOfApproachingTrainers = 2` at the beginning of the function. This will basically mimic the catching the eyes of two trainers at the same time.

I don't know if the best way to do this is by making a new battle variable or just using a flag, but it definitely could use a macro.

**Comment by BuffelSaft** [comment]
Oh, that's much more straightforward than I thought it would be. Nice!

**Comment by hedara90** [comment]
Implemented by #4741
