### ISSUE TITLE
Make more use of GetBattlerPartyData

### ISSUE THREAD

**Issue by DizzyEggg** [rh-hideout/pokeemerald-expansion#2656]
This is a handy function whose usage would clean a bit the battle code I think.
Its name is a bit long, so perhaps we could rename it so something like: "GetBattlerMon" or sth else.

Similarly, we could also have two additional functions for GetBattlerPartyDataPlayer and GetBattlerPartyDataOpponent(names are subject to change)

```
struct Pokemon *GetBattlerPartyData(u8 battlerId)
{
    struct Pokemon *mon;
    if (GetBattlerSide(battlerId) == B_SIDE_PLAYER)
        mon = &gPlayerParty[gBattlerPartyIndexes[battlerId]];
    else
        mon = &gEnemyParty[gBattlerPartyIndexes[battlerId]];

    return mon;
}
```

**Comment by Bassoonian** [comment]
Fixed by #5378
