### ISSUE TITLE
Broken string when enemy uses z move being paralyzed 

### ISSUE THREAD

**Issue by Jaizu** [rh-hideout/pokeemerald-expansion#2674]
![mGBA_iB5WESro9V](https://user-images.githubusercontent.com/18596778/218073596-285a9758-d8a4-406c-b815-f06fea2577cd.gif)

**Comment by AlexOn1ine** [comment]
Is`Leader Brock used Z Ring Power` a custom message? 
I couldn't reproduce this bug vs Roxanne and never got this particular message when a Z move was used.

**Comment by Bassoonian** [comment]
Can you reproduce this on upcoming?

**Comment by Bassoonian** [comment]
I just tried too, and can't reproduce this on upcoming. Feel free to reopen if you can.
