### ISSUE TITLE
Status moves are getting -20 score if the move order is 'wrong'

### ISSUE THREAD

**Issue by AlexOn1ine** [rh-hideout/pokeemerald-expansion#2682]
First brought up by Salem on discord. Status moves are getting a -20 score if there is no attacking move on a previous slot.
The problem seems to be coming from `AI_CheckBadMove`
![image](https://user-images.githubusercontent.com/93446519/218570312-7a20da0e-4f7e-4217-be3f-23fa42aa2b5d.png)

**Comment by AsparagusEduardo** [comment]
oh shoot? could this explain why we have so many AI issues? 😂

**Comment by AlexOn1ine** [comment]
I think I found the problem. It seems like It is in `AI_CalcDamage` inside if statement:
```
  if (gBattleMoves[move].power)
    {
        critChance = GetInverseCritChance(battlerAtk, battlerDef, move);
        normalDmg = CalculateMoveDamageAndEffectiveness(move, battlerAtk, battlerDef, moveType, &effectivenessMultiplier);
        critDmg = CalculateMoveDamage(move, battlerAtk, battlerDef, moveType, 0, TRUE, FALSE, FALSE);
```
The statement is never true if there was never a damage dealing move before the status moves. 
Though I am not sure what the correct solution is. Simply moving 
```
normalDmg = CalculateMoveDamageAndEffectiveness(move, battlerAtk, battlerDef, moveType, &effectivenessMultiplier);
```
solves the issue but I don't even know what the actual problem is and why it is happening for moves that are above damage dealing moves.
![image](https://user-images.githubusercontent.com/93446519/219893071-9ee6f995-59d2-4cf3-bc6a-331ac97fc01d.png)
