### ISSUE TITLE
Last switch in message not working properly

### ISSUE THREAD

**Issue by Jaizu** [rh-hideout/pokeemerald-expansion#2693]
Possible causes:
- Being a double batle
- Having to send a member of your party when the enemy team sends out its last Pokémon
- Both
- Something else
![mGBA_QYJmWPYHEe](https://user-images.githubusercontent.com/18596778/219314117-8d50c6a3-87bb-4b22-a5ae-5a7095adc772.gif)

**Comment by DizzyEggg** [comment]
What is wrong in that gif?

**Comment by DizzyEggg** [comment]
Oh, the slide-in message. You're right, it's also related to #1655
