### ISSUE TITLE
Add a trainer slide-in msg for dynamax/gigantamax when #2417 is merged

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#2702]
In Pokémon SwSh, trainer NPCs can have a battle dialogue when they're about to activate dynamax/gigantamax.

That cannot be properly tested right now even if we tried to implement it, because we don't have dynamax/gigantamax implemented yet.

Thus, I'm leaving this Issue ticket as a reminder until the day in which #2417 or a PR that supersedes it is merged.

**Comment by Bassoonian** [comment]
Fixed by #3581
