### ISSUE TITLE
Softlock when Castform transforms after weather ends after switching

### ISSUE THREAD

**Issue by DizzyEggg** [rh-hideout/pokeemerald-expansion#2724]
Found accidentally.

1. Send out a pokemon with Drizzle/Drought
2. Switch into Castform
3. Wait until Weather ends
4. Castform transforms back and the game dies

![castform bug](https://user-images.githubusercontent.com/16259973/220703228-0b0a4844-a835-4c52-84f9-057bf47f2cf8.gif)

Weirdly enough, this doesn't happen if there's no switching involved.

**Comment by AlexOn1ine** [comment]
It also freezes on Cherrim and I think it is happening because it is unable to do `printstring STRINGID_PKMNTRANSFORMED` because if you comment out it the game doesn't freeze.

**Comment by DizzyEggg** [comment]
Fixed by #3063
