### ISSUE TITLE
"Fill PC" option gives all mon Bulbasaur's moves

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#2821]
![mGBA_lodG2GC3v6](https://user-images.githubusercontent.com/2904965/224554330-fb724ec5-9fef-444b-ac33-f807ba188243.gif)

**Comment by pkmnsnfrn** [comment]
While somebody is looking into this:

1. Every Pokemon has Bulbasaur has a nickname.
2. Growlithe, Arcanine, Tentacool, Tentacruel and a bunch more are all at Level 94.

**Comment by AsparagusEduardo** [comment]
It's because it takes the data for a Bulbasaur and then change *only* species. #2815 will fix this.

**Comment by AsparagusEduardo** [comment]
#2815
