### ISSUE TITLE
ABILITYEFFECT_ON_TERRAIN abilities aren't activating when an ally uses a valid terrain move

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#2830]
Reported by Noelle is Best Girl(Leumas8308)#8659 on Discord.

Right now in the upcoming branch, neither Mimicry nor Quark Drive are activating when you have a Pokémon with either ability on the field and the ally uses Electric Terrain.

**Comment by AsparagusEduardo** [comment]
Maybe it's related to #2820

**Comment by AlexOn1ine** [comment]
Unable to reproduce.
![mimicry](https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/a7875f9b-1026-4599-a2f0-d3247a1613c5)

**Comment by LOuroboros** [comment]
> Unable to reproduce. ![mimicry](https://user-images.githubusercontent.com/93446519/253770511-a7875f9b-1026-4599-a2f0-d3247a1613c5.gif)

Nice, must have been fixed somehow.

Can you double check the type of Stunfisk using the battle debug menu?

**Comment by AlexOn1ine** [comment]
> Can you double check the type of Stunfisk using the battle debug menu?
![pokeemerald-13](https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/b049ce68-53a5-40f1-bf0f-1d8b1c8d04ef)

**Comment by LOuroboros** [comment]
Beautiful. Closing this then. Thanks!

*And thanks to whoever fixed this, be it accidentally or not* 😂
