### ISSUE TITLE
Pokedex Type Search Graphical Glitch Text Option

### ISSUE THREAD

**Issue by AbadabaBoy** [rh-hideout/pokeemerald-expansion#2831]
For some reason the game believes there is an additional option for typings in the pokedex search screen. This will cause a small graphical glitch.

(Plus the option for Fairy Types have not been added for the expansion)

![image](https://user-images.githubusercontent.com/128074164/225692019-c87a5fb9-14ea-4478-b963-af072e2c649a.png)

**Comment by AsparagusEduardo** [comment]
Can't reproduce. What version of the expansion are you using?
![image](https://user-images.githubusercontent.com/2904965/226060926-303d8570-cfb6-4682-a3d6-6fa6fd5f12ed.png)

**Comment by AsparagusEduardo** [comment]
Closing this due to not being able to reproduce and the lack of response.
