### ISSUE TITLE
Ability Popup Freezes When Using Skill Swap or Wandering Spirit

### ISSUE THREAD

**Issue by AaghatIsLive** [rh-hideout/pokeemerald-expansion#2844]
![pokeemerald-1](https://user-images.githubusercontent.com/109757010/226385210-324d5a7a-0fe8-487c-a62a-dc5b0159c208.png)
![pokeemerald-0](https://user-images.githubusercontent.com/109757010/226385221-264e1cd1-6f24-45cb-a7d8-dd5b42821aed.png)

**Comment by AlexOn1ine** [comment]
Mentioned in on Discord but I'll add the comment here so it isn't lost. 
```
	setbyte sFIXED_ABILITY_POPUP, TRUE
	sethword sABILITY_OVERWRITE, ABILITY_WANDERING_SPIRIT
	showabilitypopup BS_TARGET
	pause 60
	sethword sABILITY_OVERWRITE, 0
	updateabilitypopup BS_TARGET
	pause 20
	destroyabilitypopup
	pause 40

	setbyte sFIXED_ABILITY_POPUP, TRUE
	copyhword sABILITY_OVERWRITE, gLastUsedAbility
	showabilitypopup BS_ATTACKER
	pause 60
	sethword sABILITY_OVERWRITE, 0
	pause 20
	destroyabilitypopup
	pause 40
```
`BattleScript_WanderingSpiritActivates` isn't destroying the ability the second time.
