### ISSUE TITLE
Fairy Lock can rotate pokemon's sprites when used

### ISSUE THREAD

**Issue by May8th1995** [rh-hideout/pokeemerald-expansion#2845]
Shown in the video below.
![video](https://user-images.githubusercontent.com/69943962/226458804-b83bd9d6-8221-4786-b975-17b55d812e4d.mp4)

**Comment by LOuroboros** [comment]
Can't confirm the issue, but the animation does look different than the one shown in the video.

![mGBA_20230523_181901608](https://github.com/rh-hideout/pokeemerald-expansion/assets/4485172/99c93fa9-186b-4fe8-990b-a8fcc5fe15d5)

**Comment by AsparagusEduardo** [comment]
> Can't confirm the issue, but the animation does look different than the one shown in the video.

Check how the animation looks like when the enemy uses it, to see if it behaves like how the video does.

**Comment by LOuroboros** [comment]
> > Can't confirm the issue, but the animation does look different than the one shown in the video.
> 
> Check how the animation looks like when the enemy uses it, to see if it behaves like how the video does.

Ah, I didn't notice. Will do. I'll edit this post in 5 or 10 minutes with the result and post the bug with the animation on the opponent's end in a new ticket.

**Comment by LOuroboros** [comment]
So, yeah, the animation is still as bugged.

I'm not sure why, but after I used it against a Poochyena it also started to act even if the move is used by the Player.

![mGBA_20230523_183255105](https://github.com/rh-hideout/pokeemerald-expansion/assets/4485172/61645eae-6950-42ba-9bd8-dd0bc88bad45)
![mGBA_20230523_183356426](https://github.com/rh-hideout/pokeemerald-expansion/assets/4485172/0017245c-ad7e-4fba-b6ad-3ca8ac21a0a2)

**Comment by cfmnephrite** [comment]
Can I ask if Fairy Lock is supposed to look like that anyway? Minus the permanent sprite rotation, ofc

**Comment by cfmnephrite** [comment]
FIXED: https://github.com/cfmnephrite/pokeemerald/commit/5868aa01974b99e8842eec5ab7e10c1d11c22b72

**Comment by AlexOn1ine** [comment]
Closing because the bug comes from missing a correct animation. See dedicated issue #3021
