### ISSUE TITLE
Accuracy above 100% accuracy doesn't work correctly

### ISSUE THREAD

**Issue by eatthepear** [rh-hideout/pokeemerald-expansion#2885]
I'm having a hard time narrowing down where the bug is, but I've tested the following scenarios:
- a Lilligant holding a Wide Lens (which should give +10% accuracy) misses every single Giga Drain.
- a Butterfree with Compound Eyes missing every single Pollen Puff
- a Boldore missing every Rock Slide when Gravity is active
I believe the common thread is each of these moves has above 100% accuracy and somehow the game is calculating them as always miss.

**Comment by AsparagusEduardo** [comment]
Fixed in #2868
