### ISSUE TITLE
Cud Chew may need an update

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#2924]
Submitting this as a reminder.

> Cud Chew, the ability exclusive to farigiraf and paldea tauros family, will actually proc multiple times, happening every other turn after the first cud chew activation.

> For example: if you reach 25% and eat a ganlon berry turn 1, you get plus 1 defense, and turn 2, cud chew activates. Turn 3 nothing will happen, but turn 4, cud chew re-activates and you eat the berry again, now +3 defense. Even if you restored hp over the 25% mark, the ability procs every other turn.

> if the berry in question is a health restoring berry (oran, sitrus, aguav, etc.) If on the turn cud chew would activate, it doesn't activate and will no longer active the rest of the time you are on the field

https://user-images.githubusercontent.com/4485172/232670566-333b73aa-c6fd-4214-8a55-c138f0d8c412.mp4

[Source](https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/post-9568531).

Honestly, it kinda sounds like a bug in SV to me, mainly because of that weird behavior with the health restoring berries, buut... with Game Freak you just never can tell.

**Comment by kittenchilly** [comment]
This was fixed in SV 1.3.0, so it was a bug after all.

**Comment by LOuroboros** [comment]
> This was fixed in SV 1.3.0, so it was a bug after all. Recommended this be closed.

[I asked for confirmation like a week ago](https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/post-9587498). This ticket will be closed depending on the answer.

**Comment by AsparagusEduardo** [comment]
> This was fixed in SV 1.3.0, so it was a bug after all. Recommended this be closed.

Agreed.
