### ISSUE TITLE
Flatter's animation is broken on double battles

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#2925]
Title. It makes the game freeze.
![](https://media.discordapp.net/attachments/774393519569502268/1097773934746804316/mGBA_20230418_034102213.gif)

Works fine in singles though.
![mGBA_20230418_043725523](https://user-images.githubusercontent.com/4485172/232705940-3134746a-1b8e-4129-b456-56fec9199e95.gif)

**Comment by LOuroboros** [comment]
I think `gFlatterConfettiSpriteTemplate` may be the cause of the issue. I tried to remove the calls to it that happen via `CreateFlatterConfetti` in Flatter's battle script, and the animation no longer makes the game crash.

```diff
lunos:/mnt/c/Users/Administrator/Home/rhh$ diff data/battle_anim_scripts.s
diff --git a/data/battle_anim_scripts.s b/data/battle_anim_scripts.s
index cca8706cbc..a1dd9d5d6f 100644
--- a/data/battle_anim_scripts.s
+++ b/data/battle_anim_scripts.s
@@ -22456,25 +22456,6 @@ Move_FLATTER:
        createsprite gVerticalDipSpriteTemplate, ANIM_ATTACKER, 2, 5, 2, ANIM_TARGET
        delay 0
        createvisualtask SoundTask_PlaySE1WithPanning, 5, SE_M_FLATTER, SOUND_PAN_ATTACKER
-       call CreateFlatterConfetti
-       call CreateFlatterConfetti
-       call CreateFlatterConfetti
-       call CreateFlatterConfetti
-       call CreateFlatterConfetti
-       call CreateFlatterConfetti
-       call CreateFlatterConfetti
-       call CreateFlatterConfetti
-       call CreateFlatterConfetti
-       call CreateFlatterConfetti
-       call CreateFlatterConfetti
-       call CreateFlatterConfetti
-       call CreateFlatterConfetti
-       call CreateFlatterConfetti
-       call CreateFlatterConfetti
-       call CreateFlatterConfetti
-       call CreateFlatterConfetti
-       call CreateFlatterConfetti
-       call CreateFlatterConfetti
        delay 5
        createvisualtask SoundTask_PlaySE1WithPanning, 5, SE_M_FLATTER, SOUND_PAN_TARGET
        waitforvisualfinish
lunos:/mnt/c/Users/Administrator/Home/rhh$
```

![](https://media.discordapp.net/attachments/774393519569502268/1097797293824024586/mGBA_20230418_051341134.gif)

**Comment by AlexOn1ine** [comment]
If you just remove 3 lines of `CreateFlatterConfetti` it seems to work fine.
Though I don't think this is an actual fix.
![flatter](https://user-images.githubusercontent.com/93446519/232920842-8ce19ee0-5072-4472-b537-37766db179ec.gif)
