### ISSUE TITLE
Possible issue with double battles and battle strings

### ISSUE THREAD

**Issue by Jaizu** [rh-hideout/pokeemerald-expansion#2934]
![image](https://user-images.githubusercontent.com/18596778/233629101-f24dfe4f-fc08-4eeb-baca-3159120b5901.png)

**Comment by CallmeEchoo** [comment]
I was not able to reproduce this. for one tests dont allow for a double battle to happen if either participant has fewer than 2 pokemon. I also dont think this should happen in the first place? is this a feature of your hack or can this happen normally?
My best attempt at recreating this was this and I cannot see anything wrong with it
![doublesbattle](https://user-images.githubusercontent.com/65783283/235378625-91efccb1-2223-4402-819d-47fe3cc18cf0.gif)

**Comment by Jaizu** [comment]
There must be something different from the tests. In the scenario of the user only 1 mon was sent and the single battle ui was loaded, which is different from what the tests are showing.
There must be something broken with 1vs2 battles. I think it's related to #2943, the game must be very fucked up when checking amount of battlers or battler ids. 

The 1vs2 battles implementation is splitted in a lot of commits and has a lot of fixes over it, so we don't really know the exact code of it, and actually,nobody really knows how they work. Egg might know a bit, but he is not active and he doesn't test the game at all, so we are a bit in the middle of the sea.

It's a bit sad that there is no config for it (so we could avoid a broken feature) and a bit sad that such a great feature that was working perfectly fine in vanilla is broken in the expansion, specially when its a feature introduced in gen 3 that works perfectly fine on pret, but whatever.

**Comment by CallmeEchoo** [comment]
proper 1v2 battle are unfortunately not currently supported in automatic tests, but I brought it up.
can you confirm if this bug is reproduceable?

**Comment by pkmnsnfrn** [comment]
> Can I get some details on how to reproduce this, please?

When you attempt to recreate the situation described in the OP, do you get repro?

**Comment by cfmnephrite** [comment]
> > Can I get some details on how to reproduce this, please?
> 
> When you attempt to recreate the situation described in the OP, do you get repro?

Nope:
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/22523466/2ac6beb7-ba71-4bac-8e93-8402a0b44bbc)

**Comment by cfmnephrite** [comment]
> > Can I get some details on how to reproduce this, please?
> 
> When you attempt to recreate the situation described in the OP, do you get repro?

OK, I get it now. Must have been doing something wrong

**Comment by cfmnephrite** [comment]
So applying a bandaid solution to the Missingno EXP gain is pretty easy, all you need to do is change lines 4719/20 of `battle_script_commands.c` like so:
```diff
    case 5: // looper increment
        if (gBattleMoveDamage) // there is exp to give, goto case 3 that gives exp
        {
            gBattleScripting.getexpState = 3;
        }
        else
        {
-            gBattleStruct->expGetterMonId++;
-            if ((++gBattleStruct->expGetterMonId) < PARTY_SIZE)
+            if ((++gBattleStruct->expGetterMonId) < PARTY_SIZE
+                && GetMonData(&gPlayerParty[gBattleStruct->expGetterMonId], MON_DATA_SPECIES) != SPECIES_NONE)
                gBattleScripting.getexpState = 2; // loop again
            else
                gBattleScripting.getexpState = 6; // we're done
        }
        break;
```
Need to do more research to see what else is being called when an opposing mon goes down as it definitely feels like there's a pause after your sole mon gains EXP before the battle continues.

**Comment by cfmnephrite** [comment]
And the Missingno sprite showing up is fixable with two modifications to `reshow_battle_screen.c`:
```diff
static void CreateBattlerSprite(u8 battler)
{
-    if (battler < gBattlersCount)
+    if (battler < gBattlersCount && IsBattlerAlive(battler))
    {
```
```diff
static void CreateHealthboxSprite(u8 battler)
{
-    if (battler < gBattlersCount)
+    if (battler < gBattlersCount && IsBattlerAlive(battler))
    {
```

**Comment by cfmnephrite** [comment]
> Need to do more research to see what else is being called when an opposing mon goes down as it definitely feels like there's a pause after your sole mon gains EXP before the battle continues.

I'd definitely want to do this before considering this closed. Preliminary corrections handled though: https://github.com/cfmnephrite/pokeemerald/commit/f356c0bf51c8ac6b11b4140eed7a9795b4a33b5a

**Comment by cfmnephrite** [comment]
> And the Missingno sprite showing up is fixable with two modifications to `reshow_battle_screen.c`:
> 
> ```diff
> static void CreateBattlerSprite(u8 battler)
> {
> -    if (battler < gBattlersCount)
> +    if (battler < gBattlersCount && IsBattlerAlive(battler))
>     {
> ```
> 
> ```diff
> static void CreateHealthboxSprite(u8 battler)
> {
> -    if (battler < gBattlersCount)
> +    if (battler < gBattlersCount && IsBattlerAlive(battler))
>     {
> ```

Welp, never mind, looks like that solution causes issues whenever a new mon switches in:
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/22523466/a0844f0e-dbbe-4ec4-a9cd-1c0c1584833e)

**Comment by cfmnephrite** [comment]
> > And the Missingno sprite showing up is fixable with two modifications to `reshow_battle_screen.c`:
> > ```diff
> > static void CreateBattlerSprite(u8 battler)
> > {
> > -    if (battler < gBattlersCount)
> > +    if (battler < gBattlersCount && IsBattlerAlive(battler))
> >     {
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```diff
> > static void CreateHealthboxSprite(u8 battler)
> > {
> > -    if (battler < gBattlersCount)
> > +    if (battler < gBattlersCount && IsBattlerAlive(battler))
> >     {
> > ```
> 
> Welp, never mind, looks like that solution causes issues whenever a new mon switches in: ![image](https://user-images.githubusercontent.com/22523466/247394815-a0844f0e-dbbe-4ec4-a9cd-1c0c1584833e.png)

So I reversed the changes I made here (because obviously) and now I can't recreate the Missingno sprite showing up at all 🤔

**Comment by AlexOn1ine** [comment]
> So applying a bandaid solution to the Missingno EXP gain is pretty easy, all you need to do is change lines 4519/20 of `battle_script_commands.c` like so:
> 
> ```diff
>     case 5: // looper increment
>         if (gBattleMoveDamage) // there is exp to give, goto case 3 that gives exp
>         {
>             gBattleScripting.getexpState = 3;
>         }
>         else
>         {
> -            gBattleStruct->expGetterMonId++;
> -            if ((++gBattleStruct->expGetterMonId) < PARTY_SIZE)
> +            if ((++gBattleStruct->expGetterMonId) < PARTY_SIZE
> +                && GetMonData(&gPlayerParty[gBattleStruct->expGetterMonId], MON_DATA_SPECIES) != SPECIES_NONE)
>                 gBattleScripting.getexpState = 2; // loop again
>             else
>                 gBattleScripting.getexpState = 6; // we're done
>         }
>         break;
> ```
> 
> Need to do more research to see what else is being called when an opposing mon goes down as it definitely feels like there's a pause after your sole mon gains EXP before the battle continues.

You can do the same with the sprites 
Add this in `CreateBattlerSprite`
```
            if (GetMonData(&gPlayerParty[gBattlerPartyIndexes[battler]], MON_DATA_SPECIES) == SPECIES_NONE)
                return;
```
and in `CreateHealthboxSprite`
```
        else if (gBattleTypeFlags & BATTLE_TYPE_WALLY_TUTORIAL && battler == B_POSITION_PLAYER_LEFT
            || GetMonData(&gPlayerParty[gBattlerPartyIndexes[battler]], MON_DATA_SPECIES) == SPECIES_NONE)
            return;
```
Like you said this seems like a copium bandaid solution.

**Comment by Jaizu** [comment]
I feel like we are just applying ducktape and we should refactor this so the game knows which type of battle you are in

**Comment by AlexOn1ine** [comment]
> It's a bit sad that there is no config for it (so we could avoid a broken feature) and a bit sad that such a great feature that was working perfectly fine in vanilla is broken in the expansion, specially when its a feature introduced in gen 3 that works perfectly fine on pret, but whatever.

Sorry for being late but I wanted to mention that 1vs2 battles never worked correctly in vanilla gen3. If you triggered a scripted double battle with only one mon, that mon got duplicated to turn the battle into a 2vs2.

**Comment by Jaizu** [comment]
> Sorry for being late but I wanted to mention that 1vs2 battles never worked correctly in vanilla gen3. If you triggered a scripted double battle with only one mon, that mon got duplicated to turn the battle into a 2vs2.

In vanilla you can't start 1vs2 battles vs trainer battles in the wild. In the expansion you can and they break.

**Comment by AlexOn1ine** [comment]
> > Sorry for being late but I wanted to mention that 1vs2 battles never worked correctly in vanilla gen3. If you triggered a scripted double battle with only one mon, that mon got duplicated to turn the battle into a 2vs2.
> 
> In vanilla you can't start 1vs2 battles vs trainer battles in the wild. In the expansion you can and they break.

Correct me if I am wrong but I believe you can toggle it so that if you only have one mon in your party a wild double battle will default to a single battle.

**Comment by Jaizu** [comment]
> Correct me if I am wrong but I believe you can toggle it so that if you only have one mon in your party a wild double battle will default to a single battle.

I was talking about trainer battles like the twins after the first forest

**Comment by pkmnsnfrn** [comment]
Just to get to a common understanding:

- 1v2 Trainer battles don't exist in vanilla at all
- 2v2 or 1v2 wild battles don't exist in vanilla at all
- 1v2 Trainer battles exist in expansion but are somewhat broken (for reasons stated above, and I think there are more in other open issues)

> I feel like we are just applying ducktape and we should refactor this so the game knows which type of battle you are in

I don't know enough to be actually useful, but is that your hypothesis? Most of these issues stem from "the game has no idea what type of battle this is"?

**Comment by Jaizu** [comment]
> ![pokeemerald-4](https://user-images.githubusercontent.com/93446519/247586169-9b6ed5a3-9284-4f38-89f6-f1be0ccc11e8.png)

You are right, I thought that the expansion forced 1vs2 trainers by default but I must have enabled that at some point.
I will edit the comment that I posted a few messages back to clarify that. Knowing this helps a lot and makes the issue less dangerous which is super nice.

**Comment by AlexOn1ine** [comment]
```
2vs2 Trainer
- Vanilla: don't exist
- Expansion: I assume working but truly unknown 
```
Those exist in vanilla

**Comment by AsparagusEduardo** [comment]
> Those exist in vanilla

Next you're gonna tell me that abilities exist in vanilla :P

**Comment by AlexOn1ine** [comment]
> > Those exist in vanilla
> 
> Next you're gonna tell me that abilities exist in vanilla :P

They exist? 😱

But I can see that my comment is kinda random and out of nowhere. I was responding to @pkmnsnfrn

**Comment by AsparagusEduardo** [comment]
> They exist? 😱
> 
> But I can see that my comment is kinda random and out of nowhere. I was responding to @pkmnsnfrn

Nah, I was also poking fun out of what psf said lol

**Comment by pkmnsnfrn** [comment]
fixed my comment, that's what I get for posting comments before my morning coffee :P

so both of these bugs still exist but their implications are less scary than originally thought?

**Comment by AlexOn1ine** [comment]
> so both of these bugs still exist but their implications are less scary than originally thought?
Yeah. 

They only happen when you begin...
- a scripted double battle with one mon.
- wild battles that don't default to 1vs1. 
- normal wild double trainer battles if the setting differ from the expansion (they are off in the expansion).

**Comment by cfmnephrite** [comment]
Guys, Aaghat spotted something interesting. This error only seems to be occur at a certain point in the game - some sort of unknown milestone triggers it. I thought I was going crazy because I could reproduce this error and now I can't any more. What I did when I _could_ reproduce it was test a fix, commit and push it. Then I switched around party mons and PC mons before moving onto the next test and _saved the game_. When I reverted the changes because it turns out I broke something else, I found I could no longer reproduce the error.

So I think there's something in the saveblock causing this - perhaps an incorrect gPlayerPartyCount or something?

**Comment by DizzyEggg** [comment]
@Jaizu Are the 1v2 battles not working _again_ ? I thought I had fixed them for good. 😩

**Comment by Jaizu** [comment]
> @Jaizu Are the 1v2 battles not working _again_ ? I thought I had fixed them for good. 😩

Nature of rom hacking :D

**Comment by DizzyEggg** [comment]
@Jaizu @pkmnsnfrn  I actually have troubles replicating this on upcoming. I set up a 1v2 battle, but it plays fine.
![pokeemerald_01](https://github.com/rh-hideout/pokeemerald-expansion/assets/16259973/ce73bd76-cf3c-455c-83d5-004758f62b05)

Any additional steps, like type of mon, type of trainer?
