### ISSUE TITLE
Inaccurate Illusion behavior when the user is on the last slot of the party

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#2946]
Title.

In the official games, [or at least in SV](https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/post-9590584), when you send out a Pokémon with Illusion that located in the last slot of the party, the ability doesn't activate at all.

However, in the expansion that's not the case. Right now, the user is copying the Pokémon in the previous slot.

https://user-images.githubusercontent.com/4485172/233851940-f1ee9e5e-1d26-4607-8ff1-0580eb6f8d34.mp4

https://user-images.githubusercontent.com/4485172/233852468-03ec0771-09e3-4ab1-b428-ae6e40b1b9df.mp4

**Comment by AsparagusEduardo** [comment]
#2985
