### ISSUE TITLE
Burn Up without a Fire type when frozen behaves weirdly

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#2953]
Using Burn Up when frozen and lacking a Fire type to drop should simply skip trying to use the move and show the frozen animation (or perhaps test for the 20% defrosting chance) rather than using it and it failing as if not frozen.

https://user-images.githubusercontent.com/16993385/234402034-6373398e-9e5a-4056-ad08-471d7cb12edf.mov

**Comment by Bassoonian** [comment]
On further inspection, this also affects other thawing moves (e.g. when confused and frozen and trying to use a thawing move, it will evaluate the confusion before the thawing can take place)

**Comment by DizzyEggg** [comment]
Are we sure this isn't how the moves behave in the original games?

**Comment by Bassoonian** [comment]
This is, weirdly enough, exactly how it works in vanilla
