### ISSUE TITLE
The enemy Trainer does not faint properly when Ceaseless Edge is used

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#2958]
# Problem
The enemy Trainer does not faint properly when `MOVE_CEASELESS_EDGE` is used.

# Showcase / Repro

## [`data/scripts/debug.inc`](https://github.com/PokemonSanFran/pokeemerald-expansion/blob/upcoming/data/scripts/debug.inc)
```
Debug_Script_1::
   setflag FLAG_BADGE08_GET
   setflag FLAG_SYS_POKEMON_GET
   givemon SPECIES_SPEAROW,50,0
   givemon SPECIES_FLYGON,50,0
   givemon SPECIES_PIDGEOT,10,0
   giveegg SPECIES_RAYQUAZA
   trainerbattle_no_intro TRAINER_ALBERTO, Route123_Text_AlbertoDefeat
```

Run this script, and then press SELECT to enter the Battle Debug Menu.

## Battle Debug
1) Give your Pokémon the move with the ID 773
2) Use the move until the foe faints
3) Observe Bug

![The enemy Pokémon does not faint when Ceaseless Edge is used.](https://user-images.githubusercontent.com/77138753/235060958-ceb34bc3-30e2-4280-8bf3-fcc445f5ca60.gif)

# Expectation
When the move depletes the enemy HP, I expect: 
- HP is drained
- Spikes are set
- Enemy faints (this does not happen)
- Ally Pokémon gets EXP
- Next Pokémon is sent out

**Comment by LOuroboros** [comment]
I converted the .gif into a video for fast forwarding purposes. The .gif is just too long so it's a pain to re-watch.

https://user-images.githubusercontent.com/4485172/235122286-faa8a134-6331-4d6c-8dfe-c4aeb8ea9fd2.mp4

With that out of the way, I tested the move in an up-to-date copy of upcoming and I can't confirm.

![mGBA_20230428_072104973](https://user-images.githubusercontent.com/4485172/235122490-e32adfb6-d0a9-472e-9e53-a35db21c3186.gif)

My boy Rick uses the `trainerbattle_single` macro for his trainerbattle, mind you. I tested the battle with the `trainerbattle_no_intro` macro too, but the result was the same.

However, as it can be seen, there's still an issue with the move regardless, and it's that the move should be laying out the Spikes but it's not.

**Comment by pkmnsnfrn** [comment]
> I converted the .gif into a video for fast-forwarding purposes. The .gif is just too long so it's a pain to re-watch.

Thanks, edited.

> With that out of the way, I tested the move in an up-to-date copy of upcoming and I can't confirm.

Fascinating.

# Test 1
`trainerbattle_single TRAINER_RICK, Route102_Text_RickIntro, Route102_Text_RickDefeated`
**Result**: Spikes is not set, but the opponent faints.

# Test 2 
`trainerbattle_single TRAINER_WALLACE, Route102_Text_RickIntro, Route102_Text_RickDefeated`
**Result**: Spikes is set, but the opponent does not properly faint.
**Hypothesis**: Is it related to Pokemon being grounded? Wallace's team was Wailord -> Tentacruel, so this wasn't it.

# Test 3
`givemon SPECIES_SPEAROW,100,0`
`trainerbattle_single TRAINER_WALLACE, Route102_Text_RickIntro, Route102_Text_RickDefeated`
**Result**: Spikes is set, but the opponent does not properly faint.
**Hypothesis**: Is it because Lunos' Mewtwo isn't leveling?

I have no idea what's happening here. 🙃

**Comment by AsparagusEduardo** [comment]
Confirmed.
![mGBA_Xles7bZwBS](https://user-images.githubusercontent.com/2904965/235369402-2e37291a-f783-48c6-a990-61fd7007a5b1.gif)

@LOuroboros in that GIF you posted, is Mewtwo the only mon in your party? Or do you have your Battle Style to Set?

**Comment by LOuroboros** [comment]
Yes, as it can be seen at the beginning of the battle, Mewtwo was the only Pokémon in the party @AsparagusEduardo, though I also had the Battle Scene on Set.

Fwiw, I tested with 2 Pokémon, move animations enabled and a Lv90 Mewtwo in an up-to-date copy of upcoming built after a `make clean`, and I still can't confirm the issue.

![mGBA_20230430_175759505](https://user-images.githubusercontent.com/4485172/235375936-bc07eaf6-5263-44d3-a3fb-94079a658e50.gif)

**Comment by pkmnsnfrn** [comment]
> Yes, as it can be seen at the beginning of the battle, Mewtwo was the only Pokémon in the party @AsparagusEduardo, though I also had the Battle Scene on Set.
> 
> Fwiw, I tested with 2 Pokémon, move animations enabled and a Lv90 Mewtwo in an up-to-date copy of upcoming built after a `make clean`, and I still can't confirm the issue.
> 
> ![mGBA_20230430_175759505](https://user-images.githubusercontent.com/4485172/235375936-bc07eaf6-5263-44d3-a3fb-94079a658e50.gif) [ ](https://user-images.githubusercontent.com/4485172/235375936-bc07eaf6-5263-44d3-a3fb-94079a658e50.gif) ![mGBA_20230430_175759505](https://user-images.githubusercontent.com/4485172/235375936-bc07eaf6-5263-44d3-a3fb-94079a658e50.gif) [ ](https://user-images.githubusercontent.com/4485172/235375936-bc07eaf6-5263-44d3-a3fb-94079a658e50.gif)
> 
> **EDIT**: But the Spikes are still not being set too, so there's still that.

@LOuroboros I have the same result as you when battling Rick. Can you please try the tests I mention here: https://github.com/rh-hideout/pokeemerald-expansion/issues/2958#issuecomment-1527899374

**Comment by AlexOn1ine** [comment]
> Enemy faints (this does not happen)

I think it is only a visual glitch
![CEASELESS_EDGE](https://user-images.githubusercontent.com/93446519/235378361-f6c83254-082a-449a-92a3-f8b28de4dfac.gif)

**Comment by AlexOn1ine** [comment]
> Yes, as it can be seen at the beginning of the battle, Mewtwo was the only Pokémon in the party @AsparagusEduardo, though I also had the Battle Scene on Set.
> 
> Fwiw, I tested with 2 Pokémon, move animations enabled and a Lv90 Mewtwo in an up-to-date copy of upcoming built after a `make clean`, and I still can't confirm the issue.
> 
> ![mGBA_20230430_175759505](https://user-images.githubusercontent.com/4485172/235375936-bc07eaf6-5263-44d3-a3fb-94079a658e50.gif) [ ![mGBA_20230430_175759505](https://user-images.githubusercontent.com/4485172/235375936-bc07eaf6-5263-44d3-a3fb-94079a658e50.gif) ](https://user-images.githubusercontent.com/4485172/235375936-bc07eaf6-5263-44d3-a3fb-94079a658e50.gif) [ ](https://user-images.githubusercontent.com/4485172/235375936-bc07eaf6-5263-44d3-a3fb-94079a658e50.gif)
> 
> **EDIT**: But the Spikes are still not being set too, so there's still that.
Shield Dust prevents spikes setting up therefore no weird enemy bug. I don't know if this interaction is indented or not though.

**Comment by pkmnsnfrn** [comment]
> Shield Dust prevents spikes setting up therefore no weird enemy bug. I don't know if this interaction is indented or not though.

Awesome find! That explains why its just Rick. I guess future tests like this need to be on Pokémon with totally irrelevant abilities, like Commander or something.

**Comment by AlexOn1ine** [comment]
![image](https://user-images.githubusercontent.com/93446519/235506066-323a187f-aaa7-4520-9bfc-13b93e1e9a03.png)
source: https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/page-17

it seems like Ceaseless Edge spikes set up shouldn't be prevented so this is a bug. 
Also, I have a fix

**Comment by pkmnsnfrn** [comment]
> ![image](https://user-images.githubusercontent.com/93446519/235506066-323a187f-aaa7-4520-9bfc-13b93e1e9a03.png) source: https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/page-17
> 
> it seems like Ceaseless Edge spikes set up shouldn't be prevented so this is a bug.

Could you open a new issue for _that_ problem?

> Also, I have a fix for the enemy faint glitch though even if it's minor I am unsure if this is the right way. (Ceaseless Edge needed a return to correctly finish the move.

I don't know enough to know either way, but if it fixes it and passes the tests I've outlined in this issue, I think you should open a PR for it!

**Comment by AlexOn1ine** [comment]
> Could you open a new issue for that problem?
Yeah, I do some in game expansion tests and then open a issue.

> I don't know enough to know either way, but if it fixes it and passes the tests I've outlined in this issue, I think you should open a PR for it!
Thanks for testing. I will PR it.
