### ISSUE TITLE
Disguise implementation is not working correctly

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#2966]
I have tried to test each line of Bulbapedia's description and provided video evidence where I could.

# Broken Scenarios

- **Type Change**: If Mimikyu's type had been changed beforehand, it is restored to Ghost/Fairy when it changes to its Busted Form.
    - <a href="https://rb.gy/juw4y">[🎥 Expected Ghost / Fairy / Grass to revert back to Ghost / Fairy.]</a>
    - <a href="https://rb.gy/ssmtf">[🎥 Expected Normal / Normal to revert back to Ghost / Fairy.]</a>

- **Baton Pass**: If a Pokémon that has its Ability suppressed passes that effect to a Pokémon with this Ability via Baton Pass, that effect fades.
    - <a href="https://rb.gy/772c7">[🎥 After Baton Pass, Disguise should block the incoming attack. It does not.]</a>

# Fixed Scenarios

## https://github.com/rh-hideout/pokeemerald-expansion/pull/4360

- **Light Trio Z-Moves**: The Z-Moves Searing Sunraze Smash, Menacing Moonraze Maelstrom, and Light That Burns the Sky will ignore Disguise, hitting through the disguise without busting it.
    - <a href="https://rb.gy/ojdhw">[🎥 Menacing Moonraze Maelstrom should not be blocked by Disguise]</a>
    - <a href="https://rb.gy/gvk08">[🎥 Light That Burns the Sky should not be blocked by Disguise]</a>

- **Entry Hazards**: Disguise will not protect against entry hazards.
    - <a href="https://rb.gy/tukgl">[🎥 Mimikyu should take damage from Spikes.]</a>
    - **Research Question:** In the core series, are entry hazards supposed to break Disguise?

- **Weather**: Disguise will not protect against weather damage.
    - <a href="https://rb.gy/uok42">[🎥 Mimikyu should take damage from Sandstorm.]</a>
    - **Research Question:** In the core series, is weather damage supposed to break Disguise?

- **Air Balloon**: A held Air Balloon will be popped even if Disguise negates the damage.
    - <a href="https://rb.gy/4lygz">[🎥 Air Balloon should pop after the first hit.]</a>

- **Confusion**: If a Mimikyu in its Disguised Form hits itself in confusion, Disguise prevents the move from calling the damage formula.
    - <a href="https://rb.gy/t020x">[🎥 Mimikyu should not take damage from confusion.]</a>
    - **Research Question:** In the core series, does confusion damage _break_ the Substitute?

- **Message**: When this effect activates, the message, "Its disguise served it as a decoy!" is displayed, Mimikyu changes to its Busted Form, and finally the message, "<Name>'s disguise was busted!" is displayed.
    - <a href="https://rb.gy/ory9r">[🎥  Expected message, battle popup and form change to occur, but nothing happened.]</a>

# Working Scenarios

- **Damage**: If a Mimikyu in its Disguised Form is hit by a damaging move, Disguise prevents the move from calling the damage formula.
    - <a href="https://rb.gy/yi1rz">[🎥 Video]</a>

- **Immunity**: The move will thus deal no damage, and type effectiveness will not be calculated (except in case of immunity, which prevents Disguise from triggering since the move will not hit in the first place).
    - <a href="https://rb.gy/kscar">[🎥 Video]</a>

- **Multi-Hit Moves**: Disguise activates at the first strike of a multi-strike move such as Water Shuriken and will not block damage from remaining strikes. 
    - <a href="https://rb.gy/jpfda">[🎥 Video]</a>

- **Secondary Effects**: Disguise only blocks the damage from moves; additional effects of damaging moves like paralysis from Nuzzle are not prevented. 
    - <a href="https://rb.gy/sramw">[🎥 Video]</a>

- **Substitute**: If Mimikyu has a substitute, the substitute will take damage before Disguise.

- **Weakness Policy**: Weakness Policy will not activate regardless of the move's type. 
    - <a href="https://rb.gy/q282h">[🎥 Video]</a>

- **Overwrite Ability**: Gastro Acid, Worry Seed, and Simple Beam fail if the target has the Ability Disguise.
    - <a href="https://rb.gy/eho1p">[🎥 Video]</a>

- **Copy Ability Moves**: Role Play, Skill Swap, Entrainment, and Doodle fail if either Pokémon has Disguise.
    - <a href="https://rb.gy/grfsr">[🎥 Video]</a>

- **Copy Ability Abilities**: Disguise cannot be copied by Trace, Power of Alchemy, or Receiver.
    - <a href="https://rb.gy/2ruo4">[🎥 Video]</a>
    - <a href="https://rb.gy/m3erz">[🎥 Video]</a>

- **Ability Suppress**: Disguise cannot be replaced by Mummy or Lingering Aroma, traded by Wandering Spirit, or suppressed by Core Enforcer or Neutralizing Gas.
    - <a href="https://rb.gy/wtkng">[🎥 Video]</a>
    - <a href="https://rb.gy/2y8md">[🎥 Video]</a>
    - <a href="https://rb.gy/bqe0d">[🎥 Video]</a>

- **Transform**: If a Pokémon obtains Disguise with Imposter or Transform, the Ability will never activate.
    - <a href="https://rb.gy/lc5yc">[🎥 Video]</a>

- **Mold Breaker / Teravolt / Turboblaze**: Pokémon with Mold Breaker, Teravolt or Turboblaze will ignore Disguise, hitting through the disguise without busting it.
    - <a href="https://rb.gy/b0gy0">[🎥 Video]</a>
    - <a href="https://rb.gy/qdo4d">[🎥 Video]</a>

- **Light Trio Signature Moves**: The moves Moongeist Beam, Sunsteel Strike, and Photon Geyser will ignore Disguise, hitting through the disguise without busting it.
    - <a href="https://rb.gy/dw0yw">[🎥 Video]</a>
    - <a href="https://rb.gy/lts9r">[🎥 Video]</a>

## Testing
The following are all the different scripts I used for testing. If I used the debug menu, I tried to show it off in the video as much as possible.

<details>
<summary>Battle against Mimikyu with Pikachu</summary>

```
    setflag FLAG_BADGE08_GET
    givemon SPECIES_PIKACHU, 100, 0
    setwildbattle SPECIES_MIMIKYU, 100, 0
    dowildbattle
```
</details>

<details>
<summary>Battle against Mimikyu with Trevenant</summary>

```
    setflag FLAG_BADGE08_GET
    givemon SPECIES_TREVENANT, 100, 0
    setwildbattle SPECIES_MIMIKYU, 100, 0
    dowildbattle
```
</details>

<details>
<summary>Battle against Trainer Rick's Mimikyu with Tyranitar</summary>

```
    setflag FLAG_BADGE08_GET
    givemon SPECIES_TYRANITAR, 100, 0
    trainerbattle_no_intro TRAINER_RICK, Debug_FlagsNotSetOverworldConfigMessage_Text
//you'll need to edit Rick's team to have a Mimikyu as the second Pokemon
```
</details>

<details>
<summary>Battle against Mimikyu with Scizor</summary>

```
    setflag FLAG_BADGE08_GET
    givemon SPECIES_SCIZOR, 100, 0
    setwildbattle SPECIES_MIMIKYU, 50, 0
    dowildbattle
    end
```
</details>

<details>
<summary>Battle against two Mimikyu with Mikimyu, Alolan Muk, and Jigglypuff</summary>

```
    setflag FLAG_BADGE08_GET
    givemon SPECIES_MIMIKYU, 1, 0
    givemon SPECIES_MUK_ALOLAN, 100, 0
    givemon SPECIES_JIGGLYPUFF, 1, 0
    setwildbattle SPECIES_MIMIKYU, 1, 0, SPECIES_MIMIKYU, 1, 0
    dowildbattle
```
</details>

<details>
<summary>Battle against Mimikyu with Cofagrigus, Runerigus, Zygarde, Ninjask, Ditto and Mimikyu</summary>

```
    setflag FLAG_BADGE08_GET
    givemon SPECIES_COFAGRIGUS, 100, 0
    givemon SPECIES_RUNERIGUS, 100, 0
    givemon SPECIES_ZYGARDE, 100, 0
    givemon SPECIES_NINJASK, 100,0
    givemon SPECIES_MIMIKYU, 100,0
    givemon SPECIES_DITTO,100, 0
    setwildbattle SPECIES_MIMIKYU, 100, 0
    dowildbattle
```
</details>

<details>
<summary>Give player Z-Power Ring and battle with Mimikyu with Rampardos, Scizor, Lunala, Solgaleo, and Ultra Necrozma </summary>

```
    setflag FLAG_BADGE08_GET
    additem ITEM_Z_POWER_RING, 1
    givemon SPECIES_RAMPARDOS, 100, 0
    givemon SPECIES_ZEKROM, 100, 0
    givemon SPECIES_SCIZOR, 100, 0
    givemon SPECIES_LUNALA, 100, ITEM_LUNALIUM_Z
    givemon SPECIES_SOLGALEO, 100, ITEM_SOLGANIUM_Z
    givemon SPECIES_NECROZMA_ULTRA, 100, ITEM_ULTRANECROZIUM_Z
    setwildbattle SPECIES_MIMIKYU, 100, 0
    dowildbattle
```
</details>

**Comment by pkmnsnfrn** [comment]
All interactions (to my knowledge) are now tested.

**Comment by AsparagusEduardo** [comment]
What happened? Was something still broken?

**Comment by AsparagusEduardo** [comment]
I'm just now realizing that this issue isn't about Mimikyu changing form, but of Disguise edge cases.

**Comment by pkmnsnfrn** [comment]
Once Agustin finishes testing, I'll refactor this PR desc per Edu's request

**Comment by pkmnsnfrn** [comment]
@AlexOn1ine I think we should assume that all of my "broken scenarios" in the OP are still boken

**Comment by AlexOn1ine** [comment]
> @AlexOn1ine I think we should assume that all of my "broken scenarios" in the OP are still boken

which ones are broken?

**Comment by pkmnsnfrn** [comment]
Talked to Alex via DM, there are 8 broken interactions that they are looking into

**Comment by AlexOn1ine** [comment]
```
Type Change: If Mimikyu's type had been changed beforehand, it is restored to Ghost/Fairy when it changes to its Busted Form.
Baton Pass: If a Pokémon that has its Ability suppressed passes that effect to a Pokémon with this Ability via Baton Pass, that effect fades.
```
Those are untested and probably still broken with PR #4360

**Comment by pkmnsnfrn** [comment]
@AlexOn1ine What would be easier for you / people fixing battle bugs:

1) update this issue and moved the fixed stuff from broken
2) close this issue, open two new issues for each of the remaining items
3) something else
4) do nothing

**Comment by AlexOn1ine** [comment]
> 1. update this issue and moved the fixed stuff from broken

Option 1 seems to be the most reasonable.

**Comment by hedara90** [comment]
Both scenarios have been fixed on current expansion.
Types reset back to Ghost/Fairy.
And Disguise triggers after getting Baton Passed Gastro Acid. The bit for Gastro Acid is still set to 1, but Disguise ignores it.
Don't know when it was fixed. Gonna write tests then close the issue.

**Comment by AlexOn1ine** [comment]
#5249
