### ISSUE TITLE
AI sometimes calculates Rollout/Ice Ball damage incorrectly

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#2973]
`rolloutTimer` is used to calculate Rollout's base power. It is decremented in `Cmd_handlerollout()`, which is called as part of the Rollout battle script when the move is used. This means that when the AI calculates its base damage using `CalcMoveBasePower()`, it uses the value of `rolloutTimer` from the previous turn, if Rollout was the move it used that turn.

Ideally it would only ever consider Rollout's original base power (including the boost from Defense Curl), seeing as it can't choose any other moves on subsequent Rollout turns.

**Comment by BuffelSaft** [comment]
Should mention this was caught by Joggel on Discord, who provided AI score screenshots:
After using Rollout on the previous turn (`rolloutTimer = 1`):
![image](https://user-images.githubusercontent.com/28769716/235884503-0ec4f4c3-7d3f-432d-b4a8-ab5adfcf9d2c.png)
After switching in (`rolloutTimer = 0`):
![image](https://user-images.githubusercontent.com/28769716/235884615-51033cdf-47cb-4a9a-b9a2-6c469f2b8e4f.png)

**Comment by Pawkkie** [comment]
After going down a separate rabbit hole to test some of my own AI behaviour changes I found this bug, and wanted to clarify that I think you're interpreting the images sent backwards. The top image is for when the mon first switches in, and the bottom image is after using rollout the previous turn. The mon dramatically overrates Rollout when it's not been used before.

Here's a video clarifying the order:
https://github.com/rh-hideout/pokeemerald-expansion/assets/61265402/7ccfcc37-4840-44b6-b518-5d177fbf0154

An my own debug screenshots if you don't care for the video but want more evidence - 

After switching in, before using Rollout:
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/61265402/66f2d12b-135f-457c-8d5d-338b663d37a1)

After using Rollout once:
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/61265402/4ead4bf4-2c11-464b-a28a-f70191c23856)
