### ISSUE TITLE
Disobedience doesn't work with Gen8 mechanics disabled

### ISSUE THREAD

**Issue by SubzeroEclipse** [rh-hideout/pokeemerald-expansion#2984]
Not sure if this is related to #2853, but after rolling back to the old mechanic I found out that traded mons no longer disobey. Here's a boring gif where I have the Seedot traded in Rustboro City brought all the way to Level 100, which obeys me perfectly despite having no badges.
![disobedience](https://user-images.githubusercontent.com/115349505/236839881-afca18b6-0918-4391-97fa-92386b5b2b6d.gif)

**Comment by i0brendan0** [comment]
I think I might know why this happens.
```
#if B_OBEDIENCE_MECHANICS >= GEN_8
    if (!IsOtherTrainer(gBattleMons[gBattlerAttacker].otId, gBattleMons[gBattlerAttacker].otName))
        levelReferenced = gBattleMons[gBattlerAttacker].metLevel;
    else
#else
    if (gBattleMons[gBattlerAttacker].level <= obedienceLevel)
#endif
        levelReferenced = gBattleMons[gBattlerAttacker].level;

    if (levelReferenced <= obedienceLevel)
        return 0;
```
If we ignore the code specifically talking about Gen 8+ it becomes this
```
    if (gBattleMons[gBattlerAttacker].level <= obedienceLevel)
        levelReferenced = gBattleMons[gBattlerAttacker].level;

    if (levelReferenced <= obedienceLevel)
        return 0;
```
if the pokemon in question has a higher level than the value for `obedienceLevel`, `levelReferenced` isn't set to be that level. it could be any value at that point (or even more specifically, 0. which would make the next comparison always true)
I think the way to fix it would be to change it to this
```
#if B_OBEDIENCE_MECHANICS >= GEN_8
    if (!IsOtherTrainer(gBattleMons[gBattlerAttacker].otId, gBattleMons[gBattlerAttacker].otName))
        levelReferenced = gBattleMons[gBattlerAttacker].metLevel;
    else
#endif
        levelReferenced = gBattleMons[gBattlerAttacker].level;

    if (levelReferenced <= obedienceLevel)
        return 0;
```
it removes the first obedience level check that bypasses setting `levelReferenced` in the first place and just sets it.

**Comment by SubzeroEclipse** [comment]
> I think I might know why this happens.
> 
> ```
> #if B_OBEDIENCE_MECHANICS >= GEN_8
>     if (!IsOtherTrainer(gBattleMons[gBattlerAttacker].otId, gBattleMons[gBattlerAttacker].otName))
>         levelReferenced = gBattleMons[gBattlerAttacker].metLevel;
>     else
> #else
>     if (gBattleMons[gBattlerAttacker].level <= obedienceLevel)
> #endif
>         levelReferenced = gBattleMons[gBattlerAttacker].level;
> 
>     if (levelReferenced <= obedienceLevel)
>         return 0;
> ```
> 
> If we ignore the code specifically talking about Gen 8+ it becomes this
> 
> ```
>     if (gBattleMons[gBattlerAttacker].level <= obedienceLevel)
>         levelReferenced = gBattleMons[gBattlerAttacker].level;
> 
>     if (levelReferenced <= obedienceLevel)
>         return 0;
> ```
> 
> if the pokemon in question has a higher level than the value for `obedienceLevel`, `levelReferenced` isn't set to be that level. it could be any value at that point (or even more specifically, 0. which would make the next comparison always true) I think the way to fix it would be to change it to this
> 
> ```
> #if B_OBEDIENCE_MECHANICS >= GEN_8
>     if (!IsOtherTrainer(gBattleMons[gBattlerAttacker].otId, gBattleMons[gBattlerAttacker].otName))
>         levelReferenced = gBattleMons[gBattlerAttacker].metLevel;
>     else
> #endif
>         levelReferenced = gBattleMons[gBattlerAttacker].level;
> 
>     if (levelReferenced <= obedienceLevel)
>         return 0;
> ```
> 
> it removes the first obedience level check that bypasses setting `levelReferenced` in the first place and just sets it.

Good catch! I just tested and can confirm that overleveled mons disobey the player again with this change.
