### ISSUE TITLE
(Wild) doubles healthboxes are not aligned correctly

### ISSUE THREAD

**Issue by ghoulslash** [rh-hideout/pokeemerald-expansion#2993]
![pokeemerald-0](https://github.com/rh-hideout/pokeemerald-expansion/assets/41651341/14648af6-9624-4033-8a7f-ac5ecae21136)

Also mon positions

**Comment by ghoulslash** [comment]
weird, I'm fairly certain I'm on a fresh checkout of upcoming. will check again. The script I obtained the issue image with:
```
	givemon SPECIES_XATU, 40, 0
	givemon SPECIES_AGGRON, 40, 0
	setwildbattle SPECIES_VOLCARONA, 40, 0, SPECIES_VOLCARONA, 35, 0
	dowildbattle
```

**Comment by AlexOn1ine** [comment]
Yep, able to reproduce with the script

**Comment by LOuroboros** [comment]
> setwildbattle SPECIES_VOLCARONA, 40, 0, SPECIES_VOLCARONA, 35, 0
> 	dowildbattle

Can confirm.

![mGBA_20230511_160155671](https://github.com/rh-hideout/pokeemerald-expansion/assets/4485172/cf17dbd9-450b-437e-9b59-e04827c844fa)
