### ISSUE TITLE
Transform behaves irregularly in tests.

### ISSUE THREAD

**Issue by AgustinGDLV** [rh-hideout/pokeemerald-expansion#3012]
Move targets seem to not function correctly, and I was getting `ILLEGAL_MOVE` calls on a separate test. I've barely explored this, but it does seem like there's at least a slight issue.

**Bug:**
![Transform Tests](https://github.com/rh-hideout/pokeemerald-expansion/assets/103095241/0be57a3b-1341-4b7f-8505-83872157fcf7)

**Test:**
```
SINGLE_BATTLE_TEST("(TERA) Transform")
{
    GIVEN {
        PLAYER(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE, MOVE_TACKLE, MOVE_EARTHQUAKE); }
        OPPONENT(SPECIES_DITTO);
    } WHEN {
        TURN { MOVE(player, MOVE_CELEBRATE); MOVE(opponent, MOVE_TRANSFORM); }
        TURN { MOVE(opponent, MOVE_CELEBRATE); }
    }
}
```

**Comment by Bassoonian** [comment]
Fixed by #3533
