### ISSUE TITLE
Fairy Lock's animation looks either buggy or incomplete when the Player's Pokémon uses it

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#3021]
Originally posted in #2845, but since it's not directly related, I decided to make a new ticket for it.

When your Pokémon uses Fairy Lock, there is no actual lock in the move's animation. Instead there's multiple small black sticks.

![mGBA_20230523_181901608](https://github.com/rh-hideout/pokeemerald-expansion/assets/4485172/99c93fa9-186b-4fe8-990b-a8fcc5fe15d5)

**Comment by AlexOn1ine** [comment]
There is no AnimTask for `ANIM_TAG_FAIRY_LOCK_CHAINS`. It simply uses `AnimTask_VoltTackleBolt` but `ANIM_TAG_SPARK` isn't loaded which produces the fairy lock issue.
