### ISSUE TITLE
If a Pokémon with a Primal Reversion is sent out after a Pokémon that fainted, the Primal Reversion doesn't occur

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#3028]
Title.

![mGBA_20230526_184526107](https://github.com/rh-hideout/pokeemerald-expansion/assets/4485172/42b90b49-2758-4305-8232-3d26a229ac4c)

**Comment by cfmnephrite** [comment]
So, uh, this happens if you faint your own mon with Memento:
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/22523466/ffadd1f1-9812-49a7-ab26-b5ffcf9d56c3)

**Comment by cfmnephrite** [comment]
Actually nvm, something else is quite wrong here... 
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/22523466/27d6bb97-c8ae-4659-b01e-df760724f4e5)

**Comment by cfmnephrite** [comment]
Anyway, this is pretty trivial to fix - the BattleScript_FaintedMonSendOutNew needs to also call BattleScript_PrimalReversionRet - suggest making a callable reusable script for all moves that cause a switch in (including Roar, Parting Shot etc.)
