### ISSUE TITLE
Mega Evolution icon sometimes doesn't disappear when mega Evolved mon fainted

### ISSUE THREAD

**Issue by lucariokalos** [rh-hideout/pokeemerald-expansion#3032]
I saw this bug in a  rom hacks that used this expansion as a base.

**Comment by Bassoonian** [comment]
Can you verify which version of expansion the hack in question used and also find a reproduceable sequence of events that would trigger this? I'm fairly certain a similar issue was resolved recently.

**Comment by AsparagusEduardo** [comment]
Specifically, this PR #2805. Coming soon to 1.5

**Comment by AsparagusEduardo** [comment]
1.5 is out, closing the issue.
