### ISSUE TITLE
Supreme Overlord's effect is wrong

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#3035]
Its current implementation has an "initial x1.2 boost", but according to [Anubis](https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/page-20#post-9421520), Supreme Overlord only gets an additional x0.1 boost per fainted battler.

EDIT: Additionally, it's supposed to use a faint counter that's independent from this ability, and it's also used by Last Respects

**Comment by AlexOn1ine** [comment]
Edu, you think you could try and bring this back? I'll try and take a look myself and maybe we can somehow fix the failing tests.

**Comment by AlexOn1ine** [comment]
#4151
