### ISSUE TITLE
LightOfRuin freezes the game in double battles

### ISSUE THREAD

**Issue by AaghatIsLive** [rh-hideout/pokeemerald-expansion#3053]
### Description

LightOfRuin Freezes the game in double battles. Works fine in single battles. 

_**does not happen if the battle animations are turned off**_

**screenshot**

![pokeemerald-13](https://github.com/rh-hideout/pokeemerald-expansion/assets/109757010/0b2e18c1-882e-4ba1-beb8-c9b14fc05fa9)

### Version

upcoming (Edge)

### Upcoming Version

8efbe825dbd7a306af3ee8c8b4cdd4608375573a

### Discord contact info

Aaghat#2527

**Comment by AlexOn1ine** [comment]
Flatter, Devastating Drake and now Light of Ruin all freeze in doubles. I would guess that even more moves freeze the game and the animation isn't necessary a problem.

**Comment by LOuroboros** [comment]
> Flatter, Devastating Drake and now Light of Ruin all freeze in doubles. I would guess that even more moves freeze the game and the animation isn't necessary a problem.

In Flatter's and Devastating Drake's it's been proven to be *the* problem though.

**Comment by AlexOn1ine** [comment]
> > Flatter, Devastating Drake and now Light of Ruin all freeze in doubles. I would guess that even more moves freeze the game and the animation isn't necessary a problem.
> 
> In Flatter's and Devastating Drake's it's been proven to be _the_ problem though.

Hm, yeah, It just feels to much of a coincidence that they all freeze in doubles but it might be one and the scripts individually have different problems.
