### ISSUE TITLE
Sheer Force and Shield Dust do not affect the correct moves

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#3055]
### Description

Sheer Force does not negate effects that benefit the user, due to this line in battle_script_commands.c: 
`if (TestSheerForceFlag(gBattlerAttacker, gCurrentMove) && affectsUser != MOVE_EFFECT_AFFECTS_USER)`

This applies to Flame Charge, Charge Beam, Diamond Storm, Power-Up Punch, etc.

Shield Dust decides which effects to block based on the order of the move effect definitions:
`&& (gBattleScripting.moveEffect <= MOVE_EFFECT_TRI_ATTACK || gBattleScripting.moveEffect >= MOVE_EFFECT_SMACK_DOWN)) // Exclude stat lowering effects`
I suspect this was not considered/updated when adding new effects (I certainly didn't know it was there), so this is not working correctly.

This was also discussed in the discord, starting here: https://discord.com/channels/419213663107416084/774393519569502268/1117747437436665886

### Version

1.5.0 (Default)

### Discord contact info

buffelsaft

**Comment by Bassoonian** [comment]
With the Sheer Force updates of 1.8, this is now superseded by #4104
