### ISSUE TITLE
Z-BELLY DRUM freezes the game

### ISSUE THREAD

**Issue by AaghatIsLive** [rh-hideout/pokeemerald-expansion#3056]
### Description

Z-BELLY DRUM Freezes the game if you use it while your mon has full HP.

![pokeemerald-15](https://github.com/rh-hideout/pokeemerald-expansion/assets/109757010/7f3c51b7-1b7e-40d1-8d93-93123121187f)

### Version

upcoming (Edge)

### Upcoming Version

8efbe825dbd7a306af3ee8c8b4cdd4608375573a

### Discord contact info

Aaghat#2527

**Comment by AlexOn1ine** [comment]
How does Z Belly Drum behave in the original games if you are at full HP, does it let you activate the z move?
