### ISSUE TITLE
Eggs and Decamark do not use the correct palette

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#3093]
### Description

[Eggs](https://archives.bulbagarden.net/media/upload/9/9d/Spr_3e_Egg.png) and [Decamark](https://archives.bulbagarden.net/media/upload/8/8e/Spr_3r_000.png) are not using the correct palette.

# Side by Side
<details>
<summary>Vanilla / Upcoming Table</summary>

|PKMN|Vanilla|upcoming|
|---|---|---|
|Egg|![Egg Summary Screen Vanilla](https://github.com/rh-hideout/pokeemerald-expansion/assets/77138753/52d6c839-4baa-4e17-a8f9-7dee03cf2ca6)|![Egg Summary Screen Upcoming](https://github.com/rh-hideout/pokeemerald-expansion/assets/77138753/15521d10-2de8-401e-b5de-8a0532fb3497)|
|10?|![10? Pokedex Vanilla](https://archives.bulbagarden.net/media/upload/0/08/Tenquestionmarks-Pok%C3%A9dex.png)|![10? Pokedex Wheel](https://github.com/rh-hideout/pokeemerald-expansion/assets/77138753/adff096c-c3fb-4f35-9153-36452ecf759a)|

</details>

# Repro
<details>
<summary>Video and Steps</summary>

https://github.com/rh-hideout/pokeemerald-expansion/assets/77138753/14415c91-5f00-4203-8cad-9088e8d05880

1. Start a new game.
2. Overworld Debug > Give X > CHEAT Start
3. Overworld Debug > Utilities > Fly to Map > Fly to Lavaridge Town
4. Talk to the woman in front of the hot springs and take the egg.
5. Open the Pokedex and look at slot 002.
6. 🐞 Expected to see Decamark with its correct palette.
7. Close the Pokedex and open the Pokemon Party Screen.
8. Check the Egg's Summary.
9. 🐞 Expected to see the Egg with its correct palette.

</details>

### Version

upcoming (Edge)

### Upcoming Version

2100a760a

### Discord contact info

pkmnsnfrn

**Comment by AsparagusEduardo** [comment]
Might be an effect of #3051, just like what I saw in #3063.

**Comment by AsparagusEduardo** [comment]
Decamark solved in #3116

**Comment by AsparagusEduardo** [comment]
Eggs solved in #3205
