### ISSUE TITLE
Icon (and front/back sprite) palettes of some forms are incorrect

### ISSUE THREAD

**Issue by u8-Salem** [rh-hideout/pokeemerald-expansion#3103]
### Description

Below is a list of all pokemon that have palette issues. 
if they also have front or back sprite issues I note that with (f/b)

- [ ] Pikachu (1023)
- [ ] Unown (201, 1025 - 1051) (f/b)
- [ ] Deoxys (1055, 1056)
- [ ] Giratina (1072)
- [ ] Shaymin (1073)
- [ ] Tornadus (1101)
- [ ] Thundurus (1102)
- [ ] Landorus (1103)
- [ ] Kyurem (1105, 1106)
- [ ] Meloetta (1108)
- [ ] Aegislash (1157)
- [ ] Hoopa (1169)
- [ ] Wishiwashi (1176)
- [ ] Minior (1200) 
- [ ] Alcremie (1217 - 1224)

### Version

upcoming (Edge)

### Upcoming Version

cc3a6d4d940660dde30c4f226f609410414b5531

### Discord contact info

u8.Salem

**Comment by AsparagusEduardo** [comment]
#3205.
Doesn't address World Cap Pikachu not having an icon.
