### ISSUE TITLE
Proposal: Investigate AGBABI

### ISSUE THREAD

**Issue by gruxor** [rh-hideout/pokeemerald-expansion#3112]
### Description

https://github.com/felixjones/agbabi/tree/main

Generally this library is regarded as the fastest/most optimized out there for the functions it provides, and it would probably surpass the AGB SDK's macros that we use currently. Notable is its usage of FIQ (with optional functions that don't) and has overall faster sequential writes. Implementation should be _relatively_ simple and avoid compatibility issues, since we can probably alias everything out by just modifying existing macros. The library contains quite a bit, but is mostly focused on memory copy/moves - the rest revolves around integer division, RTC optimizations, and a few other miscellaneous things.

My understanding of ARM/thumb is pretty lacking, so I'm hoping some investigation from more experienced folks will help determine whether this is a good or bad idea. Some key points to determine might be:

- How much benefit could we actually get in existing copy/move/etc. calls?
- Could those optimizations potentially break existing code that relies on slower behavior, or quirks of the current functions?
- If it's deemed a good fit in general, are there certain parts that shouldn't be implemented? (or the reverse, if it's generally a _bad_ fit)
- Will it work with agbcc? ~~If not, why are we still using that garbage anyways?~~

also, shameless ping of our resident human assemblers @SBird1337 and @mrgriffin (but anyone else feel free to weigh in as well, obviously)

### Discord contact info

crater.

**Comment by mrgriffin** [comment]
From a quick scan, it seems we'd need to update the `crt0` to let us put code in the `.iwram` section. Updating `crt0` would be a great idea fwiw, we could let people initialize their variables too while we were at it :)

But it seems like a good idea to me—even only grabbing the `memset`, `memcpy`, and division implementations could be a big win. I expect everything listed on the [AEABI](https://github.com/felixjones/agbabi/blob/main/docs/aeabi.md) page should drop in just fine.

**Comment by SBird1337** [comment]
I've actually looked at these before and they really run blazingly fast (Even outperforming some of the more wonky micro optimizations I've seen in a certain old video game)

You have to bear in mind though that all of these would definitely have to run from IRAM, and even if it does not sound too big of a deal it will consume a chunk of it, potentially limiting its capacity for people implementing other features downstream (The ipatix mixer comes to mind!)
