### ISSUE TITLE
Rattled / U-Turn issue 

### ISSUE THREAD

**Issue by AlexOn1ine** [rh-hideout/pokeemerald-expansion#3124]
### Description

When U-Turn is used on a Pokemon with Rattled, the target switches out after Rattled is triggered. The user stays in and the sprite never comes back. 
![rattled_uturn](https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/ad193035-20d3-41e3-ae61-6ff4f0e87f62)
Possible solution:
```diff
BattleScript_TargetAbilityStatRaiseRet::
    copybyte gBattlerAbility, gEffectBattler
    copybyte gBattlerAttacker, gBattlerTarget
    call BattleScript_AbilityPopUp
    statbuffchange MOVE_EFFECT_AFFECTS_USER | MOVE_EFFECT_CERTAIN, BattleScript_TargetAbilityStatRaiseRet_End
    setgraphicalstatchangevalues
    call BattleScript_StatUp
 BattleScript_TargetAbilityStatRaiseRet_End:
+       setbyte gBattlerAttacker, 0
        return
```
An other solution would be to store `gBattlerAttacker` in `sSAVED_BATTLER` and restore it later instead of setting it to zero.
Unsure what the right approach here is.

### Version

upcoming (Edge)

**Comment by DizzyEggg** [comment]
Fix in #3143.
Tests in #3151.
