### ISSUE TITLE
Mega/Primal enemy party mon does not revert to base form after battle

### ISSUE THREAD

**Issue by AaghatIsLive** [rh-hideout/pokeemerald-expansion#3145]
### Description

I have encountered an issue with the Battle Form Refractor PR  #2411. It appears that the PR does not undo the mega/primal evolution of trainer/wild Pokemon.

When the player's party mon mega evolves, the `changedSpecies` attribute is set to the base form of the mon. However, this behavior is not applied to the enemy party mon.

```diff
// Saves the original species on the first form change for the player.
- if (side == B_SIDE_PLAYER && gBattleStruct->changedSpecies[monId] == SPECIES_NONE)
gBattleStruct->changedSpecies[monId] = gBattleMons[battlerId].species;

// Saves the original species on the first form change for the player.
+ if (gBattleStruct->changedSpecies[monId] == SPECIES_NONE)
gBattleStruct->changedSpecies[monId] = gBattleMons[battlerId].species;

```
removing `side == B_SIDE_PLAYER` from the check will cause the player's party mon to be turned into the enemy's reverted mon.

### Version

1.5.0 (Default)

### Discord contact info

Aaghat#2527

**Comment by DizzyEggg** [comment]
Why would this matter for the opponent's mon to revert to the base form? What's a scenario where the enemy party would be used/read after the battle's over?

**Comment by AsparagusEduardo** [comment]
> Why would this matter for the opponent's mon to revert to the base form? What's a scenario where the enemy party would be used/read after the battle's over?

Catching Primal Groudon/Kyogre 👀
