### ISSUE TITLE
The debug menu's Access PC feature isn't working properly

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#3156]
### Description

The option that lets you open the PokeStorageSys through the debug menu doesn't work correctly, though it used to.

https://github.com/rh-hideout/pokeemerald-expansion/assets/4485172/4cb006cc-fa24-4963-876a-70213a4e5f55

### Version

upcoming (Edge)

### Upcoming Version

6b5d1e7577eb7249f37f74aace054f7729ffe58d

### Discord contact info

lunos4026

**Comment by AsparagusEduardo** [comment]
Can't replicate
![mGBA_ZKlFLYa91y](https://github.com/rh-hideout/pokeemerald-expansion/assets/2904965/180a4f4d-4e30-46d7-bdd8-e5de0ecabaab)

**Comment by LOuroboros** [comment]
I'll build from clean and check again.

**Comment by LOuroboros** [comment]
Yup, now it works. Weird. Closing.
