### ISSUE TITLE
TRAINER_CUSTOM_PARTNER is always male

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#3158]
### Description

MON_DATA_OT_GENDER is not set in FillPartnerParty in the case of custom partners. This defaults to a male OT, which may be undesired behaviour if someone would like a multi battle with a female Trainer.

### Version

upcoming (Edge)

### Discord contact info

bassoonian

**Comment by AlexOn1ine** [comment]
Can't reproduce. The gender seems to be always random for me.
![pokeemerald-23](https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/dd0de22a-9c87-48fd-8eb9-35284b4256b3)
![pokeemerald-22](https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/543e54db-896e-4d28-bc4a-dc1d6b199b2c)
