### ISSUE TITLE
AI using Teleport in a trainer battle ends the battle

### ISSUE THREAD

**Issue by Joggel19** [rh-hideout/pokeemerald-expansion#3164]
### Description

If the AI uses teleport in a trainer battle, the battle is ended like it were a wild battle.
![teleport](https://github.com/rh-hideout/pokeemerald-expansion/assets/91955162/98f240d1-9bc2-476a-8e98-9a7d2e08e47f)

### Version

upcoming (Edge)

### Discord contact info

joggel

**Comment by AlexOn1ine** [comment]
Just in case someone else wants to do it. I think I solved the issue, just want to write some tests before I PR tomorrow.
