### ISSUE TITLE
Beat Up is broken

### ISSUE THREAD

**Issue by Nopinou** [rh-hideout/pokeemerald-expansion#3167]
### Description

When an opponent trainer tries to use Beat Up, it displays the message "foe xxx used Beat Up!", and then displays the trainer wants to battle text, and then the game freezes.

Tested on clean upcoming branch both by Lunos and I.

![](https://cdn.discordapp.com/attachments/1077168246555430962/1132351472911270008/mGBA_20230722_133832213.gif)

### Version

upcoming (Edge)

### Upcoming Version

Version as of 2023/07/22

### Discord contact info

Nopinou#8678

**Comment by AlexOn1ine** [comment]
The Gen5 config in PR #2541 broke Beat Up. It works fine if it's set to gen4 or lower.
