### ISSUE TITLE
Investigate possible icon rendering issue

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#3184]
### Description

#3077 showed that there might be an issue with how icons are rendered, since they never manifested until now. 

### Version

1.5.1 (Default)

### Discord contact info

AsparagusEduardo

**Comment by Bassoonian** [comment]
Since this hasn't manifested again, I'm closing this for now. It's much more likely that the centering PR did a small oopsie.
