### ISSUE TITLE
Macro for 1 player vs 2 NPC Battles

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#3197]
### Description

Trainer sight supports 1 humans versus two separate trainer opponents in Emerald. We support most other battle configurations, so this one should also be supported.

## Example
`multi_1_vs_2(TRAINER_CLAIR,lossText,TRAINER_LANCE,lossText)`

would start a battle as such

||Left|Right|
|---|---|---|
|Enemy|Clair|Lance|
|Ally|Player|

### Discord contact info

pkmnsnfrn

**Comment by pkmnsnfrn** [comment]
https://discord.com/channels/442462691542695948/442465020291317760/1137203220591157268

merp made a possible implementation and posted in pret, but of course we should ask her if we take this approach

**Comment by AlexOn1ine** [comment]
This just came up on discord. @pkmnsnfrn you think we can implement merrps implementation? 

I'll add it to the 1.9 milestone so it is not forgotten but can be removed later if we there is no pr before the release.

**Comment by pkmnsnfrn** [comment]
I didn't know or remember that merrp had one and I'm sure if we ask nicely, we can use it

**Comment by AlexOn1ine** [comment]
> I didn't know or remember that merrp had one and I'm sure if we ask nicely, we can use it



> 
> https://discord.com/channels/442462691542695948/442465020291317760/1137203220591157268
> 
> merp made a possible implementation and posted in pret, but of course we should ask her if we take this approach

:thinking:

**Comment by pkmnsnfrn** [comment]
lmao I made the issue AND wrote that comment

how do you continue to put up with my idiocy

@aarant are we allowed to steal this?

https://discord.com/channels/442462691542695948/442465020291317760/1137203220591157268

**Comment by AlexOn1ine** [comment]
> lmao I made the issue AND wrote that comment
> 
> how do you continue to put up with my idiocy
> 
> @aarant are we allowed to steal this?
> 
> https://discord.com/channels/442462691542695948/442465020291317760/1137203220591157268

Sorry, I edited my comment at the same time. I'll do it based on expansion multi battles.

**Comment by aarant** [comment]
yeah

**Comment by Bassoonian** [comment]
Added by #4741
