### ISSUE TITLE
AI softlock in recorded battles

### ISSUE THREAD

**Issue by DizzyEggg** [rh-hideout/pokeemerald-expansion#3206]
### Description

[Manectric-Rang](https://github.com/Manectric-Rang) notified me that there is an issue with AI caused by my commit here https://github.com/DizzyEggg/pokeemerald/commit/272fa07799

Quote
>Essentially, a replay hangs when the opposing AI decides to switch out (or even considers doing so, if later rethinks its decision, which is no longer the case after commit after evaluating the moves (e.g. when all moves are terrible, the move does not prevent an incoming KO, or Toxic is too advanced and the move will not solve the situation or finish the battle), but also calls RecordedBattle_ClearBattlerAction, which notably is never called during a replay in vanilla Emerald.

This should be easily fixable, Manectric even told me how he fixed the issue in his project. 
Tho I have a couple of other things going on atm, so PR for that will have to wait.

### Version

1.5.1 (Default)

**Comment by AsparagusEduardo** [comment]
How did they solve it? Do you have a link to the conversation to reference the fix?

**Comment by DizzyEggg** [comment]
This shouldn't occur anymore, recorded battles work fine as evidenced by tests.
