### ISSUE TITLE
Toxic Spikes don't function properly after a Pecha Berry activation.

### ISSUE THREAD

**Issue by SarnPoke** [rh-hideout/pokeemerald-expansion#3207]
### Description

Toxic Spikes seem to bug out if a Pokémon has its poison healed by a Pecha Berry on switch-in.

Once you've been healed by the Pecha Berry, if you switch in any other Pokémon afterwards, Toxic Spikes will not poison that Pokémon. (Judging by the nature of the bug, I'd assume an item like Lum Berry would work too.)

For clarity, here's a scenario where this bug would occur:

```
Turn 1:
* Opponent sets up 1 layer of Toxic Spikes

Turn 2:
* Player switches in Pokémon holding Pecha Berry.
* Pokémon gets poisoned but is immediately healed by Pecha Berry.

Turn 3:
* Player switches in Pokémon holding nothing.
* Pokémon does not get poisoned.

Turn 4:
* Player switches to another Pokémon holding nothing.
* Pokémon gets poisoned by the Toxic Spikes like normal.
```

Here's a video of this bug in action:

https://github.com/rh-hideout/pokeemerald-expansion/assets/77281351/11f1847c-5c26-4393-963a-7ab9841317c3

### Version

1.5.1 (Default)

### Discord contact info

sarnnn

**Comment by Pawkkie** [comment]
Can definitely reproduce. Here it is on current upcoming as well.

https://github.com/rh-hideout/pokeemerald-expansion/assets/61265402/41c01aa8-ff5f-4def-abe9-dd31b6363dc1

**Comment by Pawkkie** [comment]
Even more strangely, this only functions incorrectly during the first switchin after the berry has gone off. Every other switchin gets poisoned appropriately.

https://github.com/rh-hideout/pokeemerald-expansion/assets/61265402/f1cbc525-499b-44d1-aa06-a5be10bab755

**Comment by Pawkkie** [comment]
Sorry for the fast double-post, the first switchin after berry activation actually dodges ALL hazard damage, not just the TSpikes poisoning. Here's a Meganium using this method to avoid Stealth Rock damage as well as the poison.

https://github.com/rh-hideout/pokeemerald-expansion/assets/61265402/bec8c928-2665-4fca-bd12-24b4f7aea67c
