### ISSUE TITLE
Clear Amulet and/or Simple bug

### ISSUE THREAD

**Issue by CliffS-dev** [rh-hideout/pokeemerald-expansion#3211]
### Description

I have a battle that involves a pokemon with Simple and holding a Clear Amulet. Attempting to lower that pokemon's stats causes a pop-up that I presume is supposed to say "Pokemon's Clear Amulet prevented lowering the stat" but instead it says "Pokemon's Simple prevented lower the stat"
Not sure if it does this with any ability or if it's special for Simple because it interferes with stat changes.

### Version

1.5.1 (Default)

### Discord contact info

@cluf

**Comment by AlexOn1ine** [comment]
Can't reproduce. 
https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/0558beb0-1ef3-4657-b5ad-d69b2aede453
Could you provide the steps that produce the issue?

**Comment by AlexOn1ine** [comment]
@CliffS-dev Can you check if PR #3437 fixes this issue?

**Comment by Bassoonian** [comment]
Outdated and unreproduceable
