### ISSUE TITLE
Suggestion: Improve function AI_TryToFaint

### ISSUE THREAD

**Issue by AlexOn1ine** [rh-hideout/pokeemerald-expansion#3217]
### Description

I mentioned it in PR #3199 already but since that PR makes a lot of AI score improvements which cover a variety of edge cases, it might make sense to clean up some redundancy in `AI_TryToFaint`.

### Version

1.5.1 (Default)

**Comment by DizzyEggg** [comment]
Do you feel like this could be closed now, Alex?

**Comment by AlexOn1ine** [comment]
> Do you feel like this could be closed now, Alex?

Oh yeah. This can be closed.
