### ISSUE TITLE
Give all TMs and Fill Pocket TMHM do the same exact thing.

### ISSUE THREAD

**Issue by PCG06** [rh-hideout/pokeemerald-expansion#3225]
### Description

The debug menu has two options for giving the user TMs, being Give all TMs in Give X, and Fill Pocket TMHM in Fill PC/Pockets.
Both options give the user one TM and hence do the same thing.

### Images
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/75729017/3e7e5eea-8ae0-4f5a-9d0f-27d683c28a33)
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/75729017/ca81c139-c51b-4325-8fcc-45c8dcb9b834)

### Version

upcoming (Edge)

### Upcoming Version

f6e6a1f3839b82e547bc54c5163132927b3a3f15

### Discord contact info

pcg06

**Comment by AlexOn1ine** [comment]
Closing this. See discussion in #3388
