### ISSUE TITLE
Z-Moves don't work after Mega Evolution

### ISSUE THREAD

**Issue by BrandonExEl** [rh-hideout/pokeemerald-expansion#3227]
### Description

https://github.com/rh-hideout/pokeemerald-expansion/assets/142124410/c454042e-7f1c-43c1-8a67-e18cb8106f94

As you can see in the video, Z-Moves can't be selected after Mega Evolution. However, reversing the order allows both mechanics to be utilized. In Gen 7, a team is allowed to both Mega Evolve and use a Z-Move in a battle, so the latter is working as intended.

### Version

1.5.2 (Default)

### Discord contact info

brandonlollol

**Comment by AsparagusEduardo** [comment]
I can't tell what's going on :(
Can you please avoid the speed up for the critical parts of the video?

**Comment by BrandonExEl** [comment]
Apologies; I've created a new video with less speed up to showcase what I mean. Given the size, I've uploaded it here: https://clipchamp.com/watch/KNKBDULBqGm

1. Showcasing the Z-Power Ring in Key Items.
2. Verifying Z-Crystal being held by Pokemon (in this case, Houndoom holding Darkinium Z)
3. Mega Evolution with Mewtwo.
4. Swap to Houndoom
5. Attempt to Z-Move fails despite eligible Dark attacks.

Paired with the first video, you can see that Z-Moves work as long as they aren't after Mega Evolution. The order should not matter, however.

**Comment by BrandonExEl** [comment]
> Apologies; I've created a new video with less speed up to showcase what I mean. Given the size, I've uploaded it here: https://clipchamp.com/watch/KNKBDULBqGm
> 
> 1. Showcasing the Z-Power Ring in Key Items.
> 2. Verifying Z-Crystal being held by Pokemon (in this case, Houndoom holding Darkinium Z)
> 3. Mega Evolution with Mewtwo.
> 4. Swap to Houndoom
> 5. Attempt to Z-Move fails despite eligible Dark attacks.
> 
> Paired with the first video, you can see that Z-Moves work as long as they aren't after Mega Evolution. The order should not matter, however.

Apologies; I've created a new video with less speed up to showcase what I mean. Given the size, I've uploaded it here: https://clipchamp.com/watch/KNKBDULBqGm

Showcasing the Z-Power Ring in Key Items.
Verifying Z-Crystal being held by Pokemon (in this case, Houndoom holding Darkinium Z)
Mega Evolution with Mewtwo.
Swap to Houndoom
Attempt to Z-Move fails despite eligible Dark attacks.
Paired with the first video, you can see that Z-Moves work as long as they aren't after Mega Evolution. The order should not matter, however.

**Comment by BrandonExEl** [comment]
> I can't tell what's going on :( Can you please avoid the speed up for the critical parts of the video?

Apologies; I've created a new video with less speed up to showcase what I mean. Given the size, I've uploaded it here: https://clipchamp.com/watch/KNKBDULBqGm

Showcasing the Z-Power Ring in Key Items.
Verifying Z-Crystal being held by Pokemon (in this case, Houndoom holding Darkinium Z)
Mega Evolution with Mewtwo.
Swap to Houndoom
Attempt to Z-Move fails despite eligible Dark attacks.
Paired with the first video, you can see that Z-Moves work as long as they aren't after Mega Evolution. The order should not matter, however.

**Comment by LOuroboros** [comment]
#3233
