### ISSUE TITLE
Ball Fetch Missing gActiveBattler Setting

### ISSUE THREAD

**Issue by ghoulslash** [rh-hideout/pokeemerald-expansion#3257]
### Description

See <https://github.com/rh-hideout/pokeemerald-expansion/blob/2784f701d860a51be8a97a8306124b0d4a15a495/src/battle_util.c#L4883>

BtlController_EmitSetMonData assumes a gActiveBattler value, which is not currently set.

### Version

1.5.3 (Default)

**Comment by LOuroboros** [comment]
#3259
