### ISSUE TITLE
Option to choose data by generation

### ISSUE THREAD

**Issue by Jaizu** [rh-hideout/pokeemerald-expansion#3271]
### Description

It would be cool to change data by generation with a config/define.
Example:
Gen V movesets, Pokémon stats, types and move data.
I know this is not perfect because newer species wouldn't have data for it but they could default to the oldest one if they don't have data in that generation. Users should also be aware of this.
Changing data by user is also an option, example being using porymoves, but the expansion doesn't take current data in existing projects in consideration, so conflicts and organization commits are a super big pain in the ass to deal with.

### Discord contact info

671gz

**Comment by Bassoonian** [comment]
`P_LVL_UP_LEARNSETS`, `P_UPDATED_STATS`, `P_UPDATED_TYPES`, `B_UPDATED_MOVE_DATA` etc all serve this purpose.
