### ISSUE TITLE
Potential Problem with calling ShouldSwitch inside AI Calcs

### ISSUE THREAD

**Issue by ghoulslash** [rh-hideout/pokeemerald-expansion#3277]
### Description

ShouldSwitch will run through the battle controller data emit functions if switching should be performed. This is potentially problematic during AI calcs by maybe stomping on other data? Suggestion would be to pass an argument through ShouldSwitch, e.g. "bool32 emitResult" to safely use it in the AI calcs

### Version

1.5.3 (Default)

**Comment by AlexOn1ine** [comment]
I wonder if issue #2672 is related to this.

**Comment by Bassoonian** [comment]
Fixed by #3784
