### ISSUE TITLE
Enigma Berry's effect is not implemented

### ISSUE THREAD

**Issue by DizzyEggg** [rh-hideout/pokeemerald-expansion#3281]
### Description

HOLD_EFFECT_ENIGMA_BERRY does nothing, while it should, quoting Showdown
>Restore 1/4 max HP after holder is hit by a supereffective move

### Version

1.5.3 (Default)

**Comment by AsparagusEduardo** [comment]
#3285 reverted due to it being merged before being solved properly.

**Comment by DizzyEggg** [comment]
Fixed by #3300
