### ISSUE TITLE
Recoil moves cause recoil damage against Protect like moves

### ISSUE THREAD

**Issue by AlexOn1ine** [rh-hideout/pokeemerald-expansion#3304]
### Description

Recoil moves and moves with `EFFECT_PROTECT` not named Protect cause the user to still take recoil damage (and any additional effects). For a weird reason it only applies after a different move was previously used. For doubles it can happen the same turn the partner moves first, in singles it's on the second turn.

Simple test:
```
SINGLE_BATTLE_TEST("Protect like moves cause recoil effect")
{
    GIVEN {
        PLAYER(SPECIES_RAPIDASH);
        OPPONENT(SPECIES_BEAUTIFLY);
    } WHEN {
        TURN { MOVE(opponent, MOVE_TACKLE);
               MOVE(player, MOVE_TACKLE);
        }
        TURN { MOVE(opponent, MOVE_SILK_TRAP);
               MOVE(player, MOVE_DOUBLE_EDGE);
        }
        TURN {}
    } SCENE {
        NOT MESSAGE("Rapidash is hit with recoil!");
    }
}
```
Recording:

https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/291d86d6-afb5-4236-b037-41c2b31482d4

### Version

upcoming (Edge)

**Comment by DizzyEggg** [comment]
This is upcoming only?

**Comment by AlexOn1ine** [comment]
> This is upcoming only?

both master and upcoming
