### ISSUE TITLE
The order of key items Exp. Share messages is wrong

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#3318]
### Description

Pokémon level up before the "The rest of your team gained Exp. Points" message appears. Context in Discord: https://discord.com/channels/419213663107416084/1148047834583679056/1152881573289533512

### Version

1.5.3 (Default)

### Discord contact info

bassoonian

**Comment by AsparagusEduardo** [comment]
#3339
