### ISSUE TITLE
Z-Moves desync Recorded Battles

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#3332]
### Description

Using a Z-Move in a multiplayer link cable battle and recording the battle afterwards with the frontier pass, the Z-MOVES doesn't get shown in the recording and this leads to match desync.

From: https://discord.com/channels/419213663107416084/774393519569502268/1145308288636944435

This ticket is a placeholder so we don't forget it, but needs to be fleshed out later.

### Version

1.5.3 (Default)

### Discord contact info

aaghat

**Comment by AlexOn1ine** [comment]
#4449

Feel free to reopen if the issue still exists but I'm 99% sure it doesn't anymore since tests are recorded battles are used for tests and it is fixed there.
