### ISSUE TITLE
Z-Moves and Disobedience break battles

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#3333]
### Description

https://discord.com/channels/419213663107416084/774393519569502268/1145308711657676810

> if you use a z-move when your mon doesn't obey you and ignore your orders, it causes various issues. 

This ticket is a placeholder so we don't forget it, but needs to be fleshed out later.

### Version

1.5.3 (Default)

### Discord contact info

aaghat

**Comment by LOuroboros** [comment]
I confirmed Z-Moves are certainly misbehaving with disobedient 'mons earlier, dropping a .gif over here:

![](https://media.discordapp.net/attachments/774393519569502268/1154465359924043947/mGBA_20230921_141226866.gif)

That Wurmple should have definitely not used a Z-Move, lel.

**Comment by DizzyEggg** [comment]
How does it work in the official games? Can Z-moves even fail to disobedience or they always work?

**Comment by pkmnsnfrn** [comment]
@DizzyEggg I don't have a way to test it right now, but I would bet any amount of money that vanilla games will check for obedience and print the string for failure before anything else, and if the Pokemon passes the obedience check, THEN the mon will "surround itself with Z-Power and unleash the full force Z Move"

**Comment by LOuroboros** [comment]
> How does it work in the official games? Can Z-moves even fail to disobedience or they always work?

They can, yeah.

https://github.com/rh-hideout/pokeemerald-expansion/assets/4485172/bfb8efe5-8338-4aa8-94ae-2277dad66df8

**Comment by AlexOn1ine** [comment]
> > How does it work in the official games? Can Z-moves even fail to disobedience or they always work?
> 
> They can, yeah.
> usum.mp4

Are you allowed to use the z-move again if it the didn't obey the first time the z move was chosen?

**Comment by LOuroboros** [comment]
> > > How does it work in the official games? Can Z-moves even fail to disobedience or they always work?
> > 
> > 
> > They can, yeah.
> > usum.mp4
> 
> Are you allowed to use the z-move again if it the mon didn't obey the first time the z move was chosen?

Yes. You can keep trying to use a Z-Move until it activates.

https://github.com/rh-hideout/pokeemerald-expansion/assets/4485172/44101a93-5f68-4375-9536-13657852e8e8

**Comment by Bassoonian** [comment]
![zmoveobedience](https://github.com/user-attachments/assets/ce5cb2a2-2b9a-4a2c-b0b9-86578cad90c8)

Confirmed to still be an issue after #4449
