### ISSUE TITLE
Bergmite/Avalugg's updated and old egg groups are swapped

### ISSUE THREAD

**Issue by Flametix** [rh-hideout/pokeemerald-expansion#3370]
### Description

Currently Bergmite and Avalugg's egg groups are Monster/Monster when P_UPDATED_EGG_GROUPS >= GEN_8 and Monster/Mineral otherwise. This should be the other way around.
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/44883711/68edf9b3-d46b-422f-82ce-ad253b09bf93)

### Version

1.6.1 (Default)

### Discord contact info

flarne

**Comment by SBird1337** [comment]
01817f89e4a3dc286d29589369aed5c54b57bb8a
