### ISSUE TITLE
Salt Cure kill Visual Bug

### ISSUE THREAD

**Issue by TerraPrograms** [rh-hideout/pokeemerald-expansion#3386]
### Description

When a Pokemon with Salt Cure kills a Pokemon, a Visual Bug like in the following image occurs. I think the reason could be that the "Pokemon is being Salt Cured" text is replacing the fainted text. Keeping the last Pokemons Sprite and Colors still there.

https://cdn.discordapp.com/attachments/1083396892739776643/1158754490434977892/pokeemerald-3.png?ex=652e8937&is=651c1437&hm=d6d55022976f7e28882dbe62d8540655fac9e647fd6420696023bce6e91fd683&

### Version

upcoming (Edge)

### Upcoming Version

7c7396c

### Discord contact info

._.terra._.

**Comment by AlexOn1ine** [comment]
Can you test if this fixes the visual bug issue?
```
 BattleScript_SaltCureExtraDamage::
        playanimation BS_TARGET, B_ANIM_SALT_CURE_DAMAGE, NULL
        waitanimation
-       call BattleScript_HurtTarget_NoString
        printstring STRINGID_TARGETISHURTBYSALTCURE
        waitmessage B_WAIT_TIME_LONG
+       call BattleScript_HurtTarget_NoString
        end2
```
I couldn't reproduce the visual bug but noticed the out of place message placement.

**Comment by TerraPrograms** [comment]
> Can you test if this fixes the visual bug issue?
> 
> ```diff
>  BattleScript_SaltCureExtraDamage::
>         playanimation BS_TARGET, B_ANIM_SALT_CURE_DAMAGE, NULL
>         waitanimation
> -       call BattleScript_HurtTarget_NoString
>         printstring STRINGID_TARGETISHURTBYSALTCURE
>         waitmessage B_WAIT_TIME_LONG
> +       call BattleScript_HurtTarget_NoString
>         end2
> ```
> 
> I couldn't reproduce the visual bug but noticed the out of place message placement.

I tried this, but it does not seem to fix it.
Just making sure that we are doing the same thing, as it seems consistent for me, are you getting the kill with the direct Salt Cure Damage? If you kill the Pokemon with the indirect damage, it works fine.

**Comment by AlexOn1ine** [comment]
> I tried this, but it does not seem to fix it. Just making sure that we are doing the same thing, as it seems consistent for me, are you getting the kill with the direct Salt Cure Damage? If you kill the Pokemon with the indirect damage, it works fine.

Yeah, KO'ed by salt cure effect. 
![salt_cure](https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/1c065c30-893d-43d2-82b0-ef1400caeac7)
Can you provide your steps that reproduce the issue?
