### ISSUE TITLE
Kee Berry raises Defense by 1 stage instead of 2

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#3394]
## Description
A Kee Berry raises the holder's Defense by one stage when hit by a physical move. This consumes the Kee Berry.

When the player has a Kee Berry attached to their Pokémon, and that Pokémon is damaged by a physical attack, the Pokémon holding the Kee Berry gets +2 Defense instead of +1. +2 Defense should only apply when the holding Pokémon's ability is Ripen.

## Repo
<details>
<summary>data/scripts/debug.inc</summary>

```diff
Debug_Script_1::
+    givemon SPECIES_RAPIDASH_GALARIAN,100,ITEM_KEE_BERRY
    end

Debug_Script_2::
+    setwildbattle SPECIES_DONPHAN, 40, ITEM_NONE
+    dowildbattle
	end

Debug_Script_3::
+    setwildbattle SPECIES_HITMONCHAN, 20, ITEM_NONE
+    dowildbattle
	end
```

Run Script 1, then Script 2 or 3.

### Repro Steps
1. Rapidash is hit with physical attack by Hitmonchan
2. Kee Berry activates
3. Message prints that Rapidash gets Defense boost
4. Check Debug menu - Rapidash has +2 DEF <- bug
</details>

## Video
<details>
<summary>Video of bug</summary>

https://github.com/rh-hideout/pokeemerald-expansion/assets/77138753/e1aa4b3e-651f-4cf8-aaaa-971a26abaee2

</details>

### Version

1.6.1 (Default)

### Upcoming Version

70ed93e01b0f7910e2d96bc61be43bbbe8eaa433

### Discord contact info

pkmnsnfrn

**Comment by AlexOn1ine** [comment]
Both #3394 and #3393 have been, I just want to write some tests before PR'ing.

(Unless someone else already did it.)
