### ISSUE TITLE
World Cap Pikachu doesn't have a mini icon

### ISSUE THREAD

**Issue by kittenchilly** [rh-hideout/pokeemerald-expansion#3400]
### Description

All other Pikachu forms have an icon, except for the World Cap form.
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/23617175/19e37f19-287b-4aed-a4aa-8abc65407a0e)

### Version

1.6.1 (Default)

### Discord contact info

kittenchilly

**Comment by LOuroboros** [comment]
https://www.dropbox.com/s/rvovjswop9it2j6/025-H8.png?raw=1
Source: https://www.pokecommunity.com/showthread.php?t=368703

Ez PR.

**Comment by DizzyEggg** [comment]
#3401
