### ISSUE TITLE
The debug menu doesn't report the value of the very first flag (FLAG_TEMP_1) correctly

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#3403]
### Description

Title.

The debug menu sometimes displays the state of the `FLAG_TEMP_1` as `TRUE` and sometimes it displays it as `FALSE`, even though by default it's always set to `FALSE`. It took me a hot minute while working on a project of mine to realize it wasn't my fault, lel.

![mGBA_20231010_191006264](https://github.com/rh-hideout/pokeemerald-expansion/assets/4485172/9e798eb1-5c7e-4478-be73-6a7f70c14d32)

### Version

upcoming (Edge)

### Upcoming Version

70fbf9e9df2f2dded5d5fd783336267053d4ee37

### Discord contact info

lunos4026

**Comment by AsparagusEduardo** [comment]
Please check if #3390 fixes it

**Comment by LOuroboros** [comment]
To clarify because I feel like the .gif may not portray the issue accurately, what I did here was enter the Debug Menu, check the state of the flag and press the B button which closes the whole thing. I did it a total of 3 times as it can be seen there.

**Comment by LOuroboros** [comment]
> Please check if #3390 fixes it

Will do.

**Comment by LOuroboros** [comment]
I left the compiler run after a `make clean`, started a clean save too and sadly, the issue is still there, @AsparagusEduardo.

>commit 612da3255342a7f1c00d735d08968839d3500c88 (HEAD -> upcoming)
>Merge: 70fbf9e9df a34e0f6f6f
>Author: LOuroboros <lunosouroboros@gmail.com>
>Date:   Tue Oct 10 19:16:14 2023 -0300
>
>    Merge branch 'RHH/pr/upcoming/debugCleanup2' of https://github.com/AsparagusEduardo/pokeemerald into upcoming
>
>commit 70fbf9e9df2f2dded5d5fd783336267053d4ee37 (upstream/upcoming, upstream/HEAD)
>Author: ghoulslash <41651341+ghoulslash@users.noreply.github.com>
>Date:   Mon Oct 9 21:35:00 2023 -0400
>
>    Opportunist Ability (#2994)
>
>    Co-authored-by: Eduardo Quezada D'Ottone <eduardo602002@gmail.com>
>    Co-authored-by: ghoulslash <pokevoyager0@gmail.com>
