### ISSUE TITLE
Single repeated ASSUME failed

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#3404]
### Description

[Found here](https://github.com/rh-hideout/pokeemerald-expansion/pull/3368#discussion_r1347361067)

### Version

1.6.1 (Default)

### Discord contact info

AsparagusEduardo

**Comment by AlexOn1ine** [comment]
@AsparagusEduardo  Is this fixed by #4641?

**Comment by AsparagusEduardo** [comment]
> Is this fixed by 4641?

Yep!
![image](https://github.com/user-attachments/assets/3c01723c-aaac-4d29-a5cb-2576335909b4)
