### ISSUE TITLE
Parental Bond is nonfunctional

### ISSUE THREAD

**Issue by ZnogyroP** [rh-hideout/pokeemerald-expansion#3407]
### Description

![brokenpbond](https://github.com/rh-hideout/pokeemerald-expansion/assets/20970593/b754fd08-66b2-41e5-84f2-bdfc50c87fb3)

As title says, Parental Bond is currently broken and does nothing. Issue seems to lie somewhere in the IsMoveAffectedByParentalBond function, as forcing it to return TRUE makes it work.

### Version

1.6.1 (Default)

**Comment by AsparagusEduardo** [comment]
#3417
