### ISSUE TITLE
Can't choose target for moves that hit all adjacant target while dynamaxed

### ISSUE THREAD

**Issue by PCG06** [rh-hideout/pokeemerald-expansion#3434]
### Description

When you select a move that can hit all targets on the field, you can't select a target, and it will always hit the first target

![dynamax 1](https://github.com/rh-hideout/pokeemerald-expansion/assets/75729017/b3153513-df90-47dc-802e-32b7b90e0ca1)
![dynamax 2](https://github.com/rh-hideout/pokeemerald-expansion/assets/75729017/b53ee649-dbe0-4eb7-bacf-929f2ec4a31b)

If the first target has fainted, it hits the ally
![dynamax 3](https://github.com/rh-hideout/pokeemerald-expansion/assets/75729017/05e56764-8103-4357-8627-616843c8b0f9)

### Version

upcoming (Edge)

### Upcoming Version

14b7a702543b181c5a9d262572f2728e763366bf

### Discord contact info

pcg06

**Comment by AsparagusEduardo** [comment]
#3470
