### ISSUE TITLE
MyBoy shows white screen when booted up

### ISSUE THREAD

**Issue by doejohn126** [rh-hideout/pokeemerald-expansion#3439]
### Description

For some reason, I can't boot up my rom hack on the MyBoy emulator and it shows a white screen when I try. But this could be my own issue since I haven't tried to load a clean expansion file.

### Version

upcoming (Edge)

### Upcoming Version

latest as of 3:48PM EST 10/20/2023

### Discord contact info

doejohn126

**Comment by AsparagusEduardo** [comment]
Free or paid version?

**Comment by doejohn126** [comment]
I've been the free one from the play store.

**Comment by SBird1337** [comment]
Can you try to do this with an actual clean expansion master / upcoming? Otherwise we're probably chasing demons here :D

**Comment by doejohn126** [comment]
Yeah sure I'll try with a clean upcoming and see what happens.

**Comment by doejohn126** [comment]
Yeah my fault. This seems to be my problem as I was able to load a clean rom fine.
