### ISSUE TITLE
Certain legendary battles have their backgrounds missing

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#3444]
### Description

Only tested Ho-Oh for now, but I was able to pin down that it started with #2417's merge.

Before and after
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/2904965/cc612e2d-825e-4328-9785-a0f0bb6e0ef6)![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/2904965/372696bc-5459-461d-8abd-a28e74f55d04)

### Version

upcoming (Edge)

### Discord contact info

AsparagusEduardo

**Comment by AlexOn1ine** [comment]
#3464
