### ISSUE TITLE
Can't cancel dynamax in doubles

### ISSUE THREAD

**Issue by AlexOn1ine** [rh-hideout/pokeemerald-expansion#3466]
### Description

If you try to cancel a dynamax in doubles the mon first selected for it will still dynamax. Works fine in singles 

https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/c3bd8b77-ab02-4543-b67e-ce31c9dbee8a

### Version

upcoming (Edge)

**Comment by AsparagusEduardo** [comment]
#3470
