### ISSUE TITLE
Illuminate is missing its Gen9 effect

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#3478]
### Description

[Illuminate received an in-battle effect in patch 2.0.1 of SV.](https://bulbapedia.bulbagarden.net/wiki/Illuminate_(Ability)) This effect is still missing from RHH.

### Version

upcoming (Edge)

### Discord contact info

bassoonian

**Comment by AlexOn1ine** [comment]
#3482
