### ISSUE TITLE
Trainer customization in Battle Frontier

### ISSUE THREAD

**Issue by SubzeroEclipse** [rh-hideout/pokeemerald-expansion#3484]
### Description

In the battle facilities the vanilla struct is still present, which only allows for a partial customization of Trainer mons (it doesn't allow to pick one specific ability, for example); Trainer class balls do not work either here since they use separate TC from regular battles. Since there already have been some PRs that address BF stuff, I think extending the Trainer Control feature would be in the expansion scope.

### Discord contact info

subzeroeclipse

**Comment by AlexOn1ine** [comment]
#4313
