### ISSUE TITLE
Weak Armor interrupts Multi-Hit moves if one of the stats can't be modified

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#3492]
### Description

Issue found by @hedara90

Works in Gen 5 at least (Garbodor's defense was lowered 5 times before the start of the GIF):
![melonDS_kCEOyzeDA5](https://github.com/rh-hideout/pokeemerald-expansion/assets/2904965/61d2024a-6913-4fae-89d0-39ccc82710aa)

### Version

1.6.1 (Default)

### Discord contact info

AsparagusEduardo

**Comment by hedara90** [comment]
Video of behavior in current version.
https://github.com/rh-hideout/pokeemerald-expansion/assets/149414898/147cea86-13b2-4fb3-bbfe-05bff1356f14
