### ISSUE TITLE
Right/Down arrows don't cycle through Poke Balls on battle screen

### ISSUE THREAD

**Issue by fdeblasio** [rh-hideout/pokeemerald-expansion#3496]
### Description

Pressing right/down to change the Poke Ball from the battle screen isn't working (left/up does work though)

![rightBallSelect](https://github.com/rh-hideout/pokeemerald-expansion/assets/35279583/31dc271c-f8e8-4f13-a29a-72feee91e93a)

### Version

upcoming (Edge)

### Upcoming Version

1a6acad3cf301a8f5c46cdfaa3a521a01f103360

### Discord contact info

frankfurter0

**Comment by AlexOn1ine** [comment]
What should be the optimal behaviour, left/right (that's what I would do), up/down or all 4 directions?

**Comment by fdeblasio** [comment]
I'll have to double check on an older version, but I think the way it used to work were that left/up were the previous ball and right/down were the next ball. In the GIF, you can even see the ball bounce a little bit when right is selected as if it's supposed to change

**Comment by AlexOn1ine** [comment]
This works on master just fine. Wasn't this back ported from master to upcoming?
