### ISSUE TITLE
sText_MoveBlockedByDynamax Get's Printed even after the Pokemon Faints

### ISSUE THREAD

**Issue by AaghatIsLive** [rh-hideout/pokeemerald-expansion#3519]
### Description

Using Dragon Tail on a Dmax'ed Pokemon causes this _(see gif below)_
![dragontail](https://github.com/rh-hideout/pokeemerald-expansion/assets/109757010/f64745a5-8f0a-4d54-92c4-70d8c3e8548b)

### Version

upcoming (Edge)

### Discord contact info

aaghat

**Comment by Bassoonian** [comment]
Fixed by #3541
