### ISSUE TITLE
Spelling mistake in species info

### ISSUE THREAD

**Issue by geefuoco** [rh-hideout/pokeemerald-expansion#3525]
### Description

![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/87877876/d282ebb8-4a7b-4a9a-a90d-5590aa09706b)
Should be PUMPKABOO

### Version

upcoming (Edge)

### Upcoming Version

57c1dd97bb6dbfe99abeac64d7f0aeff88b17b18

**Comment by Bassoonian** [comment]
Fixed by #3541
