### ISSUE TITLE
Add easier way to manage Pokédex order

### ISSUE THREAD

**Issue by Jaizu** [rh-hideout/pokeemerald-expansion#3532]
### Description

I just tried to edit the national dex to just keep gen 3 + evos and the process is super annoying, I imagine this is the same for everybody that wants to make their own regional or national pokédex for their games.
If you want to just have pokémon behind the generation 3 you have to comment species one by one in different lists in pokedex_orders.h as well as pokedex_entries.h

**Comment by DizzyEggg** [comment]
That's a fair point, this should be optimized somehow

**Comment by Jaizu** [comment]
Seems like this has been simplified now. I will close the issue to help tracking open issues and open a new one if I encounter any issue once I try back in the future.
