### ISSUE TITLE
Reminder: Add CyanSMP's Gen 9 icons

### ISSUE THREAD

**Issue by doejohn126** [rh-hideout/pokeemerald-expansion#3553]
### Description

I saw this [commit ](https://github.com/leo60228/pokeemerald/commit/56f10adf1d817c8d3d35b18d803292477008ccda) and I thought it would be a good to the current icons.

### Discord contact info

doejohn126

**Comment by leo60228** [comment]
I didn't merge it because I thought the animations looked wrong for most of them. Other people might disagree, though.

**Comment by doejohn126** [comment]
I do think cyans are improvements over the current icons but I can close this if the expansion is planning on using different ones, improving them or keeping them the same.

**Comment by Jaizu** [comment]
Imo the ones linked in that commit look way better

**Comment by AsparagusEduardo** [comment]
Huh. I'm just now noticing that not all sprites in that commit were added in #3805 despite some of them being an improvement in my opinion 🤔 
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/2904965/2871caf3-ebdb-42d2-973e-7a0fec522bfe)

**Comment by AlexOn1ine** [comment]
If you think some of them are better then just PR, or just copy the whole icons over. I don't mind either. Maybe Cyan has some icons that we don't have yet?

**Comment by AsparagusEduardo** [comment]
> If you think some of them are better then just PR, or just copy the whole icons over. I don't mind either. Maybe Cyan has some icons that we don't have yet?

Right. I think I'll reopen this and assign myself to it.
