### ISSUE TITLE
Embargo passed onto a party member via Baton Pass is lifted after 1 out of 5 turns pass, when it shouldn't

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#3554]
### Description

If a Pokémon that is under the effects of Embargo uses Baton Pass to switch out the Pokémon, the one that is sent out is supposed to inherit that status and be affected by Embargo for the remainder of its active effect.

In the expansion, Embargo is lifted immediately after sending out a new Pokémon, when it should last 4 turns after the fact.

Expansion:

![Embargo_BatonPass_Fling_Expansion](https://github.com/rh-hideout/pokeemerald-expansion/assets/4485172/6fe8210f-1807-4276-9246-0f7bb6f00665)

USUM:

https://github.com/rh-hideout/pokeemerald-expansion/assets/4485172/08bd15f3-efa6-43b8-8295-e2787301c63a

### Version

upcoming (Edge)

### Upcoming Version

3004fd588aa4afe17a3bfd297978c0b932b45fef

### Discord contact info

lunos4026

**Comment by AlexOn1ine** [comment]
#3745
