### ISSUE TITLE
WIP - Port TheXaman's Move Descriptions

### ISSUE THREAD

**Issue by Pawkkie** [rh-hideout/pokeemerald-expansion#3571]
### Description

Posting this after chatting with Edu and others in the Discord. [Here](https://github.com/Pawkkie/pokeemerald-expansion/tree/xaman-move-desc)'s a branch I've made isolating the feature, with the implementation I'm currently using in my own project. This branch is based on expansion's 1.6.2 master branch.

Here's an overview showing it in action.

https://github.com/rh-hideout/pokeemerald-expansion/assets/61265402/b1d51e90-0975-4a02-87b1-c4c4ebde734f

I've disabled the descriptions for Pokemon that can mega or zmove, as they also use the start button and this was the easiest way to avoid the conflict for my purposes. I'm not using either system in my project so this was good enough for me, though it'll likely want a cleaner fix in expansion's version.

https://github.com/rh-hideout/pokeemerald-expansion/assets/61265402/fd422b28-7dfa-4e6f-aaf7-92f3b684fbaf

### Discord contact info

@Pawkkie

**Comment by KyleLaporte** [comment]
Note for future developers, just updated this branch for expansion's 1.7.0 release to compile properly with modern.

**Comment by Pawkkie** [comment]
Note for future developers, updated the branch to expansion's 1.7.0 release, minor adjustment to compile properly with modern :)

**Comment by Bassoonian** [comment]
@Pawkkie just for clarity: is your branch/this issue a basis for someone else to branch from to make a PR to expansion, or is it on your to-do list?

**Comment by Pawkkie** [comment]
> @Pawkkie just for clarity: is your branch/this issue a basis for someone else to branch from to make a PR to expansion, or is it on your to-do list?

Definitely just a basis for someone else to PR, I have no intention of taking this further or PRing it myself, and wouldn't have posted it if Edu hadn't said it might be helpful for others in the future :)

**Comment by AlexOn1ine** [comment]
#4152
