### ISSUE TITLE
Bug Bite, Stuff Cheeks, Teatime, Fling override battle scene off

### ISSUE THREAD

**Issue by ghoulslash** [rh-hideout/pokeemerald-expansion#3584]
### Description

The battle scripts set HITMARKER_NO_ANIMATIONS and then remove the bit after `consumeberry` which would reset any Battle Scene Off settings that are assigned at the start of battle. Why GF decided to make this option set a bit flag like this is beyond me but consumeberry needs a workaround.

### Version

1.6.2 (Default)

**Comment by AlexOn1ine** [comment]
#3607
