### ISSUE TITLE
Legendary Fusion unexpected behave

### ISSUE THREAD

**Issue by Kappas1243** [rh-hideout/pokeemerald-expansion#3601]
### Description

Fusioning Kyurem, Necrozma and Calyrex not resulting into the expected form.
Sometimes when selected the wrong pokemon to fuse to, the game freeze for a short amount of time.

![Calyrex](https://github.com/rh-hideout/pokeemerald-expansion/assets/151959693/5290da0c-a711-455e-b107-b270513c6931)
![KyureMaybe](https://github.com/rh-hideout/pokeemerald-expansion/assets/151959693/29279554-1ddb-416b-8824-f48a824ad5a6)
![NecrozmaNLunarizer](https://github.com/rh-hideout/pokeemerald-expansion/assets/151959693/c55f1747-4af4-4724-9d71-7b0d77945e3b)
![NecrozmaNSolarizer](https://github.com/rh-hideout/pokeemerald-expansion/assets/151959693/b004d0e6-1dd5-484f-885e-00fa05e217a0)

### Version

upcoming (Edge)

### Upcoming Version

#3596

### Discord contact info

#kappas_51087

**Comment by LOuroboros** [comment]
I did a quick test in a clean copy of the upcoming branch, and I can confirm that it's broken too.

![](https://media.discordapp.net/attachments/774393519569502268/1177676546148933713/mGBA_20231124_152428318.gif)
