### ISSUE TITLE
Fusion issues

### ISSUE THREAD

**Issue by PCG06** [rh-hideout/pokeemerald-expansion#3603]
### Description

After fusing or just exiting the party screen after attempting the fusion moves the cursor to the top of the list.

![cursorafterfusion](https://github.com/rh-hideout/pokeemerald-expansion/assets/75729017/bcce1066-3145-4bf6-b39e-3a2c2070d4f1)

If you don't do a fusion, the cursor stays on the same item, but doing it the second time moves it.

![notfusing](https://github.com/rh-hideout/pokeemerald-expansion/assets/75729017/00047d21-2038-48b3-a524-68ca7daa5aad)

Sometimes unfusing the Pokémon causes a memory leak (that's what Eduardo said) and this happens:

![partyscreenweirdingout](https://github.com/rh-hideout/pokeemerald-expansion/assets/75729017/f00ab64c-685c-4817-8748-7ec335098be8)

It happens when you fuse/unfuse more than once or twice.

### Version

upcoming (Edge)

### Upcoming Version

14b7a702543b181c5a9d262572f2728e763366bf

### Discord contact info

pcg06

**Comment by cfmnephrite** [comment]
So I don't think it's a memory leak causing the graphics problem (at least not in VRAM) - these are the summary screen tiles for first fusion, first unfusion, second fusion, then second unfusion. If it were a memory leak, you would see too much being added to VRAM and it having to overwrite itself but that's not what happens. In other words, it's not trying to write too much to VRAM but rather it's just not writing anything at all. Also interesting is the fact that after the second fusion, the summary screen is also messed up when you click Yes to teaching Necrozma Moongeist/Sunstrike.
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/22523466/2039d79b-b09f-4bf7-b7e2-b4546eedafe0)
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/22523466/7939682a-9052-4b79-b037-bc05bd63c66e)
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/22523466/6c69c0dd-4060-449f-b740-984f0d365d40)
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/22523466/b3bd4120-dac4-4e5f-993e-239376c543d4)
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/22523466/04b2bb00-9886-4809-bcb9-9444f2b942e8)
Another thing we can glean from the fourth image (i.e. what the VRAM looks like after a second infusion) - the function that renders the HP boxes gets to the now unfused mon (Necrozma) then breaks. Does that give anyone here a clue as to what in particular is causing this?

**Comment by cfmnephrite** [comment]
Update: the problem is definitely `InitPartyMenuWindows()`

**Comment by Bassoonian** [comment]
#3644
