### ISSUE TITLE
Compile error when disabling debug menu

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#3615]
### Description

Found by @fdeblasio
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/2904965/6074ccdf-5e8f-4467-9720-3fcb32ca7979)

Solution: move `Debug_FlagsAndVarNotSetBattleConfigMessage(_Text)` outside of the `.if DEBUG_OVERWORLD_MENU == TRUE` block in `data/scripts/debug.inc

### Version

upcoming (Edge)

### Discord contact info

AsparagusEduardo

**Comment by Bassoonian** [comment]
Fixed by #3617
