### ISSUE TITLE
Regional Dex uses four-digit Pokédex numbers

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#3620]
### Description

The Regional Pokédex uses four-digit Pokédex numbers, even if the highest number is lower than 1000. It should use three-digit numbers accordingly, as is the case in e.g. the summary screen.

### Version

upcoming (Edge)

**Comment by Bassoonian** [comment]
That's what I meant with "it should behave like the summary screen" :)

**Comment by AsparagusEduardo** [comment]
> That's what I meant with "it should behave like the summary screen" :)

Whoops, misread ^^;

**Comment by leo60228** [comment]
Huh, I specifically remember *fixing* this issue before the PR was merged.... I'll have to look into this more.

**Comment by AsparagusEduardo** [comment]
> Huh, I specifically remember _fixing_ this issue before the PR was merged.... I'll have to look into this more.

I think there's 2 separate sections for the regional dex numbering when the National Dex is obtained vs when it's not and we only updated the one when it is. I need to confirm in-game.

**Comment by AsparagusEduardo** [comment]
Fixed in #3562 
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/2904965/f6463fbb-d47c-4c9c-9d68-abd6afdfda18)

**Comment by Bassoonian** [comment]
Fixed by #3655
