### ISSUE TITLE
Dynamic move types issue

### ISSUE THREAD

**Issue by kleeenexfeu** [rh-hideout/pokeemerald-expansion#3638]
### Description

https://github.com/rh-hideout/pokeemerald-expansion/blob/upcoming/src/battle_main.c#L5666-L5671

This should be done differently. Hidden power, Judgment and other move can actually change type based on ate abilities, provided they haven't change because of their effect. I.E using pixilate judgment should result in a 20% boost/fairy type attack.

Instead, the dynamic move type location should be checked directly, instead of the macro GET_MOVE_TYPE, to check is it hasn't been set, and then change it depending on the ability.

All this information comes from bulbapedia, and sometimes it's not accurate. So if someone has already tested this in the games and I'm wrong about all that, the issue can be closed.

here is the article https://bulbapedia.bulbagarden.net/wiki/Pixilate_(Ability)

Also it doesn't mention weather ball, for example, but I guess it should be the same

### Version

1.6.2 (Default)

**Comment by AlexOn1ine** [comment]
> Also it doesn't mention weather ball, for example, but I guess it should be the same

It's mentioned alongside Gardevoir. 

Though I assume this is generally all correct. 

> Instead, the dynamic move type location should be checked directly, instead of the macro GET_MOVE_TYPE, to check is it hasn't been set, and then change it depending on the ability.

`GET_MOVE_TYPE` should be fine to use, no? Since it also checks the dynamic move type.

**Comment by kleeenexfeu** [comment]
Actually yeah
Instead of "if (gBattleMoves[move].type == TYPE_NORMAL", just GET_MOVE_TYPE, then if the type is normal you can change it with -ate abilities. Provided the moves don't have a special treatment

**Comment by AlexOn1ine** [comment]
Either Bulbapedia or Showdown is lying again.
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/567c7ccb-c4f6-487d-9bdc-0d099e5c5bf0)
Would be nice if someone could test ingame.

**Comment by cfmnephrite** [comment]
> Either Bulbapedia or Showdown is lying again. ![image](https://private-user-images.githubusercontent.com/93446519/288518218-567c7ccb-c4f6-487d-9bdc-0d099e5c5bf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MDU4ODIsIm5iZiI6MTcwMTkwNTU4MiwicGF0aCI6Ii85MzQ0NjUxOS8yODg1MTgyMTgtNTY3YzdjY2ItYzRmNi00ODdkLTliZGMtMGQwOTllNWM1YmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDIzMzMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NmQ2NWQ1ZWY1MGQxNWUwMWVmMmMwODczNzQxOWZjNjQ3ZWMxZjc1NzcyNTU3NTkxMzJlNTJhMWM0NDk5MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._PC2wfk1ULFJaSGRC5ojT8qw5n-YF0VNT-lcbUnjn4s) Would be nice if someone could test ingame.

[What's the lie?](https://bulbapedia.bulbagarden.net/wiki/Weather_Ball_(move)#Generation_V_onwards)
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/22523466/55a6b6f0-7f1b-42e7-845b-18c306a3cde5)

**Comment by AlexOn1ine** [comment]
> > Either Bulbapedia or Showdown is lying again. ![image](https://private-user-images.githubusercontent.com/93446519/288518218-567c7ccb-c4f6-487d-9bdc-0d099e5c5bf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MDU4ODIsIm5iZiI6MTcwMTkwNTU4MiwicGF0aCI6Ii85MzQ0NjUxOS8yODg1MTgyMTgtNTY3YzdjY2ItYzRmNi00ODdkLTliZGMtMGQwOTllNWM1YmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDIzMzMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NmQ2NWQ1ZWY1MGQxNWUwMWVmMmMwODczNzQxOWZjNjQ3ZWMxZjc1NzcyNTU3NTkxMzJlNTJhMWM0NDk5MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._PC2wfk1ULFJaSGRC5ojT8qw5n-YF0VNT-lcbUnjn4s) Would be nice if someone could test ingame.
> 
> [What's the lie?](https://bulbapedia.bulbagarden.net/wiki/Weather_Ball_(move)#Generation_V_onwards) ![image](https://private-user-images.githubusercontent.com/22523466/288577142-55a6b6f0-7f1b-42e7-845b-18c306a3cde5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MDcyNTcsIm5iZiI6MTcwMTkwNjk1NywicGF0aCI6Ii8yMjUyMzQ2Ni8yODg1NzcxNDItNTVhNmI2ZjAtN2YxYi00MmU3LTg0NWItMThjMzA2YTNjZGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDIzNTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjOTdlOTkxYjQyNmNhYzZjYzY1OWI2YmYwNjgzNzYyOGU2OTkxNDE2ZjIwMGYzZjgwNDczZWRiMDRiNWM4YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bjhCBM683ezO9UfO4tNvuVLeFAIHErGfe5ftjFIYANU)
> 
> EDIT: Oh, wait, I see what you mean, if you open the page on each ability and check the lists of supported moves, they each say Judgment. Galvanize and Aerilate also say Weather Ball... Then again, they also say Hidden Power so that's confusing.

I think Bulbapedia messed up here. They were just lazy and copied the whole list without checking. Individual pages seem correct.

**Comment by cfmnephrite** [comment]
> > > Either Bulbapedia or Showdown is lying again. ![image](https://private-user-images.githubusercontent.com/93446519/288518218-567c7ccb-c4f6-487d-9bdc-0d099e5c5bf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MDU4ODIsIm5iZiI6MTcwMTkwNTU4MiwicGF0aCI6Ii85MzQ0NjUxOS8yODg1MTgyMTgtNTY3YzdjY2ItYzRmNi00ODdkLTliZGMtMGQwOTllNWM1YmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDIzMzMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NmQ2NWQ1ZWY1MGQxNWUwMWVmMmMwODczNzQxOWZjNjQ3ZWMxZjc1NzcyNTU3NTkxMzJlNTJhMWM0NDk5MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._PC2wfk1ULFJaSGRC5ojT8qw5n-YF0VNT-lcbUnjn4s) Would be nice if someone could test ingame.
> > 
> > 
> > [What's the lie?](https://bulbapedia.bulbagarden.net/wiki/Weather_Ball_(move)#Generation_V_onwards) ![image](https://private-user-images.githubusercontent.com/22523466/288577142-55a6b6f0-7f1b-42e7-845b-18c306a3cde5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MDcyNTcsIm5iZiI6MTcwMTkwNjk1NywicGF0aCI6Ii8yMjUyMzQ2Ni8yODg1NzcxNDItNTVhNmI2ZjAtN2YxYi00MmU3LTg0NWItMThjMzA2YTNjZGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDIzNTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjOTdlOTkxYjQyNmNhYzZjYzY1OWI2YmYwNjgzNzYyOGU2OTkxNDE2ZjIwMGYzZjgwNDczZWRiMDRiNWM4YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bjhCBM683ezO9UfO4tNvuVLeFAIHErGfe5ftjFIYANU)
> > EDIT: Oh, wait, I see what you mean, if you open the page on each ability and check the lists of supported moves, they each say Judgment. Galvanize and Aerilate also say Weather Ball... Then again, they also say Hidden Power so that's confusing.
> 
> I think Bulbapedia messed up here. They were just lazy and copied the whole list without checking. Individual pages seem correct.

If that's the case, then Galvanize works on Weather Ball but Pixilate doesn't??

**Comment by AlexOn1ine** [comment]
> > > > Either Bulbapedia or Showdown is lying again. ![image](https://private-user-images.githubusercontent.com/93446519/288518218-567c7ccb-c4f6-487d-9bdc-0d099e5c5bf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MDU4ODIsIm5iZiI6MTcwMTkwNTU4MiwicGF0aCI6Ii85MzQ0NjUxOS8yODg1MTgyMTgtNTY3YzdjY2ItYzRmNi00ODdkLTliZGMtMGQwOTllNWM1YmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDIzMzMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NmQ2NWQ1ZWY1MGQxNWUwMWVmMmMwODczNzQxOWZjNjQ3ZWMxZjc1NzcyNTU3NTkxMzJlNTJhMWM0NDk5MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._PC2wfk1ULFJaSGRC5ojT8qw5n-YF0VNT-lcbUnjn4s) Would be nice if someone could test ingame.
> > > 
> > > 
> > > [What's the lie?](https://bulbapedia.bulbagarden.net/wiki/Weather_Ball_(move)#Generation_V_onwards) ![image](https://private-user-images.githubusercontent.com/22523466/288577142-55a6b6f0-7f1b-42e7-845b-18c306a3cde5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MDcyNTcsIm5iZiI6MTcwMTkwNjk1NywicGF0aCI6Ii8yMjUyMzQ2Ni8yODg1NzcxNDItNTVhNmI2ZjAtN2YxYi00MmU3LTg0NWItMThjMzA2YTNjZGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDIzNTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjOTdlOTkxYjQyNmNhYzZjYzY1OWI2YmYwNjgzNzYyOGU2OTkxNDE2ZjIwMGYzZjgwNDczZWRiMDRiNWM4YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bjhCBM683ezO9UfO4tNvuVLeFAIHErGfe5ftjFIYANU)
> > > EDIT: Oh, wait, I see what you mean, if you open the page on each ability and check the lists of supported moves, they each say Judgment. Galvanize and Aerilate also say Weather Ball... Then again, they also say Hidden Power so that's confusing.
> > 
> > 
> > I think Bulbapedia messed up here. They were just lazy and copied the whole list without checking. Individual pages seem correct.
> 
> If that's the case, then Galvanize works on Weather Ball but Pixilate doesn't??

Idk, In the bulba screenshot it says Galvanize doesn't work

**Comment by AlexOn1ine** [comment]
> Like I said, if you open each ability's page, some of them claim Weather Ball works. I'm disinclined to believe them but it's still a little confusing.

Would be good if someone just tests this in gen7.

**Comment by cfmnephrite** [comment]
I feel like the onus is on whoever opened the issue to check that there even was an issue in the first place...

**Comment by AlexOn1ine** [comment]
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/cf6f079d-f338-46fe-89fe-ddc57b810e5f)

![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/092afdd5-e09f-4bab-a08f-1016593db64d)
