### ISSUE TITLE
Egg Moves need a refactor

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#3653]
### Description

See #3562 

### Version

upcoming (Edge)

**Comment by cfmnephrite** [comment]
How would you do this without adding a `prevo` field to `SpeciesInfo`?

**Comment by mrgriffin** [comment]
> How would you do this without adding a `prevo` field to `SpeciesInfo`?

I think we could at least split `gEggMoves` up into separate arrays, and also write the individual arrays as literals in the species_info header files (similar to `evolutions` etc etc)?

`gEggMoves` is absolutely horrifying, a single array that intermingles species IDs (offset by `20000`) with move IDs.

**Comment by cfmnephrite** [comment]
> > How would you do this without adding a `prevo` field to `SpeciesInfo`?
> 
> I think we could at least split `gEggMoves` up into separate arrays, and also write the individual arrays as literals in the species_info header files (similar to `evolutions` etc etc)?
> 
> `gEggMoves` is absolutely horrifying, a single array that intermingles species IDs (offset by `20000`) with move IDs.

Sorry, I was half asleep when I wrote that comment  and I realise it makes no sense. I took adding egg moves as a compound literal as a given. I was trying to ask if we would also add the field as part of an egg moves reform - for an easy way to retrieve them - or stick to using the old function for calculating prevos by iterating over literally every species.

**Comment by AsparagusEduardo** [comment]
#4534
