### ISSUE TITLE
pokemon_icon.c needs a commented out icon table to preserve PoryMap support

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#3663]
### Description

Technically not an expansion issue but a PoryMap one, but we should try to get a config pushed into PoryMap so we can remove this relic (because it will confuse people, I can guarantee you that)

### Version

upcoming (Edge)

**Comment by Jaizu** [comment]
This will get fixed with next porymap release

**Comment by AlexOn1ine** [comment]
#3896
