### ISSUE TITLE
Destiny Bond + Explosion causes a visual bug

### ISSUE THREAD

**Issue by TheLastMudkip** [rh-hideout/pokeemerald-expansion#3677]
### Description

If you kill a mon using destiny bond with explosion the explosion mon dies twice and then the game hangs

Repro step:
Use destiny bond with the faster mon. Then have the opposing slower mon use explosion. The Hp Bar of the explosion mon will drop 2 times then the game will hang.

### Version

1.6.2 (Default)

### Discord contact info

thelastmudkip

**Comment by AlexOn1ine** [comment]
Wrote a test but couldn't find the issue for now because it seems like Explosion removes `HITMARKER_DESTINYBOND` so Idk for now. 
```
SINGLE_BATTLE_TEST("Explosion does not trigger Destiny Bond")
{
    GIVEN {
        PLAYER(SPECIES_WOBBUFFET) { HP(1); };
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_DESTINY_BOND); MOVE(opponent, MOVE_EXPLOSION);}
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_DESTINY_BOND, player);
        HP_BAR(opponent);
        ANIMATION(ANIM_TYPE_MOVE, MOVE_EXPLOSION, opponent);
        HP_BAR(player);
        NOT HP_BAR(opponent);
    }
}
```

**Comment by DizzyEggg** [comment]
Are you sure the game hangs? I got the hp bar dropping 2 times, but without hanging.

**Comment by TheLastMudkip** [comment]
I can no longer repo the hang either. Looks like it may be fine now.
