### ISSUE TITLE
Telekensis is not applying lock on effect

### ISSUE THREAD

**Issue by TheLastMudkip** [rh-hideout/pokeemerald-expansion#3679]
### Description

Telekenesis is currently only functioning as magnet rise for the target. Telekinesis should also make it so moves with an accuracy check cannot miss the target.

### Version

1.6.2 (Default)

### Discord contact info

thelastmudkip

**Comment by kleeenexfeu** [comment]
To be a little more accurate, telekinesis shouldn't apply the lock on effect: the latter allows the target to be hit in a semi invulnerable state (fly, dig..), while a flying telekinesis-ed pokemon wouldn't be hit during fly under otherwise normal conditions.

**Comment by DizzyEggg** [comment]
@TheLastMudkip Could you add an example in a battle(which move in particular) scenario, so it's easier for us to check the issue?
