### ISSUE TITLE
Frisk does not always target the correct target side of the field.

### ISSUE THREAD

**Issue by TheLastMudkip** [rh-hideout/pokeemerald-expansion#3681]
### Description

When Frisk is triggered on switch in it will use the mon opposite of it's ability in the ability pop up and then show the items of the side of the mon whose ability is frisk.

![FriskBug](https://github.com/rh-hideout/pokeemerald-expansion/assets/124942719/abbad8e0-b803-4a24-aa59-d0fe6cd3b874)
Here Typhlosion has the ability frisk and is holding an eject button. 
Swampert has torrent and is holding a life orb

### Version

1.6.2 (Default)

### Discord contact info

thelastmudkip

**Comment by AlexOn1ine** [comment]
Could you please provide some steps to reproduce this?

**Comment by TheLastMudkip** [comment]
For me it repos roughly 50% of the time. 
All you need to do is get into a trainer a battle where the opposing pokemon has held items. Switch out your mon and send in a mon with frisk. 
Not sure where the inconsistency is coming from. It seems like the battlers are getting swapped at some point but I have not really had time to dig into it yet.
