### ISSUE TITLE
Imprison is not updated to gen V mechanics

### ISSUE THREAD

**Issue by TheLastMudkip** [rh-hideout/pokeemerald-expansion#3682]
### Description

Starting in Gen 5 imprison should be usable even if no other mon has the same moves as the user. Additionally when imprison is used as long as the user is on the field no other mon should be able to use any moves known by the user.

Source: https://bulbapedia.bulbagarden.net/wiki/Imprison_(move)

### Version

1.6.2 (Default)

### Discord contact info

thelastmudkip

**Comment by Bassoonian** [comment]
Fixed by #3710
