### ISSUE TITLE
Ion Deluge triggers the users Lightning Rod/Volt Absorb

### ISSUE THREAD

**Issue by TheLastMudkip** [rh-hideout/pokeemerald-expansion#3683]
### Description

When a mon whose ability is Lightning Rod or Volt Absorb uses ion deluge their ability will suck in the move preventing it from activating.

For example if a volt absorb Lanturn uses ion deluge it will heal 25%.
What should happen is the ion deluge effect should be applied to the field that turn and all normal moves used after it will become electric type moves.

### Version

1.6.2 (Default)

### Discord contact info

thelastmudkip

**Comment by AlexOn1ine** [comment]
Could you test this one on upcoming please? Or do you have a save file so I can test it?

**Comment by AlexOn1ine** [comment]
The problem comes from `accuracycheck`, specifically when `AbilityBattleEffects` is called. I think battlers are mixed somewhere but I couldn't find the exact cause. Also tests aren't able to catch this.
