### ISSUE TITLE
gFusionTablePointers should include defines by families instead of by gens.

### ISSUE THREAD

**Issue by ivaantxo** [rh-hideout/pokeemerald-expansion#3691]
### Description

In src/data/pokemon/form_change_table_pointers.h, gFusionTablePointers is defined by P_GEN_X instead of by P_FAMILY_X, but a user might want a gen but not those specific Pokémon.

### Version

upcoming (Edge)

### Upcoming Version

ec9cc9a

### Discord contact info

Iván#7099

**Comment by AsparagusEduardo** [comment]
#3692
