### ISSUE TITLE
Update the "How to add a new Pokémon species" wiki tutorial

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#3693]
### Description

After all the changes made to species data, I think someone should take some time to update the [How to add a new Pokémon species](https://github.com/rh-hideout/pokeemerald-expansion/wiki/How-to-add-a-new-Pok%C3%A9mon-species) article, once all the changes are finally made.

### Version

upcoming (Edge)

### Upcoming Version

The latest one, lel.

### Discord contact info

lunos4026

**Comment by Bassoonian** [comment]
Identical to #3765
