### ISSUE TITLE
Config for items of released Pokémon

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#3703]
### Description

As of Generation 8, releasing a Pokémon should move its held item to the bag. Need to test in a game what happens if the bag is full and can't hold its item.

**Comment by Bassoonian** [comment]
Not a bag limit, but I'm sure there's a limit to how many items you can hold, so attempting to release a Pokémon that holds an Oran Berry if you already have 999 or 9,999 (or whatever the limit is) Oran Berries in your bag should do something (or nothing at all, in which case we also have an answer to our question).

**Comment by AlexOn1ine** [comment]
#4577
