### ISSUE TITLE
Add missing Spirit Shackle/Anchor Shot tests

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#3715]
### Description

#3668 apparently fixed those move's effects but didn't add tests for them.

### Discord contact info

AsparagusEduardo

**Comment by AlexOn1ine** [comment]
Unless I'm missing something, I don't think writing a valid test for those moves is possible.

**Comment by AsparagusEduardo** [comment]
Oh, my bad
