### ISSUE TITLE
EVO_TRADE_SPECIFIC_MON (Karrablast / Shelmet Evolution Method) Non-functional

### ISSUE THREAD

**Issue by katykat5099** [rh-hideout/pokeemerald-expansion#3756]
### Description

The trade evolution method for Shelmet and Karrablast currently does not work.
Discovered simply by trying to make a in-game trade for this evolution method.
I also went to test with link cable trading as well, also does not work there.

### Version

upcoming (Edge)

### Upcoming Version

d79fe11bb1cae8ae1abbe55fd019171c290a95fa

### Discord contact info

kakarikiki

**Comment by DizzyEggg** [comment]
Are you sure this occurs on clean master/upcoming? I just checked an in-game trade and the pokemon evolved.

**Comment by katykat5099** [comment]
Issue on my end, mb
