### ISSUE TITLE
Tandemaus evolution method is incorrect

### ISSUE THREAD

**Issue by kittenchilly** [rh-hideout/pokeemerald-expansion#3760]
### Description

Currently we have it so it can evolve through any source of level up. Tandemaus should only evolve through a level up in battle.
We should also add the mechanic where it evolves without playing the evolution animation if leveled up without having been switched in (would really only apply with gen 6 exp share).
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/23617175/04de49d3-5081-4310-9349-8bc87d0a2ca9)

### Version

1.7.0 (Default)

### Discord contact info

kittenchilly

**Comment by AlexOn1ine** [comment]
#4759

**Comment by Bassoonian** [comment]
Not true, that PR only partially fixes this (as it says in the description)

**Comment by FosterProgramming** [comment]
Should this still be classified as bug?

**Comment by AlexOn1ine** [comment]
> Should this still be classified as bug?

yes, it's incorrect behavior. Even if a bug needs a wide range refactor, it's still a bug.

**Comment by AlexOn1ine** [comment]
Or Ig I don't know. It's probably more of a feature request since there is no actual behavior
