### ISSUE TITLE
Update the wiki article for adding new species

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#3765]
### Description

Leftover stuff that I forgot to do ^^;

https://github.com/rh-hideout/pokeemerald-expansion/wiki/How-to-add-a-new-Pok%C3%A9mon-species

### Version

1.7.0 (Default)

### Discord contact info

AsparagusEduardo

**Comment by Bassoonian** [comment]
Fixed (see [this wiki page](https://github.com/rh-hideout/pokeemerald-expansion/wiki/How-to-add-a-new-Pok%C3%A9mon-species-(Version-1.8.x)))
