### ISSUE TITLE
ALWAYS_CRIT is misleading

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#3771]
### Description

Gens 2-5 don't guaranteee that a critical hit always happens if the ratio is 3.
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/2904965/9f8cba54-071b-45ba-a02f-14facb64c4b5)
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/2904965/d12f74b3-349f-46e1-b59c-7e99225de6c0)

The use of that define should be reverted.

### Version

1.7.0 (Default)

### Discord contact info

AsparagusEduardo

**Comment by AlexOn1ine** [comment]
Should the define be just removed?

**Comment by AlexOn1ine** [comment]
> Not only that, but a flag should be added to replace the `EFFECT_ALWAYS_CRIT` effect, something like `criticalHitAlways`

Oh, now I see what you mean.

**Comment by Bassoonian** [comment]
Fixed by #3779
