### ISSUE TITLE
Egg lacking egg textures

### ISSUE THREAD

**Issue by katykat5099** [rh-hideout/pokeemerald-expansion#3775]
### Description

Eggs dont appear to have a texture
![DecamarkEgg](https://github.com/rh-hideout/pokeemerald-expansion/assets/12654608/d1b95759-8c82-4942-8968-f566c396ddf9)

### Version

upcoming (Edge)

### Upcoming Version

13a4bf5838ec7cf1472fba9d197a09d5f7c64c24

### Discord contact info

kakarikiki

**Comment by katykat5099** [comment]
Alright after some more testing, the egg actually IS hatchable.
I guess the egg textures must just be incorrect, then?

**Comment by AsparagusEduardo** [comment]
This should've been a priority bugfix 😬

**Comment by Bassoonian** [comment]
Fixed by #3879
