### ISSUE TITLE
Quick ball selector allows user to use a TM instead of a ball

### ISSUE THREAD

**Issue by Ninjdai1** [rh-hideout/pokeemerald-expansion#3790]
### Description

(also works on latest upcoming as of this issue's creation)
Quickly switching between the first and last ball in the quick ball selector allows the user to pick the first TM in the TM bag.
Using it launches a default pokeball but consumes the TM

Both ball and tm bag need to be full (tested using debug menu's give balls/tms)

![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/65647523/370f42b0-0bbf-489c-a8ea-c9c78a572d05)
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/65647523/26aa890a-2228-4d31-ad9a-2324f296f223)
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/65647523/44fb5dcf-bf0a-4040-80a1-8e1d661e01fd)
![bug](https://github.com/rh-hideout/pokeemerald-expansion/assets/65647523/826e4ad9-e46e-4f81-8682-1bdcef1754af)

### Version

1.7.0 (Default)

### Discord contact info

@ninjdai

**Comment by LOuroboros** [comment]
I managed to reproduce this on my end specifically after having used the debug menu's Fill Pocket features to obtain Poké Balls and TMs.

**Comment by Ninjdai1** [comment]
Using the selected tm consumes it, but the bug still occurs after it is used, but the displayed tm is the next one in bag

**Comment by AaghatIsLive** [comment]
> I managed to reproduce this on my end specifically after having used the debug menu's Fill Pocket features to obtain Poké Balls and TMs.
> 
> ![image](https://media.discordapp.net/attachments/1077168246555430962/1187524986655735898/mGBA_20231221_194010660.gif)

Can confirm that this happens even without the use of debug menu
