### ISSUE TITLE
Item Use targets incorrectly (most prominent in double battles)

### ISSUE THREAD

**Issue by katykat5099** [rh-hideout/pokeemerald-expansion#3794]
### Description

Items used sometimes are not used correctly. Some examples:

- Using persim berry on confused pokemon
- Potions used on slot 1 pokemon on slot 2's turn
- Using Paralyze heal on confused pokemon cures it (works in general..)

**Reproduce:**
The easiest way to reproduce this issue is in double battles, go into a double battle, have your pokemon in slot 1 be damaged and try to heal it with a potion using the slot 2 pokemon's turn.

Use debug or enemy moves to confuse / status players pokemon

Potion:
![PotionIncorrectHeal](https://github.com/rh-hideout/pokeemerald-expansion/assets/12654608/f610d3cc-2bdf-4f81-914c-643e75a90e07)

Berry:
![ConfuseHealBug](https://github.com/rh-hideout/pokeemerald-expansion/assets/12654608/af462bde-6cb4-4cad-898e-fd2904c9b5c8)

### Version

1.7.0 (Default)

### Upcoming Version

96cb4d382311e1a127549d5ee30f72a7c33bc669

### Discord contact info

kakarikiki

**Comment by Ninjdai1** [comment]
Can confirm on upcoming
As of my testing, it would seem like the selected item is used on the mon which move was used, and not on the actual target

**Comment by MandL27** [comment]
Can confirm ninjdai's observations. Additionally, in doubles, using an item on mon 2 during mon 1's turn will make it be used on mon 1, though the text still says the correct mon.
This affects the entire useitem script, too, not just the effect. For an upcoming PR I was adding an animation to both UseItemMessage and ItemRestoreHP, and both of those played on the wrong mon.
