### ISSUE TITLE
Metronome potentially rolls invalid moves + causes freeze

### ISSUE THREAD

**Issue by katykat5099** [rh-hideout/pokeemerald-expansion#3804]
### Description

Metronome appears to be able to roll a invalid move which causes some issues and a game crash.

### Version

1.7.0 (Default)

### Upcoming Version

3a5ca6f8f0b4fd345cf134a04b37361f8f2f776f

### Discord contact info

kakarikiki

**Comment by AlexOn1ine** [comment]
This issue is that invalid are currently in the expansion 
```
#define MOVE_833 833
#define MOVE_834 834
#define MOVE_835 835
#define MOVE_836 836
#define MOVE_837 837
#define MOVE_838 838
#define MOVE_839 839
#define MOVE_840 840
#define MOVE_841 841
#define MOVE_842 842
#define MOVE_843 843
#define MOVE_844 844
#define MOVE_845 845
#define MOVE_846 846
#define MOVE_847 847
```
This will be resolved in a couple of days automatically once all the data is added. 
There was also a discussion about max moves but they will never be called by Metronome because they come after `MOVES_COUNT_GEN9`

**Comment by AlexOn1ine** [comment]
#3704
