### ISSUE TITLE
Maushold 3 and 4 icons switched

### ISSUE THREAD

**Issue by MartyKen** [rh-hideout/pokeemerald-expansion#3810]
### Description

![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/73791756/3acaf9ea-f15c-42b7-8200-27a877421be3)
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/73791756/b52cc340-340c-4b77-9f82-3c23477f80a5)
The icons for maushold 3 and 4 are switched.

### Version

1.7.0 (Default)

**Comment by AlexOn1ine** [comment]
#3809
