### ISSUE TITLE
Graphical issue after successive Ally Switch uses 

### ISSUE THREAD

**Issue by ghoulslash** [rh-hideout/pokeemerald-expansion#3816]
### Description

![ally_switch](https://github.com/rh-hideout/pokeemerald-expansion/assets/41651341/1c1663a2-7fb2-4059-b1bc-c4d53c2a1c6d)

After using ally switch the 2nd time or more, there are a few frames where the old battler sprites appear

The first issue is that the underground sprite shouldnt be cloned. The second issue is the dig user uses MOVE_NONE. This is easily fixed by swapping `gLockedMoves`

**Comment by DizzyEggg** [comment]
I wonder if #3540 would fix it 🤔

**Comment by ghoulslash** [comment]
> I wonder if #3540 would fix it 🤔 

Actually it does appear to have :)

**Comment by DizzyEggg** [comment]
But wait @ghoulslash #3540 was not merged :D

**Comment by ghoulslash** [comment]
> But wait @ghoulslash #3540 was not merged :D 

Oh I had assumed that was the last ally switch fix PR, which seems to have fixed the problem haha
