### ISSUE TITLE
Neutralizing Gas / Intrepid Sword interaction causes a game loop / freeze

### ISSUE THREAD

**Issue by AlexOn1ine** [rh-hideout/pokeemerald-expansion#3820]
### Description

When you switch out a mon with Neutralizing Gas, Intrepid Sword is activated as it should but then the ability user is switched out into a bad egg. I haven't tested it in-game but I imagine the same interaction will happen. 

https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/895195e0-9628-408a-b7a0-9357d704889e

Test in #3821

### Version

1.7.0 (Default)

**Comment by Bassoonian** [comment]
Fixed by #3821
