### ISSUE TITLE
Ally Switch + Semi Invulnerable Partner is buggy

### ISSUE THREAD

**Issue by ghoulslash** [rh-hideout/pokeemerald-expansion#3827]
### Description

When using Ally Switch and your ally is mid turn with e.g. Dig, there are graphical and functional issues
![ally_switch_dig](https://github.com/rh-hideout/pokeemerald-expansion/assets/41651341/a115ddab-0dfb-44be-a60d-3dce314d5cdf)

### Version

1.7.0 (Default)

**Comment by Bassoonian** [comment]
Fixed by #3835
