### ISSUE TITLE
Colored nature stats are based on original nature, even if a mint is used

### ISSUE THREAD

**Issue by fdeblasio** [rh-hideout/pokeemerald-expansion#3833]
### Description

When a Mint is used on a Pokemon, the colored stats are still based on its original nature, not its hidden nature due to natureMod using the nature modifiers of the original nature
`const s8 *natureMod = gNatureStatTable[sMonSummaryScreen->summary.nature];`

### Version

upcoming (Edge)

### Discord contact info

Frankfurter0

**Comment by Bassoonian** [comment]
Fixed by #3898
