### ISSUE TITLE
Type icons next to battle bars

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#3914]
### Description

With a config of course. Popular CFRU feature.

**Comment by pkmnsnfrn** [comment]
https://github.com/PokemonSanFran/magm-8/commit/0e36c53d098730cca2dcd7af672588be9b746e24
https://github.com/PokemonSanFran/magm-8/commit/f345f580d6a0933efef98f8cebdbe8dfff8d4080

@Petuuuhhh has an implementation they started on and they have given permission to use it

**Comment by pkmnsnfrn** [comment]
https://github.com/rh-hideout/pokeemerald-expansion/pull/4910
