### ISSUE TITLE
Species that do not count towards the Pokédex should have a flag in SpeciesInfo instead of using a static array

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#3932]
### Description

Context: https://github.com/rh-hideout/pokeemerald-expansion/pull/3900#issuecomment-1876321511

ideally this would deprecate [sRegionalNotCountedList ](https://github.com/Bassoonian/pokeemerald-expansion/blob/0f078ead3077385b7c0c7599d214136cb49aff83/src/birch_pc.c#L24).

### Discord contact info

pkmnsnfrn

**Comment by LOuroboros** [comment]
Why add a flag to the Pokemon struct though? Is there a reason not to add it to SpeciesInfo instead?

Space in the Pokemon struct is super valuable imo, and that doesn't really feel like the right place for this anyway because it's not really a flag that you'd apply to each individual Pokémon, but a flag that should encompass the entire species.

**Comment by pkmnsnfrn** [comment]
> Why add a flag to the Pokemon struct though? Is there a reason not to add it to SpeciesInfo instead?
> 
> Space in the Pokemon struct is super valuable imo, and that doesn't really feel like the right place for this anyway because it's not really a flag that you'd apply to each individual Pokémon, but a flag that should encompass the entire species.

I misspoke, you're 100% right

**Comment by Bassoonian** [comment]
I'll figure this out tomorrow. Not a bugfix, so I assume that means it'd target upcoming? Or should we just push it to master so it can be in 1.7.2 since it deprecates something not currently in 1.7.1?

**Comment by AlexOn1ine** [comment]
> I'll figure this out tomorrow. Not a bugfix, so I assume that means it'd target upcoming? Or should we just push it to master so it can be in 1.7.2 since it deprecates something not currently in 1.7.1?

I would say master
