### ISSUE TITLE
FORM_CHANGE_BATTLE_SWITCH might be conflicting with Dynamax

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#3936]
Since it's called via returntoball which is called via Dynamax, it might be causing issues there. Haven't tested in-game.

This commit by @Pokabbie might fix it, though it might make more sense to invert the check and TRUE/FALSE uses: https://github.com/Pokabbie/pokeemerald-rogue/commit/023737c20898cdc71ea4a79cbe19f1a1325f61a1

Version
1.7.1 (Default)

Upcoming Version
No response

Discord contact info
AsparagusEduardo

**Comment by AsparagusEduardo** [comment]
Re-opened

**Comment by Pokabbie** [comment]
I haven't got a clean branch of Emerald Expansion locally so I'm unable to test but this issue was specifically Gigantamax forms weren't working as it would immediately attempt to revert the queued form change back to base form

**Comment by AsparagusEduardo** [comment]
Just confirmed that applying this fix fixes #4048 at least.

> I haven't got a clean branch of Emerald Expansion locally so I'm unable to test but this issue was specifically Gigantamax forms weren't working as it would immediately attempt to revert the queued form change back to base form

For some reason, the issue wasn't manifesting in a clean expansion until Gigantamax Factor was implemented.
I'll create a PR with your fix @Pokabbie (except with the boolean inverted) ^^;
