### ISSUE TITLE
Paldean Tauros has wrong base stats

### ISSUE THREAD

**Issue by SPMoo66** [rh-hideout/pokeemerald-expansion#3940]
### Description

All breeds of Paldean Tauros are currently using the same TAUROS_MISC_INFO define which contains the base form's stats, but the Paldean form is supposed to have different base stats.

### Version

1.7.1 (Default)

### Discord contact info

moo66

**Comment by kaicardenas2** [comment]
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/150625530/90f0ec74-4ee1-4e5b-8d7e-647c741eb233)
yeah slightly different
