### ISSUE TITLE
Item Balls with TMs inside are colored gold

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#3944]
### Description

[Original Discussion](https://discord.com/channels/419213663107416084/1193434690321911828/1193622930207293491)

Originally requested for https://github.com/rh-hideout/pokeemerald-expansion/pull/3942 but was out of scope

In Generations 5 or lower, [all Item Balls look the same.](https://youtu.be/y0vrLCPTfO8?list=PLezVRrFF7SXT8fUGMcOz11laIPSIQkmMy&t=93) 

Starting in Generation 6, [Item Balls with TMs or HMs are colored gold.](https://youtu.be/cddrCvDEIn4?list=PLezVRrFF7SXR8K29ljTws0vm2ZK7WjxPD&t=26)

Item Balls in expansion with TMs in them should turn gold (and be disabled via a config). This should probably wait until after Dynamic Overworld Palettes is merged.

### Discord contact info

pkmnsnfrn

**Comment by Bassoonian** [comment]
Closing this analogously to #3947
