### ISSUE TITLE
Config for double battles with one Pokémon

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#3951]
### Description

Add a config (or two!) for the following two features:

- [x] You can fight double battles (eg twins) with only one Pokémon in your party
- [x] You can be spotted by two trainers at the same time and engage in a 1v2 multi battle with only one Pokémon in your party

**Comment by AsparagusEduardo** [comment]
You can already do this, it's the scripts themselves that check for 2 mon,but if you remove that check, 1v2 battles are supported.

**Comment by AsparagusEduardo** [comment]
> You can already do this, it's the scripts themselves that check for 2 mon,but if you remove that check, 1v2 battles are supported.

I meant the first point, my bad.

**Comment by Bassoonian** [comment]
Fixed by #4007
