### ISSUE TITLE
Migration Scripts need a proper "home"

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#3952]
### Description

As we change more and more of Game Freak's systems, we should provide ways to allow users to gracefully migrate from old systems to new ones. These migration scripts should likely be stored in the repo itself, but the following needs to be answered:

## Questions
1. Where in the repo should we store these?
2. How do we make users aware they exist?
3. What qualifies to go into this directory?

## Examples

- https://github.com/rh-hideout/pokeemerald-expansion/pull/3545/files#diff-711dacf9fe445b7fa2c824f53e32318f3534f6fdb0872d38797d7ed5dd570922
- https://github.com/rh-hideout/pokeemerald-expansion/blob/f7bf1f4e320ce00d3434f337aaf796b2489e6ced/item_ball_refactor_helper.py

### Version

upcoming (Edge)

### Discord contact info

pkmnsnfrn

**Comment by AlexOn1ine** [comment]
#3997
