### ISSUE TITLE
HGSS Pokédex duplicate sprites after using "Search"

### ISSUE THREAD

**Issue by resetes12** [rh-hideout/pokeemerald-expansion#3960]
### Description

https://github.com/rh-hideout/pokeemerald-expansion/assets/67122715/c7c8aaf3-1191-4721-972e-c0a6f80bb2d8

It's a bit difficult to explain, so here's a video. Basically, after using the "search" function of the HGSS Pokédex, checking a Pokémon with an evolution, navigating to "Evos", entering any of the evolutions, and then going back to the search results creates a duplicate sprite of the second dex entry you entered.

### Version

1.7.1 (Default)

### Discord contact info

restes

**Comment by hedara90** [comment]
Confirmed still an issue on 1.8.5.
How to reproduce.

1. Enable HGSS pokedex
2. Search for "Name" with "ABC"
3. Enter the pokedex page for Charmeleon
4. Go to Evolution page
5. Click on Charizard
6. Press the B button to go back to the search results
7. The Charmeleon sprite is now replaced with the Charizard sprite

I assume that the sprite you entered the species pokedex page from is replaced with the species you exited the pokedex page from.
