### ISSUE TITLE
Sandaconda Gigantamax form is missing description

### ISSUE THREAD

**Issue by SPMoo66** [rh-hideout/pokeemerald-expansion#3963]
### Description

Sandaconda's Gigantamax form has no description and the comma is bumped down to the next line
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/17258424/f7314749-b4f2-4d79-aed5-4701a1575ae9)

### Version

1.7.1 (Default)

### Discord contact info

moo66

**Comment by AsparagusEduardo** [comment]
#3972
