### ISSUE TITLE
The Battle Tower's multi battles are broken

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#3966]
### Description

Basically, title. You can lose a multi battle out of nowhere and just because. Don't ask me why.

I found this during my tests for a move name and description refactor I'm working on, so I switched to a clean copy of upcoming, `git pull`ed to update it, `make mostlyclean` and then built a new ROM to see if it was still happening, and effectively, it is.

![mGBA_20240111_001517414](https://github.com/rh-hideout/pokeemerald-expansion/assets/4485172/1d99ecb5-6884-406a-b227-643e5bdfb0f6)

### Version

upcoming (Edge)

### Upcoming Version

5b5b9e7e5099ffd2c3aae1df5109fb8671af24bb

### Discord contact info

lunos4026

**Comment by Bassoonian** [comment]
I just did some additional testing, this occurs whenever you defeat either of the two opposing Pokémon. I'll try to bisect and find when this bug manifested

**Comment by Bassoonian** [comment]
This has been broken since at least 1.4. I can't manage to build 1.3 anymore (maybe because M1 support didn't yet exist at this time? who knows), so if anyone would be open to dig a bit further and look for the commit that caused it, that'd be great!

**Comment by LOuroboros** [comment]
57c929275ffb965ddae94b20ee88485f1122312a aka v0.9.0 still has the bug.

![](https://media.discordapp.net/attachments/774393519569502268/1194967705950896179/mGBA_20240111_083425248.gif)

The first commit submitted in 2022 does not have the issue though.

![](https://cdn.discordapp.com/attachments/774393519569502268/1194972457036161125/mGBA_20240111_085319110.gif)

In other words, the issue was introduced between January 9, 2022 and the date in which the v0.9.0 was released *(September 2022, but its commit signature is from Aug 29, 2022.)*

**Comment by Bassoonian** [comment]
The offending function is `NoAliveMonsForPlayerAndPartner`, which consistently returns 0 because `if (gBattleTypeFlags & BATTLE_TYPE_INGAME_PARTNER && gPartnerTrainerId > TRAINER_PARTNER(PARTNER_NONE))` is not passing, even when in a multi battle. Removing this condition renders the function identical to `NoAliveMonsForPlayer`, which is also very peculiar, so a thorough review and possible rewrite is in order here.

**Comment by LOuroboros** [comment]
I think a fix should be pushed to address the issue for the time being.

This ticket can be kept open in the meantime.

The problem here is caused by asking the code to check for preset trainer partner party data, but since the Battle Tower's partners are generated on the fly, they don't really have a valid partner trainer Id.

```diff
diff --git a/src/battle_script_commands.c b/src/battle_script_commands.c
index dd84a15d4..f38bd6d28 100644
--- a/src/battle_script_commands.c
+++ b/src/battle_script_commands.c
@@ -4501,7 +4501,7 @@ static bool32 NoAliveMonsForPlayerAndPartner(void)
     u32 i;
     u32 HP_count = 0;

-    if (gBattleTypeFlags & BATTLE_TYPE_INGAME_PARTNER && gPartnerTrainerId > TRAINER_PARTNER(PARTNER_NONE))
+    if (gBattleTypeFlags & BATTLE_TYPE_INGAME_PARTNER)
     {
         for (i = 0; i < PARTY_SIZE; i++)
         {
```

An alternative would be to assign a value for Battle Frontier-like trainer partners, which may be more desirable.

**Comment by ShinyDragonHunter** [comment]
`if (gBattleTypeFlags & BATTLE_TYPE_INGAME_PARTNER && gPartnerTrainerId > TRAINER_PARTNER(PARTNER_NONE))` should only pass if it's a non-tower partner. Each possible partner has its own ID, that's what `gPartnerTrainerId` is. And if I'm understanding it correctly, IDs 0-299 are tower partners which can also be used for opponent frontier trainers

**Comment by LOuroboros** [comment]
> `if (gBattleTypeFlags & BATTLE_TYPE_INGAME_PARTNER && gPartnerTrainerId > TRAINER_PARTNER(PARTNER_NONE))` should only pass if it's a non-tower partner.

That's a problem, because the function is executed through `Cmd_checkteamslost` which is a battle script command function, and surely the Battle Tower runs that through certain battle scripts when the conditions are met, just like any type of battle does. It's called for weather damage, it's called for Future Sight, it's called for poison damage, it's called when a Pokémon faints, etc, etc.

Jasper said on Discord that they have an idea to deal with things and they'll look into it tomorrow fwiw.
