### ISSUE TITLE
Upcoming/1.8.0 will need a pokeemerald-extension specific variant of the Adding a new move tutorial

### ISSUE THREAD

**Issue by GraionDilach** [rh-hideout/pokeemerald-expansion#3985]
### Description

This is to explain the significance of EFFECT vs MOVE_EFFECT and the primary vs secondary differences.

### Version

upcoming (Edge)

### Upcoming Version

ff0aed31b3bd5c09ca2db5884a5d2ab9c53d0074

### Discord contact info

GraionDilach

**Comment by AsparagusEduardo** [comment]
Done in: https://github.com/rh-hideout/pokeemerald-expansion/wiki/How-to-add-a-new-move-(Version-1.8.0-and-higher)
