### ISSUE TITLE
Deprecate GetBerryCountString

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#4010]
### Description

Originally mentioned here: https://github.com/rh-hideout/pokeemerald-expansion/pull/4001#discussion_r1453578315

We should deprecate `GetBerryCountString` in favor of `CopyItemNameHandlePlural` (or something similar).

### Discord contact info

pkmnsnfrn

**Comment by AlexOn1ine** [comment]
#4012
