### ISSUE TITLE
Glimmering Charm has a broken palette

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#4011]
### Description

title

### Version

1.7.1 (Default)

**Comment by AsparagusEduardo** [comment]
I don't know, It looked good enough to me when I approved it 👀 
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/2904965/e9adaae9-e11e-401a-a043-8d2ef5959a09)
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/2904965/3215cf1e-796b-4903-b934-f9b5fe2296c7)

Maybe it's missing black outlines?
