### ISSUE TITLE
Add item space checks after every item (notably key items)

### ISSUE THREAD

**Issue by fakuzatsu** [rh-hideout/pokeemerald-expansion#4019]
### Description

This ensures if any changes are made to the items in the future, there will be no further issues. See #3978

### Version

1.7.2 (Latest release)

### Discord contact info

Zatsoo

**Comment by AlexOn1ine** [comment]
How do you fix that? A lot of items are tied to the story and you get them in the middle and often times you get them in the middle of a conversation.
