### ISSUE TITLE
Protective Pads + Fluffy Interaction Bug

### ISSUE THREAD

**Issue by TerraPrograms** [rh-hideout/pokeemerald-expansion#4034]
### Description

Protective Pads ignores Fluffy when it shouldn't.

### Version

1.7.2 (Latest release)

### Upcoming/master Version

58102e6

### Discord contact info

._.terra._.

**Comment by AsparagusEduardo** [comment]
Source?

**Comment by AlexOn1ine** [comment]
> Source?

Afaik Protective Pads doesn't turn contact moves into non contact moves. I believe the way it's implemented in expansion is incorrect

**Comment by AsparagusEduardo** [comment]
> Afaik Protective Pads doesn't turn contact moves into non contact moves. I believe the way it's implemented in expansion is incorrect, Protective Pads I mean. In expansion it turns contact moves into non contact moves. [It just removes negative effects cause by contact ](https://bulbapedia.bulbagarden.net/wiki/Protective_Pads)

Aaah, that makes sense.
