### ISSUE TITLE
Corrosion Bug

### ISSUE THREAD

**Issue by TerraPrograms** [rh-hideout/pokeemerald-expansion#4035]
### Description

Corrosion doesn't work on damaging moves with poison chance against Poison-types.

### Version

1.7.2 (Latest release)

### Upcoming/master Version

58102e6

### Discord contact info

._.terra._.

**Comment by ZnogyroP** [comment]
This is the canon behaviour of the ability.

**Comment by Bassoonian** [comment]
After a discussion on Discord, this does indeed appear to be a bug.
