### ISSUE TITLE
Gigantamax isn't changing a Pokémon's form

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#4048]
### Description

I have a Charizard with the Gigantamax Factor enabled that knows Flamethrower, the Dynamax Band in the bag and the dynamax battle flag toggled ON, and yet, when my Charizard uses G-Max Wildfire it's not transforming into G-Max Charizard.

![](https://media.discordapp.net/attachments/774393519569502268/1198912957678112798/mGBA_20240122_055121485.gif)

***Note**: the 1 and the 0 on the 3rd debug script are me confirming whether the Gigantamax Factor was enabled or not by storing the result of `GetMonData(&gPlayerParty[gSpecialVar_0x8004], MON_DATA_GIGANTAMAX_FACTOR);` in a text buffer. 1=TRUE, 0=FALSE.*

### Version

upcoming (Edge)

### Upcoming/master Version

7ba3f53d423f61c701226185039859626e65426d

### Discord contact info

lunos4026

**Comment by AsparagusEduardo** [comment]
#4108
