### ISSUE TITLE
PLA's Aux Items are missing sprites

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#4059]
### Description

Title

### Version

upcoming (Edge)

**Comment by AlexOn1ine** [comment]
Missing sprite label?

**Comment by Bassoonian** [comment]
I'd just widen the scope to graphical bugs, because then we can classify all the wrong palette and sprite error issues there too

**Comment by AlexOn1ine** [comment]
> I'd just widen the scope to graphical bugs, because then we can classify all the wrong palette and sprite error issues there too

agree

**Comment by Bassoonian** [comment]
Fixed by #4160
