### ISSUE TITLE
Metric conversion config option.

### ISSUE THREAD

**Issue by OnlyNeedJuan** [rh-hideout/pokeemerald-expansion#4073]
### Description

The option to toggle stuff like the pokedex entries from Imperial units to Metric units and Metric use of the comma as a separator would be a great option to have in config.h. There already are some defines for that sorta thing, but you can't really do anything with them right now.

![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/30689440/b6a312d6-0b75-4a9f-9404-71ba354f8603)
at the moment this doesn't do anything.

**Comment by LOuroboros** [comment]
#4183
