### ISSUE TITLE
RTC events are not happening at all

### ISSUE THREAD

**Issue by johannakullmann** [rh-hideout/pokeemerald-expansion#4084]
### Description

Clock-based events like berry growth and daily events do not work. Planted berries do not grow, and it seems like the daily flags are not cleared either (i.e. the berry master will only ever gift berries to the player once).
The clock in the player's house seems to work fine though.

Noticed on RetroArch on (unmodified) version 1.7.2. 
Berries are growing normally in vanilla emerald without issues on the same emulator.

### Version

1.7.2 (Latest release)

### Discord contact info

jojoo0

**Comment by johannakullmann** [comment]
After playing around with the clock, it looks like the daily events do work. I'm not sure what was going on, I'll test more and open another issue if I can narrow down what was going on.

**Comment by GraionDilach** [comment]
Using fast-forward and/or a hardware which lacks RTC capabilities (like the Miyoo Mini with it's fake RTC emulation) could be the source of this (some emulators return the underlying hardware's timestamps for RTC use). That's beyond the repository's control.

Adopting https://www.pokecommunity.com/threads/simple-modifications-directory.416647/page-24#post-10678054 in a romhack can be a workaround.
