### ISSUE TITLE
Dancer + Teeter Dance

### ISSUE THREAD

**Issue by TerraPrograms** [rh-hideout/pokeemerald-expansion#4101]
### Description

Dancer is supposed to copy Teeter Dance (which is listed as a danceMove). However, it does not work. Perhaps all dance moves with the Flag `MOVE_TARGET_FOES_AND_ALLY` fail to get copied.

### Version

upcoming (Edge)

### Upcoming/master Version

09d12fb

**Comment by Bassoonian** [comment]
(only partially fixed)

**Comment by AlexOn1ine** [comment]
> (only partially fixed)

Dancer is able to copy Teeter Dance now but only works in singles correct. In doubles the ability still copies the move but hits/confuses only one pokemon. I assume the target flag is not respected in this case.
