### ISSUE TITLE
Sticky Barb + Toxic Debris

### ISSUE THREAD

**Issue by TerraPrograms** [rh-hideout/pokeemerald-expansion#4103]
### Description

Sticky Barb does not get transferred if Toxic Debris activates.

### Version

upcoming (Edge)

### Upcoming/master Version

09d12fb

**Comment by DizzyEggg** [comment]
@TerraPrograms Are you sure this happens on master/upcoming? I couldn't repro it, the Sticky Barb was transferred correctly. Maybe your Pokemon was already holding an item and that's why it wasn't transferred?

**Comment by TerraPrograms** [comment]
> @TerraPrograms Are you sure this happens on master/upcoming? I couldn't repro it, the Sticky Barb was transferred correctly. Maybe your Pokemon was already holding an item and that's why it wasn't transferred?

I have just double checked and I cannot reproduce the results. I can only assume I did a mistake in testing, whatever it was. Apologies for that, I will close this issue.
