### ISSUE TITLE
Confirm what happens with Skill Swap on Intrepid Sword battler in SV

### ISSUE THREAD

**Issue by ghoulslash** [rh-hideout/pokeemerald-expansion#4130]
### Description

As per discussion in #4115, it sounds like if skill swap copies dauntless shield/intrepid sword, it will get the switch in effect, but dauntless shield etc will not reactivate when the original battler is switched back in. The current setup would have skill swap NOT gain the stat boost. One solution is for "activatedAbility" to be reset for skill swap, but then re-toggled at the end of skill swaps battle script to prevent the aforementioned switch-back-in issue.

### Version

1.7.3 (Latest release)

**Comment by ZnogyroP** [comment]
I think you've misunderstood the issue a little (either that or I'm misreading your proposal).

Canon behaviour, per [this post](https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/page-18#post-9418675):
- Alakazam vs. Zacian. Alakazam uses Skill Swap, receives Intrepid Sword. Intrepid Sword activates.
- Alakazam vs. Zacian. Alakazam uses Skill Swap, receives Intrepid Sword. Intrepid Sword activates. Alakazam and Zacian both switch out and switch back in. Alakazam uses Skill Swap, receives Intrepid Sword. Intrepid Sword does not activate.
- Alakazam vs. Zacian. Alakazam uses Skill Swap, receives Intrepid Sword. Intrepid Sword activates. Zacian switches out for Zamazenta. Alakazam uses Skill Swap, receives Dauntless Shield. Dauntless Shield activates.

Unfortunately, even the proposed solution here would produce inaccurate behaviour - Intrepid Sword should not reactivate for the same Pokémon if Skill Swapped twice, but separate one-time use Abilities should activate, such as Intrepid Sword -> Dauntless Shield. It also doesn't address the issue of Transform (with the proposal in #4115 a Ditto that transforms into Zacian and gets the boost that then subsequently transforms into Zamazenta would not get the boost from Dauntless Shield).

**Comment by AlexOn1ine** [comment]
#4171
