### ISSUE TITLE
One-hit KO gets guillotine'd

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#4153]
### Description

`One-hit KO` gets decapitalised to `One-hit Ko` at the moment. I'm sure there's other places where Guillotine is doing unintended work (move descriptions, Pokédex entries...) that we ought to check and fix.

### Version

upcoming (Edge)

**Comment by AsparagusEduardo** [comment]
I was going to add KO to the list of common exceptions that Guillotine add, but I found out the following issue with that implementation:
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/2904965/15d9191b-191a-48e8-aece-3b19f3b8206f)

Tagging @aarant in case they want to solve this issue on their branch themselves or if they want me to see into PRing a fix myself.

**Comment by aarant** [comment]
Hm...ah yeah, I forgot that there are actual words that contain "TM" in them.

I'll look into it on my branch, but I think there's probably 2-3 options:

1. Fixed-case all instances of "TM" manually, and remove the bigram exception. There's probably a lot, though, so this isn't ideal.
2. #ifdef instances of "DEPARTMENT", decapping it when DECAP_ENABLED. There's 12 from a quick search, all in script files, but if I remember right you can use ifdefs in scripts fine.
3. New character that disables the bigrams until the end of the placeholder/string. I feel like this would make the implementation more complicated though.

I'd probably go with 2 and that's what I'll do on my branch I think

**Comment by mrgriffin** [comment]
At the moment it looks like the bigram code tracks the previous character... Would it be possible to track the previous two characters, and then use that extra character to detect if we're in the second letter of a two-letter word? So `DEPARTMENT` would have `lastChars={'R', 'T'}, currChar='M'`, and `R` isn't a word boundary\* so the `M` is decapitalized. Whereas `This TM` would have `lastChars={' ', 'T'}, currChar='M'`, and ' ' _is_ a word boundary, so the `M` stays capitalized.

\* borrowing from the concept from [Perl's `\b` regexp metacharacter](https://www.regular-expressions.info/wordboundaries.html), although I think we'd have slightly different rules for what constitutes a "word".

**Comment by LOuroboros** [comment]
"EV" and "IV" also get decapped by the way, unless someone addressed that in the past few days. Since the conversation became more about the terms that are being decapped than about OHKO itself, I figured it'd be fine to mention it.

**Comment by mrgriffin** [comment]
> One-hit KO gets decapitalised

> "EV" and "IV" also get decapped by the way

Hmm... Are there any two-letter words that should be decapitalized? [AN, BE, GO, HI, IF, ...](https://www.dictionary.com/e/word-finder/2-letter-words/), I wonder if these even appear capitalized in the game... I wouldn't expect so, since they're not nouns. I'll investigate with a little grepping if I have time.

I wonder if it would make more sense to default to preserving case, and have a list of exceptions. (To detect two-letter words we could use `lastChars[2]` plus an extra character of lookahead—we know it's safe to look ahead because there's at least an `EOS` terminator.)

**Comment by aarant** [comment]
> At the moment it looks like the bigram code tracks the previous character... Would it be possible to track the previous two characters, and then use that extra character to detect if we're in the second letter of a two-letter word? So `DEPARTMENT` would have `lastChars={'R', 'T'}, currChar='M'`, and `R` isn't a word boundary* so the `M` is decapitalized. Whereas `This TM` would have `lastChars={' ', 'T'}, currChar='M'`, and ' ' _is_ a word boundary, so the `M` stays capitalized.
> 
> * borrowing from the concept from [Perl's `\b` regexp metacharacter](https://www.regular-expressions.info/wordboundaries.html), although I think we'd have slightly different rules for what constitutes a "word".

We'd want to check

> > One-hit KO gets decapitalised
> 
> > "EV" and "IV" also get decapped by the way
> 
> Hmm... Are there any two-letter words that should be decapitalized? [AN, BE, GO, HI, IF, ...](https://www.dictionary.com/e/word-finder/2-letter-words/), I wonder if these even appear capitalized in the game... I wouldn't expect so, since they're not nouns. I'll investigate with a little grepping if I have time.
> 
> I wonder if it would make more sense to default to preserving case, and have a list of exceptions. (To detect two-letter words we could use `lastChars[2]` plus an extra character of lookahead—we know it's safe to look ahead because there's at least an `EOS` terminator.)

Yeah. This is what I'll implement, making two-letter words immune, if on either side the character is a ctrl character, whitespace or a digit (can't just be non-letter, because "MR." exists)

**Comment by aarant** [comment]
Added a commit to improve this: https://github.com/aarant/pokeemerald/commit/37bba1d5871ed47a842f2effec194feebe79e924

![romhack-465](https://github.com/rh-hideout/pokeemerald-expansion/assets/24759293/5f71acd0-7d92-4b1e-9002-d5f896117749)

Will merge this into guillotine-expansion and open a PR

**Comment by Bassoonian** [comment]
Obsolete due to the removal of Guillotine
