### ISSUE TITLE
Add FREE_EXTRA_SEEN_FLAGS for struct Pokedex

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#4177]
### Description

`FREE_EXTRA_SEEN_FLAGS` only handles `SaveBlock1`'s seen flags. However `SaveBlock1` also has unused flags in its `Pokedex` struct.
I'd like for that to be handled as well.

### Discord contact info

AsparagusEduardo

**Comment by Bassoonian** [comment]
I just tried this, and for some reason (padding?) the net gain appears to be unchanged. I think it's better to just leave it as is in that case?

**Comment by Bassoonian** [comment]
Oh, you said SaveBlock1, so I didn't bother checking SaveBlock2! My bad

**Comment by AsparagusEduardo** [comment]
> Oh, you said SaveBlock1, so I didn't bother checking SaveBlock2! My bad

Whoops, my bad, I meant `SaveBlock2` instead of 1 ^^;

**Comment by Bassoonian** [comment]
Fixed by #4213
