### ISSUE TITLE
PokéNav gets incorrectly decapitalized with guillotine

### ISSUE THREAD

**Issue by fdeblasio** [rh-hideout/pokeemerald-expansion#4181]
### Description

Using guillotine for decapitalization causes PokéNav to mistakenly have a lowercase N
![test-0](https://github.com/rh-hideout/pokeemerald-expansion/assets/35279583/fc4eba48-5b9e-4179-8527-ed27a1fdf1b6)

### Version

upcoming (Edge)

### Upcoming/master Version

3598a187031c7b93c760919bc2bc8826c638609f

### Discord contact info

Frankfurter0

**Comment by AlexOn1ine** [comment]
I think for those it's fine if they are handled on the user side. Though we should add a small tutorial in the release section.

**Comment by Bassoonian** [comment]
Obsolete due to the removal of Guillotine
