### ISSUE TITLE
Starter Pokémon received from Birch have a chance of having their hidden ability

### ISSUE THREAD

**Issue by fdeblasio** [rh-hideout/pokeemerald-expansion#4186]
### Description

The Pokémon picked for the Zigzagoon battle sometimes have their hidden ability

![test-1](https://github.com/rh-hideout/pokeemerald-expansion/assets/35279583/58b882e5-72f7-4b65-9fc6-13aa77bea906)

### Version

upcoming (Edge)

### Upcoming/master Version

e73c58ed2e24a2ea67595617924f92f3be0fe794

### Discord contact info

Frankfurter0

**Comment by pkmnsnfrn** [comment]
https://github.com/rh-hideout/pokeemerald-expansion/blob/e73c58ed2e24a2ea67595617924f92f3be0fe794/src/script_pokemon_util.c#L351

I don't think the new givemon block hidden abilities. I think the correct fix is that if the user does not explicitly define a hidden ability, one will never be randomly rolled.

**Comment by AsparagusEduardo** [comment]
> https://github.com/rh-hideout/pokeemerald-expansion/blob/e73c58ed2e24a2ea67595617924f92f3be0fe794/src/script_pokemon_util.c#L351
> 
> I don't think the new givemon block hidden abilities. I think the correct fix is that if the user does not explicitly define a hidden ability, one will never be randomly rolled.

It could be replaced by `NUM_NORMAL_ABILITY_SLOTS`

**Comment by pkmnsnfrn** [comment]
Just confirmed, changing `NUM_ABILITY_SLOTS` to `NUM_NORMAL_ABILITY_SLOTS` resolves this issue and but I do not know the downstream impacts of making that change.

https://youtu.be/tUQH7JYFz2o (video is processing)

**Comment by AsparagusEduardo** [comment]
> Just confirmed, changing `NUM_ABILITY_SLOTS` to `NUM_NORMAL_ABILITY_SLOTS` resolves this issue and but I do not know the downstream impacts of making that change.

Looking at the code, any non-specified abilityNum in givemon will cause it to default to `NUM_ABILITY_SLOTS` and therefore choose randomly between the regular 2 abilities.

**Comment by AlexOn1ine** [comment]
#4192
