### ISSUE TITLE
The Lotad/Seedot sizes don't take the unit config into account

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#4188]
### Description

See #4183

> This PR DOES NOT address the size printing issue in Lotad / Seedot house. This will come in a future PR.

### Version

upcoming (Edge)

**Comment by pkmnsnfrn** [comment]
@Bassoonian can you please assign to this me?

**Comment by Bassoonian** [comment]
Done!

**Comment by Bassoonian** [comment]
Fixed by #4193
