### ISSUE TITLE
Whiteout with max-length player name and Guillotine enabled causes overflow + crash

### ISSUE THREAD

**Issue by Ultimate-Bob** [rh-hideout/pokeemerald-expansion#4202]
### Description

Mentioned in the discord here: https://discord.com/channels/419213663107416084/774393519569502268/1208076831958372382

If a player has a name with 7 characters (max length) and has Guillotine decaps enabled, then a whiteout will result in a text overflow and crash with a jump to an invalid address.

![7chars](https://github.com/rh-hideout/pokeemerald-expansion/assets/39687914/4376c015-7f45-4573-a945-641b7ef59463)
![Screenshot_20240217_023608](https://github.com/rh-hideout/pokeemerald-expansion/assets/39687914/2dc5118f-df90-412c-ad00-3a264b3996c6)

### Version

upcoming (Edge)

### Upcoming/master Version

ebe13ff

### Discord contact info

ultimate_bob

**Comment by AlexOn1ine** [comment]
#4206
