### ISSUE TITLE
Get rid of Mgbaprintf

### ISSUE THREAD

**Issue by DizzyEggg** [rh-hideout/pokeemerald-expansion#4222]
### Description

`Mgbaprintf` is an artifact of the past where tests were in their infancy. What we should do is just use `DebugPrintf` instead.

Note: remember to port `%q` which allows to print `uq_4_12` numbers.
Note: port anything else which `Mgbaprintf` does and `DebugPrintf` does not.

### Version

1.7.4 (Latest release)

**Comment by DizzyEggg** [comment]
These are valid arguments. 
For what it's worth maybe it's better to keep `MgbaPrintf_`? 
I would only change the name to something like `TestMgbaPrintf`, so that it's not used outside of tests. Not like it's a big deal, but just to avoid confusion why there are 2 printf functions.

**Comment by mrgriffin** [comment]
Up to you! Rename sounds fine if you think that's best, there's a bunch of `Test_Foo` functions, so it seems reasonable to add one more :+1:

**Comment by Bassoonian** [comment]
Fixed by #4642
