### ISSUE TITLE
Convert Fossil revival list to use SBird's multichoice system

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#4233]
### Description

It would hopefully serve as a good example for people to implement their own lists using the system.

### Discord contact info

AsparagusEduardo

**Comment by Bassoonian** [comment]
There's already a reminder to convert all existing vanilla multilists to SBird's system (#3899) which would be more "vanilla" than adding a list not present in vanilla Emerald for reference.

**Comment by AsparagusEduardo** [comment]
> There's already a reminder to convert all existing vanilla multilists to SBird's system (#3899) which would be more "vanilla" than adding a list not present in vanilla Emerald for reference.

My bad. Will close this issue then.

**Comment by AlexOn1ine** [comment]
did we need some banned list for the battle tower or something?

**Comment by AsparagusEduardo** [comment]
> did we need some banned list for the battle tower or something?

It was a proposal due to the increased amount of banned species, but not necessary imo. The list only grows that big if you actively catch all those Pokémon, which in on itself is becoming an edge case, especially now that disabling families is a thing.

You can see a gif of it in #3465.

**Comment by LOuroboros** [comment]
> There's already a reminder to convert all existing vanilla multilists to SBird's system (#3899) which would be more "vanilla" than adding a list not present in vanilla Emerald for reference.

That sounds awful. There's way too many multichoices in the game. Converting all of them will produce an obscene number of merge conflicts downstream.

**Comment by AlexOn1ine** [comment]
> > There's already a reminder to convert all existing vanilla multilists to SBird's system (#3899) which would be more "vanilla" than adding a list not present in vanilla Emerald for reference.
> 
> That sounds awful. There's way too many multichoices in the game. Converting all of them will produce an obscene number of merge conflicts downstream.

Why would it cause a lot of conflicts if it is code that is almost never touched by a user?

**Comment by LOuroboros** [comment]
> > > There's already a reminder to convert all existing vanilla multilists to SBird's system (#3899) which would be more "vanilla" than adding a list not present in vanilla Emerald for reference.
> > 
> > 
> > That sounds awful. There's way too many multichoices in the game. Converting all of them will produce an obscene number of merge conflicts downstream.
> 
> Why would it cause a lot of conflicts if it is code that is almost never touched by a user?

Overworld scripts are not touched by users? 🤔 ...

**Comment by AlexOn1ine** [comment]
> > > > There's already a reminder to convert all existing vanilla multilists to SBird's system (#3899) which would be more "vanilla" than adding a list not present in vanilla Emerald for reference.
> > > 
> > > 
> > > That sounds awful. There's way too many multichoices in the game. Converting all of them will produce an obscene number of merge conflicts downstream.
> > 
> > 
> > Why would it cause a lot of conflicts if it is code that is almost never touched by a user?
> 
> Overworld scripts are not touched by users? 🤔 ...

touche

**Comment by LOuroboros** [comment]
> > > > > There's already a reminder to convert all existing vanilla multilists to SBird's system (#3899) which would be more "vanilla" than adding a list not present in vanilla Emerald for reference.
> > > > 
> > > > 
> > > > That sounds awful. There's way too many multichoices in the game. Converting all of them will produce an obscene number of merge conflicts downstream.
> > > 
> > > 
> > > Why would it cause a lot of conflicts if it is code that is almost never touched by a user?
> > 
> > 
> > Overworld scripts are not touched by users? 🤔 ...
> 
> touche

And I didn't even mention the files where vanilla's are declared and defined 😅

**Comment by AlexOn1ine** [comment]
> And I didn't even mention the files where vanilla's are declared and defined 😅

I'm still not sure how much we should care in this case but those are good points.
