### ISSUE TITLE
Basculegion Female might be missing an entry in the cry tables

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#4234]
### Description

Originally mentioned by skolgrahd in Pret's Discord server.

![firefox_20240228_180325866](https://github.com/rh-hideout/pokeemerald-expansion/assets/4485172/ad7f620f-62cf-4785-86ea-23b9bfab2209)

I gave it a quick check, and I'd say it checks out.

I only find 2 mentions of Basculegion; one for `gCryTable` and one for `gCryTable_Reverse`, when there should be 2 mentions in each table; one for Male Basculegion and one for Female Basculegion.

https://github.com/rh-hideout/pokeemerald-expansion/blob/upcoming/sound/cry_tables.inc

https://github.com/rh-hideout/pokeemerald-expansion/blob/upcoming/include/constants/species.h

### Version

upcoming (Edge)

### Upcoming/master Version

e3d9a19f455c5e753980f2149c9e9c478aaa2510

### Discord contact info

lunos4026

**Comment by AsparagusEduardo** [comment]
I can't find a source that says that Basculegion has different cries based on the form, unlike stuff like Oinkologne.

**Comment by AsparagusEduardo** [comment]
I can't find a source that says that Basculegion has different cries based on the form, unlike stuff like Oinkologne.

Also, looking at the image, it doesn't even seems like they're using 1.7, since cry tables were refactored into being unique and based on a `CRY_xxx` enum.

**Comment by Bassoonian** [comment]
This was fixed in #3242. The user is using an outdated version of expansion.
