### ISSUE TITLE
Errant commas in gen9.h may cause issues making changes in lines below

### ISSUE THREAD

**Issue by ghost** [rh-hideout/pokeemerald-expansion#4236]
### Description

I added some evos to gimmighoul_roaming and gimmighoul_chest which caused a small cascade of errors, eventually leading to a make error caused by line end commas on line 4505 and 4536.

Removing these commas fixed the issue. I am working in 1.7.3, but the commas exist in 1.7.4 as well. 
![Screenshot 2024-02-29 213759](https://github.com/rh-hideout/pokeemerald-expansion/assets/156539960/a5e25a75-9f23-4c2f-bc38-d48abbdf0551)

### Version

1.7.3

### Discord contact info

sv_cheats

**Comment by AsparagusEduardo** [comment]
This is because your edited macro expanded to invalid code. With #4230, we'll be removing those macros to avoid confusion for users.

**Comment by AlexOn1ine** [comment]
#4230
