### ISSUE TITLE
Guillotine does not impact GetStringWidth

### ISSUE THREAD

**Issue by mrgriffin** [rh-hideout/pokeemerald-expansion#4242]
### Description

`GetStringWidth` should return the number of pixels that the text would use when rendered, but [it doesn't seem like there's any special logic in that function when Guillotine is in effect](https://github.com/rh-hideout/pokeemerald-expansion/blob/upcoming/gflib/text.c#L1586-L1599)?

For something like #4241 uppercase characters are usually the same or wider than lowercase so it will just mean that text uses a narrower font than it has to sometimes. But if we invert Guillotine for move names then the opposite will happen, meaning that we could under-estimate the width and cause visible clipping. The tests in #4241 also rely on `GetStringWidth` being correct.

I think center- and right- aligning text is simply broken. [`src/international_string_util.c`](https://github.com/rh-hideout/pokeemerald-expansion/blob/upcoming/src/international_string_util.c) defines multiple functions for aligning which are ultimately implemented in terms of `GetStringWidth`.

### Version

upcoming (Edge)

**Comment by aarant** [comment]
Both `FIXED_CASE` and `UNFIX_CASE` chars their glyph width should be defined as 0 in [fonts.c](src/fonts.c), so I don't see the issue?

**Comment by aarant** [comment]
There was a similar issue to this in poryscript; the solution there was to use the maximum string width in pixels of both upper and lowercase characters, to guarantee consistency whether or not decap is being used

**Comment by mrgriffin** [comment]
Correct me if I'm wrong, but the issue is that uppercase glyphs may have a different width to lowercase glyphs, so the computed width of the string can be incorrect?

If we're computing incorrect widths, then it seems impossible for centered text and right-aligned text to be positioned correctly, although I don't know if there are any vanilla examples of this occurring. Even if it doesn't happen in vanilla, there's no reason to think it couldn't affect a downstream project however.

**Comment by aarant** [comment]
I see what you mean now. Yeah we would have to re-implement the decap logic in the width calculator somehow

**Comment by mrgriffin** [comment]
While working on #4241 I found an example where this matters—`PrintHeldItemName` in `src/pokemon_summary_screen.c` centers the item's name.

**Comment by Bassoonian** [comment]
Obsolete due to the removal of Guillotine
