### ISSUE TITLE
Item names should have more than 14 characters

### ISSUE THREAD

**Issue by mrgriffin** [rh-hideout/pokeemerald-expansion#4248]
### Description

Examples from z-nogyroP:
- Weakness Policy (15)
- Scroll of Darkness (17)
- Fighting Tera Shard (19)
- Mythical Pecha Berry (20)

Related to #4243, in the sense that these names could also be displayed on the summary screen. I expect other UIs' fonts would also need adjusting.

Perhaps a `B_EXPANDED_ITEM_NAMES` config, to mirror `B_EXPANDED_MOVE_NAMES` and `B_EXPANDED_ABILITY_NAMES`? It would be good to support the official item names, instead of using our unofficial ones.

### Version

1.7.4 (Latest release)

**Comment by mrgriffin** [comment]
Will be fixed by #4241.

**Comment by Bassoonian** [comment]
Fixed by #4241
