### ISSUE TITLE
No configs for official species names

### ISSUE THREAD

**Issue by mrgriffin** [rh-hideout/pokeemerald-expansion#4249]
### Description

We have `B_EXPANDED_MOVE_NAMES` and `B_EXPANDED_ABILITY_NAMES`, but not a `P_EXPANDED_SPECIES_NAMES`.

tbf, I think `P_EXPANDED_SPECIES_NAMES` should probably just be a check against the length of `POKEMON_NAME_LENGTH`, because this means that if somebody increases `POKEMON_NAME_LENGTH` to 12 (which is something #3438 supports) they'd automatically get the official species names instead of our unofficial ones.

### Version

master (default when pulling, unreleased bugfixes)

**Comment by mrgriffin** [comment]
Will be fixed by #4241.

**Comment by Bassoonian** [comment]
Fixed by #4241
