### ISSUE TITLE
Player Name in Save Summary being wrongly decapitalised

### ISSUE THREAD

**Issue by m-row1709** [rh-hideout/pokeemerald-expansion#4287]
### Description

Despite having set

`#define DECAP_NICKNAMES     FALSE`

in /config/decap.h, the Player Name is still decapitalised in the Save Summary screen. See the two below images for an example of what I mean:

![decap_bug_1](https://github.com/rh-hideout/pokeemerald-expansion/assets/69256924/f2e4cbc5-fe0e-46a4-b5e7-217fafe14116)

![decap_bug_2](https://github.com/rh-hideout/pokeemerald-expansion/assets/69256924/497bafdc-9200-40ce-94c3-42e0b1cfa218)

Edit: The Player Name is also being wrongly decapitalised in the Trainer Card screen:

![decap_bug_3](https://github.com/rh-hideout/pokeemerald-expansion/assets/69256924/92c44c45-27f9-4474-b220-29804d69e859)

### Version

1.8.0 (Latest release)

### Discord contact info

msr_1709

**Comment by Bassoonian** [comment]
Obsolete due to the removal of Guillotine
