### ISSUE TITLE
Eggs on summary screen cause the game to crash

### ISSUE THREAD

**Issue by SBird1337** [rh-hideout/pokeemerald-expansion#4300]
### Description

Mentioned by a few people on discord, starting [here](https://discord.com/channels/419213663107416084/1077168246555430962/1221198705169010828).

User Ivantxo also mentions a potential relation to #4250.

I did not have time to confirm it yet.

### Version

1.8.0 (Latest release)

### Discord contact info

karathan

**Comment by Erkey830** [comment]
https://github.com/rh-hideout/pokeemerald-expansion/assets/103591587/fdccb008-c378-4ce3-80e5-d6f5dd7a4063

video by ivantxo

I got same issue on master branch ;)

**Comment by AsparagusEduardo** [comment]
Confirmed that reverting #4250 fixes the issue. I'll try to look up the specific change, but if you don't hear from me in a day, please be free to continue the search.
