### ISSUE TITLE
Z-Moves not cancelling in Double Battles

### ISSUE THREAD

**Issue by damon-murdoch** [rh-hideout/pokeemerald-expansion#4314]
### Description

There seems to be some bug with Z-moves in doubles where if you select one and then cancel it after you reach your second pokemons selections, the next move used by a pokemon in that slot becomes that move anyway

This happens even if the Pokemon who committed to the Z-Move switches out, for example I committed to using a Z-move on Lando-T but changed my mind and switched it out, then the next turn the Gengar I switched it into used ground z lmao

This bug has been present for a very long time (I first noticed it when I re-enabled Z-Moves in the Battle Frontier months ago) but forgot to say anything about it until now :)

### Version

master (default, unreleased bugfixes)

**Comment by damon-murdoch** [comment]
Discord Contact Info: sirscrubbington

**Comment by AlexOn1ine** [comment]
I might be doing something wrong but I couldn't reproduce it.

https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/0c9171bb-0547-4875-adfa-d72cba806208


https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/089f4500-4a19-41f4-94f4-ec55a3534fef

**Comment by damon-murdoch** [comment]
Interesting - All of the times I have encountered this bug I have been playing in the Battle Frontier - I just didn't see why that would make a difference for this but might be worth noting

Next time I have a chance to test I should be able to record a video of it happening

**Comment by Bassoonian** [comment]
![zmovedouble](https://github.com/user-attachments/assets/49baa987-2445-4686-8e6d-480429ef515e)
![zmovedouble2](https://github.com/user-attachments/assets/abdd035d-cfa6-4116-b7a0-c98a7771efd6)

Confirmed to be working on the latest upcoming, both in normal battles and in the battle frontier.
