### ISSUE TITLE
Battle Frontier crash with certain decap settings

### ISSUE THREAD

**Issue by johannakullmann** [rh-hideout/pokeemerald-expansion#4315]
### Description

With certain decapitalization settings, the game crashes before starting a battle in the Battle Frontier/Battle Tent (more precisely: when trying to display the Easy Chat message before the battle).

To reproduce, in decap.h, set:
```
#define DECAP_ENABLED TRUE
...
#define DECAP_EASY_CHAT     TRUE // Easy Chat words and interface.
#define DECAP_FIELD_MSG     FALSE // Field messages (including scripts!).`
```
Crashes the game when displaying the Easy Chat message before Frontier battles (tested with Slateport Battle Tent, Battle Factory Singles, Battle Dome, Battle Tower Singles)

### Version

1.8.1 (Latest release)

### Discord contact info

jojoo0

**Comment by Bassoonian** [comment]
Obsolete due to the removal of Guillotine
