### ISSUE TITLE
Migration script convert_parties.py broken by default

### ISSUE THREAD

**Issue by agsmgmaster64** [rh-hideout/pokeemerald-expansion#4361]
### Description

Using the migration script in its current intended state will fail for a few reasons, the first being that there's a typo within the python script in the line defining trainer_starting_status_definition that has an extra ``` left over for whatever reason, and the second being that it will fail if trainers.h is not reverted before the commit with the changes made as it will otherwise throw a bunch of errors about the added lines from the commit itself and have the resulting file with incorrect information.

### Version

upcoming (Edge)

### Upcoming/master Version

8bd5ac2e7a56305cb4db64a453cf532335ee71ba

### Discord contact info

agsmgmaster64

**Comment by mrgriffin** [comment]
#4362 addresses the leftover ``` which snuck in from a recommend change that was blindly committed.

**Comment by Bassoonian** [comment]
Fixed by #4362
