### ISSUE TITLE
trainers.party not properly accounting for numbers in a name

### ISSUE THREAD

**Issue by agsmgmaster64** [rh-hideout/pokeemerald-expansion#4365]
### Description

Attempting to add in numbers to the species itself within trainers.party will be completely ignored when attempting to compile the file. This is more obvious with Porygon2 specifically as it will be compiled as Porygon instead.

### Version

upcoming (Edge)

### Upcoming/master Version

8bd5ac2e7a56305cb4db64a453cf532335ee71ba

### Discord contact info

agsmgmaster64

**Comment by AsparagusEduardo** [comment]
#4366
