### ISSUE TITLE
Future Sight failure string

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#4375]
### Description

#4350 fixed some Future Sight issues, but we bumped into Showdown using a specific text if Future Sight fails because the target has already fainted when it hits which is not in the vanilla games. This should be tested and edits should be made to expansion as necessary.

### Version

master (default, unreleased bugfixes)

**Comment by kittenchilly** [comment]
SV does not have any equivalent specific future sight fail message. Currently unsure what it really prints if it fails, but it could be the generic "But it failed" string

**Comment by AlexOn1ine** [comment]
It seems like there is no message in the mainline games (that is what we currently have as well)

![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/b1a7b08c-3ab2-4c39-adcb-8c17a5bf9f82)

Screenshot provided by @kittenchilly
