### ISSUE TITLE
ABILITY_BATTLE_BOND

### ISSUE THREAD

**Issue by Pyredrid** [rh-hideout/pokeemerald-expansion#438]

**Comment by petuuuhhh** [comment]
lol what just happened? can somebody explain why I'm getting a notif for this?

**Comment by LOuroboros** [comment]
> 
> 
> lol what just happened? can somebody explain why I'm getting a notif for this?

![Untitled664](https://user-images.githubusercontent.com/4485172/97508065-70cbf600-195d-11eb-9e8e-c801b2867944.png)

**Comment by petuuuhhh** [comment]
your commit doesn't reference this issue. so why does it say it does?

**Comment by LOuroboros** [comment]
> 
> 
> your commit doesn't reference this issue. so why does it say it does?

What do you mean by "my commit"? 🤔 
The notification is stating that you pushed a commit to a repository or a branch of a repository under your account 9 hours ago that referenced this issue somehow. That is probably the reason why you received a notification.

**Comment by AsparagusEduardo** [comment]
#1704
