### ISSUE TITLE
Gengar's and Mega Gengar's cries are not playing normally

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#4384]
### Description

Found by andryz90 in the Discord server.

I checked it out on an up-to-date copy of the upcoming branch and it seems to be correct.

Gengar's cry doesn't play neither in battles nor in the summary screen. Mega Gengar's doesn't play in battles either.

https://github.com/rh-hideout/pokeemerald-expansion/assets/4485172/9da38a25-a6eb-4fd1-826c-69efe23e03b7

### Version

upcoming (Edge)

### Upcoming/master Version

5bf379720f04daa148b85da07c9d88696832637d

### Discord contact info

lunos4026

**Comment by AsparagusEduardo** [comment]
Confirmed that it's also happenin in master.
