### ISSUE TITLE
Steven Partner Battle String Error

### ISSUE THREAD

**Issue by CeeJiggy** [rh-hideout/pokeemerald-expansion#4398]
### Description

When starting the partner battle with  Steven in the Mossdeep Space Center, what seems to be Steven's trainer class is loaded with a ton of junk characters. I personally also experience his trainer class being "Dragon Tamer" after updating to 1.8.2
![StevenMultiBattle](https://github.com/rh-hideout/pokeemerald-expansion/assets/92240739/d09f14a1-8b23-4d31-8f82-d817e8ca4ee6)

### Version

1.8.2 (Latest release)

### Discord contact info

ceejiggy

**Comment by Bassoonian** [comment]
The culprit is #4216
