### ISSUE TITLE
Add a way to change the Tera type via scripting

### ISSUE THREAD

**Issue by agsmgmaster64** [rh-hideout/pokeemerald-expansion#4436]
### Description

Currently in upcoming, there are ways to generate a mon with a given Tera type, but there are no ways by default to allow you to change an existing mon's Tera type, even though it is possible to do so in Scarlet/Violet.

There are already a few scripting macros that set something similar, like `togglegigantamaxfactor` and `hypertrain`, so that can be expanded to allow changing Tera types as well, something along the lines of `checkteratype` for checking a Tera type and `setteratype` for setting such.

### Discord contact info

agsmgmaster64

**Comment by AlexOn1ine** [comment]
#4460
