### ISSUE TITLE
Fur Coat not Breakable

### ISSUE THREAD

**Issue by mrgriffin** [rh-hideout/pokeemerald-expansion#4448]
### Description

[Bulbapedia lists Fur Coat as ignored by Mold Breaker](<https://bulbapedia.bulbagarden.net/wiki/Ignoring_Abilities#Ignorable_Abilities>).

Found by PCG.

I haven't looked into [kc's comment](<https://discord.com/channels/419213663107416084/774393519569502268/1233161578296119416>):

> **kittenchilly**: It might not have the tag in the official games

But I don't think it matters what the official games do--we shouldn't have an override in the code rather than using the obvious solution. Anyway, I've raised this issue because maybe there are more abilities that incorrectly use the official GF move flags rather than the move flags that are accurate to the behavior and it would be worth fixing them all at once.

### Version

1.8.2 (Latest release)

**Comment by kittenchilly** [comment]
Showdown's implementation does have Fur Coat set as breakable, so it really might be us just forgetting to assign it.

**Comment by kittenchilly** [comment]
Ok, I looked into a datamine and indeed we just forgot to assign it. Fur Coat should have the breakable tag.
