### ISSUE TITLE
Wrong Pokemon Takes Damage After Forced Switch with Ejection Items from Stealth Rock

### ISSUE THREAD

**Issue by hedara90** [rh-hideout/pokeemerald-expansion#4457]
### Description

When a Pokemon is switched in as a replacement for a Pokemon ejected with Eject Button/Pack, and Stealth Rock is active on their side, the opponent who caused the damage/stat drop is the one who takes the damage.
The damage that the opponent takes is still determined by the Pokemon that is switched in, so the opponent takes damage equal to an fraction of the max HP of the Pokemon switching in.
Furthermore, the game gets confused about which Pokemon is supposed to be removed from being rendered, which results in two Pokemon occupying one slot graphically, but this is fixed by going to another screen (party/bag/debug).

In a double battle it gets even more wonky, the Pokemon that takes the damage is opponent's second slot, regardless of which slot caused the ejection.

https://github.com/rh-hideout/pokeemerald-expansion/assets/149414898/8872c509-e744-40c8-a613-ae5650ca86c4

https://github.com/rh-hideout/pokeemerald-expansion/assets/149414898/8934a554-24c7-4398-90ba-6b3fbd91d94f

### Version

1.8.2 (Latest release)

### Discord contact info

hedara#5073

**Comment by AlexOn1ine** [comment]
I couldn't reproduce for now. Could you by chance share your save file? Otherwise I'll do some testing at a later time.
