### ISSUE TITLE
Partners might not use the correct palette

### ISSUE THREAD

**Issue by ShinyDragonHunter** [rh-hideout/pokeemerald-expansion#4477]
### Description

Because it's still trying to use gPartnerSpriteId for the loading of partner pics, it can result in the wrong palette being loaded for any partner that doesn't use Steven's back pic. The fix for this would be to remove the use of gPartnerSpriteId as with the recent partner rework, it's no longer required as the back pic data is derived from the partner data itself.

Cropped screenshot of what happens in-game:
![efrwef](https://github.com/rh-hideout/pokeemerald-expansion/assets/32826900/3767c327-a346-47e9-a17c-b5f2ad315194)

I'm more than willing to discuss the fix as I know exactly what it is

### Version

1.8.2 (Latest release)

**Comment by Bassoonian** [comment]
> I'm more than willing to discuss the fix as I know exactly what it is

Would you be open to just PRing it too?
