### ISSUE TITLE
Pokemon loses 33% of Max HP when switching in after ally fainted while Dynamaxed

### ISSUE THREAD

**Issue by WillKolada** [rh-hideout/pokeemerald-expansion#4484]
### Description

Ran into a strange issue where Bitter Malice did damage to a Normal type despite the message claiming it had no affect and the animation not playing. For context, the user was a Hisuian Zoroark (disguised as an Obstagoon) and the target was a Bloodmoon Ursaluna. There's no Ring Target involved, nor any type-effectiveness-altering moves (Soak, Miracle Eye, Odor Sleuth, etc.). Ursaluna is holding a Soft Sand and H-Zoroark is holding a Throat Spray.

The Ursaluna was at full HP. It switched into the Bitter Malice. This screenshot was taken at the end of that turn.

![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/57021938/382e43f4-29d4-4908-8cb4-fe1e0e558e9f)

Guess you'll have to trust me on that to some extent, lol. Anyways, I looked around at various potentially relevant files and programs (not exhaustively, but a cursory investigation) and couldn't turn up anything. Not sure how specific this is. Might be something to do with Mind's Eye, or Illusion, or Bitter Malice, or some combination thereof.

### Version

upcoming (Edge)

### Upcoming/master Version

0aad2a9ba7b358f559c50ecc07a8752400f1d64f

### Discord contact info

Special K#8400

**Comment by AlexOn1ine** [comment]
My suspicion is that something is wrong with `TryNoticeIllusionInTypeEffectiveness` but I couldn't reproduce it. 
  

https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/f30f0b8e-4c6b-41e5-884e-719d6d02139f
```
SINGLE_BATTLE_TEST("Transformed Hisuian Zoroark does no Damage to switched in pokemon")
{
    GIVEN {
        PLAYER(SPECIES_WOBBUFFET);
        PLAYER(SPECIES_URSALUNA_BLOODMOON) { Ability(ABILITY_MINDS_EYE); };
        OPPONENT(SPECIES_ZOROARK_HISUIAN);
        OPPONENT(SPECIES_OBSTAGOON);
    } WHEN {
        TURN { SWITCH(player, 1); MOVE(opponent, MOVE_BITTER_MALICE); }
    } SCENE {
        NONE_OF {
            ANIMATION(ANIM_TYPE_MOVE, MOVE_SHADOW_BALL, player);
            HP_BAR(opponent);
        }
    }
}
```

**Comment by WillKolada** [comment]
Okay, upon reflection, it may not actually have anything to do with Bitter Malice. As I said, the battle scene accurately reflected that Bitter Malice did no damage via the message and the lack of move animation. However, Ursaluna still lost 33% of its HP upon switching in. I think this might somehow be an error with entry hazards.

In a previous fight, an opponent Iron Moth switched into Stealth Rocks generated by Kleavor's Stone Axe move. It took the expected 25%, along with the "stones dug in" message, then appeared to take another 33% or so, ending up at roughly 42% of its max HP. I was puzzled by this, but didn't mention it since I had no idea what caused it. I thought maybe it was a Quark Drive/Booster Energy issue, since the Iron Moth was holding a Booster Energy, but the version I was on hadn't yet implemented the item. Now, however, these incidents seem like they might be linked. After all, Kleavor's Stone Axe rocks were also present in this fight--on the opponent's side again, so you wouldn't expect my Ursaluna to be impacted by them, but still. The additional damage taken lines up too cleanly for me to think it's a coincidence.

As far as I know, there is no situation where any one entry hazard would do 33% max HP to a mon, so maybe I'm off base here. The damage also appears to be type agnostic. And Ursaluna appeared to take the damage after Bitter Malice failed to hit it, rather than before, which is when you'd expect entry hazards to activate. But maybe there's something to it.

**Comment by WillKolada** [comment]
I know I've been spitballing all kinds of crazy theories here but I actually think I know what this is now.

I just had Kleavor switch in with 33% of its health missing, even though no entry hazards were set up anywhere. But what DID happen just before it switched in is that its Dynamaxed ally had just been KO'd while Dynamaxed. Kleavor took the health penalty for the Dynamax ending prematurely. I'm actually certain this is what happened in the Iron Moth instance as well--that Trainer had just switched in after their G-Max Centiskorch was KO'd while Dynamaxed, and I'm fairly certain the same thing happened with the Ursaluna Bloodmoon switching in on Bitter Malice.

So the issue is with switching in after a Dynamaxed ally fainted while Dynamaxed.
