### ISSUE TITLE
Pursuit issues 

### ISSUE THREAD

**Issue by AlexOn1ine** [rh-hideout/pokeemerald-expansion#4492]
### Description

Interaction that is likely broken (unconfirmed):

> Pursuit will now hit any adjacent opponent that attempts to switch out (but not more than one per turn), regardless of who it originally targeted. This effect bypasses redirection effects such as [Follow Me](https://bulbapedia.bulbagarden.net/wiki/Follow_Me_(move)).

Missing effect:
> If the target is using [Volt Switch](https://bulbapedia.bulbagarden.net/wiki/Volt_Switch_(move)) or [Parting Shot](https://bulbapedia.bulbagarden.net/wiki/Parting_Shot_(move)), Pursuit's special effect will activate only if the user of Pursuit would usually act later than the target (its power will only be doubled in that case).
Pursuit is now affected by King's Rock.

### Version

upcoming (Edge)

**Comment by lhearachel** [comment]
Additional missing interaction: As of generation 5, Pursuit will run through the usual checks for Self-Hit Confusion and Full Paralysis when attempting to intercept a switching opponent. These checks were skipped up through generation 4.

[Reference for video evidence](https://discord.com/channels/419213663107416084/774393519569502268/1293676401744150550) (too large to upload directly to Github)

**Comment by AlexOn1ine** [comment]
#5707
