### ISSUE TITLE
"Bugs" with the HGSS Pokedex

### ISSUE THREAD

**Issue by Meister-anon** [rh-hideout/pokeemerald-expansion#4512]
### Description

There's 2 types of errors as far as I can tell, but they all deal with the evo page of the dex.
1.is errors loading the target species icons.
-when a species has multiple evo methods to the same target species it reloads the icon.

2. dpad navigation issues when scrolling the evolutions.
    moving up on the dpad works, fine the issue is Down Dpad, doesn't really work quite right.
plus the selector arrow isn't loaded unless more than 1 evo method is checked and you've seen the target species,
which may be by intention but it hides the functionality that you can  scroll and select the evolution to navigate to their pages.

also once you DO have the selector arrow accessed, it doesnt block navigation to a mon that isn't in the dex list/index.
which breaks dex scrolling if you select them, forcing you to back out with B.

https://discord.com/channels/419213663107416084/419214240277200898/1237168041385787543
Link above is to the rhh discord with my full notes on the subject with gifs.

![evolution errors](https://github.com/rh-hideout/pokeemerald-expansion/assets/78051659/f6becd74-b1ee-4a58-a202-0c216d437c10)

![navigation errors](https://github.com/rh-hideout/pokeemerald-expansion/assets/78051659/cd05d4a4-f722-4d95-aedd-10b3de5f97b3)

Situation illustrated was
caught wurmple seen cascoon, never saw silcoon etc.

2 evo methods for combusken  and 2 evo methods for blaziken

.evolutions = EVOLUTION({EVO_LEVEL, 16, SPECIES_COMBUSKEN},
                        {EVO_LEVEL_ATK_GT_DEF, 16, SPECIES_COMBUSKEN}),

.evolutions = EVOLUTION({EVO_LEVEL, 36, SPECIES_BLAZIKEN},
                        {EVO_DARK_SCROLL, 16, SPECIES_BLAZIKEN}),

### Version

1.8.3 (Latest release)

**Comment by Meister-anon** [comment]
Found one other thing while this is still open.

//If there are no evolutions print text
    if (times == 0 && depth == 0)
    {
        StringExpandPlaceholders(gStringVar4, sText_EVO_NONE);
        PrintInfoScreenTextSmall(gStringVar4, base_x-7-7, base_y + base_y_offset*depth_i);
    }

This line is supposed to make dex display text species has no evo if the mon doesn't have an evolution.
but instead its only drawing a blank screen.

![mGBA_Y2gkZNsLnb](https://github.com/rh-hideout/pokeemerald-expansion/assets/78051659/cd989ed3-d34a-41df-b6e1-253d5ce71513)

**Comment by Meister-anon** [comment]
oh right forgot one last thing,
so you can naviate to a mon you've seen from evo page,
and from there you can move left to stats  but then can't move back to evo.

think this is some weird missed case with the evo screen inputs
well the stats screen,  you can move left from evo, if seen but can't move right from stats if seen.
oh looks like its in all the input pages, they let you go left
but you can't go right unless you own the mon...

not a problem for most but if you can navigate to evo if seen
you should be able to get back to evo from stats.
without needing to catch the mon...


![mGBA_eFmiUFAnJ6](https://github.com/rh-hideout/pokeemerald-expansion/assets/78051659/dbd3baa8-345c-40f7-891b-77412e45b699)

If you all decide to change that its a simple fix, just remove this from  the B case in handlestats screen input

if (!sPokedexListItem->owned)
            PlaySE(SE_FAILURE);

**Comment by Sneed69** [comment]
Another issue: due to the way eeveelution icon printing is handled, removing a Glaceon or Leafeon evolution method causes this:
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/56992013/01b0c8dc-5224-4ea7-b047-e3c758f029f4)

**Comment by AlexOn1ine** [comment]
Fixed in #4514

> except https://github.com/rh-hideout/pokeemerald-expansion/issues/4512#issuecomment-2100615174 as that seems like intended behavior
