### ISSUE TITLE
Trainerproc does not support Chinese characters

### ISSUE THREAD

**Issue by Bubble791** [rh-hideout/pokeemerald-expansion#4531]
### Description

![捕获](https://github.com/rh-hideout/pokeemerald-expansion/assets/34066581/42f49893-da4b-4fd5-a33a-8855e33ab546)

### Version

1.8.3 (Latest release)

**Comment by mrgriffin** [comment]
Could you share a copy of the input, and what your expected output is?

**Comment by Bubble791** [comment]
> Could you share a copy of the input, and what your expected output is?

[trainers.txt](https://github.com/rh-hideout/pokeemerald-expansion/files/15261927/trainers.txt)
expected the trainer's name is still in Chinese

**Comment by mrgriffin** [comment]
I don't have a fix for Windows, but this is an update to say that Chinese characters work fine on my Linux box. It would be interesting to try and work out which environments are affected by this; unfortunately I don't have anything but my Linux box to test with.

**Comment by Bassoonian** [comment]
Fixed by #4734
