### ISSUE TITLE
Future Sight Crashing Game

### ISSUE THREAD

**Issue by TeamAquasHideout** [rh-hideout/pokeemerald-expansion#4542]
### Description

![Screenshot_20240510-084747](https://github.com/rh-hideout/pokeemerald-expansion/assets/108838662/430c4973-208c-488d-a6a2-8ccee47d35f7)

I'm not 100% sure this is an Expansion bug but I really didn't edit any battle code at all other than changing the species and levels of trainer mons as they're created. But I don't touch any move or ability code at all. I'm on the most recent version of Expansion. This user was using a mobile emulator but I encountered the same exact bug on mGBA the other day. 

### Version

1.8.3 (Latest release)

**Comment by AlexOn1ine** [comment]
If possible could any of the players that discovered the bug provide steps to reproduce it? Otherwise it will be hard to find the cause of the issue.

**Comment by TeamAquasHideout** [comment]
Afaik its just having a future sight trigger on a mon who has just fainted. That's what they described here and that's what happened before I experienced it as well, I haven't tried to recreate it and won't have time to try to for a bit

**Comment by AlexOn1ine** [comment]
okay, I think I know what is happening.

**Comment by AlexOn1ine** [comment]
Hmm, I can't reproduce. I would need to know how the mon got knocked out.

**Comment by TeamAquasHideout** [comment]
It was days ago when I had it occur so I don't remember, I asked the person who submitted the bug report and they said they didn't either, but its a Lickilicky level 37 it'll be one of the four moves right before 37 in the learnset I believe. They said they think it was Stomp.

**Comment by AlexOn1ine** [comment]
It was probably the move Wrap that killed to mon by residual damage. I didn't get the freeze but the behavior was still bugged.

**Comment by AlexOn1ine** [comment]
@TeamAquasHideout  #4543 Should hopefully fix it but I couldn't test the freeze.

**Comment by TeamAquasHideout** [comment]
Will apply the change, hopefully it's fixed. Just a random thing I remembered though, is there any difference of Future Sight by Gen? Because I believe they were playing my patch that uses Gen 5 as Gen Latest for all the behaviors based on that constant, so the difference theoretically could be there? Idk. Hopefully this solves it either way.

**Comment by AlexOn1ine** [comment]
> Will apply the change, hopefully it's fixed. Just a random thing I remembered though, is there any difference of Future Sight by Gen? Because I believe they were playing my patch that uses Gen 5 as Gen Latest for all the behaviors based on that constant, so the difference theoretically could be there? Idk. Hopefully this solves it either way.

Future Sight has a lot of differences but the expansion uses the latest change only and there is no config but since gen5 the only difference is the base power, all other changes happened in gen5
