### ISSUE TITLE
Curious Medicine fails to activate upon switch-in

### ISSUE THREAD

**Issue by WillKolada** [rh-hideout/pokeemerald-expansion#4556]
### Description

Twice in a row, a Galarian Slowking with Curious Medicine as its ability switched in and failed to reset the stats of other Pokemon on the field. The first time was against a Sneasler with +1 Attack, while the second was against a Bloodmoon Ursaluna with +3 Special Defense (pictured below). No message was printed when the Slowking switched in.

![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/57021938/414b330e-bf23-4a6e-91b7-9c9babbefb50)

### Version

upcoming (Edge)

### Upcoming/master Version

0aad2a9ba7b358f559c50ecc07a8752400f1d64f

### Discord contact info

Special K#8400

**Comment by hedara90** [comment]
Was this your own Slowking-G that switched in in a double battle? Because Curious Medicine only resets the stat stages of **ally** pokemon, not opponents.

**Comment by WillKolada** [comment]
I am an idiot. I thought I'd double-checked how the ability works. Sorry for raising this issue lol.
