### ISSUE TITLE
Ally Switch + Acupressure should fail when new target becomes the user

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#4565]
### Description

The following test isn't behaving as it does in at least Gen 5.
```
// Verified on Showdown, even though Bulbapedia says otherwise.
DOUBLE_BATTLE_TEST("Acupressure works after ally used Ally Switch")
```
Unfortunetly, "works on Showdown" isn't gonna cut it anymore, because Smogon isn't going to test all non-viable edge cases.

### Expansion: Target left vs right (user Wynaut)
![mGBA_7l5BDRqH5x](https://github.com/rh-hideout/pokeemerald-expansion/assets/2904965/ae4a8ed6-439a-489c-8b83-3d6f2cbbf293) ![mGBA_oxzPQ0qbBR](https://github.com/rh-hideout/pokeemerald-expansion/assets/2904965/c233f5f8-e7db-4516-96d8-cee87457db91)

### Gen 5: Target left vs right (user Doduo)
![melonDS_hXe0cvYdaC](https://github.com/rh-hideout/pokeemerald-expansion/assets/2904965/375cfe1f-6c3b-4fe6-8b48-43449b7fa898) ![melonDS_3RN9B4KFVg](https://github.com/rh-hideout/pokeemerald-expansion/assets/2904965/299d125d-d68e-4360-b7b1-32eb9a081564)

### Version

1.8.3 (Latest release)

### Upcoming/master Version

ebdc9ffc39eb6443116bef155fb4840396f67ad3

### Discord contact info

AsparagusEduardo

**Comment by AlexOn1ine** [comment]
Is this only an issue for gen5 and was changed in gen6+?

**Comment by hedara90** [comment]
I tested it in Gen 6, and going from not self-target to self-target makes the move fail there.
I'm assuming it's the same in Gen 7, but I didn't test there yet since I didn't have the pokemon required for the setup.
