### ISSUE TITLE
Safari Zone crash on MyBoy

### ISSUE THREAD

**Issue by Kasenn** [rh-hideout/pokeemerald-expansion#4566]
### Description

The game completely freezes during Safari Zone encounters when played on the MyBoy android emulator. The freeze happens as soon as the window with the safari ball amount has finished sliding in but before the battle controls appear. The freeze seems to have started happening in 1.7.0 and may have something to do with the modern compiler as rom made using `make agbcc` seems to work fine

### Version

1.8.3 (Latest release)

**Comment by Bassoonian** [comment]
Are we talking about the paid version of MyBoy or the free one?

**Comment by kittenchilly** [comment]
If Safari Zone doesn't crash on real hardware, its an emulation issue which we can't really do anything about...

**Comment by AlexOn1ine** [comment]
> If Safari Zone doesn't crash on real hardware, its an emulation issue which we can't really do anything about...

That's not true. Egg already solved some issues where it would crash on an mobile emulator (Idr which one)

**Comment by DizzyEggg** [comment]
@Kasenn Does it happen on clean 1.8.3 master? I tried to reproduce the issue, but Safari Zone worked fine for me, no crashes spotted on neither no$gba and MyBoy.

**Comment by Kasenn** [comment]
Okay so I did some more testing. Last time the version of 1.8.3 I tested (and kept crashing) was a project that had been updated from an older version (I think it was 1.7.2) with no other changes (it was meant to be a clean repo I had around for reference purposes). I went and created a completely new repo and it seems the crashes are indeed gone

**Comment by Bassoonian** [comment]
Not reproducible on a clean repo
