### ISSUE TITLE
Avalnche Should Not be a Spread Move

### ISSUE THREAD

**Issue by TheLastMudkip** [rh-hideout/pokeemerald-expansion#4580]
### Description

Avalanche should be a move where the user has to chose a target in doubles instead of affecting both enemies.

https://bulbapedia.bulbagarden.net/wiki/Avalanche_(move)

### Version

upcoming (Edge)

### Discord contact info

TheLastMudkip

**Comment by Bassoonian** [comment]
Fixed by #4581
