### ISSUE TITLE
Inner Focus, Scrappy, etc grant immunity to stat drop moves if the attacker has Intimidate

### ISSUE THREAD

**Issue by Sneed69** [rh-hideout/pokeemerald-expansion#4602]
### Description

https://github.com/rh-hideout/pokeemerald-expansion/assets/56992013/d39bae3e-1fc4-47d8-9149-f82acf6fec5e

### Version

upcoming (Edge)

### Discord contact info

duke5614

**Comment by iriv24** [comment]
those 2 abilities have that effect, that is correct behavior

**Comment by Sneed69** [comment]
Inner focus granting immunity to scary face is not the correct behavior.

**Comment by iriv24** [comment]
should probably change the title then

**Comment by ZnogyroP** [comment]
The title does not say "Inner Focus [etc] grant immunity to stat drops from Intimidate." The title says "Inner Focus [etc] grant immunity to stat drops if the attacker has Intimidate." The title correctly describes the incorrect behaviour.
