### ISSUE TITLE
Wrong move descriptions

### ISSUE THREAD

**Issue by AlexOn1ine** [rh-hideout/pokeemerald-expansion#4618]
### Description

> #4617 there are some other oddities in the file (giga drain has a unique description, so does flip turn), but I ain't here to rock the boat just fix the obvious error

Pointed out by Lhea on discord. 

### Version

1.8.3 (Latest release)

**Comment by Bassoonian** [comment]
`sFeintDescription` is also left behind as now unused string since the merger of #4617

**Comment by AlexOn1ine** [comment]
I feel those are fine. feel free to re-open if you disagree
