### ISSUE TITLE
Full Restore error in battle

### ISSUE THREAD

**Issue by wiz1989** [rh-hideout/pokeemerald-expansion#4619]
### Description

When using a Full Restore on a not-active party mon in battle, it only heals the HP but doesn't heal the status condition (only tested with paralysis so far).

### Version

1.8.3 (Latest release)

**Comment by AlexOn1ine** [comment]
Is this the same issue #4603? If it is it will be fixed in 1.8.4

**Comment by wiz1989** [comment]
Thanks for pointing it out! Will close this issue then!
