### ISSUE TITLE
Game crashes when Neutralizing Gas mon is switched out vs Intimidate mon

### ISSUE THREAD

**Issue by skolgrahd** [rh-hideout/pokeemerald-expansion#4627]
### Description

Switching out a Pokémon with the ability Neutralizing Gas against a Pokémon with Intimidate crashes the game. This is repeatable.

The correct behavior should be for Intimidate's ability popout to occur before Weezing swaps, which is what is happening. The first breach from vanilla behavior is when Incineroar switches out. Here's Bulbapedia's description of the vanilla behavior:

> Once Neutralizing Gas is no longer applying, Abilities that activate when gained (i.e. [Abilities that activate when a Pokémon is switched in](https://bulbapedia.bulbagarden.net/wiki/Category:Abilities_that_activate_upon_entering_battle), such as [Intimidate](https://bulbapedia.bulbagarden.net/wiki/Intimidate_(Ability))) immediately pop up an activation message regardless of whether they have already done so, with the exceptions of [Unnerve](https://bulbapedia.bulbagarden.net/wiki/Unnerve_(Ability)) (which still applies but without displaying a message) and [Imposter](https://bulbapedia.bulbagarden.net/wiki/Imposter_(Ability)) (which only activates when switched in, not when gained). If Neutralizing Gas stops applying because the Pokémon with Neutralizing Gas is about to switch out, those Abilities activate before the switch occurs (e.g. if Intimidate is activated this way, it will decrease the Attack of the Pokémon with Neutralizing Gas before it switches out, rather than decreasing the Attack of the Pokémon who switches in to replace it).

![mGBA_ZrC8ToBiKb](https://github.com/rh-hideout/pokeemerald-expansion/assets/162426316/5c60a7e5-2afc-4865-90b7-0c7ee6cd1933)

### Version

1.8.3 (Latest release)

### Discord contact info

Skolgrahd#6928

**Comment by AlexOn1ine** [comment]
I believe the bug happens because Intimidate interrupts the `BattleScript_NeutralizingGasExits`. I'm not sure how a clean fix would look like. I assume it is worse in double battles.

**Comment by Bassoonian** [comment]
Fixed by #4668, will be exceptionally be fixed in 1.9 only due to under the cover refactors.
