### ISSUE TITLE
convert_item_icons.py doesn't append commas to secondaryId for Z Crystals

### ISSUE THREAD

**Issue by WillKolada** [rh-hideout/pokeemerald-expansion#4649]
### Description

The lack of this comma prevents make from successfully resolving.

### Version

upcoming (Edge)

### Upcoming/master Version

06cbc9a1625bc4cecdcc62d96ae546c009f7ced8

### Discord contact info

Special K#8400

**Comment by kittenchilly** [comment]
You have to append the commas manually. It should be like that already, unless you forgot to append a comma to a custom item.

**Comment by kittenchilly** [comment]
Or you didn't merge the vanilla expansion items.h, which you probably should as other stuff may go wrong with the script.

**Comment by WillKolada** [comment]
I did append them manually in my case, but it's strange since only Z Crystals were affected for me. None of my custom items were. I didn't accept the items.h changes from the merge I did since I didn't want to lose my custom items, hence my use of the migration script. Were commas added to the end of the last variable of Z Crystals in a recent commit?

**Comment by kittenchilly** [comment]
After checking, yeah it seems like they were. I guess they were missing accidentally unlike all other items.

**Comment by kittenchilly** [comment]
But I don't think its an issue with the script, its more enforcing a style (and the script checks for the comma and the curly bracket to know if its the last variable that it should append the new item icon stuff below it)

**Comment by WillKolada** [comment]
That all makes sense. It's just that the seeming proximity of the Z Crystal style correction to the item icon refactoring likely means that others will encounter this issue as well. Not sure much can be done to resolve that, however.

**Comment by AlexOn1ine** [comment]
closing this since at this point it probably doesn't matter and worst case can manually be adjusted
