### ISSUE TITLE
Dynamax AI sees base moves rather than promoted Max Moves

### ISSUE THREAD

**Issue by WillKolada** [rh-hideout/pokeemerald-expansion#4650]
### Description

When deciding which move to use, a Dynamax Pokemon will reference the base move in its moveset rather than the promoted Max Move. This is especially problematic for any status move that should be interpreted as Max Guard.

This appears to be because `gChosenMoveByBattler[gBattlerAttacker]` and `gBattleMons[gBattlerAttacker].moves[gChosenMovePos]` do not promote their respective moves to the Max versions and are what the AI references. `gChosenMove`, conversely, does promote the move.

### Version

upcoming (Edge)

### Upcoming/master Version

06cbc9a1625bc4cecdcc62d96ae546c009f7ced8

### Discord contact info

Special K#8400

**Comment by hedara90** [comment]
Partially fixed by #5299 (I think), it now reads the correct base power of moves.
But it didn't change anything regarding secondary effects of Max Moves.

**Comment by AlexOn1ine** [comment]
> But it didn't change anything regarding secondary effects of Max Moves.

I don't think they need to get a score increase based on their secondary effect. They are primarily moves with a high base power, the secondary effect is a bonus. If you do evaluate them you risk the AI not going for best damage in this case
