### ISSUE TITLE
In a Double Battle, the AI's right slot switches in early

### ISSUE THREAD

**Issue by WillKolada** [rh-hideout/pokeemerald-expansion#4656]
### Description

In a scenario where either of the AI's Pokemon have fainted, if the player's right slot Pokemon has also fainted, the AI will switch in their right slot before the player is prompted to switch in their post-KO Pokemon, giving the player an advantage.

### Version

upcoming (Edge)

### Upcoming/master Version

06cbc9a1625bc4cecdcc62d96ae546c009f7ced8

### Discord contact info

Special K#8400

**Comment by DizzyEggg** [comment]
Do we know how it works in the official games? 
The easiest scenario for test would be a double battle with one mon using explosion, so that all battlers faint.

**Comment by hedara90** [comment]
Gen 3 switch in order if all battlers fainted. Tested on cartridge Emerald. Speed of individual Pokemon doesn't matter.
`4 2`
`1 3`
In Gen 7, you choose all every pokemon to send out at the same time, nothing is sent out until everything has been chosen. Tested on cartridge Ultra Sun.

**Comment by DizzyEggg** [comment]
> Gen 3 switch in order if all battlers fainted. Tested on cartridge Emerald. Speed of individual Pokemon doesn't matter. `4 2` `1 3` In Gen 7, you choose all every pokemon to send out at the same time, nothing is sent out until everything has been chosen. Tested on cartridge Ultra Sun.

Thanks hedara! A new config will be needed then

**Comment by AlexOn1ine** [comment]
> > Gen 3 switch in order if all battlers fainted. Tested on cartridge Emerald. Speed of individual Pokemon doesn't matter. `4 2` `1 3` In Gen 7, you choose all every pokemon to send out at the same time, nothing is sent out until everything has been chosen. Tested on cartridge Ultra Sun.
> 
> Thanks hedara! A new config will be needed then

I personally wouldn't config this because our doubles are already not gen3 compatible. A config would be only confusing
