### ISSUE TITLE
Pokemon Learning moves that they should'nt be learning on that level

### ISSUE THREAD

**Issue by RWXOLIVE** [rh-hideout/pokeemerald-expansion#4660]
### Description

I encountered a little bug  with Pokemon learning a move again after the next level
and learning moves at the wrong level  

![image_2024-05-30_143541677](https://github.com/rh-hideout/pokeemerald-expansion/assets/163889652/5655070a-8e09-4b2c-b50a-f0059f551cc8) 

https://github.com/rh-hideout/pokeemerald-expansion/assets/163889652/8e049217-f45a-4267-99c6-eaa564a72bcf

### Version

1.8.4 (Latest release)

### Discord contact info

rwxo

**Comment by RWXOLIVE** [comment]
I;m using gen 9 learnsets

**Comment by Bassoonian** [comment]
Not reproduceable on a clean expansion branch
