### ISSUE TITLE
Check if link contests are broken by DOWP

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#4699]
### Description

Title

### Version

1.8.4 (Latest release)

**Comment by iriv24** [comment]
Are there any specific things to check/look for for this? Just a general "do any palettes look messed up"? I didn't even know link contests were a thing, but now I'm planning to trap some poor soul into doing one with me on upcoming to see if anything looks off

**Comment by iriv24** [comment]
I played through an entire link contest (and lost, Mahita the Makuhita is cracked btw) and took some screenshots of things on both my screens and everything looked normal by my standards, didn't see any anomalies in any palettes in the overworld or the palette itself. I considered making an entire recording of the contest, but PSF talked me down from that ledge. 

![linkcontest1](https://github.com/user-attachments/assets/bf541675-6ad0-4a76-9762-cc3f24c7f076)
![linkcontest2](https://github.com/user-attachments/assets/7bd382c9-1445-4e99-a17f-4ee31a4cd1c2)
![linkcontest3](https://github.com/user-attachments/assets/ccd57729-4a62-4953-9676-e2d40f2b2f7d)

However if a recording of a link contest is still desired, ill do it!

**Comment by Bassoonian** [comment]
That was all that’s necessary, thanks! @aarant you can consider this a non-issue in your branches too :)
