### ISSUE TITLE
Add Heal Bell - Soundproof Generation Based Interactions

### ISSUE THREAD

**Issue by Sneed69** [rh-hideout/pokeemerald-expansion#4704]
### Description

Currently I believe only the default Gen III interaction is implemented.

From https://bulbapedia.bulbagarden.net/wiki/Heal_Bell_(move):

## Generation II to IV

Heal Bell does not affect Pokémon with the [Ability](https://bulbapedia.bulbagarden.net/wiki/Ability) [Soundproof](https://bulbapedia.bulbagarden.net/wiki/Soundproof_(Ability)), including inactive Pokémon.
## Generation V

Heal Bell now lists Pokémon that are healed.

Heal Bell can affect Pokémon with the Ability Soundproof.
## Generation VI to VII

Heal Bell no longer affects active Pokémon with the Ability Soundproof. Inactive Pokémon are healed regardless of Abilities.

If powered up by a [Normalium Z](https://bulbapedia.bulbagarden.net/wiki/Normalium_Z) into Z-Heal Bell, the user regains all of its HP. [Throat Chop](https://bulbapedia.bulbagarden.net/wiki/Throat_Chop_(move)) cannot prevent a Pokémon from using Z-Heal Bell.
## Generation VIII onward

Heal Bell now always affects the user, even if it has Soundproof; however, it still cannot affect other active Pokémon with Soundproof.

### Discord contact info

duke5614

**Comment by Bassoonian** [comment]
Fixed by #4732
