### ISSUE TITLE
Opening the debug menu in a Poké Center resets the game

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#4721]
### Description

Broken as of ab682ce9009a4a26eb326d698cdb8a819d2d17ab (master into upcoming merge the 15th of May)

EDIT: actually, maybe not. I have no idea what is going here

### Version

upcoming (Edge)

**Comment by AsparagusEduardo** [comment]
> EDIT: actually, maybe not. I have no idea what is going here

👀

**Comment by Bassoonian** [comment]
Yeah, I spent 2 hours trying to figure out the exact PR that caused the regression, but with a bunch of commits from master spread around I honestly don't know anymore :( probably best for someone else to look again from scratch

**Comment by AsparagusEduardo** [comment]
#4725
