### ISSUE TITLE
Blank name in naming screen sets Pokémon’s nickname to species name, stays after evolving

### ISSUE THREAD

**Issue by MelonSpeedruns** [rh-hideout/pokeemerald-expansion#4807]
### Description

Issue is pretty self-explainatory. Getting a Pokémon, then not naming it anything reverts the nickname, but the name of the Pokémon doesn't get updated if it evolves.

### Version

1.8.0

### Discord contact info

melonspeedruns

**Comment by DizzyEggg** [comment]
I couldn't really reproduce. Could you add more detailed steps?

**Comment by hedara90** [comment]
Can't reproduce on 1.8.5.
Tested by catching a pokemon, entering nickname screen and confirming while text field was still blank. When it evolved it correctly had the evolved species name as nickname.
