### ISSUE TITLE
GBAGFX does not support Linux line endings for palettes

### ISSUE THREAD

**Issue by nashalexander** [rh-hideout/pokeemerald-expansion#4814]
### Description

On Linux systems LF line endings are generated instead of CRLF. The tool used to convert palette files does not handle these properly, and instead errors out. This would be a simple fix to allow the tool to function properly with a Linux development machine.

### Error returned
```
tools/gbagfx/gbagfx graphics/pokemon/mightyena/shiny.pal graphics/pokemon/mightyena/shiny.gbapal
LF line endings aren't supported.
```

### Version

1.8.4 (Latest release)

### Discord contact info

crimsonocean

**Comment by Bassoonian** [comment]
[Fixed by pret](https://github.com/pret/pokeemerald/commit/c0d630ee6304df61a5304942386308a872aeb504)
