### ISSUE TITLE
DIRE_CLAW incorrect leatnset for Basculegion in gen9 learnsets

### ISSUE THREAD

**Issue by wiz1989** [rh-hideout/pokeemerald-expansion#4835]
### Description

See this line: https://github.com/rh-hideout/pokeemerald-expansion/blob/277b8607df7368241734ac59afb7d029d36f3918/src/data/pokemon/level_up_learnsets/gen_9.h#L12804

MOVE_DIRE_CLAW is exclusive to Sneasler

### Version

1.8.4 (Latest release)

### Discord contact info

wiz1989

**Comment by ShadowzLmao2** [comment]
I can confirm this. Opening https://github.com/rh-hideout/pokeemerald-expansion/blob/master/src/data/pokemon/level_up_learnsets/gen_9.h and going to Basculegion, it has Dire claw, however Dire Claw is not on https://dex.pokemonshowdown.com/pokemon/basculegion
