### ISSUE TITLE
Tweak trainer control for Terastal and Dynamax

### ISSUE THREAD

**Issue by AlexOn1ine** [rh-hideout/pokeemerald-expansion#4861]
### Description

Remove shouldDynamax and shouldTerastal because it is covered with teraType and dynamaxLevel

### Version

upcoming (Edge)

**Comment by Sneed69** [comment]
`dynamaxLevel` is always set when using trainerproc

**Comment by AlexOn1ine** [comment]
> `dynamaxLevel` is always set when using trainerproc

we should turn it off then

**Comment by Bassoonian** [comment]
Fixed by #4962
