### ISSUE TITLE
Incorrect Diamond Storm data

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#4869]
### Description

Found in The Pit's Discord
![Screenshot_20240625_080549_Discord](https://github.com/rh-hideout/pokeemerald-expansion/assets/2904965/570b6834-09ac-4959-940a-e81cc873dd24)

Probably only needs a ".self = TRUE" for the move effect. 
![Screenshot_20240625_080143_Chrome](https://github.com/rh-hideout/pokeemerald-expansion/assets/2904965/147bb909-b6c6-41c0-9a8c-57b7fa592b0a)

### Version

master (default, unreleased bugfixes)

### Upcoming/master Version

Current as of issue creation

### Discord contact info

AsparagusEduardo

**Comment by ShadowzLmao2** [comment]
I can confirm that this bug exists and that the suggested bug fix actually works when compiled. What i did was I got a diancie and in a wild battle used diamond storm. It did indeed raise the wild mon's defense. Adding .self = TRUE, in fixes it in the same scenario listed before
