### ISSUE TITLE
Any object event using "PALSLOT_NPC_SPECIAL" when a mugshot is loaded

### ISSUE THREAD

**Issue by ShinyDragonHunter** [rh-hideout/pokeemerald-expansion#4877]
### Description

When `Mugshots_CreateTrainerPics` is called, it reserves 10 sprite palettes and anything after slot 10 get unloaded. `PALSLOT_NPC_SPECIAL` uses slot 11.

The fix for it is simple and just removing `gReservedSpritePaletteCount = 10;` and moving `gReservedSpritePaletteCount = 12;` to below `task->tPlayerSpriteId` initialisation. I'm aware it's most likely not going to be an issue once dynpals is out but I thought I'd mention it in the meantime

### Version

1.8.4 (Latest release)

**Comment by Bassoonian** [comment]
Adding this to the 1.9 milestone simply because the implementation of DOWP should mean this issue can get closed right before release

**Comment by AlexOn1ine** [comment]
Closing this since at this point it is a non issue
