### ISSUE TITLE
Battle debug is not up to date with changes on status2

### ISSUE THREAD

**Issue by Nopinou** [rh-hideout/pokeemerald-expansion#4889]
### Description

Example:
In include/constants/battle.h, we have #define STATUS2_FOCUS_ENERGY (1<<31).
In src.battle_debug.c, we have Focus Energy expected at bit 20 ({/*Focus Energy*/ 1, 20} in sStatus2Bitfield

I also have the feeling the value of the bit is not properly shown when selecting one of these bits: if I have used Focus energy, in its current version I should check for the torment field IG (31 in sStatus2Biefield) which always appears as 0 upon selection.

I did not check status 3&4, status 1 works fine

### Version

1.8.4 (Latest release)

### Discord contact info

Nopinou#8678

**Comment by AlexOn1ine** [comment]
There is a pr in the works  #4643. Should make it to expansion soon

**Comment by Nopinou** [comment]
Woops, didn't know that! I'll close this issue then

**Comment by AlexOn1ine** [comment]
> Woops, didn't know that! I'll close this issue then

no worries. you could have kept it open :sweat_smile:
