### ISSUE TITLE
MOVE_EMBARGO Effect

### ISSUE THREAD

**Issue by ultima-soul** [rh-hideout/pokeemerald-expansion#49]

**Comment by ProjectRevoTPP** [comment]
This move effect is actually incomplete. It does not prevent trainers from using items; ShouldUseMove nor battle_ai_switch_items never considers the Embargo status.

**Comment by LOuroboros** [comment]
> 
> 
> This move effect is actually incomplete. It does not prevent trainers from using items; ShouldUseMove nor battle_ai_switch_items never considers the Embargo status.

I tested it in a clean copy of the battle_engine and I can confirm that Embargo is currently not affecting the items of the trainer of a Pokémon currently suffering the effects of Embargo.

https://user-images.githubusercontent.com/4485172/126882862-6bda6fe4-328d-4a18-9907-42768ca1fa73.mp4

**Comment by Syreldar** [comment]
in ShouldUseItem(void)
`
    if (gStatuses3[gActiveBattler] & STATUS3_EMBARGO)
        return FALSE;
`

**Comment by DizzyEggg** [comment]
#1579
