### ISSUE TITLE
AnimTask_HorizontalShake is broken

### ISSUE THREAD

**Issue by JoKaT-dev-pixel** [rh-hideout/pokeemerald-expansion#4949]
### Description

`AnimTask_HorizontalShake` had problems with animation where the terrain remains frozen.
This bug appeared after updates from **1.7.3**.

![ezgif-3-7cbb11b59c](https://github.com/rh-hideout/pokeemerald-expansion/assets/136481681/9118ccfc-8cd9-4e93-a6df-92abac94e96a)

### Version

1.8.5 (Latest release)

### Discord contact info

joker0234

**Comment by Bassoonian** [comment]
![earthquaketerrain](https://github.com/rh-hideout/pokeemerald-expansion/assets/16993385/ba819b68-7af5-47a8-abf2-dff2c70bbd4e)
confirmed on a clean expansion

I suspect #4560 is to blame

**Comment by Pawkkie** [comment]
I feel like a proper maintainer now I spent a tonne of time binary searching commit numbers to find the one that broke it lol

This was broken by #4139!
