### ISSUE TITLE
SKULL BASH Effect is Broken

### ISSUE THREAD

**Issue by JoKaT-dev-pixel** [rh-hideout/pokeemerald-expansion#4950]
### Description

Use the Move `SKULL BASH` to loop the Substitute message until the game freezes.

![ezgif-3-2adfff7755](https://github.com/rh-hideout/pokeemerald-expansion/assets/136481681/4d0d47d3-c68f-4330-af4d-1a7b3864bd76)

### Version

1.8.5 (Latest release)

### Discord contact info

joker0234

**Comment by AlexOn1ine** [comment]
https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/c92481aa-2ec2-4a41-ba6b-f871bbe89578

Can't repro. Anything special you do before?

**Comment by Bassoonian** [comment]
`EFFECT_TWO_TURNS_ATTACK` and `EFFECT_SUBSTITUTE` only differ one in value. I think you messed up a merge somewhere. Are there other move effects that are wrong and happen to be off by one?

**Comment by JoKaT-dev-pixel** [comment]
> `EFFECT_TWO_TURNS_ATTACK` and `EFFECT_SUBSTITUTE` only differ one in value. I think you messed up a merge somewhere. Are there other move effects that are wrong and happen to be off by one?

Yes, even Sky Attack and it then displays the message of the Substitute in loop

**Comment by Bassoonian** [comment]
Sure, but Sky Attack is also a two-turn attack, which just confirms my suspicions. What about moves that are not two-turn attacks? How does Substitute behave?

**Comment by JoKaT-dev-pixel** [comment]
> Sure, but Sky Attack is also a two-turn attack, which just confirms my suspicions. What about moves that are not two-turn attacks? How does Substitute behave?

Substitute works perfectly and the bug affects everything that contains `TwoTurns `. (Dig, Solarbeam, etc)

**Comment by Bassoonian** [comment]
Merge issue, not reproducible to expansion
