### ISSUE TITLE
Test saving on AGBFIRM

### ISSUE THREAD

**Issue by tertu-m** [rh-hideout/pokeemerald-expansion#4955]
### Description

@pkmnsnfrn Please test saving on AGBFIRM and report if it works or not.

### Version

upcoming (Edge)

### Discord contact info

tertu

**Comment by pkmnsnfrn** [comment]
https://3ds.eiphax.tech/nsui.html

Using this guide, with a ROM compiled with modern, I am able to 

* play the game
* save inside the truck
* reboot game
* set clock
* save in littleroot
* reboot game
* resume game

all without any issues, errors, or special customization.

**Comment by tertu-m** [comment]
OK, looks like there's nothing we have to do here then!
