### ISSUE TITLE
Sleep Talk fails on repeated attempts

### ISSUE THREAD

**Issue by Kasenn** [rh-hideout/pokeemerald-expansion#4957]
### Description

Sleep Talk works fine on 1st attempt but every attempt after this fails. 

https://github.com/user-attachments/assets/4b1ac1cf-0353-46a1-9adb-87e0d970ae4d

Here's the Komala from the video:
    .lvl = 30,
    .species = SPECIES_KOMALA,
    .ability = ABILITY_COMATOSE,
    .heldItem = ITEM_CHOICE_BAND,
    .moves = {MOVE_SLEEP_TALK, MOVE_LAST_RESORT},

### Version

1.8.5 (Latest release)

**Comment by mrgriffin** [comment]
Do you know if this behavior occurs for moves other than Last Resort?

**Comment by Kasenn** [comment]
No idea. I did try some basic moves but the problem is that it's hard to test because then the AI will prefer using them directly

**Comment by mrgriffin** [comment]
Have you tried reproducing this as a player? Does Sleep Talk fail if you do the things the AI did, with the Komala the AI had?

**Comment by Kasenn** [comment]
Not yet but I can try

**Comment by Kasenn** [comment]
Same issue when used by the player

**Comment by mrgriffin** [comment]
Perfect, thank you! Could you check if it's specific to Last Resort? I ask because you could imagine Last Resort getting a bit weird due to it caring about which other moves have been chosen.

**Comment by Kasenn** [comment]
Tried with rapid spin instead and had the same issue. However, I think the issue is with the choice items instead because i tried unequipping the choice band and both last resort and rapid spin started working fine afterwards

**Comment by mrgriffin** [comment]
Ah, cool, thanks for digging into what's going on. That'll make it easier to work out what's going wrong in the code :)

**Comment by Kasenn** [comment]
I also tried it in vanilla Ultra Sun to see if it was intended behavior but it seemed to work perfectly fine there
