### ISSUE TITLE
Convert single-use string variables to COMPOUND_STRINGs

### ISSUE THREAD

**Issue by fdeblasio** [rh-hideout/pokeemerald-expansion#4959]
### Description

From @Bassoonian in #4951 
>These are only used once, so I would personally be inclined to convert them to COMPOUND_STRINGs and remove them from strings.c and strings.h. The only reason they're lumped with the rest of the strings is for pret matching purposes and it just makes it harder to edit imo

I think this logic should be applied to all single-use strings

- [x] Berry Blender
- [x] PokeNav
- [x] Default player names
- [x] Mechadolls
- [x] PC text
- [x] Bag pockets
- [x] Berries
- [x] PokeBlocks

### Discord contact info
Frankfurter0

**Comment by Bassoonian** [comment]
8/8 tasks done
