### ISSUE TITLE
gBitTable is strictly worse than 1 << i

### ISSUE THREAD

**Issue by luckytyphlosion** [rh-hideout/pokeemerald-expansion#5007]
### Description

I don't know if this has been mentioned before but gBitTable should essentially not exist. it's just slower than doing `1 << i` (two opcodes) instead of `gBitTable[i]` (multiple opcodes + two rom reads)

### Version

1.8.5 (Latest release)

### Discord contact info

luckytyphlosion

**Comment by hedara90** [comment]
#5123 
#5193
