### ISSUE TITLE
Tera Shift is supposed to trigger before any other ability

### ISSUE THREAD

**Issue by hedara90** [rh-hideout/pokeemerald-expansion#5016]
### Description

Currently Tera Shift triggers after other abilities have happened (speed order?), but it should happen before anything else.

https://github.com/user-attachments/assets/07d98d07-a407-4989-91e6-100c1c13cb5c

### Version

upcoming (Edge)

### Discord contact info

hedara

**Comment by hedara90** [comment]
I don't think so, they don't officially exist at the same time, but it would be reasonable to assume that they happen at the "same" time since they're both the same kind of form changing abilities, so between them it would be determined by speed.

**Comment by AlexOn1ine** [comment]
This should be fixed with the Simultaneous HP reduction pr.
