### ISSUE TITLE
Update install instructions for WSL1

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#5028]
### Description

From https://github.com/pret/pokeemerald/pull/2016

> It turns out that Microsoft changed WSL such that the default is now WSL2, and also broke the link to the Microsoft Store in the INSTALL.md. This PR aims to fix this. 
I did not test building the project completely from scratch from the available machine I could use to install WSL, however, I did test that the instructions do install WSL running version 1 correctly.

I imagine we should check and update our `INSTALL.md` to match.

### Version

master (default, unreleased bugfixes)

### Discord contact info

pkmnsnfrn

**Comment by Bassoonian** [comment]
Shouldn't this be fixed in pret's install instead?

**Comment by pkmnsnfrn** [comment]
The PR that I linked is to fix it for pret. I created this issue because I want to make sure somebody remembers to check if our install.md is ALSO outdated in a similar way.

**Comment by pkmnsnfrn** [comment]
#5045
