### ISSUE TITLE
Jellicent graphic error/bug

### ISSUE THREAD

**Issue by sandstormdark** [rh-hideout/pokeemerald-expansion#5051]
### Description

Hi guys, I think the expansion has a bug with a particular pokemon, it is Jellicent female, not only in debug has the problem with the icon looks bad, but also in the summary, I thought to implement this pokemon in my project but with this nasty bug is not possible, I hope you can fix it.

![Captura de pantalla (312)](https://github.com/user-attachments/assets/36f053ee-6166-407a-8293-bd3c11c9e8c4)
![Captura de pantalla (313)](https://github.com/user-attachments/assets/7c3c03ce-607b-4fdc-b12b-f5c2863c6902)
![Captura de pantalla (306)](https://github.com/user-attachments/assets/8eda1c4b-257b-4ff2-bd5f-8b8d920e63a3)

### Version

1.8.5 (Latest release)

### Upcoming/master Version

master

**Comment by hedara90** [comment]
I cannot reproduce the issue with the full sprite.
On a clean up to date version of `master` there is no issue with female Jellicent.
![pokeemerald-0](https://github.com/user-attachments/assets/ffd8dbf2-9d9c-4839-b783-b80c7bd9be41)

You have the male sprite of Jellicent using the female palette, shown below
![anim_front-export](https://github.com/user-attachments/assets/e31842fb-5133-4105-a4e5-2fe56f086bed)

**Comment by sandstormdark** [comment]
I will do a clean master install, and I will update you if the problem is solved.

**Comment by AsparagusEduardo** [comment]
From Discord:
![image](https://github.com/user-attachments/assets/4f3bc496-877e-4481-a937-d339748413eb)
![image](https://github.com/user-attachments/assets/b16bd07e-20ed-4d73-a569-b4838ea5e6ba)
