### ISSUE TITLE
Tera Crystal not appearing in Tera animation

### ISSUE THREAD

**Issue by PhallenTree** [rh-hideout/pokeemerald-expansion#5058]
### Description

At some point between last week's master to upcoming merge (https://github.com/rh-hideout/pokeemerald-expansion/commit/ae48293806919bb58557aa29c2582f3b282d53d3) and the current upcoming version the Tera Crystal used in the Tera animation stopped appearing and instead some other graphic appears.

https://github.com/user-attachments/assets/5a450803-9275-4c3c-b2cc-00bb7322d211

### Version

upcoming (Edge)

### Upcoming/master Version

https://github.com/rh-hideout/pokeemerald-expansion/commit/18aff2db3bf310d703cd548c167f9aa447a319ca

### Discord contact info

PhallenTree

**Comment by AsparagusEduardo** [comment]
#5063
