### ISSUE TITLE
Urshifu-Rapid-Strike Has Incorrect Transparent Pixels

### ISSUE THREAD

**Issue by lhearachel** [rh-hideout/pokeemerald-expansion#5069]
### Description

I found this while working on my implementation of gen4-style shadows.

![image](https://github.com/user-attachments/assets/d8951704-8ab6-4799-a1ac-448c0bc01ad6)
![image](https://github.com/user-attachments/assets/6ce1d791-bd45-43a0-8aa9-aeca86d02831)

### Version

1.8.5 (Latest release)

### Upcoming/master Version

`upcoming`

### Discord contact info

lhea

**Comment by kittenchilly** [comment]
This was fixed in #5071
