### ISSUE TITLE
Pyroar and Indede don't use female follower sprites

### ISSUE THREAD

**Issue by Cafeei** [rh-hideout/pokeemerald-expansion#5124]
### Description

Title 
![IMG_20240809_012012](https://github.com/user-attachments/assets/f0805017-9aef-4364-a2e9-4bf5f3924f24)
![IMG_20240809_011936](https://github.com/user-attachments/assets/6ad3b68f-e64f-440b-b41b-0bbf9381791b)
![Screenshot_2024-08-09-01-20-23-022_it dbtecno pizzaboygba-edit](https://github.com/user-attachments/assets/855afa48-e0ee-4228-8d1d-4ab5e21340a8)

![Screenshot_2024-08-09-01-48-43-197_it dbtecno pizzaboygba-edit](https://github.com/user-attachments/assets/3615c029-f303-45ff-a5e8-94db79f326c7)
![IMG_20240809_020309](https://github.com/user-attachments/assets/8ce9321d-69ff-4c1b-973a-bf1f126f1e77)
![Screenshot_2024-08-09-01-48-10-752_it dbtecno pizzaboygba-edit](https://github.com/user-attachments/assets/30f1e82a-679b-49e6-9d0c-621e9c75b678)

### Version

1.9.0 (Latest release)

**Comment by AsparagusEduardo** [comment]
#5394
