### ISSUE TITLE
Double Tera Possible in Double Battles

### ISSUE THREAD

**Issue by TeamAquasHideout** [rh-hideout/pokeemerald-expansion#5125]
### Description

I've already told Agustin and PSF but I figured I'd make an actual issue since I didn't see PSF make one before going to bed. 

In normal Double Battles (non multi, non two trainers) both Enemy mons are able to Tera. As well as both of the player mons. PSF confirmed in vanilla Expansion this is true at least for Player mons, but didn't try replicating it for the trainer mons. 

I don't have any clips but it's easy to replicate, just start a double battle and try to Tera twice.

### Version

1.9.0 (Latest release)

### Discord contact info

archie5000

**Comment by pkmnsnfrn** [comment]
```diff
Debug_EventScript_Script_1::
+	setflag FLAG_BADGE01_GET
+	setflag FLAG_BADGE02_GET
+	setflag FLAG_BADGE03_GET
+	setflag FLAG_BADGE04_GET
+	setflag FLAG_BADGE05_GET
+	setflag FLAG_BADGE06_GET
+	setflag FLAG_BADGE07_GET
+	setflag FLAG_BADGE08_GET
+   additem ITEM_TERA_ORB,1
+   givemon SPECIES_THROH,100,0,teraType=TYPE_GHOST
+   givemon SPECIES_SAWK,100,0,teraType=TYPE_DARK
+   givemon SPECIES_HITMONTOP,100,0,teraType=TYPE_WATER
+   special HealPlayerParty
+	trainerbattle_double TRAINER_TATE_AND_LIZA_1, MossdeepCity_Gym_Text_TateAndLizaIntro, MossdeepCity_Gym_Text_TateAndLizaDefeat, MossdeepCity_Gym_Text_TateAndLizaNeedTwoMons, MossdeepCity_Gym_EventScript_TateAndLizaDefeated, NO_MUSIC
    release
    end
```

When run from the truck, it is able to be reproduced on 113f8de9b1579185068ade583b89ca9887f60aef

https://github.com/user-attachments/assets/51238b02-8d90-4742-b6e7-dad0e8bf8497

**Comment by iriv24** [comment]
Can confirm it happens with mego evos as well, double battle against one trainer with mons each with a mega stone
![doublemega](https://github.com/user-attachments/assets/46228d59-406c-4330-b32f-5a1348bc34d3)

**Comment by DeusGrim** [comment]
Had anyone checked if dynamax is still having the issue also i posted it like a week ago but all the gimmicks are having the same issue. Seems to be an overarching situation and not a specific gimmick problem

**Comment by pkmnsnfrn** [comment]
@DeusGrim it is being worked on. you are right. https://github.com/rh-hideout/pokeemerald-expansion/pull/5235

**Comment by DeusGrim** [comment]
Once the issue is fixed, is it possible to make it configurable? it would make for an interesting configuration for double battles.

**Comment by pkmnsnfrn** [comment]
> Once the issue is fixed, is it possible to make it configurable? it would make for an interesting configuration for double battles.

I cannot imagine anybody in the Senate would approve of intentionally adding incorrect behavior and a config that we would then need to maintain

but I've been wrong before. I would vote no, but if you're serious, bring it up in https://discord.com/channels/419213663107416084/1233459650578350081
