### ISSUE TITLE
Zigzagoon at the start of the game using Dynamax gimmick or Tera

### ISSUE THREAD

**Issue by RWXOLIVE** [rh-hideout/pokeemerald-expansion#5128]
### Description

Zigzagoon at the start of the game using Dynamax gimmick or Tera

After digging through trying to figure out why the Zigzagoon is dynamaxing, I've opted to add it the list of Pokemon that cant dmax. (battle.dynamax.c)

After adding this is opted for tera
![image_2024-08-10_002313208](https://github.com/user-attachments/assets/2a3cac36-9c83-4ab5-a40a-c8f0d8ead946)

https://github.com/user-attachments/assets/c3645037-70c9-420e-b052-42b1802577cd

### Version

1.9.0 (Latest release)

### Upcoming/master Version

Master

### Discord contact info

RWXOLIVE

**Comment by Bassoonian** [comment]
Fixed by #5129
