### ISSUE TITLE
Double Dynamax

### ISSUE THREAD

**Issue by DeusGrim** [rh-hideout/pokeemerald-expansion#5143]
### Description

currently during double battles if a player hasn't dynamaxed while on player's turn the dynamax gimmick can be activated for both the players pokemon on that turn.
![pokeemerald-0](https://github.com/user-attachments/assets/99f9079f-1f19-45e0-b01f-04aea3a4a1b5)

### Version

1.9.0 (Latest release)

**Comment by AlexOn1ine** [comment]
At this point it is fair to say that all gimmick can be triggered twice in a double. See #5125
