### ISSUE TITLE
Round preventing Pokemon to make a Move

### ISSUE THREAD

**Issue by TerraPrograms** [rh-hideout/pokeemerald-expansion#5148]
### Description

If the AI manages to setup a double Round, it can change the Turnorder dynamically. This seems to create some issues and can make one of the Players Pokemon unable to move. Here is a clip for reference where Leavanny was not allowed to get its move off. (It's not because of Throat Spray, I tested further with this)
Note: The Partner switching out is necessary to recreate this. For some reason it has to be the Pokemon in the right switching out to trigger this Bug.

https://github.com/user-attachments/assets/aeb9bb9b-528e-43ec-b849-f9615755e751

### Version

1.9.0 (Latest release)

### Discord contact info

._.terra._.

**Comment by hedara90** [comment]
I did some investigation into this and wrote tests for Round. But I couldn't immediately find what the cause was.
Turn order was unchanged before and after the first Round usage.
It might be something in `src/battle_script_commands.c:TryUpdateRoundTurnOrder`.
```
[WARN] GBA Debug:	Round Used
[WARN] GBA Debug:	0: 2
[WARN] GBA Debug:	1: 1
[WARN] GBA Debug:	2: 3
[WARN] GBA Debug:	3: 0
[WARN] GBA Debug:	Round Used
[WARN] GBA Debug:	0: 2
[WARN] GBA Debug:	1: 1
[WARN] GBA Debug:	2: 3
[WARN] GBA Debug:	3: 0
```

**Comment by TerraPrograms** [comment]
> I did some investigation into this and wrote tests for Round. But I couldn't immediately find what the cause was. Turn order was unchanged before and after the first Round usage. It might be something in `src/battle_script_commands.c:TryUpdateRoundTurnOrder`.
> 
> ```
> [WARN] GBA Debug:	Round Used
> [WARN] GBA Debug:	0: 2
> [WARN] GBA Debug:	1: 1
> [WARN] GBA Debug:	2: 3
> [WARN] GBA Debug:	3: 0
> [WARN] GBA Debug:	Round Used
> [WARN] GBA Debug:	0: 2
> [WARN] GBA Debug:	1: 1
> [WARN] GBA Debug:	2: 3
> [WARN] GBA Debug:	3: 0
> ```

I also did some investigations, and while they were to no avail, I wanna share my suspicion. I looked at TryUpdateRoundTurnOrder and thought it looked fine.  I believed the issue lies somehow with the line `gActionsByTurnOrder[i] = B_ACTION_CANCEL_PARTNER;` in `Cmd_switchineffects`. Since TryUpdateRoundTurnOrder uses gActionsByTurnOrder
But take this with a grain of salt because I am a lot less experienced with the codebase than you and understand a lot less what is going on.
