### ISSUE TITLE
Micle Berry Issues

### ISSUE THREAD

**Issue by TerraPrograms** [rh-hideout/pokeemerald-expansion#5149]
### Description

Micle Berry seems to not work properly. It is supposed to multipliy the accuracy of the holder's **next** move by 1.2, which means the effect can carry on to the next turn (At least that's how I understand it to work, feel free to correct me if I am wrong). But the effect just wears off once the Turn ends, resulting in no effect.

Here is an example to demonstrate. Megahorns Accuracy boosted with Micle Berry is 102%, which means it should always hit with the Micle Berry effect. 

https://github.com/user-attachments/assets/caa3f8d1-755c-4cfe-a5f5-8682e601a2ff

### Version

1.9.0 (Latest release)

### Discord contact info

._.terra._.

**Comment by AlexOn1ine** [comment]
is there any other berry that works like that?

**Comment by TerraPrograms** [comment]
> is there any other berry that works like that?

I believe Micle Berry is the only one

**Comment by Pawkkie** [comment]
I just tested this on Showdown, and at least as far as Showdown is concerned, this effect _does_ go across turns. It even has a message indicating as such.

![image](https://github.com/user-attachments/assets/b765835c-fb97-4d36-b81d-9d79800c0c03)


https://github.com/user-attachments/assets/a860e7ae-7228-4acb-81f4-8b951cfc3b28
