### ISSUE TITLE
Ice Face doesn't regenerate after switching in during Hail

### ISSUE THREAD

**Issue by TerraPrograms** [rh-hideout/pokeemerald-expansion#5150]
### Description

Title. 

Quote Bulbapedia: "When an Eiscue that's in its Ice Face form is hit by a physical move, it takes no damage and changes into its Noice Face form. If a hailstorm or snowstorm begins while Eiscue is in its Noice Face form, **or if it is sent out in its Noice Face form during hail**, it will immediately revert to its Ice Face form."

Clip: 
https://github.com/user-attachments/assets/50bdb047-231f-4cf9-ba42-6d34ac7fa135

### Version

1.9.0 (Latest release)

### Discord contact info

._.terra._.

**Comment by hedara90** [comment]
Fixed by #5171
