### ISSUE TITLE
Salac Berry Activation Timing issues

### ISSUE THREAD

**Issue by TerraPrograms** [rh-hideout/pokeemerald-expansion#5152]
### Description

https://github.com/user-attachments/assets/8cfbb9c1-ffab-4eb1-be6d-a545b7569f94

Passive Damage (Toxic Poison in this case) seems to mess with the Activation timing. When Arcanine drops to 16 HP, Salac Berry is supposed to immediately activate. But it only gets activated after using the next move.
Didn't test other berries but more berries are very likely affected.

### Version

1.9.0 (Latest release)

### Discord contact info

._.terra._.

**Comment by AlexOn1ine** [comment]
This will be either fixed in #5036 or a simple fix right now could be adding `ENDTURN_ITEMS3` before `ENDTURN_BATTLER_COUNT`
