### ISSUE TITLE
`FRONTIER_BRAIN_SPRITES` needs to be removed

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#5164]
### Description

`FRONTIER_BRAIN_SPRITES` very unintuitively also determines the trainer ID. This macro should be removed.

### Version

upcoming (Edge)

**Comment by AlexOn1ine** [comment]
Also `TRAINER_BACK_SPRITE` and `TRAINER_SPRITE` or modified so the define becomes searchable.

**Comment by Bassoonian** [comment]
#5166
