### ISSUE TITLE
Pokémon with less than 16 max HP do not take damage from Sandstorm

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#5180]
### Description

# Testing Script
```diff
Debug_EventScript_Script_1::
+	setflag FLAG_BADGE01_GET
+	setflag FLAG_BADGE02_GET
+	setflag FLAG_BADGE03_GET
+	setflag FLAG_BADGE04_GET
+	setflag FLAG_BADGE05_GET
+	setflag FLAG_BADGE06_GET
+	setflag FLAG_BADGE07_GET
+	setflag FLAG_BADGE08_GET
+    givemon SPECIES_WEEDLE,2,ITEM_FOCUS_SASH,hpEv=252,hpIv=252,move1=MOVE_CELEBRATE
+    givemon SPECIES_WEEDLE,3,ITEM_FOCUS_SASH,hpEv=0,hpIv=252,move1=MOVE_CELEBRATE
+    givemon SPECIES_WEEDLE,3,ITEM_FOCUS_SASH,hpEv=92,hpIv=252,move1=MOVE_CELEBRATE
+    setwildbattle SPECIES_TYRANITAR,38,0
+    dowildbattle
	release
	end

```

# Steps
1. Run Script 1
2. Use Celebrate with first Weedle
3. Expected first Weedle should get hit with an attack, survive with 1 HP, then faint from Sandstorm damage
4. First Weedle takes no sandstorm damage

# Video

https://github.com/user-attachments/assets/a49497b5-a00d-40d8-854e-0aab50cad429

### Version

1.9.0 (Latest release)

### Upcoming/master Version

25f7f431fa

### Discord contact info

pkmnsnfrn

**Comment by AlexOn1ine** [comment]
#5183
