### ISSUE TITLE
Pokemon's Stats are not consistently generated

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#5181]
### Description

# Testing Script
```diff
Debug_EventScript_Script_1::
+	setflag FLAG_BADGE01_GET
+	setflag FLAG_BADGE02_GET
+	setflag FLAG_BADGE03_GET
+	setflag FLAG_BADGE04_GET
+	setflag FLAG_BADGE05_GET
+	setflag FLAG_BADGE06_GET
+	setflag FLAG_BADGE07_GET
+	setflag FLAG_BADGE08_GET
+    givemon SPECIES_WEEDLE,2,ITEM_FOCUS_SASH,hpEv=252,hpIv=252,move1=MOVE_CELEBRATE
+    givemon SPECIES_WEEDLE,3,ITEM_FOCUS_SASH,hpEv=0,hpIv=252,move1=MOVE_CELEBRATE
+    givemon SPECIES_WEEDLE,3,ITEM_FOCUS_SASH,hpEv=92,hpIv=252,move1=MOVE_CELEBRATE
+    special ChoosePartyMon
	release
	end

```

# Steps
1. Run Script 1
2. Observe HP values
3. Reboot
4. Run Script 1
5. Observe HP Values
6. HP Values from Step 2 and 5 SHOULD match, but they sometimes do not.

# Video

https://github.com/user-attachments/assets/c6ef0822-5fe0-4139-a9e0-8a89821e997b

https://github.com/user-attachments/assets/056dd6c7-17ea-471d-ac20-f895596799bd

### Version

upcoming

### Upcoming/master Version

25f7f431fa

### Discord contact info

pkmnsnfrn

**Comment by AlexOn1ine** [comment]
mentioned by hedara already but the hpIv is illegal.
