### ISSUE TITLE
Gulp Missile ability should not be traceable

### ISSUE THREAD

**Issue by wiz1989** [rh-hideout/pokeemerald-expansion#5184]
### Description

By definition Trace cannot copy Gulp Missile since it is a form changing ability.
![grafik](https://github.com/user-attachments/assets/d5ae8b76-f887-408a-9484-61e4bea7b07a)

### Version

1.8.5

### Discord contact info

wiz1989

**Comment by AlexOn1ine** [comment]
see comment from kittenchilly #5185
