### ISSUE TITLE
Tera types should carry over when they evolve

### ISSUE THREAD

**Issue by AlexOn1ine** [rh-hideout/pokeemerald-expansion#5205]
### Description

The current implementation doesn't carry over the current tera type of a pokemon once it evolves which is not vanilla

### Version

1.9.0 (Latest release)

**Comment by AsparagusEduardo** [comment]
A potential solution for this could be to set the Tera type upon evolution

**Comment by ShinyDragonHunter** [comment]
Could you not just do it so it's not changed once it's set unless the shards are used?

**Comment by Bassoonian** [comment]
> A potential solution for this could be to set the Tera type upon evolution

I was thinking the same! Would also need to be set upon form change to account for forms changing types. Seems like the least invasive fix that is also backwards-compatible

**Comment by pkmnsnfrn** [comment]
https://github.com/rh-hideout/pokeemerald-expansion/pull/5424 means that this is still open

**Comment by AlexOn1ine** [comment]
duplicate #4530
