### ISSUE TITLE
AI's caulcation of "hitsToKO" factors in held items

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#5218]
### Description

If the AI knows the enemy is holding an item that would increase the number of hits required to KO (Focus Sash, Occa Berry, Focus Band, Ganlon Berry), then this is factored into the decision making.

### Discord contact info

Pawkkie

**Comment by AlexOn1ine** [comment]
it does recognize Resist Berries. Focus Band is a gimmick item that should be considered as something that would prevent death. Agree on the other points so Focus Sash and Sturdy abilities.

**Comment by Pawkkie** [comment]
Closed by #5371 , #5373, and #5375
