### ISSUE TITLE
Pivot moves take speed into account

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#5220]
### Description

When deciding if to use Volt Switch or U-Turn, the AI will check their speed against the enemy. 

If the AI is 
* slower, it will switch offensively (because the new mon will not need to take a hit)
* faster, it will switch defensively (becuase the new mon will need to take a hit - this is current default)

### Discord contact info

Pawkkie

**Comment by Pawkkie** [comment]
Closed by #5379
