### ISSUE TITLE
AI does not recognize benefits from Contrary

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#5222]
### Description

> The AI did not recognize its partner benefited from Contrary and preferred to use other moves. When it only had Skill Swap, it gave Contrary to the player. 

# Flags Used
`AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_TRY_TO_FAINT | AI_FLAG_CHECK_VIABILITY | AI_FLAG_HELP_PARTNER`

# AI Team
```
Spinda
Ability: Contrary
- Skill Swap
- Encore
- Fake Tears
- Swagger

Arcanine
Ability: Intimidate
- Extremespeed
- Morning Sun
- Close Combat
- Overheat
```

> The goal is to have Spinda use Skill Swap first turn on Arcanine, giving it Contrary for [Overheat / Close Combat] and triggering Intimidate on the player again. Instead, Spinda [tends] to [use] Swagger [on] the player while Arcanine uses Close Combat.

### Version

master (default, unreleased bugfixes)

### Discord contact info

Jinnora

**Comment by Pawkkie** [comment]
Addressed by #5360
