### ISSUE TITLE
AI does not recognize when to stop using defensive moves

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#5223]
### Description

> I've had mons spam Max Guard and sometimes setup even though already at the maximum stat stage

### Version

master (default, unreleased bugfixes)

**Comment by Pawkkie** [comment]
Is there any shot you have any more information on who provided this bug report / are they willing to investigate providing any steps to reproduce?

**Comment by pkmnsnfrn** [comment]
They didn't give their name. :(

**Comment by Pawkkie** [comment]
I vote we close this, we have no information about the context in which this behaviour was occurring or how to reproduce it, and I haven't been able to just *make it happen* by messing around. Thoughts?
