### ISSUE TITLE
Showing what the Partner Ai will use in multi-battles 

### ISSUE THREAD

**Issue by Awakeon** [rh-hideout/pokeemerald-expansion#5233]
### Description

A common problem in romhacks that have multi-battles is that the  Partner Ai can feel very unpredictable and seem to even screw you over on occasion. This happens a lot in radical red and inclement Emerald (just the first 2 that jumped into my head) to help with this being able to see who the Partner Ai is about to target should drastically help with this. If you knew who the Partner Ai was targeting it makes planning way more predictable, allows you to actually play with the Ai instead of being annoyed by it. 

This can work by having an option (with whatever button is available) that allows you see what move the partner Ai is about to use and who they are targeting. 

### Discord contact info

awakeon

**Comment by AlexOn1ine** [comment]
do you have suggestions how it would be shown in the interface?

**Comment by hedara90** [comment]
![pokeemerald-3](https://github.com/user-attachments/assets/3f38ea09-b362-42e3-b7a6-1be1d6dfd3f9)

Replacing "What will <Pokemon> do?" with what the ally would do could maybe work?

**Comment by Awakeon** [comment]
> ![pokeemerald-3](https://github.com/user-attachments/assets/3f38ea09-b362-42e3-b7a6-1be1d6dfd3f9)
> 
> 
> 
> Replacing "What will Pokemon do?" with what the ally would do could maybe work?
> 
> The prompt for what the player pokemon will do seems mostly redundant in a multi-battle.

Yeah this works just fine, there might be issues with moves with long names but just letting the player know who the Ai wants to attack should suffice.

I was thinking, You know when you press R to throw your most recent Pokéball so what if in a multi-battle when you pressed R you get a text box that says who the Ai is targeting and the move they are going to use which fixes the whole long name issue.

**Comment by AlexOn1ine** [comment]
#5307
