### ISSUE TITLE
exp from trainer battles remains low

### ISSUE THREAD

**Issue by carpheart** [rh-hideout/pokeemerald-expansion#527]
I'm not sure this is a common issue, but I made it past Watson and halfway into route 111 when I noticed I was still earning about 30 exp per pokemon in trainer battles.

I've since restarted and the issue isn't in my new game.

I can't code or anything, but I'll provide any additional information if needed.

**Comment by carpheart** [comment]
I played through this section again and now the expirence seems to have capped out at 71 exp per pokemon.

There is definitely an issue with the expirence earned in the game. I'll play through it once more and report my findings. Maybe I can pinpoint when the experience locks up.

**Comment by carpheart** [comment]
Actually, I think I've figured it out

I had a lvl. 8 teddiursa as my HM whore. I tested it with a few other pokemon and the expirence you receive seems to be limited by the level of the lowest pokemon in your party. The lower the level, the lower your expirence is capped at. That is unless that pokemon takes part in the battle. Under that circumstance, xp is limited on your higher level pokemon, and all other expirence is awarded to the lower level pokemon. For example, in one battle, my grovyle earned 12 exp while a lvl 5 hoothoot I was experimenting with earned ~700 exp.

I hope this helps.
I really love the project and the work you're doing!

**Comment by ShinyDragonHunter** [comment]
Are you in the RH Hideout Discord? You may get more help and feedback from there. The Discord isn’t just for this either, it’s a community full of people who are willing to help if you needed it

**Comment by AsparagusEduardo** [comment]
Is there a savefile you can provide for further testing?

**Comment by carpheart** [comment]
I have 2 different save files from 2 completely different games
[Pokemon Mega Moemon Emerald v0.4.2 - Extra Overworld Sprites sav 2.zip](https://github.com/rh-hideout/pokeemerald-expansion/files/5425000/Pokemon.Mega.Moemon.Emerald.v0.4.2.-.Extra.Overworld.Sprites.sav.2.zip)
[pokesaves.zip](https://github.com/rh-hideout/pokeemerald-expansion/files/5425010/pokesaves.zip)


 which I will attach below.
Both of them are saved in the pokecentre of mauville city by the PC. Any trainers left to fight are north in route 111 or near mt. chimney.

I've since done some more testing and the experience being capped does not seem to be effected by which type the low level pokemon is, just that it is a lower level.
I've since started a third game and the issue is still persistent, but its too soon to confirm.
I'm playing version 0.4.2 if that's what you mean by build. I'll link to where I downloaded it from if you need an exact copy. But i can't imagine i'm the only one with this issue if its happened 3 times in a row for 
[Pokemon Mega Moemon Emerald v0.4.2 - Extra Overworld Sprites sav 1.zip](https://github.com/rh-hideout/pokeemerald-expansion/files/5424999/Pokemon.Mega.Moemon.Emerald.v0.4.2.-.Extra.Overworld.Sprites.sav.1.zip)

me.
https://www.mediafire.com/file/pjceyeged1k011f/Pokemon_Mega_Moemon_Emerald_v0.4.2_-_Extra_Overworld_Sprites.zip/file

I've tested my save files on the Myboy! and Visualboyadvance emulators.

**Comment by carpheart** [comment]
I don't know why it wasn't showing my uploads before I commented, but "pokesaves.zip" contains the two .sav files and the other two are the game each with one the the save files.

**Comment by ExpoSeed** [comment]
From the creator, Leafjewel: "It's probably just MME and people not training their lower leveled mons. Yeah, the Teddiursa as the HM slave is probably the culprit. If they trained it or took it out of the party, then exp gains would go back up."

This isn't a bug on our end, it's related to MME's exp formula.
