### ISSUE TITLE
Slateport Battle Tent/Battle Factory zeroes out player party if "REST" option is chosen

### ISSUE THREAD

**Issue by SarnPoke** [rh-hideout/pokeemerald-expansion#5280]
### Description

NOT A DUPE OF #5082

When choosing to rest in either the Battle Factory or the Slateport Battle Tent, the player's party will be replaced with "??????????" after the game restarts.
1. Win a battle in the Battle Tent/Factory.
2. Choose "REST".
3. After game reload, choose "GO ON".
4. All of player's mons will now be "??????????".

Video:

https://github.com/user-attachments/assets/6b2f28f8-61bd-43d0-860c-2b3a08f746e7

### Version

1.9.1 (Latest release)

### Discord contact info

sarnnn

**Comment by pkmnsnfrn** [comment]
This was broken by 5a986c6d04c96090c77d1471472220e928466cb0.
the commit before it, b58ccac4bf does not have this problem.
