### ISSUE TITLE
Cinderace Gigantamax back sprite is missing a row of pixels

### ISSUE THREAD

**Issue by lhearachel** [rh-hideout/pokeemerald-expansion#5294]
### Description

The left ear is missing a row of pixels before it connects with the BG-layer used by the text box.

![image](https://github.com/user-attachments/assets/72ae9398-209f-4507-920c-fc1dfac161d2)

### Version

1.9.1 (Latest release)

### Discord contact info

lhea

**Comment by hedara90** [comment]
There is an issue for sprite issues in general, #5135, I update the main post of that with things mentioned in the comments.
Makes the issues a bit less cluttered.
