### ISSUE TITLE
If Max Guard protects against a Max Move, no attack string is printed

### ISSUE THREAD

**Issue by hedara90** [rh-hideout/pokeemerald-expansion#5311]
### Description

https://github.com/user-attachments/assets/d9bcea59-b9f3-4743-8aeb-b6f28fcec150

Potentially fixed by moving `attackstring` in `BattleScript_EffectMaxMove` to be before `attackcanceler`, but I'm unsure of side-effects of this approach.

### Version

master (default, unreleased bugfixes)

### Discord contact info

hedara

**Comment by AlexOn1ine** [comment]
if you move attackstring before attackcanceler the attackstring will still get printed even if the move fails.
