### ISSUE TITLE
Lycanroc midday overworld sprite using wrong color

### ISSUE THREAD

**Issue by Kasenn** [rh-hideout/pokeemerald-expansion#5319]
### Description

Lycanroc midday form uses color 0 for the actual sprite, making it partially see-through.
![image](https://github.com/user-attachments/assets/110eeb8f-ed2c-4885-ab9a-7dd47a43b15f)

### Version

1.9.1 (Latest release)

**Comment by hedara90** [comment]
Fixed by #5336
