### ISSUE TITLE
Pledge moves can infinitely loop their attack message if an opponent's combo doesn't happen

### ISSUE THREAD

**Issue by PhallenTree** [rh-hideout/pokeemerald-expansion#5329]
### Description

This test times out. Upon looking at the .elf file, the `attackstring` kept being printed over and over, potentially related to the fact the combo attempted by the opponent failed.

```
DOUBLE_BATTLE_TEST("Pledge move combo doesn't trigger on opponent's Pledge move")
{
    GIVEN {
        PLAYER(SPECIES_WOBBUFFET) { Speed(4); }
        PLAYER(SPECIES_WYNAUT) { Speed(3); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(8); }
        OPPONENT(SPECIES_WYNAUT) { Speed(5); Status1(STATUS1_SLEEP_TURN(2)); }
    } WHEN {
        TURN { MOVE(opponentLeft, MOVE_FIRE_PLEDGE, target: playerLeft);
               MOVE(opponentRight, MOVE_GRASS_PLEDGE, target: playerLeft); 
               MOVE(playerLeft, MOVE_GRASS_PLEDGE, target: opponentRight); }
    } SCENE {
        NONE_OF {
            ANIMATION(ANIM_TYPE_MOVE, MOVE_FIRE_PLEDGE, opponentLeft);
            ANIMATION(ANIM_TYPE_MOVE, MOVE_FIRE_PLEDGE, opponentRight);
            ANIMATION(ANIM_TYPE_MOVE, MOVE_GRASS_PLEDGE, opponentRight);
            ANIMATION(ANIM_TYPE_MOVE, MOVE_FIRE_PLEDGE, playerLeft);
        }
        ANIMATION(ANIM_TYPE_MOVE, MOVE_GRASS_PLEDGE, playerLeft);
        HP_BAR(opponentRight);
    }
}
```

https://github.com/user-attachments/assets/29d8f7d3-1ed9-4958-a474-6ed44d8ebdb0

Confirmed this happens in normal battles as well:

https://github.com/user-attachments/assets/21eca205-af5e-4497-955e-842cf8bb7e42

### Version

upcoming (Edge)

### Upcoming/master Version

https://github.com/rh-hideout/pokeemerald-expansion/commit/4f393541855e35e1c5bbc2b98ffd1207cb36378b

### Discord contact info

PhallenTree

**Comment by hedara90** [comment]
Related to #5041 ?

**Comment by PhallenTree** [comment]
Maybe to this part 

> "If the turn order goes opponentRight -> playerRight -> opponentLeft, playerRight will repeat their last move before the opponents combo executes, and it will not loop. If it's playerLeft instead of playerRight the player does not move between combo call and execution."
