### ISSUE TITLE
Laser Focus doesn't work

### ISSUE THREAD

**Issue by SarnPoke** [rh-hideout/pokeemerald-expansion#5335]
### Description
Currently, Laser Focus does not result in a guaranteed critical hit for the user on the turn following the use of the move.

### Video

https://github.com/user-attachments/assets/3f71bf93-1c31-466e-9a1e-8c87cecb75ff

### To reproduce

1. Use Laser Focus in battle.
2. Use an attacking move.

### Version

1.9.1 (Latest release)

### Discord contact info

sarnnn

**Comment by hedara90** [comment]
Can you reproduce this on latest `master`?
I tried to reproduce it, but the Laser Focus test passes, as does 15 manual checks in game.

**Comment by SarnPoke** [comment]
Issue was tested in the Zigzagoon tutorial battle. Will close.
