### ISSUE TITLE
Remove Deoxys Hack 

### ISSUE THREAD

**Issue by ExpoSeed** [rh-hideout/pokeemerald-expansion#534]
Currently, the Deoxys hack does not function properly, displaying the wrong graphics because graphics have been changed. This should be altered or removed to function as intended.

**Comment by LOuroboros** [comment]
It's worth to mention that alongside the battle sprites not working correctly, the base stats of the SPECIES_DEOXYS are probably being modified by functions like `GetDeoxysStat` or `SetDeoxysStats`, so those would need to go too.

**Comment by ShinyDragonHunter** [comment]
https://github.com/ShinyDragonHunter/pokefirereddx/commit/0b6871a79c884a3139f23d559967651653ba55a5

https://github.com/ShinyDragonHunter/pokefirereddx/commit/2a9627c44662fbbbf3b497a702dc203417d596d2

I have here two commits that may help towards the removal of the Deoxys hack. First one removes the decompression function for Deoxys and moves the Deoxys pic loading into the one function and you’d follow that one to remove the `handleDeoxys` or `DontHandleDeoxys` etc and then you’d follow the second link to remove the actual forme stuff for Deoxys.

**Comment by ultima-soul** [comment]
Resolved in #1311.
