### ISSUE TITLE
Opponent sprites disappear after being defeated

### ISSUE THREAD

**Issue by satanicswirlix** [rh-hideout/pokeemerald-expansion#5342]
### Description

After defeating a trainer in battle, their sprite will disappear, and the player's will slide in instead, causing your Pokemon's palette to change.

https://github.com/user-attachments/assets/8cf03525-d661-4578-8eff-d30f024eb457

![bug](https://github.com/user-attachments/assets/4531947f-6c00-494f-b281-2e88b415f3c3)

### Version

1.9.1 (Latest release)

### Discord contact info

brooksanyuri

**Comment by AlexOn1ine** [comment]
Can't confirm. Have you tested on an expansion rom?

**Comment by satanicswirlix** [comment]
> Can't confirm. Have you tested on an expansion rom?

Yes, I forgot to say this is on an unmodified rom of pokeemerald-expansion. It happens when playing as May too.

**Comment by hedara90** [comment]
I can confirm it.
![pokeemerald-0](https://github.com/user-attachments/assets/c4ee31f9-1898-4630-87de-b9108f48a3ec)

**Comment by hedara90** [comment]
#5326 Is the cause. Before that it doesn't happen. And reverting it makes the problem disappear.
Seems to be that scripts weren't updated for the change.
