### ISSUE TITLE
Loading Into Maps with Multiple Layouts is Broken

### ISSUE THREAD

**Issue by iriv24** [rh-hideout/pokeemerald-expansion#5343]
### Description

Just tested this on clean upcoming, haven't tested in master yet.
If you are on a map that has multiple different layouts (the relevant maps can be determined by searching for `setmaplayoutindex`, so far I've seen this behavior on Route 111, Sootopolis, and in Shoal Cave) and you save your game, close it, then load it back up, the area past the edges of the screen won't load the correct map layout. See GIFs for behavior:

First GIF: in Shoal Cave, everything is normal, saving the game
![shoalcave1](https://github.com/user-attachments/assets/23978833-25d2-422c-81e1-9e762c4086c1)

Second GIF: after saving and closing the game, loaded back up. Past the edges of my screen, the map layout for low tide shoal cave gets loaded, even though when I saved it, it was high tide
![shoalcave2](https://github.com/user-attachments/assets/ba32f5b3-8302-4457-bac3-027712cd5121)

I've seen the same thing happen where saving on Route 111 with Mirage Tower off screen, then loading back up will cause Mirage Tower to always be there, even if you've already grabbed a fossil and it faded away.
Same thing in Sootopolis with the layouts with the legendaries battling vs normal Sootopolis.

### Version

upcoming (Edge)

### Discord contact info

iriv24

**Comment by Liamjd14** [comment]
Dont know if this helps but i con confirm this also happens on the master branch as well (tested with a fresh clone)

**Comment by hedara90** [comment]
I've made a fix for this issue, if you could test as much as possible that would be nice.
