### ISSUE TITLE
Add config for Mega Evolution turn order

### ISSUE THREAD

**Issue by ExpoSeed** [rh-hideout/pokeemerald-expansion#535]
Gen 6:
> In Generation VI, performing Mega Evolution will not alter the turn order. A Pokémon with a lower Speed than their opponent will still go after them on the one turn the Mega Evolution occurs, even if their Mega Evolution increases Speed and would otherwise cause them to go first. The opposite is also true for Pokémon who lose Speed from Mega Evolution, such as Garchomp. However, turn order will be determined normally on every turn afterwards.
> 
> Likewise, even if a Pokémon only has an Ability such as Prankster before Mega Evolution, appropriate moves will gain priority. If a Pokémon gains Prankster upon Mega Evolution, appropriate moves will not gain priority.

Gen 7: 
> In Generation VII, a Pokémon's Speed after Mega Evolution is used to determine turn order, not its Speed before. Likewise, if a Pokémon only has an Ability such as Prankster before Mega Evolution, appropriate moves will not gain priority. If a Pokémon gains Prankster upon Mega Evolution, appropriate moves will gain priority.

This change has a large impact on how battles with Mega Evolution play out. For instance, Gen 6 M-Sableye gets both Magic Bounce and Prankster benefits on the turn it evolves, while M-Diancie and M-Beedrill outright require protect due to being both frail and slow on the turn they Mega Evolve.

**Comment by AsparagusEduardo** [comment]
#1918
