### ISSUE TITLE
Add support for starting double battles with only one party member

### ISSUE THREAD

**Issue by Pyredrid** [rh-hideout/pokeemerald-expansion#537]
In RSE, double battles started while the player only has a single pokemon leads to buggy and undefined behaviour.  Its why the script command `trainerbattle_double` checks for the player's party count, and why Tate & Liza won't even start a battle unless the player has 2 pokemon with them, despite this blocking progression.

Later generations handled this edgecase by letting the player start the double battle, and they'd only send out their one pokemon.

**Comment by AsparagusEduardo** [comment]
#1538
