### ISSUE TITLE
NPC Trainer Repeatedly Uses Switcheroo Without Held Item

### ISSUE THREAD

**Issue by sixtycardpickup** [rh-hideout/pokeemerald-expansion#5411]
### Description

Enemy trainer’s Minun uses Switcheroo repeatedly (video only shows once, but it happened ~5 times in a row before Minun used Spark) when it is not holding an item & I don’t think trainer/Minun had any reason to expect receiving an item before using Switcheroo.
In case Minun’s initial battle state is relevant, Minun started the battle holding a berry.

https://github.com/user-attachments/assets/ebbdb263-1a3f-448f-b5aa-891a9acd43ca

AI flags:
```AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_TRY_TO_FAINT | AI_FLAG_CHECK_VIABILITY | AI_FLAG_SMART_SWITCHING | + any automatically assigned to double battles. | [and I think also] AI_FLAG_OMNISCIENT ```

### Version

1.9.2 (Latest release)

### Upcoming/master Version

Master

### Discord contact info

sixty_card_pickup

**Comment by hedara90** [comment]
Tested a bit.
After the berry is consumed, Switcheroo gets the same score as an attack.
![pokeemerald-0](https://github.com/user-attachments/assets/d99762e1-b4d6-48b8-876c-0781cba2faa7)

**Comment by hedara90** [comment]
I tracked it down to here in `src/battle_ai_main.c`
![20240921_18h00m22s_grim](https://github.com/user-attachments/assets/381c7056-487d-43c1-ac76-28f4c4e1e58d)

It doesn't seem to take into account if the target has an item, even if it has already tried to use Switcheroo and it failed.
