### ISSUE TITLE
Primal Reversion not Always Activating in Double Battles

### ISSUE THREAD

**Issue by iriv24** [rh-hideout/pokeemerald-expansion#5425]
### Description

I don't know if I narrowed down the _only_ condition that causes this, but the one I can reproduce the most consistently is:
In a double battle, both opposing mons get KO'ed AND one of your mons gets KO'ed all in one turn. 
You then choose a mon to throw out, then opponent throws out both their mons. 
If both their mons have the ability to do a primal reversion, only one of them does it.
I'm not sure if there are other scenarios that cause only one mon to primally revert in a double battle. I believe the expected behavior is that they will both revert.

Sorry the video is in the middle of a turn, it was too long if i did the full turn. this is turn one, i had a torchic who i KO'ed with EQ, which also took out the opposing 2 mons.

https://github.com/user-attachments/assets/bbbc5acd-05be-4866-b77f-c145aadbee8d

![pokeemerald-0](https://github.com/user-attachments/assets/5f1d59e2-0193-4f1f-ba49-cba5be7fac5f)

I was able to reproduce on master and upcoming

### Version

1.9.2 (Latest release)

### Discord contact info

iriv24

**Comment by AlexOn1ine** [comment]
duplicate issue #5427
