### ISSUE TITLE
Berry Mutations always yield a Persim Berry

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#5432]
# Description

According to `sBerryMutations`, there are no permutations of berries that should create the Persim Berry.

Whenever a berry is planted, grown and picked OR picked from vanilla AND when Mutations are turned on, a Persim Berry is granted as the mutation.

I believe this means there are two at least problems:
- Berries ALWAYS mutate, even when `OW_BERRY_MUTATION_CHANCE` is set to  25.
- Mutations always yield Persim, even though Persim is never possible.
	- This could also be "Persim Berry is granted when it should always be zero". 

# Replication

`wget https://files.catbox.moe/4cnxn0.inc -O data/scripts/debug.inc && wget https://files.catbox.moe/l0focv.h -O include/config/overworld.h`

## Steps
1. Start a new game
2. Run Debug > Scripts > Script 1
3. Pick Oran Berry on Route 104 (Expected just Oran Berry, also got Persim Berry)
4. Pick Cheri Berry on Route 104 (Expected just Oran Berry, also got Persim Berry)
4. Plant Lum Berry
5. Plant Sitrus Berry
6. Plant Liechi Berry
7. Plant Ganlon Berry
8. Run Debug > Utilities > Berry Functions > Ready Map Trees
9. Pick all trees, observing they all yield Persim berries as well as original Berry
10. Plant any Berry
11. Water planted Berry
12. Run Debug > Utilities > Berry Functions > Grow Map Trees
13. Repeat 11 and 12 3 more times
14. Pick trees, observing they all yield Persim berries as well as original Berry
15. Run Debug > Scripts > Script 2
16. Pick any Berry on Route 123 (Expected just single Berry, also got Persim Berry)

# Videos
## Ready Map Trees
https://github.com/user-attachments/assets/0ca8edb3-c91c-4848-91fa-140f63278beb

## Grow Map Trees
https://github.com/user-attachments/assets/df3138bd-d2cf-41ea-bab4-5622dffaa120

## Vanilla Trees
https://github.com/user-attachments/assets/a30d1352-977b-46e1-89a0-8fbe0156de1f

### Version

upcoming (Edge)

### Discord contact info

pkmnsnfrn

**Comment by sixtycardpickup** [comment]
I've got this one too, if that helps to confirm bug status.
