### ISSUE TITLE
Uproar test potentially wrong

### ISSUE THREAD

**Issue by ghoulslash** [rh-hideout/pokeemerald-expansion#5445]
### Description

The uproar test (https://github.com/rh-hideout/pokeemerald-expansion/blob/master/test/battle/move_effect/uproar.c#L9) assigns Voltorb soundproof but also expects it to wake up from soundproof, which is incorrect behavior according to <https://github.com/rh-hideout/pokeemerald-expansion/blob/1c022f4d34ef4fdf6a894815fd4b4617b15932ed/src/battle_util.c#L2664>. 

Conversation/GIF starts here: https://discord.com/channels/419213663107416084/1077009799293710357/1290119643612184718

### Version

1.9.2 (Latest release)

**Comment by AlexOn1ine** [comment]
> While a Pokémon is making an uproar, Pokémon cannot fall asleep (even if they have Soundproof or are not adjacent to the Pokémon making the uproar). Pokémon can be made drowsy by [Yawn](https://bulbapedia.bulbagarden.net/wiki/Yawn_(move)), but a drowsy Pokémon cannot fall asleep during an uproar (even if it has Soundproof).

According to Bulbapedia this is correct behavior

**Comment by AlexOn1ine** [comment]
discussed on discord
