### ISSUE TITLE
Test and `make check` documentation

### ISSUE THREAD

**Issue by Pawkkie** [rh-hideout/pokeemerald-expansion#5459]
### Description

New documentation file that includes

- What's the test suite
- What's `make check`
- The currently in-codebase comments explaining how to write tests

**Comment by hedara90** [comment]
Some of these points are handled by [this wiki page](https://rh-hideout.github.io/pokeemerald-expansion/how_to_testing_system.html)

**Comment by Pawkkie** [comment]
> Some of these points are handled by [this wiki page](https://rh-hideout.github.io/pokeemerald-expansion/how_to_testing_system.html)

This is excellent. How do I as a new users who doesn't know where this is find it?

That's not tryna be dense I genuinely don't know where you pulled that link from lol

**Comment by hedara90** [comment]
Wiki->sidebar->show more->testing system->replacement link

**Comment by Pawkkie** [comment]
Okay maybe the actual solution to this is just putting a link to the documentation website directly in the README. I didn't realize there was both a documentation website *and* the `docs` folder and that their contents were different.

**Comment by Pawkkie** [comment]
I was either blind or squinting at the repo weirdly or something, there's already a really thorough guide for this in `docs`. Closing.
