### ISSUE TITLE
Missing Footprints

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#546]
Submitting this issue as a reminder. Currently, the pokemon_expansion branch is missing footprints for every single new species.

I'm getting the Gen. 4 ones out of the way.

**Comment by LOuroboros** [comment]
Droppìng here a few quick links as a reminder, or else they'll get lost if left alone in the server.

Gen. 5 species code for `src/data/pokemon_graphics/footprint_table.h`, `include/graphics.h` and `src/data/graphics/pokemon.h`
https://discord.com/channels/419213663107416084/419214240277200898/770712098354364497

Gen. 6 species code for `src/data/pokemon_graphics/footprint_table.h`, `include/graphics.h` and `src/data/graphics/pokemon.h` and footprint sprites
https://discord.com/channels/419213663107416084/419214240277200898/770703343026176010

**Comment by LOuroboros** [comment]
Finishing work on the Gen. 5 footprints. I'm tweaking the position of some of them before submitting a PR.

**Comment by Blackforest92** [comment]
Pointing a link for Gen 7 and Gen 8 codes [here](https://discord.com/channels/419213663107416084/419214240277200898/772457112315101214).

**Comment by AsparagusEduardo** [comment]
#547, #551, #1600 and #2002
