### ISSUE TITLE
Hidden Power not Working in Various Ways with P_SHOW_DYNAMIC_TYPES set to TRUE

### ISSUE THREAD

**Issue by iriv24** [rh-hideout/pokeemerald-expansion#5461]
### Description

If you set `P_SHOW_DYNAMIC_TYPES` to TRUE and start interacting with Hidden Power, you get some funky stuff.
If you try to teach a mon the TM for Hidden Power, most of the time the game gets to the screen where it would display the moves and it looks like this:
![pokeemerald-1](https://github.com/user-attachments/assets/e7583680-ed52-48f7-afab-5062fd2bdb02)
and then the game freezes.

If you do get Hidden Power onto a mon and try to view their moves in the summary screen, the same behavior happens where it looks like that ^ and then freezes.

And then if you try to see the dynamic type in battle, it looks like this:
![pokeemerald-0](https://github.com/user-attachments/assets/596f9594-2316-44e2-a979-4b9d70176f9e)

Haven't tested other moves that are affected, plz close if this is a duplicate or something.

Saw this on fresh upcoming on 10/2

### Version

upcoming (Edge)

### Discord contact info

iriv24

**Comment by Bassoonian** [comment]
Fixed by #5463
