### ISSUE TITLE
Some followerd change sprites when reloading the game or changing a move in their learnset.

### ISSUE THREAD

**Issue by Liamjd14** [rh-hideout/pokeemerald-expansion#5470]
### Description

When reloading the game or changing the move using a tm/hm or move relerner some pokemon's OW sprites change to a  different one, as seen in the videos below. currently i have tested terapagos and ogerpon. terapagos changes to woobat and ogerpon to simisage. Footage is from a fresh clone on the repo

[terapagos reload save.webm](https://github.com/user-attachments/assets/9ed976ae-0ed0-4c05-99c2-38a511049279)

[terapagos teach hm surf.webm](https://github.com/user-attachments/assets/7cd70ab1-9452-448d-bbdc-cf986369c896)

### Version

upcoming (Edge)

### Upcoming/master Version

Latest Commit (4th october)

### Discord contact info

Liamjd14

**Comment by Liamjd14** [comment]
I will update this comment with others that i find:

Taurantula
Ogerpon
Terapagos (small form)

**Comment by hedara90** [comment]
I cannot replicate this on either `master` or `upcoming` updated 10 min ago.
I ran `make clean` before both set of tests.

**Comment by Liamjd14** [comment]
> I cannot replicate this on either `master` or `upcoming` updated 10 min ago. I ran `make clean` before both set of tests.

I'm not sure what is causing it then as the testing was from a fresh clone of the current upcoming repo, I have tried it on  another fresh copy and have the same happening.

**Comment by Cafeei** [comment]
![image](https://github.com/user-attachments/assets/092cc343-4c85-49d5-ae6c-726f52704047)
Reproducible on the latest upcoming on mGBA

**Comment by hedara90** [comment]
Ok, I managed to reproduce it.
It **HAS** to be a female pokemon, male don't trigger this. And every single one of my Terapagos were male.
Which makes sense if #5394 is the cause.

**Comment by hedara90** [comment]
Learning moves has nothing to with this issue.
The only thing that matters is if the overworld sprite is loaded in a way that does not show the "exit pokeball" animation.

**Comment by AsparagusEduardo** [comment]
#5470

**Comment by Bassoonian** [comment]
> #5470

You're referring to the issue, not to the PR that (hopefully?) fixed it

**Comment by AsparagusEduardo** [comment]
> You're referring to the issue, not to the PR that (hopefully?) fixed it

...yes. My bad
