### ISSUE TITLE
rename directories and file paths to match 5075

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#5473]
### Description

`graphics/pokemon/meowth/alolan` should become `graphics/pokemon/meowth/alola` to match the changes made in https://github.com/rh-hideout/pokeemerald-expansion/pull/5075

### Version

upcoming (Edge)

### Discord contact info

pkmnsnfrn

**Comment by AsparagusEduardo** [comment]
I'm doing this atm.

Would female forms be handled like this too? (`meowstic/female/back.png` -> `meowstic/f/back.png`)

![image](https://github.com/user-attachments/assets/45e51444-51fe-49e9-bb5f-08fb2a14cd86)

**Comment by AsparagusEduardo** [comment]
Also, do we want to standarize the symbol names too?
![image](https://github.com/user-attachments/assets/fb6f314e-49dc-45ae-8551-4884fccfb8cd)

**Comment by pkmnsnfrn** [comment]
> I'm doing this atm.

Oh, I thought @kittenchilly was talking about doing it - as long as we're not duplicating work! ty either way.

> Would female forms be handled like this too? (`meowstic/female/back.png` -> `meowstic/f/back.png`)
> 
> ![image](https://private-user-images.githubusercontent.com/2904965/379744651-45e51444-51fe-49e9-bb5f-08fb2a14cd86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NzQ0MzgsIm5iZiI6MTcyOTc3NDEzOCwicGF0aCI6Ii8yOTA0OTY1LzM3OTc0NDY1MS00NWU1MTQ0NC01MWZlLTQ5ZTktYmI1Zi0wOGZiMmExNGNkODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjRUMTI0ODU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWRjMjQwZDg1OWU1MmYxYTUyZDM3ZWQzYmIxZTdkOTZjYTY4OGFmNmIwMWU5Mzc4NzhjOTMxMjc0NGEyZWI2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.f95JGzEeweFaKr1qx50dkZtfxoEp5X4nh_SCOEUUsY8)

I don't like it but I think so, yes.

> Also, do we want to standarize the symbol names too?

I don't see a reason we SHOULDN'T.

**Comment by AsparagusEduardo** [comment]
Just confirmed with kitten and gave me the ok to handle it :)

**Comment by AsparagusEduardo** [comment]
#5581
