### ISSUE TITLE
Clean up Shedinja generation

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#5478]
### Description

Since #5422 got reverted by #5424, it also reverted the Shedinja code cleanup. I'm making this issue so it doesn't get lost.

### Version

master (default, unreleased bugfixes)

### Upcoming/master Version

06fefe3

### Discord contact info

AsparagusEduardo

**Comment by AlexOn1ine** [comment]
#5501
