### ISSUE TITLE
Entering the sealed chamber with Dig Freezes Follower

### ISSUE THREAD

**Issue by iriv24** [rh-hideout/pokeemerald-expansion#5482]
### Description

Follower gets frozen when you dig to get into the sealed chamber.

![digsealedchamber](https://github.com/user-attachments/assets/b5e39761-70e7-4a6c-b0c6-31e730cf9f09)

Some say Donphan is still there to this day.

### Version

upcoming (Edge)

### Discord contact info

iriv24

**Comment by iriv24** [comment]
Im pretty sure you have to use flash for one of the regis somewhere and i havent tested that but same thing could happen

**Comment by hedara90** [comment]
It only happens for the Sealed Chamber, the other Regi locations don't freeze the follower.

**Comment by Bassoonian** [comment]
In all likelihood, there is a release missing. There’s a high chance this is also broken on the base followers branch, so I’ve contacted @aarant as it likely affects her branch too.

**Comment by hedara90** [comment]
I have it fixed, just figuring out how to push it to the correct repo

**Comment by hedara90** [comment]
Fix is here: [#43](https://github.com/aarant/pokeemerald/pull/43l)

**Comment by aarant** [comment]
Fixed this myself upstream in d80190fe105eee12bbf74ae29647ac909084d35c, I made it work like Rock Smash / Cut where if the follower is the one using Dig it will move and dig the wall
