### ISSUE TITLE
Unexpected character in battle_partners

### ISSUE THREAD

**Issue by AdamS-Catalyst** [rh-hideout/pokeemerald-expansion#5496]
### Description

This is from a complete fresh download of pokemerald-expansion. 
The error occurs when compiling in either MSYS2 or Cygwin.

![image](https://github.com/user-attachments/assets/404c7326-3657-4017-b792-916e103e53c7)

### Version

master (default, unreleased bugfixes)

**Comment by hedara90** [comment]
It is known.
On Cygwin and msys2 you have to disable competetive syntax and run `trainerproc` manually.

**Comment by AdamS-Catalyst** [comment]
> It is known. On Cygwin and msys2 you have to disable competetive syntax and run `trainerproc` manually.

Thank you, do you have link or something that will help me do that?
I couldn't find anything through google.

**Comment by AdamS-Catalyst** [comment]
Thank you, I'll give those changes a shot.
I wanted to try WSL, but I'm afraid I get confused even at step 1.

**Comment by hedara90** [comment]
Closing as won't fix.
Workaround is known.
For a more permanent fix the following has been suggested.
> the problem is probably that trainerproc doesn't parse \r\n line endings, so it's "just" a matter of finding all the '\n's (there's 5) and allowing those loops to parse \r\n as a newline
