### ISSUE TITLE
Animation playing again after Battle Debug menu use

### ISSUE THREAD

**Issue by ExpoSeed** [rh-hideout/pokeemerald-expansion#550]
UltimaSoul: "wtf
I found the most bizarre bug.
I encountered a wild double battle and then if I went to the Battle Debug menu and went back, the animation would play again for one of the mons
But the thing is, I can't find another battle that this gets reproduced on"

UltimaSoul: "Okay
:PogChamp:
I replicated the bug
And uh... I didn't do anything different?"

may be related to #520

**Comment by AsparagusEduardo** [comment]
Closing this as it doesn't seem like anyone else has had the issue since it was opened (or at least addressed).
