### ISSUE TITLE
Dynamic line breaks in strings

### ISSUE THREAD

**Issue by hedara90** [rh-hideout/pokeemerald-expansion#5507]
### Description

Instead of having to manually define every line break in strings, the text printer should be able to dynamically insert line breaks at good places.
Implementation details such as scrolling, stretched spaces, breaks in middle of multi-word terms and font choice to be discussed.

### Discord contact info

hedara

**Comment by AsparagusEduardo** [comment]
Closed by #3240

**Comment by AsparagusEduardo** [comment]
Reopening as this matter can also apply to other text instances

**Comment by AlexOn1ine** [comment]
duplicate #5709
