### ISSUE TITLE
Improve Toxic Switch AI

### ISSUE THREAD

**Issue by Pawkkie** [rh-hideout/pokeemerald-expansion#5509]
### Description

As per discussion in #5462, "AI_FLAG_SMART_SWITCHING: AI will switch out if it has been Toxic'd for at least two turns 50% of the time with more than 1/3 HP remaining" is questionable behaviour at best and actively awful at worst as it just gives the player free damage on an incoming mon. Cases involving HP thresholds etc. should at this point be much better handled by other functions like `HasBadOdds`.

Was out of scope for that PR, is probably out of scope for #5466 but maybe. Leaving a note here so we don't forget.

### Discord contact info
@Pawkkie

**Comment by Pawkkie** [comment]
@AlexOn1ine D'you think this behaviour is good if the AI has a Good Switchin (defensive mon that wins 1v1), or would you toss it regardless?

I am down to either add a clause up front to make sure there's a good switchin or axe it.

**Comment by AlexOn1ine** [comment]
I think that's fine. From a player perspective I would switch If I had a really good counter

**Comment by Pawkkie** [comment]
Closed by #5466
