### ISSUE TITLE
AI calc speed dropped significantly 

### ISSUE THREAD

**Issue by AlexOn1ine** [rh-hideout/pokeemerald-expansion#5534]
### Description

For some reason the AI delay got much worse since I last checked. It was at 49 frames previously and increased to 71. I haven't checked on master yet but this is something we have to fix in my view. 

![image](https://github.com/user-attachments/assets/4758d6fb-809e-45ef-b07a-d5e049e6bc0b)

### Version

upcoming (Edge)

**Comment by Pawkkie** [comment]
Confirmed, also confirmed it occurs on upcoming but most master, master is still 58 frames

![image](https://github.com/user-attachments/assets/38adefbc-dade-4e57-ace2-5e4729963291)

**Comment by Pawkkie** [comment]
This was introduced by #5440 which made ShouldSwitch run for every battler. This is expensive until it gets refactored in a similar way to Getbestmonintegrated.

Short term solution is likely to be only bothering to calculate it if a move has the hit escape effect or the trainer has the prediction flag once that's finished.

Putting this here so we don't forget.

**Comment by Pawkkie** [comment]
Alternative solution, we already have to run ShouldSwitch once per battler with emitResult set to True to determine if they should switch. So this is running it twice for every battler.

If we could refactor in such a way as to use the initial ShouldSwitch result without having to rerun the entire function again for emitResult that should also solve the issue and might be cleaner.

**Comment by AlexOn1ine** [comment]
> Alternative solution, we already have to run ShouldSwitch once per battler with emitResult set to True to determine if they should switch. So this is running it twice for every battler.
> 
> If we could refactor in such a way as to use the initial ShouldSwitch result without having to rerun the entire function again for emitResult that should also solve the issue and might be cleaner.

sounds good

**Comment by Pawkkie** [comment]
Fixed by #5466
