### ISSUE TITLE
Add Trainer Party Types for Set Abilities

### ISSUE THREAD

**Issue by surskitty** [rh-hideout/pokeemerald-expansion#557]
For the `battle_engine`, it would be very useful if it was possible to define in `src/data/trainer_parties.h` what abilities a given trainer's pokemon have. The difference between Flannery's Torkoal having White Smoke or Drought is substantial.

**Comment by surskitty** [comment]
[This commit by Syreldar was linked in Discord](https://github.com/Syreldar/pokeemerald/commit/e4c8b21eb9a351c44e20008dcbc3648d69693462) implementing full control over trainer parties. It's got a whole lot of other stuff in that commit, but it's interesting reference.

Personally, I think it ought to have a bunch more default values rather than specifying everything every time, but that's much fancier than my PR #1343 expanding the vanilla system with an annoying amount of copying and pasting.

**Comment by AsparagusEduardo** [comment]
#2733
