### ISSUE TITLE
Mega-evolution anim does not load the shiny palette

### ISSUE THREAD

**Issue by Nopinou** [rh-hideout/pokeemerald-expansion#5571]
### Description

![mega_shiny](https://github.com/user-attachments/assets/d5c167d5-98a0-49ed-9ace-5efc0e85b1f2)
On latest upcoming, did not test in master.

### Version

upcoming (Edge)

### Discord contact info

Nopinou#8678

**Comment by hedara90** [comment]
Confirmed, it's happening on `master`too.

**Comment by hedara90** [comment]
#4816 is the cause
