### ISSUE TITLE
Certain Species not properly Converting with Competitve format

### ISSUE THREAD

**Issue by Robdeezy** [rh-hideout/pokeemerald-expansion#5575]
### Description

When pasting into src/data/trainers.party , certain species like Indeedee and Florges who have alternate forms get converted weirdly into src/data/trainers.h. For Florges the showdown paste is Florges-White which turns into SPECIES_FLORGES_WHITE rather than the correct SPECIES_FLORGES_WHITE_FLOWER which will cause an error upon making the .gba. Similarly Indeedee Male and Female show up as SPECIES_INDEEDEE_M,SPECIES_INDEEDEE_F instead of SPECIES_INDEEDEE_MALE or SPECIES_INDEEDEE_FEMALE.
I tested all the mons on this serebii page https://www.serebii.net/games/forms.shtml
Below is a list of Mons where this issue occurs based on my testing (besides the indeedee and florges cases above): 
Basculegion (M)
Basculegion-F (F)
Floette
Flabebe

Didn't get a chance to test alcremie since showdown only allows the base form not the different ones

### Version

1.9.3 (Latest release)

### Discord contact info

Robdeezy

**Comment by AsparagusEduardo** [comment]
We currently have the `SPECIES_FLORGES_WHITE` and such defined as synonyms in the `include/constants/species.h` file.
In 1.10, we will discontinue the full names such as `SPECIES_FLORGES_WHITE_FLOWER` to keep in line with Showdown's and CFRU's standard, and also to minimize duplicity.

Do you actually have issues when building the rom, or were you describing a potential issue?

**Comment by Robdeezy** [comment]
I was reporting this issue for mgriffin as these naming issues prevented the rom from being made currently using the SPECIES_ format is a workaround for these outliers just wanted to bring attention to it

**Comment by badabingbada** [comment]
just a heads up; this also happens with farfetch'd, which trainers.party wants to read as SPECIES_FARFETCH_D, when it is actually SPECIES_FARFETCHD. 

I am probably the first (and last) person to ever add Farfetch'd to an ingame team and find this bug. Added a line to species.h to fix it for now:

#define SPECIES_FARFETCH_D                              SPECIES_FARFETCHD

**Comment by AlexOn1ine** [comment]
#5581
