### ISSUE TITLE
Light Ball applying to all pikachu forms

### ISSUE THREAD

**Issue by iriv24** [rh-hideout/pokeemerald-expansion#5624]
### Description

unless theres some wizardry with the forms, i think it only applies to regular pikachu currently. ill get to this eventually if no one else does

![image](https://github.com/user-attachments/assets/50378a41-187c-4887-90ab-d4e40d108ab3)

### Discord contact info

iriv24

**Comment by kittenchilly** [comment]
That says "It IS compatible with Cosplay Pikachu, Pikachu in a cap, and Gigantamax Pikachu"
I think we have it implemented correctly

**Comment by kittenchilly** [comment]
HOLD_EFFECT_LIGHT_BALL checks against atkBaseSpeciesId, meaning we do have it working with every Pikachu form since they are all in the form table.

**Comment by iriv24** [comment]
> HOLD_EFFECT_LIGHT_BALL checks against atkBaseSpeciesId, meaning we do have it working with every Pikachu form since they are all in the form table.

ohh thats how atkbasespecies works, nice, cosplay pikachu enjoyers rejoice
