### ISSUE TITLE
[item_expansion] Premier Ball freezes the game on MODERN

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#565]
Kind of a reminder, but it's mainly just me wanting to keep track of the issues that arise.
Attempting to use the Premier Ball in a ROM with the item_expansion built with the modern compiler causes the game to freeze.
![Untitled846](https://user-images.githubusercontent.com/4485172/98404647-bff2e480-2049-11eb-9bf9-cbb5959dd64d.gif)

**Comment by LOuroboros** [comment]
It's worth noting that the issue doesn't happen in a ROM built with the regular compiler. It's specific to the Modern one.

**Comment by AsparagusEduardo** [comment]
Pret recently fixed this issue. To be fixed on next sync.

**Comment by ExpoSeed** [comment]
Possibly fixed in #578. needs investigation

**Comment by LOuroboros** [comment]
> 
> 
> Possibly fixed in #578. needs investigation

Yep, it definitely was. I tested a clean copy of the item_expansion in its latest commit and the Premier Ball is no longer making the game freeze on Modern.

Closing this issue.
