### ISSUE TITLE
Hurricane's animation is broken

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#567]
![Hurricane](https://user-images.githubusercontent.com/28769716/98419171-59250800-20e9-11eb-81e0-b371718bda49.gif)
Note this wasn't tested on a clean version of the battle engine, so it could just be a mistake on my end.

**Comment by LOuroboros** [comment]
Can confirm, the aniamtion is certainly broken on a clean copy of the battle_engine.
![Untitled860](https://user-images.githubusercontent.com/4485172/98420525-27b72880-2066-11eb-87cb-4f4f21e9dbfa.gif)

**Comment by ExpoSeed** [comment]
#568
