### ISSUE TITLE
Kee Berry activates when double battle partner is hit with a physical move

### ISSUE THREAD

**Issue by SPMoo66** [rh-hideout/pokeemerald-expansion#5674]
### Description

If a Pokemon is holding a Kee Berry and its double battle partner is hit with a physical move, the berry will activate.

![KeeBerry](https://github.com/user-attachments/assets/5b68dc18-bacf-4952-9f53-41f8ccafc23d)

### Version

1.9.3 (Latest release)

### Discord contact info

moo66

**Comment by hedara90** [comment]
It seems that Kee berries will proc for every battler except for the attacker when any pokemon on the field gets git by a physical move
![keewhat](https://github.com/user-attachments/assets/49d3fa69-6f67-458e-9fe4-0969329327d5)

**Comment by pkmnsnfrn** [comment]
https://github.com/rh-hideout/pokeemerald-expansion/issues/4105

Weird that this didn't kill it

**Comment by hedara90** [comment]
It also happens with Enigma Berry, but not for the attacker partner.
I would assume that it's something to do with `ItemEffectMoveEnd` item effects.
