### ISSUE TITLE
Ice Face procs after opposing mon switches in

### ISSUE THREAD

**Issue by iriv24** [rh-hideout/pokeemerald-expansion#5677]
### Description

Per description of Ice Face: "If a hailstorm or snowstorm begins while Eiscue is in its Noice Face form, or if it is sent out in its Noice Face form during hail, it will immediately revert to its Ice Face form. Eiscue will not revert to its Ice Face form if there is already hail when it changes into its Noice Face form.

https://github.com/user-attachments/assets/9b5fb2ef-a04e-4b42-9b50-17e9caa079c7

I suspect when the opposing mon is being thrown out the code is incorrectly checking for the "sent out in its Noice Face form during hail, it will immediately revert to its Ice Face form" case.

### Version

master (default, unreleased bugfixes)

### Discord contact info

iriv24

**Comment by kittenchilly** [comment]
This is likely the same issue as #5660 since we don't do Ice Face in the correct order currently.

**Comment by hedara90** [comment]
It might've been my Ice Face refactor that broke it too, if it wasn't broken before that.
It seems to be a simple fix, I gotta test it some more though.
