### ISSUE TITLE
OpponentHandleChoosePokemon can result in a negative chosenMonId to send out next

### ISSUE THREAD

**Issue by iriv24** [rh-hideout/pokeemerald-expansion#5681]
### Description

i dont know if this is even a bug since i cant get it to reproduce any bad behavior in game on clean expansion, but it feels incorrect to me that with the ACE flag set, when it comes time to throw out the ace as they are the last mon remaining, the `chosenMonId` is being set to -1
![image](https://github.com/user-attachments/assets/dd528f8b-36cf-4f5a-bca9-0153675e5f60)

[Link to relevant function](https://github.com/rh-hideout/pokeemerald-expansion/blob/67c7106fee57e293b6a96c435c0989c41f79cd76/src/battle_controller_opponent.c#L651)

I found this by debugprinting in upcoming after i was getting a crash using the ACE flag in my own game, unless this isnt the correct way to print this variable, then this line results in -1 when the ace gets thrown out. 

![image](https://github.com/user-attachments/assets/f0f1d014-892e-4ca3-8c20-54baf6c1448d)/

Feel free to close this if its a non-issue, i still havent determined what's causing my game to crash or why upcoming _isnt_ crashing, mostly just creating this for tracking purposes.

ill just attach one screenshot of the bad behavior im seeing in my own game for the sake of having it.
![Screenshot (15)](https://github.com/user-attachments/assets/345f3d04-03cf-4522-9fc3-7520df37ab93)

### Version

upcoming (Edge)

### Discord contact info

iriv24

**Comment by Pawkkie** [comment]
Closed by #5684
