### ISSUE TITLE
Game freezes when a mon faints to an absorb move

### ISSUE THREAD

**Issue by iriv24** [rh-hideout/pokeemerald-expansion#5687]
### Description

My guess would be caused by [5670](https://github.com/rh-hideout/pokeemerald-expansion/pull/5670) because that code just changed. When a pokemon gets fainted by an absorb move, they faint, their cry gets played twice, and then the game freezes.

https://github.com/user-attachments/assets/79f5250d-e641-4e31-9aab-d7107f7962e7

### Version

upcoming (Edge)

### Discord contact info

iriv24

**Comment by Pawkkie** [comment]
Closed by #5688
