### ISSUE TITLE
Battle frontier crashes game

### ISSUE THREAD

**Issue by Pawkkie** [rh-hideout/pokeemerald-expansion#5690]
### Description

Starting a battle in the battle frontier crashes on upcoming. This was originally reported by SirScrubbington on Discord. I've checked the Battle Factory and Battle Tower and can confirm at least both of those two crash on battle start.

This does *not* crash on master, so it's something in upcoming. We should probably bisect this before 1.10.

### Version

upcoming (Edge)

### Discord contact info

@Pawkkie

**Comment by damon-murdoch** [comment]
Hi, thanks for testing this for me :)

Here is a screenshot I took of the error occuring, along with the crash logs:
![image](https://github.com/user-attachments/assets/73505a55-b547-41fd-8556-2d09d99c2e65)

Please note, that the 'illegal opcode' is always the same (at least in my experience), so this may indicate that the same bad memory address is being accessed each time.

**Comment by Pawkkie** [comment]
Finished doing git bisect, the problematic commit is #5622

**Comment by Pawkkie** [comment]
Finished doing git bisect, the problematic commit seems to be #5622

**Comment by Pawkkie** [comment]
Closed by #5699
