### ISSUE TITLE
HGSS Dex has broken ORDER modes

### ISSUE THREAD

**Issue by jschoeny** [rh-hideout/pokeemerald-expansion#5693]
### Description

ORDER_A_TO_Z shows multiple entries for each Pokemon.
![pokeemerald-0](https://github.com/user-attachments/assets/90013f64-ff56-4178-be52-ecc4bd4d100c)

When `HOENN DEX` mode is enabled and an Order other than `NUMERICAL MODE` is selected, National Dex Pokemon are also included in the list.
![pokeemerald-1](https://github.com/user-attachments/assets/03704147-9bd6-4acf-b3e3-afd220da2153)

### Version

upcoming (Edge)

### Upcoming/master Version

572ea141af83caf2f57d50c4e74cb493fb306c88

### Discord contact info

te_on

**Comment by jschoeny** [comment]
Haven't tested, but based on where I'm pretty sure the culprit is (https://github.com/rh-hideout/pokeemerald-expansion/blob/master/src/pokedex_plus_hgss.c#L2562-L2632), git blame shows it last being changed at least 20 months ago (when the code was isolated to its own file).

**Comment by hedara90** [comment]
Yea, it's been bugged since inception. It's broken in 20e3b43
