### ISSUE TITLE
AI Smart Switching not registering Immunity abilities

### ISSUE THREAD

**Issue by Robdeezy** [rh-hideout/pokeemerald-expansion#5701]
### Description

Encountered issue with AI smart switching not registering Flash Fire as an immunity to fire type moves. In my example eruption killed both party mons so the ai wouldn't switch to the mon with flash fire in the back which is immune to it.
In the two gifs below you can see that since lava plume doesn't OKO the ninetails it will switch into it where as the eruption does more damage and therefore the AI doesnt switch.
The Ai had the following flags for all tests :AI: Check Bad Move / Smart Switching / Omniscient
![Flash Fire Test](https://github.com/user-attachments/assets/553dd038-2496-48ca-9d41-9f4280fc7740)

![flashfire test 2](https://github.com/user-attachments/assets/66ef5ac7-0be2-481e-bc3f-fd224eb78ecc)

Below are similar examples with other abilities:
Dry Skin:
![Dry Skin](https://github.com/user-attachments/assets/f1315ddb-cb4a-4a32-9ec4-54d8ea809ed7)

Lightning Rod
![Lightning Rod](https://github.com/user-attachments/assets/1b9e79d3-ac91-4c83-94bb-66972b54b24a)

Motor Drive
![Motor Drive](https://github.com/user-attachments/assets/8085f8cc-64db-4180-a295-b48241c7af2d)

Levitate (this one works as expected)
![Levitate](https://github.com/user-attachments/assets/62281e5b-e0c5-420c-ba65-60f8be32bae7)

Sap Sipper
![Sap sipper](https://github.com/user-attachments/assets/ef0d1d33-45fc-4f63-b430-c73c8ea84916)

Storm Drain
![storm drain](https://github.com/user-attachments/assets/004fd52f-9ad6-4568-9afc-64b5851435c4)

Soundproof
![Sound Proof](https://github.com/user-attachments/assets/da2d296d-a615-4c5d-8ce1-d803d86cb9fc)

Volt Absorb
![volt absorb](https://github.com/user-attachments/assets/610c2439-6e0b-45dd-bce0-c322dbea1859)

Water Absorb
![water absorb](https://github.com/user-attachments/assets/c9027381-c7ba-489c-80af-7fc0f3ab8cf4)

Please let me know if there's anything else you need from me or i can assist with!

### Version

1.9.3 (Latest release)

### Discord contact info

Robeezy

**Comment by Pawkkie** [comment]
This is already fixed on upcoming along with a number of other switching behaviours with #5466 :)

These will get migrated to master with the 1.10 release!

https://github.com/user-attachments/assets/0dbc58da-2091-45eb-9c0c-d3b90d4a97d6
