### ISSUE TITLE
Blunder Policy + Immunities bug

### ISSUE THREAD

**Issue by TerraPrograms** [rh-hideout/pokeemerald-expansion#5718]
### Description

As an example, if a Pokemon with Blunder Policy uses Focus Blast against a Ghost Type, it will **sometimes** activate the Blunder Policy, despite it only activating on misses due to accuracy check. 
The intended interaction is Blunder Policy never activating. Source: https://bulbapedia.bulbagarden.net/wiki/Blunder_Policy

What I suspect happening here is that when Focus Blast would internally evaluate as a miss, it will activate Blunder Policy regardless. If you set Focus Blast accuracy to 1 for testing purposes, it activates much more.

### Version

1.9.3 (Latest release)

### Discord contact info

._.terra._.

**Comment by mrgriffin** [comment]
What's the expected behavior when holding Blunder Policy and using Focus Blast against a Ghost-type?

Should the Blunder Policy never activate or should it always activate?

**Comment by TerraPrograms** [comment]
> What's the expected behavior when holding Blunder Policy and using Focus Blast against a Ghost-type?
> 
> Should the Blunder Policy never activate or should it always activate (or something else)?

Blunder Policy should never activate in that case. Apologies for the unclear descriptions. Edited the Post :)

**Comment by AlexOn1ine** [comment]
What should happen in case of protect?

**Comment by ShadowzLmao2** [comment]
> What should happen in case of protect?

It should also not activate.
