### ISSUE TITLE
AI Not recognizing ability of their own battler on the field with smart switching or smart mon choices

### ISSUE THREAD

**Issue by iriv24** [rh-hideout/pokeemerald-expansion#5743]
### Description

It seems like when you have the `Smart Switching` flag or the `Smart Mon Choices` flag, the AI overwrites (or doesnt restore?) AI data somewhere, and the AI sees the ability of its current mon on the field as the ability of the last mon in its party.

Steps to reproduce:
Have the AI lead a pokemon with prankster (i was using mega-banette, but im pretty sure you can actually reproduce this in any situation) and give them a status move, like will-o wisp. Make sure you have more than 1 pokemon in the AI Party, and make sure they have `Smart Switching` or `Smart Mon Choices`.
Lead your own pokemon thats a dark type and have the `B_PRANKSTER_DARK_TYPES` config >= `GEN_7`
See AI try to use status move into dark type and fail over and over again.

Here is the exact AI data i was using (mega banette has prankster, but to reiterate, i dont think this issue is tied to mega evolution):
```
=== TRAINER_SIDNEY ===
Name: SIDNEY
Class: Elite Four
Pic: Elite Four Sidney
Gender: Male
Music: Elite Four
Items: Full Restore / Full Restore
Double Battle: No
AI: Check Bad Move / Try To Faint / Check Viability / Smart Switching / Omniscient / Smart Mon Choices
Mugshot: Purple

Banette @ Banettite
Level: 46
Ability: Insomnia
IVs: 30 HP / 30 Atk / 30 Def / 30 SpA / 30 SpD / 30 Spe
- Will-o Wisp
- Tackle

Gengar @ Black Sludge
Level: 46
Ability: Cursed Body
IVs: 30 HP / 30 Atk / 30 Def / 30 SpA / 30 SpD / 30 Spe
- Will-o Wisp
- Shadow Claw
- Thunderbolt

Haunter @ Black Sludge
Level: 46
Ability: Levitate
IVs: 30 HP / 30 Atk / 30 Def / 30 SpA / 30 SpD / 30 Spe
- Will-o Wisp
- Shadow Claw
- Thunderbolt
```

and my pokemon was a level 31 relaxed greninja with water pulse, smoke screen, shadow sneak, and spikes.
also attached is the ai scoring on turn 2, after mega evolving and failing to use will-o wisp.
![pokeemerald-2](https://github.com/user-attachments/assets/90cc6218-ec69-45d5-aa33-7f08f2ac1910)

checked for kicks, heres turn 1 of whimsicott with prankster in same scenario:
![pokeemerald-3](https://github.com/user-attachments/assets/8503cac7-c9bf-4c71-8b54-3b6ee4865474)

to see this issue, i was using the following debug print statements.
![image](https://github.com/user-attachments/assets/09d00bf4-9a9b-4750-9473-cd3345a3c7c5)

`aiData->abilities[battlerAtk]` is printing the ability of the last mon in the party.
`gBattleMons[battlerAtk].ability` is printing the ability of the current mon on the field.

Finally, i saw the issue present with either `Smart Switching`, `Smart Mon Choices`, or both. The issue was not present when i removed both of those flags.

### Version

upcoming (Edge)

### Discord contact info

iriv24

**Comment by AlexOn1ine** [comment]
#5746
