### ISSUE TITLE
Snubbull Grandbull learnset errors

### ISSUE THREAD

**Issue by equezada-jej** [rh-hideout/pokeemerald-expansion#5798]
### Description

![Screenshot_20241210_151521_Discord](https://github.com/user-attachments/assets/e6258b51-d477-4b6a-afba-fa17fde83762)

### Version

1.10.0 (Latest release)

### Discord contact info

AsparagusEduardo

**Comment by kittenchilly** [comment]
![image](https://github.com/user-attachments/assets/9b660cdf-b0a4-4f08-9c73-418832eca522)
This behavior is correct in SV.
