### ISSUE TITLE
Crash with Town Map item

### ISSUE THREAD

**Issue by khbsd** [rh-hideout/pokeemerald-expansion#5835]
## Description:
Game crashes when:
- you have not accessed the Town Map via the bag during the current game load, and
- you register the Town Map, save and restart, then use it with Select

## Notes
- tested on latest `upcoming` commit, with a new save
- when you give the Town Map to yourself and register it, the first time it will probably work, but on subsequent loads it crashes.
- accessing the region map at a Pokemon Center doesn't count, it needs to be from the Bag
- from the debug Give Item menu, the Town Map item is no. 713

### Version

upcoming (Edge)

### Upcoming/master Version

https://github.com/rh-hideout/pokeemerald-expansion/commit/b22a867e119268e898e18dfb47cfc5f7bf308c89

### Discord contact info

khbsd

**Comment by iriv24** [comment]
I "fixed" this in #5810 in master, looks like it's just not merged to upcoming yet

**Comment by khbsd** [comment]
oh, rad. will close this then!
