### ISSUE TITLE
Jellicent OW sprite faces wrong side direction

### ISSUE THREAD

**Issue by wiz1989** [rh-hideout/pokeemerald-expansion#5904]
### Description

![grafik](https://github.com/user-attachments/assets/0ffd10c6-d85a-4abb-8901-81b48fa292f4)

### Version

1.9.4

### Discord contact info

wiz1989

**Comment by hedara90** [comment]
I just thought it swam backwards

**Comment by hedara90** [comment]
Already listed in #5135
