### ISSUE TITLE
Destiny bond can be used in succession

### ISSUE THREAD

**Issue by wiz1989** [rh-hideout/pokeemerald-expansion#5905]
### Description

Since Gen 7 Destiny Bond will always fail if it was successfully executed on the previous turn.
However, it doesn't as of now.

https://github.com/user-attachments/assets/a44f1c43-9254-4b4e-81a4-6ec78483062e

### Version

1.9.4

### Discord contact info

wiz1989

**Comment by hedara90** [comment]
Fixed in #5652
