### ISSUE TITLE
Berries restored by Recycle aren't being consumed immediately when conditions are met.

### ISSUE THREAD

**Issue by Toby313** [rh-hideout/pokeemerald-expansion#9]

**Comment by LOuroboros** [comment]
Which conditions? I can't find any info about Recycle stating that berries recovered by it are consumed right away or anything of the like, which is kind of what the title of this issue implies; that they should be consumed right away.

**Comment by Toby313** [comment]
The conditions being the HP requirement, so in the case of Oran Berry 50%. After restoring the berry, it should immediately check if HP is below 50% and consume it if this is the case.

**Comment by LOuroboros** [comment]
> 
> 
> The conditions being the HP requirement, so in the case of Oran Berry 50%. After restoring the berry, it should immediately check if HP is below 50% and consume it if this is the case.

Ah, I see. You're right. I tested it on USUM and I can confirm that's how the move's effect it's supposed to behave too.
https://streamable.com/pexpv2

**Comment by ExpoSeed** [comment]
#1338
